api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
api/src/test/java/org/openmrs/api/ConceptServiceTest.java

Used the ignoreCase() method to ensure that the comparison is case insensitive.

TRUNK-4452: Changed getConceptsByMapping() to be case insensitive

---

api/src/main/java/org/openmrs/api/ConceptService.java
api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java
api/src/test/java/org/openmrs/api/ConceptServiceTest.java

Parsed concept id for concept.unknown as an integer (as was done for concept.true and concept.false). Not sure if it should support other data types as well.

TRUNK-4474: Added Core Global Property for representing Unknown Concept

---

api/src/test/java/org/openmrs/api/EncounterServiceTest.java
pom.xml

Fix for TRUNK-4590 and TRUNK-4591
When running under Java 1.8 the previous H2 version result in lock timeouts on EncounterServiceTest
saveEncounter_shouldNotOverwriteObsAndOrdersCreatorOrDateCreated and
saveEncounter_shouldSetDateStoppedOnTheOriginalAfterAddingReviseOrder.

Updated the h2 dependency version to 1.4.185

---

webapp/src/main/webapp/WEB-INF/view/dictionary/conceptForm.jsp

The parameter in the ajax request defaulted to the English locale previously with the default value being the current Fully Specified Name. The error was caused because the request always resulted in a match as the user input was neglected.
The patch takes the locale selected into account and sends the appropriate string.

TRUNK-4520: Send correct parameter in AJAX request

---

api/src/main/java/org/openmrs/PersonName.java
api/src/main/java/org/openmrs/obs/handler/AbstractHandler.java
web/src/main/java/org/openmrs/web/dwr/DWRPersonService.java

http://issues.openmrs.org/browse/GCI-9
Objective of this commit is to replace new String() with String.valueOf() at several instances as valueOf is more efficient.

Changed String constructor to valueOf

---

api/src/main/java/org/openmrs/api/context/ServiceContext.java
api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
api/src/main/java/org/openmrs/api/impl/VisitServiceImpl.java
api/src/main/java/org/openmrs/module/ModuleMustStartException.java
api/src/main/java/org/openmrs/reporting/export/DataExportFunctions.java
api/src/main/java/org/openmrs/util/Format.java
web/src/main/java/org/openmrs/web/controller/form/FormFormController.java
web/src/main/java/org/openmrs/web/controller/user/RoleFormController.java
web/src/main/java/org/openmrs/web/filter/StartupFilter.java

... of Collections.EMPTY_LIST, EMPTY_MAP and EMPTY_SET
GCI-9
Collections.emptyList(),emptyMap() and emptySet() should be used instead
of Collections.EMPTY_LIST, EMPTY_MAP and EMPTY_SET

GCI-9 - Collections.emptyList(),emptyMap() and emptySet() should be used instead and Empty statements should be removed

---

.gitignore
api/pom.xml
api/src/main/java/org/springframework/test/annotation/NotTransactional.java
api/src/test/java/org/openmrs/api/AdministrationServiceTest.java
pom.xml
release-test/pom.xml
test/pom.xml
tools/pom.xml
web/pom.xml
web/src/main/java/org/springframework/http/converter/json/MappingJacksonHttpMessageConverter.java
web/src/main/java/org/springframework/web/servlet/mvc/AbstractFormController.java
web/src/main/java/org/springframework/web/servlet/mvc/AbstractWizardFormController.java
web/src/main/java/org/springframework/web/servlet/mvc/BaseCommandController.java
web/src/main/java/org/springframework/web/servlet/mvc/SimpleFormController.java
web/src/main/java/org/springframework/web/servlet/view/json/MappingJacksonJsonView.java
web/src/main/java/org/springframework/web/util/ExpressionEvaluationUtils.java
web/src/test/java/org/openmrs/web/controller/form/FieldTypeListControllerTest.java
webapp/.gitignore
webapp/pom.xml
webapp/src/main/resources/log4j.xml

Initial attempt of upgrading to Spring 4, with a minimal number of changes. Only the Spring and servlet jars have been updated. Spring 3 files that were removed in 4 have been added back under org.springframework package in core api as a first cut. I also re-versioned the maven projects to 1.12.0.SPRING-SNAPSHOT to make it easier to avoid build conflicts when building against both Spring 3 and Spring 4. Added a log4j file logger that is off by default, to make it easier to record errors on startup.
mvn clean package works and all tests pass. The classic UI works and many modules load cleanly, but there are still several runtime issues that need to be addressed before it will be possible to run all of the modules needed for the reference app.

change spring version to 4.1.4RELEASE

---

api/src/main/java/org/openmrs/api/db/hibernate/PatientSearchCriteria.java

Fixed:
-- Switch statements should end with a default case
Ticket: https://issues.openmrs.org/browse/GCI-9

Switch statements should end with a default case

---

api/src/main/java/org/openmrs/ConceptNumeric.java
api/src/main/java/org/openmrs/ConceptReferenceTermMap.java
api/src/main/java/org/openmrs/ConceptStateConversion.java
api/src/main/java/org/openmrs/FormField.java
api/src/main/java/org/openmrs/Obs.java
api/src/main/java/org/openmrs/PersonAddress.java
api/src/main/java/org/openmrs/ProgramWorkflowState.java
api/src/main/java/org/openmrs/Role.java
api/src/main/java/org/openmrs/Tribe.java
api/src/main/java/org/openmrs/module/ModuleConditionalResource.java

Make progress on Sonar's [Useless parentheses around expressions should be removed to prevent any misunderstanding](https://ci.openmrs.org/sonar/drilldown/issues/1865?rids%5B%5D=1868&rids%5B%5D=1873&rule=squid%3AUselessParenthesesCheck&rule_sev=MAJOR&severity=MAJOR#). 
Melange task: https://www.google-melange.com/gci/task/view/google/gci2014/5708233700278272

GCI-9: Useless parentheses around expressions should be removed to prevent any misunderstanding

---

tools/src/main/resources/eclipse/OpenMRSFormatter.xml

instead of putting all elements in one line
* improves readability
* leads to good diffs, where added/deleted elements can be spotted right away

OpenMRSFormatter stacks enum elements one per line

---

webapp/pom.xml

@rkorytkowski https://issues.openmrs.org/browse/TRUNK-4660
update to jetty 8.0.0 solves the problem

TRUNK-4660 "Administration page does not display"

---

api/src/test/java/org/openmrs/util/HttpClientTest.java

Fix test post_shouldPostUrlParametersAndGetResponse(org.openmrs.util.HttpClientTest)

TRUNK-4522: Fix HttpClientTest test on JVM 1.8.

---

web/src/test/java/org/openmrs/scheduler/web/controller/SchedulerFormControllerTest.java
web/src/test/java/org/openmrs/scheduler/web/controller/TaskHelperTest.java

Exceptions in TaskHelperTest and SchedullerFormControllerTest when run under JVM 1.8. 
Resolves: 
https://issues.openmrs.org/browse/TRUNK-4598
https://issues.openmrs.org/browse/TRUNK-4599
https://issues.openmrs.org/browse/TRUNK-4601
https://issues.openmrs.org/browse/TRUNK-4602
https://issues.openmrs.org/browse/TRUNK-4603 (here I have posted explanation)
https://issues.openmrs.org/browse/TRUNK-4604
Also, after merge this PR, we can resolve https://issues.openmrs.org/browse/TRUNK-3948 just by removing "@Ignore" annotation and it will works.

TRUNK-4603 Test fails under JVM 1.8

---

api/src/test/java/org/openmrs/util/HttpClientTest.java

The problem is in HashMap parameters order.
HashMap<String, String> parameters = new HashMap<String, String>();
parameters.put("one", "one");
parameters.put("two", "two");
The assertion like : assertThat(stream.toString(), is("&two=two&one=one")).
Is not pretty good idea.
Can we use something like:
assertThat(stream.toString(), contains("&two=two");
assertThat(stream.toString(), contains("&one=one");
It would be more stable, as we can't predict parameters order in HashMap.

Trunk 4522: JVM 1.8 test fails.

---

pom.xml

Looks like some tests are failing, but something on Bamboo agents are not picking them up. 
https://talk.openmrs.org/t/openmrs-core-build-failure-noticed-on-2015-05-28/2007/16
The affected build is:
https://ci.openmrs.org/browse/TRUNK-MASTER-JOB1-931/log
I can reproduce the failures locally (oracle jdk 8), any version of maven 3.2 (3.2.3 and 3.2.5), on my vagrant box (openjdk 8). TravisCI has the failure as well. With this change, I intend to have a consistent behaviour. 
This new version of surefire shows the error messages a little bit more clear as well. 
```
Results :
Tests in error: 
EncounterServiceTest.saveEncounter_shouldNotOverwriteObsAndOrdersCreatorOrDateCreated:562 » PessimisticLock
EncounterServiceTest.saveEncounter_shouldSetDateStoppedOnTheOriginalAfterAddingReviseOrder:283 …
```

TRUNK-4604: Upgrading surefire plugin to make sure Bamboo will pick failures.

---

api/src/main/java/org/openmrs/api/context/Context.java
api/src/main/java/org/openmrs/api/impl/AdministrationServiceImpl.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java
api/src/main/java/org/openmrs/validator/ValidateUtil.java
api/src/test/java/org/openmrs/api/AdministrationServiceTest.java
api/src/test/java/org/openmrs/validator/ValidateUtilTest.java
api/src/test/resources/org/openmrs/include/standardTestDataset.xml

Hey @dkayiwa I've opened another PR for the disable validation issue. I changed how this is done so that it doesn't interfere with other OpenMRS unit test. I've also added some unit tests of my own.
See https://issues.openmrs.org/browse/TRUNK-4626

TRUNK-4626: Allows disabling of validation of OpenMRS objects via a global property.

---

api/src/main/resources/liquibase-update-to-latest.xml
api/src/main/resources/org/openmrs/api/db/hibernate/EncounterType.hbm.xml
api/src/test/java/org/openmrs/api/EncounterServiceTest.java

Add changed_by and date_changed columns to encounter_type table. Includes the
hibernate mapping file changes and liquibase changesets.
To verify, I 1) ran `mvn test` on my mac, and 2) ran the webapp in Jetty and confirmed
the columns were created and that changing an encounter type updated them.
This is my first patch on OpenMRS; please let me know if there are other behaviors
that unittests could exercise or if there is additional verification I need to run.
https://issues.openmrs.org/browse/TRUNK-4729

TRUNK-4729: Add changedBy and dateChanged attributes to EncounterType.

---

api/src/main/java/org/openmrs/api/EncounterService.java
api/src/main/java/org/openmrs/api/db/EncounterDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
api/src/main/java/org/openmrs/parameter/EncounterSearchCriteria.java
api/src/main/java/org/openmrs/parameter/EncounterSearchCriteriaBuilder.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java
api/src/test/resources/org/openmrs/api/include/EncounterServiceTest-initialData.xml

Deprecate the old api method and add a new one that uses a parameter
object (EncounterSearchCriteria) instead of individual parameters.
Provide a convenience builder EncounterSearchCriteriaBuilder for
creating unmodifiable instances of the search criteria.

TRUNK-4571: Get encounters by creation/modification date

---

api/src/main/java/org/openmrs/api/AmbiguousOrderException.java
api/src/main/java/org/openmrs/api/OrderService.java
api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

if the caller acknowledges that they are aware of the overlap, otherwise
AmbiguousOrderException have to be thrown
https://issues.openmrs.org/browse/TRUNK-4702

TRUNK-4702. OrderService should allow you to save overlapping DrugOrders

---

webapp/src/main/webapp/WEB-INF/view/portlets/customMostRecentObs.jsp

trims comma-separated values (from dashboard.overview.showConcepts GP) before using them, to also allow whitespaces before and after commas (for this specific GP)

TRUNK-4463 trim concept ids after being tokenised

---

pom.xml

Updating the mysql-connector-java to use 5.1.28 version of jar.

Fixing the missed update for mysql driver from 5.1.8 to 5.1.28

---

api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java

Since my last pull request did not match the guidelines, I have now created a new one. 
This is for TRUNK-4691, ConceptService.saveConcept now forces isSet==true, if the concept has set members.

TRUNK-4691 - Force isSet when concept has set members

---

api/src/main/resources/liquibase-update-to-latest.xml

Added indexes for the following columns:
* global_property.property
* concept_class.name
* concept_datatype.name
* concept_reference_term.uuid (was already in place)

TRUNK-4743: Create missing database indexes

---

webapp/src/main/webapp/WEB-INF/view/portlets/customMostRecentObs.jsp

delimiter for multiple elements in Strings stays (implicitly) comma

trunk-4463 use forEach instead of forTokens JSTL tag

---

api/src/main/java/org/openmrs/validator/EncounterTypeValidator.java
api/src/test/java/org/openmrs/validator/EncounterTypeValidatorTest.java
webapp/src/main/webapp/WEB-INF/messages.properties
webapp/src/main/webapp/WEB-INF/messages_de.properties
webapp/src/main/webapp/WEB-INF/template/headerFull.jsp
webapp/src/main/webapp/WEB-INF/template/headerMinimal.jsp
webapp/src/main/webapp/WEB-INF/view/admin/encounters/encounterRoleForm.jsp
webapp/src/main/webapp/WEB-INF/view/admin/encounters/encounterTypeForm.jsp
webapp/src/main/webapp/WEB-INF/view/admin/locations/locationAttributeType.jsp
webapp/src/main/webapp/WEB-INF/view/admin/provider/providerAttributeTypeForm.jsp
webapp/src/main/webapp/WEB-INF/view/admin/visits/visitAttributeTypeForm.jsp
webapp/src/main/webapp/WEB-INF/view/admin/visits/visitTypeForm.jsp
webapp/src/main/webapp/WEB-INF/view/scripts/openmrsmessages.js.withjstl
webapp/src/main/webapp/openmrs.js

We changed the character length limitations on certain textareas (five places had length restrictions in place).
* user input will be rejected when typing although the limit is reached
* if somehow the user provides longer text than allowed, the validator opens the input mask again with error displayed
* while typing into the textarea you get a hint right below the textarea how many characters are left (starting with 30% of the maximal length)
* typing, cut and paste events are covered as well
* english and german i18n message inserted (the others need to be adapted, how do you handle this? create new tickets?)

TRUNK-2280: Refactor maximum length checking in the view layer

---

release-test/pom.xml

updated release-test/pom.xml as discussed here : https://issues.openmrs.org/browse/TRUNK-4751

TRUNK-4751 - Change openmrs-core master version to 2.0.0-SNAPSHOT 

---

api/src/main/java/org/openmrs/module/ModuleUtil.java
webapp/pom.xml

Hi Daniel,
I think that consistency in file naming is important, however I understand your concerns :) I will leave the "extensionless"  temporary file as is.
Jason

TRUNK-4637 : delete temp jar files related to modules

---

api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/test/java/org/openmrs/api/impl/UserServiceImplTest.java

Added password validation using OpenmrsUtil.validatePassword() to UserServiceImpl changePassword, methods and also created test cases for every change i made
https://issues.openmrs.org/browse/TRUNK-4752

TRUNK-4752: User password should be validated before changing it

---

webapp/pom.xml

- Jetty starts without problems.
- All tests pass.

TRUNK-4638: Upgraded Jetty to 9.3.3.v20150827.

---

api/src/main/java/org/openmrs/module/ModuleFactory.java

Selected critical issues
`org.openmrs.module.ModuleFactory.loadModules(List) makes inefficient use of keySet iterator instead of entrySet iterator.`
`org.openmrs.module.ModuleFactory.getLoadedModulesMapPackage() makes inefficient use of keySet iterator instead of entrySet iterator.`
`Redundant nullcheck of tmpExtensions, which is known to be not-null. org.openmrs.module.ModuleFactory.stopModule(Module, boolean, boolean)`

Fix three critical issues on OpenMRS sonarqube

---

api/src/main/java/org/openmrs/validator/UserValidator.java
api/src/test/java/org/openmrs/validator/UserValidatorTest.java

It would not accept emails like `me@t-mobile.de`. Now it does.

TRUNK-4803: Fixed and simplified email regex

---

api/src/main/java/org/openmrs/BaseOpenmrsData.java
api/src/main/java/org/openmrs/BaseOpenmrsMetadata.java
api/src/main/java/org/openmrs/Concept.java
api/src/main/java/org/openmrs/ConceptMapType.java
api/src/main/java/org/openmrs/ConceptName.java
api/src/main/java/org/openmrs/ConceptNameTag.java
api/src/main/java/org/openmrs/ConceptNumeric.java
api/src/main/java/org/openmrs/Drug.java
api/src/main/java/org/openmrs/Field.java
api/src/main/java/org/openmrs/FieldAnswer.java
api/src/main/java/org/openmrs/FormField.java
api/src/main/java/org/openmrs/FormResource.java
api/src/main/java/org/openmrs/GlobalProperty.java
api/src/main/java/org/openmrs/PatientIdentifier.java
api/src/main/java/org/openmrs/Person.java
api/src/main/java/org/openmrs/PersonAddress.java
api/src/main/java/org/openmrs/PersonAttributeType.java
api/src/main/java/org/openmrs/PersonName.java
api/src/main/java/org/openmrs/RelationshipType.java
api/src/main/java/org/openmrs/Retireable.java
api/src/main/java/org/openmrs/Voidable.java

https://issues.openmrs.org/browse/TRUNK-2205
After deprecating all isXyz() having corresponding getXyz() methods, i realized that there were now calls to the deprecated isXyz() inside the code, even getXyz() only calls isXyz() internally. I will create a jira ticket to remove calls to the deprecated isXyz() methods.

TRUNK-2205: Jackson JSON cannot handle BaseOpenmrsObject

---

web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
web/src/test/java/org/openmrs/module/web/WebModuleUtilTest.java

Stopped automatically preprending moduleId to the start of message properties

Fix for TRUNK-3920

---

api/src/main/java/org/openmrs/api/impl/AdministrationServiceImpl.java
api/src/test/java/org/openmrs/api/AdministrationServiceTest.java

**Issue**:[TRUNK-4818](https://issues.openmrs.org/browse/TRUNK-4818): 
In AdministrationServiceImpl.getPresentationLocales() the set we return is a HashSet, but this causes us to lose the ordering of locales (that ultimately comes from an admin-configured global property)
Instead we should use a LinkedHashSet, in order to preserve the order of locales we get from getAllowedLocales() (and ultimately the admin configured via a global property).<br>
**Fix**: Changed `presentationLocales` from `HashSet` to `LinkedHashSet` to preserve insertion order as discussed in ticket. Also added a Unit Test

[TRUNK-4818] : Changed `presentationLocale` to LinkedHashSet to Preserve Insertion Order of Locales

---

web/src/main/java/org/openmrs/web/controller/LoginController.java

**Issue**: [[TRUNK-4817] Backport LUI-60 where user is redirected to home page if he/she tries to access login page while logged in.](https://issues.openmrs.org/browse/TRUNK-4817)<br>
If the User is Authenticated, then he should be redirected to his/her OpenMRS home page and should not be allowed the access the login page
**Note**: There is a travis build failure due to a buffer overflow which is not caused due to this commit. The current code as already been reviewed and verified for merging in LUI-60 which is fixed

Redirecting Authenticated User to home if user tries to access 'login .htm' page [TRUNK-4817]

---

api/src/main/resources/liquibase-update-to-latest.xml

Adding a changeSet that adds uuids where it doesn't exist, before adding not null constraint.
https://issues.openmrs.org/browse/TRUNK-3915.

TRUNK-3915: Adding a changeSet that adds uuids where it doesn't exist, before adding not null constraint.

---

web/src/main/java/org/openmrs/web/controller/user/UserFormController.java
web/src/test/java/org/openmrs/web/controller/user/UserFormControllerTest.java
web/src/test/resources/org/openmrs/web/controller/include/UserFormControllerTest.xml
webapp/src/main/webapp/WEB-INF/messages.properties
webapp/src/main/webapp/WEB-INF/view/admin/users/userForm.jsp

Fix for [TRUNK-4734/LUI-65](https://issues.openmrs.org/browse/LUI-65): Implement a new CheckBox which when selected creates a Provider Account for the user being created in user.form
*Already merged in LUI [here](https://github.com/openmrs/openmrs-module-legacyui/pull/41)*
[Image1](https://issues.openmrs.org/secure/attachment/44399/final.jpg)
[Image2](https://issues.openmrs.org/secure/attachment/44398/final2.jpg)

Fix for TRUNK-4734 (LUI-65).

---

api/src/test/java/org/openmrs/module/ModuleActivatorTest.java
api/src/test/java/org/openmrs/module/ModuleTestData.java

The main problem was with the order of plugins in pom.xml. While starting a module, it checks for required openmrs version. Since, the build-helper was out of order, the openmrs.properties file wasn't updated with any value. It was throwing start up error for modules.

TRUNK-4678 | Fix ModuleActivatorTest

---

release-test/pom.xml

The UI tests were not running properly as Selenium couldn’t open a
connection properly. Updating to the latest version now makes it work.
I’m currently making the tests run by putting the dependency in on the POM for openmrs-distro-referenceapplication. I’m assuming that dependencies added to the core will make their way over to the reference application. If I’m mistaken then please comment and I will add the dependancy to the reference application as well. Thank you!

Updated Selenium for Firefox 45 (RA-1081)

---

api/src/main/java/org/openmrs/OrderSet.java
api/src/main/java/org/openmrs/api/OrderSetService.java
api/src/main/java/org/openmrs/api/db/OrderSetDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderSetDAO.java
api/src/main/java/org/openmrs/api/impl/OrderSetServiceImpl.java
api/src/main/resources/org/openmrs/api/db/hibernate/OrderSet.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/OrderSetMember.hbm.xml
api/src/test/java/org/openmrs/api/OrderSetServiceTest.java

Added helper methods to OrderSet model.
a. removing an orderSetMember from an orderSet
b. retiring an orderSetMember in an orderSet
c. fetching unretired orderSetMembers
Added a method to fetch orderSetMembers by Uuid.
Retiring an orderSet retires the orderSetMembers as well.
Added bi-directional mapping between orderSet and orderSetMember.

OrderSet-Story Extra Changes

---

api/src/main/java/org/openmrs/hl7/handler/ORUR01Handler.java
api/src/test/java/org/openmrs/hl7/handler/ORUR01HandlerTest.java

In the description of the ticket, it was explicitly mention that return value of form should be null if uuid OR id is null.
While fixing the bug i realised that this will not solve the issue, since if either of uuid or id is present we get the form using that value (we prefer form id if uuid is not found or prefer form uuid over id if both are present), thus if either of the value is present the return value should not be null.
Incase both uuid and id is null then, the return value of should be null.

TRUNK-4093 FIX- return null if uuid AND id is null

---

api/src/main/java/org/openmrs/module/UpdateFileParser.java
api/src/test/java/org/openmrs/module/UpdateFileParserTest.java

This pull request accompanies JIRA ticket APPTEST-52 (https://issues.openmrs.org/browse/APPTEST-52).
The tests added in UpdateFileParserTest.java apply 65% branch coverage to UpdateFileParser.java, which as of now has no test coverage.

added tests for UpdateFileParser.java in UpdateFileParserTest.java

---

api/src/test/java/org/openmrs/api/PatientServiceTest.java

class: openmrs-core/api/src/test/java/org/openmrs/api/PatientServiceTest.java
unit test: checkPatientIdentifiers_shouldThrowErrorWhenPatientHasIdenticalIdentifiers
Developers expect a DuplicateIdentifierException to be thrown during testing, but this not the case. The reason for this is because a PatientIdentifierException is thrown before a DuplicateIdentifierException can be raise. To fix this, the "location" field of the PatientIdentifier field must be initialized.

TRUNK-4851 fix error in unit test

---

api/src/main/java/org/openmrs/module/Module.java
api/src/test/java/org/openmrs/module/ModuleTest.java

This pull request accompanies JIRA ticket TRUNK-4850 (https://issues.openmrs.org/browse/TRUNK-4850)
In Module.java, getExtensions() was changed so that extensionNames are expanded when its contents do not match extensions.  Originally, getExtensions() would not call expandExtensionNames() if extensions and extensionNames were the same size, even if the contents of the two variables did not match.  The JIRA ticket goes into more detail on this issue.  
The Unit tests added in ModuleTest.java test these changes when extensionNames is null, is empty, matches extensions, and is the same size as extensions but does not match it.

Changed getExtensions() so extensionNames expands when contents do not match

---

api/src/main/java/org/openmrs/module/Module.java
api/src/test/java/org/openmrs/module/ModuleExtensionsTest.java
api/src/test/java/org/openmrs/module/ModuleTest.java

The accompanying JIRA ticket is: https://issues.openmrs.org/browse/APPTEST-56
Since the Module.getExtensions() tests in ModuleTest.java used PowerMock, their test coverage is not tracked by jacoco.  These tests were moved into their own file, ModuleExtensionsTest.java, so that new tests could be added to ModuleTest.java and still be trackied with jacoco and Sonarqube.

Added more tests to ModuleTest.java and moved the Module.getExtensions() tests

---

api/src/test/java/org/openmrs/validator/PersonNameValidatorTest.java

In PersonNameValidatorTest.java,
add ignore unit tests that fail due to the bug reported in
https://issues.openmrs.org/browse/RA-543?filter=10068

APPTEST-55: Add ignore unit tests in PersonNameValidatorTest.java

---

api/src/main/java/org/openmrs/Concept.java
api/src/main/java/org/openmrs/api/PatientService.java
api/src/test/java/org/openmrs/ConceptTest.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java

the additional unit test in Concept Test cover the additional branches needed to reach 100% branch coverage in hasName method.
the additional unit test in PatientServiceTest cover previously un-tested processDeath method in PatientService.

TRUNK-4856 Adding more unit test for ConceptTest, PatientServiceTest

---

api/src/main/java/org/openmrs/api/impl/PatientSetServiceImpl.java
api/src/test/java/org/openmrs/api/PatientSetServiceTest.java

If we call method PatientSetService#getPatientsHavingDrugOrder(java.util.Collection, java.util.Collection, GroupMethod, Date, Date) with following parameters, it will throw NullPointerException.
Parameters:
patientIds = null
takingIds = a collection list with number of element larger than zero
groupMethod = GroupMethod.NONE
fromDate = null
toDate = null
Original code fails for added test: getPatientsHavingDrugOrder_shouldGetAllPatientsDoNotContainAnyDrugInTheDrugList
Ticket: https://issues.openmrs.org/browse/TRUNK-4864

Add tests for TRUNK-4864 and fix NullPointerException issue

---

webapp/src/main/webapp/WEB-INF/dwr.xml
webapp/src/main/webapp/WEB-INF/tags/providerField.tag

Orderer input field no longer loses data after form error messages. The Oderer is now populated with the data the user had previously typed before clicking "Save Order".
Changed provider.name to provider.displayName in providerField.tag. Additionally added the getProvider method for DWRProviderService in the dwr.xml file

RAD-151 radiolgyOrderForm looses Orderer on error

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore

* added .github/PULL_REQUEST_TEMPLATE.md which will be shown
to every contributor opening a new PR. Its used as a guidance
to ensure PRs will be created in a consistent format with all
required information.
see https://issues.openmrs.org/browse/TRUNK-4863

TRUNK-4863 Add github pull request template

---

api/src/main/java/org/openmrs/module/ModuleFileParser.java

ModuleFileParser is missing 1.5 and 1.6 as valid config versions.
see https://issues.openmrs.org/browse/TRUNK-4899

TRUNK-4899 ModuleFileParser missing some validConfigVersions

---

.travis.yml

travis CI builds of openjdk6 fail due to
https://github.com/travis-ci/travis-ci/issues/5227
* updated travis.yml with workaround
see https://issues.openmrs.org/browse/TRUNK-4900

TRUNK-4900 Travis CI buffer overflow in openjdk6

---

web/src/main/java/org/openmrs/web/dwr/DWRConceptService.java
web/src/test/java/org/openmrs/web/dwr/DWRConceptServiceTest.java
web/src/test/resources/org/openmrs/web/dwr/include/DWRConceptServiceTest-coded-concept-with-no-answers.xml

Changed the data structure that holds Concept Results from `List` to `Set` since `Set` only allows for unique results.
see https://issues.openmrs.org/browse/TRUNK-4846
`git pull --rebase upstream 1.11.x`.

TRUNK-4846: Concept search by ID displays double results 

---

api/src/test/java/org/openmrs/obs/BinaryDataHandlerTest.java
api/src/test/java/org/openmrs/obs/BinaryStreamHandlerTest.java
api/src/test/java/org/openmrs/obs/ImageHandlerTest.java
api/src/test/java/org/openmrs/obs/MediaHandlerTest.java
api/src/test/java/org/openmrs/obs/TextHandlerTest.java

TRUNK-2136: Add unit tests
Add unit tests for ComplexObsHandler.getSupportedViews() and ComplexObsHandler.supportsView(), as discussed in review notes
see https://issues.openmrs.org/browse/TRUNK-2136

TRUNK-2136: Add unit tests

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java

HibernateOrderDAO has a whitespace in one of its exceptions message codes in
getNextOrderNumberSeedSequenceValue
* remove whitespace in message code string
* remove unused code in getNextOrderNumberSeedSequenceValue
see https://issues.openmrs.org/browse/TRUNK-4902

TRUNK-4902 HibernateOrderDAO exception uses wrong message code

---

web/src/main/java/org/openmrs/web/WebConstants.java
web/src/main/java/org/openmrs/web/controller/LoginController.java
web/src/test/java/org/openmrs/web/controller/LoginControllerTest.java

The existing code was not working properly. The referel_url was being cut after '#" so it was redirecting only to the main page.
Now all hashes in redirect_url attribute has to be changed to 'HASHTAG', so the link won't be sliced.
see https://issues.openmrs.org/browse/RA-1111

TRUNK-4859 Add redirect url parameter to login page

---

api/src/main/java/org/openmrs/validator/ConceptValidator.java
api/src/main/resources/messages.properties
api/src/test/java/org/openmrs/ConceptTest.java
api/src/test/java/org/openmrs/api/ConceptServiceTest.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java
api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java
api/src/test/java/org/openmrs/validator/ConceptValidatorTest.java
api/src/test/java/org/openmrs/validator/OrderFrequencyValidatorTest.java

Concept validator now requires datatype and conceptClass fields. I have added two unit tests to verify those changes and updated the others where necessary (wherever the test checked against `errors.hasErrors()`
see https://issues.openmrs.org/browse/TRUNK-4915

TRUNK-4915 Concept validator should require datatype and conceptClass fields

---

api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneQuery.java
api/src/test/java/org/openmrs/api/ConceptServiceTest.java

The skipSame-method in LuceneQuery generates a new instance of
fullTextQuery even if there are no search results. In this way all
concepts will be returned without filtering them.
* only call buildQuery() in skipSame when results were found
* add test to ConceptServiceTest
see https://issues.openmrs.org/browse/TRUNK-4922

TRUNK-4922 ConceptDAO filters concept classes only if results were found

---

api/src/main/resources/org/openmrs/api/db/hibernate/Concept.hbm.xml

Removed the not-null requirement from the many-to-many relationship on the changedBy column. Confirmed against a newly generated Concept.hbm.xml that this constraint doesn't belong.
Build Success.
All tests passed.
No new tests required.

TRUNK-4913 Concept.hbm.xml not-null on optional changedBy

---

api/src/main/java/org/openmrs/Obs.java
api/src/test/java/org/openmrs/ObsTest.java

The Dirty Flag should not be set for new Obs that are still not saved in the database.  Refer to the design form [here](https://notes.openmrs.org/2016-09-15-Developers-Forum) and the talk [here](https://talk.openmrs.org/t/openmrs-2-0-saving-visit-saves-the-encounters-under-it-but-not-the-obs-of-the-encounters/7925/34).
see https://issues.openmrs.org/browse/TRUNK-4942

TRUNK-4942 - Dirty Flag should not be set for new obs

---

api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
api/src/main/resources/messages.properties
api/src/test/java/org/openmrs/api/ObsServiceTest.java

TRUNK-4944
This PR refactors the existing org.openmrs.api.ObsService#saveObs(org.openmrs.Obs, String).  No additional functionality is added in this PR.  The subsequent PRs will add a fix for the saving the childObs if it is dirty and not the complete obs hierarchy as mentioned by @bmamlin [here](org.openmrs.api.ObsService#saveObs(org.openmrs.Obs, String))
- [x ] My pull request only contains one single commit.

Refactored obsService#saveObs(org.openmrs.Obs,String)

---

api/src/main/resources/liquibase-update-to-latest.xml

Addition to previous PR for TRUNK-4936:
Only add new column uniqueId if it doesnt already exist in table
concept_reference_source
see https://issues.openmrs.org/browse/TRUNK-4936

TRUNK-4936 Add precondition for addcolumn changeset

---

api/src/main/java/org/openmrs/validator/ConceptSourceValidator.java
api/src/main/resources/org/openmrs/api/db/hibernate/ConceptSource.hbm.xml
api/src/test/java/org/openmrs/api/ConceptServiceTest.java
api/src/test/java/org/openmrs/validator/ConceptSourceValidatorTest.java

Fixes ConceptSourceValidator which does not fail if "description" is
empty altough the description column is required.
* add not-null="true" to name and description fields in ConceptSource.hbm.xml
* Validator now fails on empty "description"
see https://issues.openmrs.org/browse/TRUNK-4953

TRUNK-4953 ConceptSourceValidator doesnt fail on empty description

---

api/src/main/resources/liquibase-update-to-latest.xml

Some integration-test's failed on h2 due to the introduced liquibase changeset
for TRUNK-4936. ALTER TABLE sql statement generated by h2 contains a
syntax error. h2 does only seem to handle unique constraints well when
creating the table, or on its own and not when adding the column.
* remove the nested <constraints> element from the changeset
* use addColumn and addUniqueConstraint
see https://issues.openmrs.org/browse/TRUNK-4936

TRUNK-4936 Fix integration-test on h2 due to liquibase changeset

---

.travis.yml
api/pom.xml
pom.xml
web/pom.xml

* add jacoco maven plugin for generating coverage reports
* add coveralls maven plugin to send jacoco reports to coveralls.io
* add travis after_success command to send jacoco reports to
coveralls.io after successful builds
* jacoco and coverals are configured in root pom pluginmanagement
* jacoco generates coverage for api and web projects
see https://issues.openmrs.org/browse/TRUNK-1916

TRUNK-1916 Code coverage and Test report for OpenMRS

---

api/src/main/java/org/openmrs/Obs.java
api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
api/src/test/java/org/openmrs/ObsTest.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java
api/src/test/java/org/openmrs/api/ObsServiceTest.java
api/src/test/resources/org/openmrs/api/include/EncounterServiceTest-saveObsHierarchyTests.xml
api/src/test/resources/org/openmrs/api/include/ObsServiceTest-EncounterOverwrite.xml

TRUNK-4944
This PR fixes the cloning of parent obs when a child (leaf) obs is edited.   The following are the things that are done
- Removed setting the dirty flag when obs.setGroupMembers(), obs.addGroupMember() and obs.removeGroupMember() is called
- EncounterService.saveEncounter() will use encounter.getObsAtTopLevel() so that we just pick up the top level obs.  Saving a top level obs using obsService.saveObs() will take care of individually saving the leaf obs.
- Added integration tests for various obs hirearchies and saving of obs at different levels - leaf, middle level, top level and peer at top level
see https://issues.openmrs.org/browse/TRUNK-4944

Fix for editing a child obs makes the parent obs dirty and creates a new instance

---

web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java

Password values were pre-filled in the installation wizard UI because they were stored in the wizardModel. I interpreted "run the installation wizard" to mean any access where the hidden page variable was not set. In that case we set all password entries in the model back to an empty string.
I was not able to find working tests for the InstallationWizard. It appears that UI tests are non-working ... probably because most of the UI was moved to a module.

TRUNK-2877 Don't set password values in the UI in the installation wizard

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
api/src/test/java/org/openmrs/api/db/PatientDAOTest.java
api/src/test/resources/org/openmrs/api/db/hibernate/include/HibernatePatientDAOTest-patients.xml

TRUNK-4949 Patient Merge - HibernatePatientDAO - getDuplicatePatientsByAttributes - Not performing on large database 
Modified the getDuplicatePatientsByAttributes method to:
1. have a group by + having count greater than 1 clause to identify duplicate patient IDs using native sql 
2. Then using the patient IDs identified in step 1 fetching Patients using HQL instead of all the self joins which was was case earlier.
see https://issues.openmrs.org/browse/TRUNK-4949

Trunk 4949

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
api/src/test/java/org/openmrs/api/db/EncounterDAOTest.java
api/src/test/resources/org/openmrs/api/db/include/EncounterDAOTest-initialData.xml

1. Added a new patient identifier to the encounter test file with strings instead of numeric. 
2. Added a test that fails.
TRUNK-4720: createEncounterQuery now no longer assumes that identifiers always contain digits. Refactored the method. Added a test to make sure that partial identifiers would not be matched.
see https://issues.openmrs.org/browse/TRUNK-4720

TRUNK-4720 createEncounterQuery now no longer assumes that identifiers always contain digits.

---

api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
api/src/main/java/org/openmrs/api/order/exceptions/CannotDeleteOrderPropertyInUseException.java
api/src/main/java/org/openmrs/api/order/exceptions/CannotDiscontinueAlreadyDiscontinuedOrderException.java
api/src/main/java/org/openmrs/api/order/exceptions/CannotDiscontinueOrderWithActionException.java
api/src/main/java/org/openmrs/api/order/exceptions/CannotEditAlreadyExistingOrderException.java
api/src/main/java/org/openmrs/api/order/exceptions/CannotEditOrderPropertyInUseException.java
api/src/main/java/org/openmrs/api/order/exceptions/CannotStopRetrospectiveDiscontinuedOrderException.java
api/src/main/java/org/openmrs/api/order/exceptions/CannotUnvoidOrderException.java
api/src/main/java/org/openmrs/api/order/exceptions/EditedOrderDoesNotMatchPreviousException.java
api/src/main/java/org/openmrs/api/order/exceptions/InvalidOrderException.java
api/src/main/java/org/openmrs/api/order/exceptions/PreviousOrderRequiredException.java
api/src/main/java/org/openmrs/api/order/exceptions/UnchangeableOrderPropertyException.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

Modifying some Order Exception definitions to be more in line with the messages.properties. Fixing test to map to these new definitions.
- [ x] My pull request only contains one single commit.
- [ x] My pull request is based on the latest master branch
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

TRUNK-4696: added specific exception classes for the Order Service

---

api/src/main/java/org/openmrs/util/OpenmrsUtil.java

see https://issues.openmrs.org/browse/TRUNK-4957

TRUNK-4957: Removed code duplication in OpenmrsUtil class

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java

Added @Override annotation to the below methods of org.openmrs.api.db.hibernate.HibernatePatientDAO.java
01.getPatient
02.savePatient
03.getAllPatients
04.deletePatientIdentifierType
05.getPatientIdentifiers
06.savePatientIdentifierType
07.deletePatient
08.getPatientIdentifierType
09.getAllPatientIdentifierTypes
10.getPatientIdentifierTypes
11.getDuplicatePatientsByAttributes
12.getPatientByUuid
13.getPatientIdentifierByUuid
14.getPatientIdentifierTypeByUuid
15.isIdentifierInUseByAnotherPatient
16.getPatientIdentifier
17.savePatientIdentifier
18.deletePatientIdentifier
19.getCountOfPatients
20.getCountOfPatients
21.getAllergies
22.getAllergyStatus
23.getAllergy
24.getAllergyByUuid
I haven't implemented the feature completely. But I started working on it.
see …

TRUNK-4839: Exposing Patient Search Options Via UI

---

api/pom.xml
api/src/main/java/org/openmrs/api/AdministrationService.java
api/src/main/java/org/openmrs/api/impl/AdministrationServiceImpl.java
api/src/main/java/org/openmrs/api/impl/LocationServiceImpl.java
api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/main/resources/api-ehcache.xml
api/src/main/resources/applicationContext-service.xml
api/src/main/resources/ehcache.xml
api/src/main/resources/hibernate.default.properties
api/src/test/java/org/openmrs/api/AdministrationServiceTest.java
pom.xml

This PR introduces Spring's caching functionality to OpenMRS. As proof of concept, results of `getSearchLocales` are cached. 
We couldn't use annotation driven cache configuration, because we are still using old `TransactionProxyFactoryBean` to handle transactions, so CacheInterceptor is added to preInterceptors of `TransactionProxyFactoryBean`, to handle cache. More info can be found [in Spring documentation](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html).
~~In long run, we probably will want to replace SimpleCacheManager with EhCacheManager, but I couldn't properly inject it, I guess HIbernate's second level cache ehCache is colliding with it, because when it was disabled, I was able to register my API EhCacheManager~~
I managed to set up ehcache …

TRUNK-3675 Introduce caching to getSearchLocales()

---

api/src/main/resources/ehcache.xml
api/src/main/resources/org/openmrs/api/db/hibernate/Privilege.hbm.xml

Enabled hibernate second level cache for org.openmrs.Privilege
see https://issues.openmrs.org/browse/TRUNK-4980

TRUNK-4980 | Add Hibernate second level cache for Privilege

---

api/src/main/resources/liquibase-update-to-2.1.xml

TRUNK-4906 Adding unique constraint to cohort_member uuid
Adding unique constraint to the cohort_member column uuid
see https://issues.openmrs.org/browse/TRUNK-4906

TRUNK-4906 Adding unique constraint to cohort_member uuid

---

api/src/main/java/org/openmrs/Patient.java
api/src/main/java/org/openmrs/Person.java
api/src/test/java/org/openmrs/PersonTest.java

Changed `Person` copying constructor so that it makes deep copy of an object. This includes also sets of addresses, names and attributes. To achieve those `deepCopy()` functions were added to `PersonAddress`, `PersonName` and `PersonAttribute`. 
Fields of following data types are deep copied:
- String
- Integer
- Date
- Boolean
- Set and each element in it
- PersonAddress
- PersonName
- PersonAttribute
Fields of following data types are shallow copied:
- User
- Person
- PersonAttributeType
- Concept
Two new classes were added:
- `DeepCopyUtil` - provides helper functions to make deep copies of `String`, `Date`, `Integer`, and `Boolean` objects
- `DeepCopyUtilTestHelper` - via reflection tests if all private (non-static, non-final) fields of a class and its super classes are properly …

TRUNK-4925 Deep copy all fields of Person

---

api/src/main/java/org/openmrs/api/ObsService.java

Deprecated the method and added a @deprecated javadoc comment pointing to existing method.
Please check and let me know if any changes are to be made.
https://issues.openmrs.org/browse/TRUNK-4994

TRUNK-4994 Possibly remove this method

---

api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java

TRUNK-4991:  Check patient has at least one sufficient identifier
Remove useless TODO -> Check patient has at least one sufficient identifier
see https://issues.openmrs.org/browse/TRUNK-4991

TRUNK-4991: Check patient has at least one sufficient identifier

---

api/src/main/java/org/openmrs/util/OpenmrsUtil.java
api/src/test/java/org/openmrs/util/OpenmrsUtilTest.java

I replaced custom implementation of copy file in OpenmrsUtil.copyFile(...) with the apache commons IOUtils.copy(...). This is for reducing the code. I also added 3 tests for testing above functionality. I also decided to change method return type from void to boolean. It didnt change usage of method but helped with testing.
see https://issues.openmrs.org/browse/TRUNK-4958

TRUNK-4958: Refactored OpenmrsUtil.copyFile method

---

api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
api/src/test/java/org/openmrs/api/ObsServiceTest.java
api/src/test/resources/org/openmrs/api/include/ObsServiceTest-initial.xml

The line of code which is used to evict obs from session is causing the issue as it doesn't evict its children. Hence written a recursive method which is called to evict Obs, and its children also from session.
https://issues.openmrs.org/browse/TRUNK-5019
1.Edit an existing observation so that all the observations are dirty and there is a new obs added as a child at depth >1 i.e 
If A->B->C is the obs tree, then add new obs D under B.
Expected : New A(B(CD)) obs tree will be created.
Actual : New A(B(CD)) obs tree is created but D is voided.

TRUNK-5019 Error Scenario in Obs Save : New child Obs not saving when entire Obs group is updated

---

api/src/main/java/org/openmrs/Encounter.java
api/src/test/java/org/openmrs/EncounterTest.java

before removing a provider a check has been added to see if it has already been voided or not. added test case.
see: https://issues.openmrs.org/browse/TRUNK-5017

TRUNK-5017 Encounter.removeProvider fails if same provider has already been removed once before

---

api/src/main/java/org/openmrs/api/ConceptService.java
api/src/main/java/org/openmrs/api/db/ConceptDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
api/src/test/java/org/openmrs/api/ConceptServiceTest.java

Added method to return conceptService using hl7Code as a param.
Added tests to check for NULL values and also obtain an expected ConceptSource when given a valid hl7Code.
ConceptService.getConceptSourceByHL7Code(String)
see https://issues.openmrs.org/browse/TRUNK-4947
- [ x] My pull request only contains one single commit.
- [ x] My pull request is based on the latest master branch
- [x ] My code follows the code style of this project.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

TRUNK-4947 Add ConceptService.getConceptSourceByHL7Code(java.lang.String)

---

api/src/main/java/org/openmrs/Encounter.java
api/src/main/java/org/openmrs/PatientProgram.java
api/src/main/java/org/openmrs/Role.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java
api/src/main/java/org/openmrs/api/handler/PersonSaveHandler.java
api/src/main/java/org/openmrs/api/impl/DatatypeServiceImpl.java
api/src/main/java/org/openmrs/api/impl/FormServiceImpl.java
api/src/main/java/org/openmrs/api/impl/ProgramWorkflowServiceImpl.java
api/src/main/java/org/openmrs/api/impl/VisitServiceImpl.java
api/src/main/java/org/openmrs/hl7/handler/ADTA28Handler.java
api/src/main/java/org/openmrs/hl7/handler/ORUR01Handler.java
api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
api/src/main/java/org/openmrs/logic/result/Result.java
api/src/main/java/org/openmrs/messagesource/impl/MutableResourceBundleMessageSource.java
api/src/main/java/org/openmrs/propertyeditor/WorkflowCollectionEditor.java
api/src/main/java/org/openmrs/util/DatabaseUpdater.java
api/src/main/java/org/openmrs/util/databasechange/CheckDrugOrderUnitAndFrequencyTextNotMappedToConcepts.java
api/src/main/java/org/openmrs/validator/ConceptValidator.java
web/src/main/java/org/openmrs/web/filter/update/UpdateFilterModel.java

Replaced all the other ways of checking if size is 0 by using isEmpty() function
see https://issues.openmrs.org/browse/TRUNK-5030

TRUNK-5030 Collection.isEmpty() should be used to test for emptiness

---

api/src/main/java/org/openmrs/api/EventListeners.java
api/src/main/java/org/openmrs/hl7/HL7Util.java
api/src/main/java/org/openmrs/logic/LogicTransform.java
api/src/main/java/org/openmrs/logic/result/Result.java
api/src/main/java/org/openmrs/module/Module.java
api/src/main/java/org/openmrs/module/ModuleClassLoader.java
api/src/main/java/org/openmrs/util/DoubleRange.java
api/src/main/java/org/openmrs/util/OpenmrsUtil.java
api/src/main/java/org/openmrs/util/Security.java
api/src/main/java/org/openmrs/util/databasechange/SourceMySqldiffFile.java
web/src/main/java/org/openmrs/module/web/WebModuleUtil.java

Replaced instances of synchronized class StringBuffer with unsynchronized class StringBuilder
where StringBuffer is used for local variables in which the state will not be shared among threads and thus the synchronization is not needed.
see https://issues.openmrs.org/browse/TRUNK-5038

TRUNK-5038 Replace StringBuffer with StringBuilder

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java

Added a check to see if size of list is zero and then logged a warning "No concept found..."
see https://issues.openmrs.org/browse/TRUNK-5036

TRUNK - 5036 HibernateConceptDAO.getConceptByName() method logs incorrect warning message

---

api/src/main/java/org/openmrs/Encounter.java

TRUNK-5075 EncounterTest random failures
There is a certain build failure that occurs randomly. Here is the maven build error : 
Failed tests: 
EncounterTest.getObsAtTopLevel_shouldGetObsInTheSameOrderObsIsAddedToTheEncounter:195 expected:<[secon]d obs> but was:<[thir]d obs>
see https://issues.openmrs.org/browse/TRUNK-5075

TRUNK-5075 EncounterTest random failures

---

README.md

the travis ci badge in the readme was a png which is why it looked to
blurry in comparison to the other badges which are all svg.

make travis ci badge in readme svg

---

web/src/main/resources/org/openmrs/web/filter/initialization/progress.vm

I have added a bit of code which ensures that the last progress bar during the installation does not cross 99% so as to avoid confusion caused among the implementors
see https://issues.openmrs.org/browse/TRUNK-4018

TRUNK-4018 Initial Setup (installer) sits at 100% too long before actually finishing

---

api/src/main/java/org/openmrs/obs/handler/AbstractHandler.java
api/src/test/java/org/openmrs/api/ObsServiceTest.java

modified:   api/src/main/java/org/openmrs/obs/handler/AbstractHandler.java
This unit test was throwing an APIException prior to the change.
modified:   api/src/test/java/org/openmrs/api/ObsServiceTest.java

TRUNK-5077: AbstractHandler doesn't fail to purge obs with missing file.

---

checkstyle.xml

we already flag unused imports using codacy but the rule is currently
manually configured in the codacy UI using the PMD checker.
* add the checkstyle rule which flags introduction of UnusedImports as
error so we keep the style in the repository and do not rely on manual
configurations in codacy
see https://issues.openmrs.org/browse/TRUNK-5085

TRUNK-5085 Add checkstyle rule UnusedImports

---

api/src/test/java/org/openmrs/api/ObsServiceTest.java

Second commit to align the new test case added in `ObsServiceTest` with what was pushed on all other branches (1.10.x, 1.11.x, 1.12.x and 2.0.x).
https://issues.openmrs.org/browse/TRUNK-5077

TRUNK-5077: Aligning ObsServiceTest with branch 2.0.x.

---

api/src/main/java/org/openmrs/api/impl/OrderSetServiceImpl.java

TRUNK-5056: To Increase readability replaced  org.springframework.util.StringUtils.hasLength to apache StringUtils.isBlank
Replaced org.springframework.util.StringUtils.hasLength used in
https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/api/impl/OrderSetServiceImpl.java#L48
with the apache commons StringUtils.isEmpty to increase readability. apache StringUtils.isBlank returns true is the given string is null, whitespace(" ") or empty("") values 
https://issues.openmrs.org/browse/TRUNK-5056
- [x ] All new and existing tests passed.

TRUNK-5056:Use apache StringUtils in OrderSetServiceImpl

---

api/src/main/java/org/openmrs/BaseCustomizableMetadata.java
api/src/main/java/org/openmrs/api/context/Context.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
api/src/main/java/org/openmrs/messagesource/PresentationMessageMap.java
web/src/main/java/org/openmrs/module/web/WebModuleUtil.java

The use of a fully qualified name which is covered by an import statement is redundant.
Use the non-fully qualified name.
see https://issues.openmrs.org/browse/TRUNK-5097

TRUNK-5097 Unnecessary fully qualified name

---

api/src/test/java/org/openmrs/api/OpenmrsServiceTest.java
api/src/test/java/org/openmrs/api/ProviderServiceTest.java
api/src/test/java/org/openmrs/api/UserServiceTest.java
api/src/test/java/org/openmrs/attribute/AttributeIntegrationTest.java
api/src/test/java/org/openmrs/layout/name/NameTemplateTest.java
api/src/test/java/org/openmrs/propertyeditor/ConceptAnswersEditorTest.java
api/src/test/java/org/openmrs/test/StartModuleAnnotatioTest.java
api/src/test/java/org/openmrs/util/DrugsByNameComparatorTest.java
api/src/test/java/org/openmrs/util/ReflectTest.java
web/src/test/java/org/openmrs/web/filter/update/util/FilterUtilTest.java

used eclipse cleanup feature on all packages, now tests are also clean
of unused imports and are organized according to our convention
see https://issues.openmrs.org/browse/TRUNK-5086

TRUNK-5086 Remove unused and organize imports in tests

---

README.md

the wiki page on IDE setup got a new landing page which links to
different IDEs

fix link in readme to IDE setup

---

api/src/main/java/org/openmrs/Patient.java
api/src/main/java/org/openmrs/Person.java
api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
api/src/main/java/org/openmrs/api/impl/PersonServiceImpl.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java
api/src/test/java/org/openmrs/api/PersonServiceTest.java

Replace use of PersonAdress/PatientIdentifier/PersonName/RelationshipType.isPreferred
which is deprecated with getPreferred
see https://issues.openmrs.org/browse/TRUNK-5106

TRUNK-5106 Replace use of deprecated isPreferred

---

api/src/main/java/org/openmrs/validator/PersonValidator.java

* replace use of log4j with slf4j logging facade in PersonValidator
* use parametrized message with log.debug which avoids superfluous
object creation when the logger is disabled for the DEBUG level and
removes if clause which causes a double check for wether DEBUG level is
enabled
see https://issues.openmrs.org/browse/TRUNK-5114

 TRUNK-5114 Using different logging implementations instead of facade

---

api/src/main/java/org/openmrs/Person.java
api/src/main/java/org/openmrs/api/handler/PersonSaveHandler.java
api/src/main/java/org/openmrs/api/handler/PersonUnvoidHandler.java
api/src/main/java/org/openmrs/api/handler/PersonVoidHandler.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java
api/src/test/java/org/openmrs/api/handler/PersonUnvoidHandlerTest.java
api/src/test/java/org/openmrs/api/handler/PersonVoidHandlerTest.java

replace use of Person.isPersonVoided which
is deprecated in favor of getPersonVoided
see https://issues.openmrs.org/browse/TRUNK-5104

TRUNK-5104 Replace use of Person.isPersonVoided

---

api/src/main/java/org/openmrs/BaseOpenmrsData.java
api/src/main/java/org/openmrs/Encounter.java
api/src/main/java/org/openmrs/Voidable.java
api/src/main/java/org/openmrs/api/handler/UnvoidHandler.java
api/src/main/java/org/openmrs/api/handler/VoidHandler.java
api/src/test/java/org/openmrs/api/UserServiceTest.java
api/src/test/java/org/openmrs/api/handler/BaseUnvoidHandlerTest.java
api/src/test/java/org/openmrs/api/handler/BaseVoidHandlerTest.java

some javadocs, comments were still referencing the deprecated isVoided
see https://issues.openmrs.org/browse/TRUNK-5111

TRUNK-5111 Replace refs to deprecated isVoided in javadocs

---

pom.xml
tools/src/main/resources/eclipse/templates.xml
tools/src/main/resources/intellij/templates.xml

in preparation of the move away from the custom @should annotations and
the need for the test generator plugin add eclipse and intellij templates
to quickly create the scaffold for unit tests
* add template for creating @Before setUp()
* add template for creating @Test for standard unit test
* add template for creating @Test for unit test testing that a method
throws a certain exception with the org.junit.rules.ExpectedException
also added templates for logging to help get rid of the confusion
when logging. people use commons or log4j instead of the logging facade
slf4j
* add template for declaring slf4j Logger for a class
* add templates for standard log.info/debug/warn/error
* add templates for parametrized log.info/debug/warn/error
meaning log.info("some message {}", myParameter)

Add eclipse and intellij templates for unit tests

---

tools/src/main/resources/eclipse/templates.xml
tools/src/main/resources/intellij/templates.xml

remove the 'methodName_' part of the test and testException
code templates for Intellij and Eclipse

Update IDE test code templates to match conventions

---

api/src/test/java/org/openmrs/validator/AlertValidatorTest.java

* arrange test implementations in a arrange, act, assert style (or what
we often called the given,when,then) so its clear to see whats been
tested and what the outcome should be
* split test that tested null/empty/whitespace of alert text in a
single test as these are independent

Extract setUp and clean AlertValidatorTest

---

api/src/test/java/org/openmrs/validator/AllergyValidatorTest.java

fixed errors in AllergyValidatorTest's, a few tests where just
asserting that the "allergen" field had an error but not the actual
code which lead to the fact that a few paths where not tested because the
Allergy passed in did not match the test expectations (either the
Allergen was null or the AllergenType of the Allergen not set)
* fixed test 'shouldFailIdAllergenTypeIsNull' which passed because
due to "allergyapi.allergen.required" coming from Allergen being null
not from the AllergenType
added assertion for the correct error code and passed in an Allergen to the
Allergy with no AllergenType
* arrange test implementations in a arrange, act, assert style (or what
we often called the …

Extract setUp and fix tests in AllergyValidatorTest

---

api/src/test/java/org/openmrs/validator/BaseAttributeTypeValidatorTest.java

* replace the VisitAttributeTypeValidator with an implementation added
to this test class. Reason is the VisitAttributeTypeValidator does some
things before calling super.validate which prevents us from testing
validate(null, errors)
* add test for validate(null, errors)
* add test for minOccurs < 0
* add test for datatypeConfig is blank when of type RegexValidatedTextDatatype
* rename test shouldRequireDatatypeConfigurationIfDatatypeEqualsRegexValidatedText
which was actually testing the datatypeConfig.invalid path
* add test for wrong preferred handler type
* add test for invalid handlerConfig
* arrange tests to match code so reading code/test side by side is easy
* move happy path to the end

Clean and add tests to BaseAttributeTypeValidatorTest

---

tools/src/main/resources/eclipse/templates.xml
tools/src/main/resources/intellij/templates.xml

there is no need for the throws Exception clauses in the tests
therefore removed it from the intellij and eclipse templates

Remove throws Exception from IDE code templates

---

api/src/test/java/org/openmrs/test/Verifies.java
checkstyle.xml

all usages of @Verifies and @verifies were removed in TRUNK-5122
and thus @Verifies is deprecated and flagged using checkstyle
see https://issues.openmrs.org/browse/TRUNK-5135

TRUNK-5135 Deprecate @Verifies

---

api/src/test/java/org/openmrs/test/matchers/HasFieldErrors.java
api/src/test/java/org/openmrs/test/matchers/HasFieldErrorsTest.java
api/src/test/java/org/openmrs/validator/PersonNameValidatorTest.java

* add a custom hamcrest matcher HasFieldError which enables
assertThat(errors, hasFieldError());
assertThat(errors, hasFieldError("text"));
assertThat(errors, hasFieldError("text", "error.null"));
* matcher has factories which enables the above after static imports of
the matcher
* show use of matcher in PersonNameValidatorTest
see https://issues.openmrs.org/browse/TRUNK-5136

TRUNK-5136 Add custom hamcrest matcher HasFieldError

---

api/src/main/java/org/openmrs/api/db/hibernate/PatientSearchCriteria.java

The `PatientSearchCriteria` class is deprecated. This TODO is on a private method, called by another private method, called by the helper method `prepareCriteria`. This method is only called in one place, `HibernateEnounterDAO` which doesn't pass in the parameter that would lead to this line of code being executed.
Therefore, we think the code is not used and the test is not required.
@annashipman @davbo @TheDoubleK
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && …

TRUNK-248: Remove TODO from deprecated and unused code

---

api/src/test/java/org/openmrs/test/matchers/HasGlobalErrors.java
api/src/test/java/org/openmrs/test/matchers/HasGlobalErrorsTest.java
api/src/test/java/org/openmrs/validator/ConceptValidatorTest.java
api/src/test/java/org/openmrs/validator/PersonNameValidatorTest.java

Add a custom hamcrest matcher HasGlobalErrors which enables
assertThat(errors, hasGlobalErrors());
assertThat(errors, hasGlobalErrors("error.null"));
Provide factories which enables the above after static imports of
the matcher.
Show use of matcher in PersonNameValidatorTest and ConceptValidatorTest
see https://issues.openmrs.org/browse/TRUNK-5137

TRUNK-5137 Add custom hamcrest matcher HasGlobalError

---

api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
api/src/main/java/org/openmrs/api/impl/LocationServiceImpl.java
api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
api/src/main/java/org/openmrs/api/impl/PersonServiceImpl.java
api/src/main/java/org/openmrs/api/impl/ProviderServiceImpl.java
api/src/main/java/org/openmrs/api/impl/VisitServiceImpl.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java
api/src/test/java/org/openmrs/api/ProviderServiceTest.java

made changes to unretireXXX() and unvoidXXX() methods such that they call save methods on  spring proxy object obtained from calling Context.getXXXService().
see https://issues.openmrs.org/browse/TRUNK-4916

TRUNK-4916 Validators should be called when unretiring/unvoiding an object

---

api/src/main/java/org/openmrs/util/UpgradeUtil.java

UpgradeUtil may not close a stream.
Wrapped PreparedStatements into try-with-resources as well in order to simplify and close the preparedStatement automatically. 
see https://issues.openmrs.org/browse/TRUNK-5031
Test cases were not changed. Can not add a new test case to capture the scenario of **UpgradeUtil#getConceptIdForUnits** getting the file stream being opened as there is …

TRUNK-5031 UpgradeUtil may not close a stream

---

api/src/test/java/org/openmrs/propertyeditor/ConceptMapTypeEditorTest.java
api/src/test/java/org/openmrs/propertyeditor/ConceptReferenceTermEditorTest.java

added
ConceptMapTypeEditorTest.java
ConceptReferenceTermEditorTest.java
see https://issues.openmrs.org/browse/TRUNK-5139

TRUNK-5139 Add tests

---

api/src/main/java/org/openmrs/propertyeditor/ConceptMapTypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/ConceptReferenceTermEditor.java
api/src/main/java/org/openmrs/propertyeditor/PersonEditor.java

remove check if OpenmrsObject.id is null in getAsText() in case the object is not null
since its the PK and its guaranteed to be not null.
see https://issues.openmrs.org/browse/TRUNK-5158

TRUNK-5158 PropertyEditors check for null primary key in getAsText

---

api/src/main/java/org/openmrs/propertyeditor/ConceptAttributeTypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/LocationAttributeTypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/LocationTagEditor.java

Remove isAuthenticated check in PropertyEditors.setAsText()
ConceptAttributeTypeEditor.java
LocationAttributeTypeEditor.java
LocationTagEditor.java
which is not needed
see https://issues.openmrs.org/browse/TRUNK-5159

TRUNK-5159 Remove isAuthenticated check in PropertyEditors

---

api/src/main/java/org/openmrs/propertyeditor/ProgramWorkflowStateEditor.java
api/src/test/java/org/openmrs/propertyeditor/ProgramWorkflowStateEditorTest.java

the catch block will never be reached since getByUuid() just returns
null if nothing is found. The exception in the try block is normally
thrown by Integer.valueOf() if the text is a uuid and not a number
* use getState(Integer) first to try to get the ProgramWorkflowState by
its id
* is text is not an Integer, the exception in Integer.valueOf will lead
to the catch block being executed which then tries to fetch by the uuid
* added tests
see https://issues.openmrs.org/browse/TRUNK-5154

TRUNK-5154 ProgramWorkflowStateEditor tries to get state by uuid twice

---

api/src/main/java/org/openmrs/propertyeditor/ConceptAttributeTypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/LocationAttributeTypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/LocationEditor.java
api/src/main/java/org/openmrs/propertyeditor/LocationTagEditor.java
api/src/test/java/org/openmrs/propertyeditor/ConceptAttributeTypeEditorTest.java
api/src/test/java/org/openmrs/propertyeditor/LocationAttributeTypeEditorTest.java
api/src/test/java/org/openmrs/propertyeditor/LocationEditorTest.java
api/src/test/java/org/openmrs/propertyeditor/LocationTagEditorTest.java

ConceptAttributeTypeEditor.java
LocationAttributeTypeEditor.java
LocationEditor.java
LocationTagEditor.java
which where the only ones returning null, in ~37 PropertyEditors
see https://issues.openmrs.org/browse/TRUNK-5162

TRUNK-5162 Few PropertyEditor getAsText return null if value is null

---

api/src/main/java/org/openmrs/propertyeditor/CohortEditor.java
api/src/main/java/org/openmrs/propertyeditor/ConceptAnswerEditor.java
api/src/main/java/org/openmrs/propertyeditor/ConceptAttributeTypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/ConceptClassEditor.java
api/src/main/java/org/openmrs/propertyeditor/ConceptDatatypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/ConceptEditor.java
api/src/main/java/org/openmrs/propertyeditor/ConceptNameEditor.java
api/src/main/java/org/openmrs/propertyeditor/ConceptNumericEditor.java
api/src/main/java/org/openmrs/propertyeditor/ConceptSourceEditor.java
api/src/main/java/org/openmrs/propertyeditor/DrugEditor.java
api/src/main/java/org/openmrs/propertyeditor/EncounterEditor.java
api/src/main/java/org/openmrs/propertyeditor/EncounterTypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/FormEditor.java
api/src/main/java/org/openmrs/propertyeditor/LocationAttributeTypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/LocationEditor.java
api/src/main/java/org/openmrs/propertyeditor/LocationTagEditor.java
api/src/main/java/org/openmrs/propertyeditor/OpenmrsPropertyEditor.java
api/src/main/java/org/openmrs/propertyeditor/OrderEditor.java
api/src/main/java/org/openmrs/propertyeditor/PatientEditor.java
api/src/main/java/org/openmrs/propertyeditor/PatientIdentifierTypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/PersonAttributeEditor.java
api/src/main/java/org/openmrs/propertyeditor/PersonAttributeTypeEditor.java
api/src/main/java/org/openmrs/propertyeditor/ProgramWorkflowEditor.java
api/src/main/java/org/openmrs/propertyeditor/ProgramWorkflowStateEditor.java
api/src/main/java/org/openmrs/propertyeditor/UserEditor.java
api/src/main/java/org/openmrs/propertyeditor/VisitEditor.java
api/src/main/java/org/openmrs/propertyeditor/VisitTypeEditor.java

Add abstract OpenmrsPropertyEditor for OpenmrsObject's
which tries to get an object via its id and if that fails via its uuid
Let
CohortEditor.java
ConceptAnswerEditor.java
ConceptAttributeTypeEditor.java
ConceptClassEditor.java
ConceptDatatypeEditor.java
ConceptEditor.java
ConceptNameEditor.java
ConceptNumericEditor.java
ConceptSourceEditor.java
DrugEditor.java
EncounterEditor.java
EncounterTypeEditor.java
FormEditor.java
LocationAttributeTypeEditor.java
LocationEditor.java
LocationTagEditor.java
OpenmrsPropertyEditor.java
OrderEditor.java
PatientEditor.java
PatientIdentifierTypeEditor.java
PersonAttributeEditor.java
PersonAttributeTypeEditor.java
ProgramWorkflowEditor.java
ProgramWorkflowStateEditor.java
UserEditor.java
VisitEditor.java
VisitTypeEditor.java
extend OpenmrsPropertyEditor. …

TRUNK-5164 Add abstract OpenmrsPropertyEditor

---

api/src/main/java/org/openmrs/propertyeditor/ConceptMapTypeEditor.java
api/src/test/java/org/openmrs/propertyeditor/ConceptMapTypeEditorTest.java

ConceptMapTypeEditor does not try getting the object via uuid after it failed
to get it via its id although the service provides the method.
This is usually done (>30 editors for OpenmrsObjects).
see https://issues.openmrs.org/browse/TRUNK-5165

TRUNK-5165 ConceptMapTypeEditor does not get object via uuid

---

api/src/main/java/org/openmrs/propertyeditor/ConceptReferenceTermEditor.java
api/src/test/java/org/openmrs/propertyeditor/ConceptReferenceTermEditorTest.java

ConceptMapTypeEditor does not try getting the object via uuid after it failed to get it via its id
although the service provides the method. This is usually done (>30 editors for OpenmrsObjects).
see https://issues.openmrs.org/browse/TRUNK-5166

TRUNK-5166 ConceptReferenceTermEditorTest does not get object via uuid

---

api/src/main/java/org/openmrs/propertyeditor/PersonEditor.java
api/src/test/java/org/openmrs/propertyeditor/PersonEditorTest.java

PersonEditor does not throw an IllegalArgumentException if Person
is not found given text which is different than ~30 PropertyEditors for OpenmrsObjects
see https://issues.openmrs.org/browse/TRUNK-5167

TRUNK-5167 PersonEditor does not throw if Person not found

---

api/src/main/java/org/openmrs/util/MemoryLeakUtil.java
web/src/main/java/org/openmrs/web/Listener.java

Remove MemoryLeakUtil.shutdownKeepAliveTimer since its implementation
is based on a non-existing field and throws an exception on its first
line; also thereby remove a dependency on a sun package
see https://issues.openmrs.org/browse/TRUNK-5096

TRUNK-5096 Remove MemoryLeakUtil.shutdownKeepAliveTimer

---

api/src/main/java/org/openmrs/validator/PersonNameValidator.java

PersonNameValidator implements Validator so client code can call
validate to get the same behavior as calling validatePersonName which
should be made private in a major release
see https://issues.openmrs.org/browse/TRUNK-5174

TRUNK-5174 Deprecate PersonNameValidator.validatePersonName

---

web/src/test/java/org/openmrs/web/filter/update/UpdateFilterModelTest.java

add UpdateFilterModelTest since it was missing; needed to uses
PowerMockRunner since its calling static methods on DatabaseUpdater

Add UpdateFilterModelTest

---

api/src/main/java/org/openmrs/api/db/hibernate/DropMillisecondsHibernateInterceptor.java
api/src/test/java/org/openmrs/api/db/hibernate/DropMillisecondsHibernateInterceptorTest.java

Truncate milliseconds on if its a instance of Date and not Time
see https://issues.openmrs.org/browse/TRUNK-5183
No? …

TRUNK-5183 Not able to save data of java.sql.Time data type

---

api/src/test/java/org/openmrs/ConceptTest.java

replaced use of databene benerator from ConceptTest with constant names
of concepts since we only needed max of 2 different names per test
relying on this outdated or any fake data generator is overkill.
* also refactored the helper methods, removing the name 'mock' since we
are creating real instances of Concept/ConceptName and not mocks
see https://issues.openmrs.org/browse/TRUNK-5118

TRUNK-5118 Remove databene benerator from ConceptTest

---

api/src/main/java/org/openmrs/Concept.java
api/src/main/java/org/openmrs/ConceptName.java

Replaced nullSafeEquals with equals for enums
see https://issues.openmrs.org/browse/TRUNK-5195 …

TRUNK-5195 Do not use nullSafeEquals in ConceptName enum comparisons 

---

api/src/main/java/org/openmrs/util/Security.java
api/src/test/java/org/openmrs/util/SecurityTest.java
checkstyle.xml
web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
web/src/main/java/org/openmrs/web/filter/initialization/TestInstallUtil.java

replaced use of org.apache.xerces.impl.dv.util.Base64
with java8 Base64
added small refactorings TestInstallUtil.getResourceInputStream
* extracted private methods to improve readability
* renamed parameter
* use parametrized log message style and remove if since log.info
already checks for the log level
set checkstyle rule: Import from illegal package - org.apache.xerces
see https://issues.openmrs.org/browse/TRUNK-5205

TRUNK-5205 Use java8 Base64 instead of xerces

---

api/src/main/java/org/openmrs/annotation/OpenmrsProfileExcludeFilter.java
api/src/main/java/org/openmrs/module/ModuleClassLoader.java
api/src/test/java/org/openmrs/annotation/OpenmrsProfileExcludeFilterTest.java
api/src/test/java/org/openmrs/annotation/OpenmrsProfileExcludeFilterWithModulesTest.java
api/src/test/java/org/openmrs/annotation/OpenmrsProfileWithoutTest1Module.java
api/src/test/java/org/openmrs/module/ModuleClassLoaderTest.java
api/src/test/java/org/openmrs/test/StartModuleAnnotationTest.java
api/src/test/java/org/openmrs/test/StartModuleExecutionListener.java

`@OpenmrsProfile` loads Spring resources conditionally based on missing module(s)
https://issues.openmrs.org/browse/TRUNK-5213

TRUNK-5213: @OpenmrsProfile loads Spring resources conditionally based on missing module(s)

---

api/src/main/java/org/openmrs/annotation/OpenmrsProfileExcludeFilter.java
api/src/main/java/org/openmrs/module/ModuleClassLoader.java
api/src/test/java/org/openmrs/annotation/OpenmrsProfileExcludeFilterTest.java
api/src/test/java/org/openmrs/annotation/OpenmrsProfileWithoutTest1Module.java
api/src/test/java/org/openmrs/module/ModuleClassLoaderTest.java
api/src/test/java/org/openmrs/test/StartModuleAnnotationTest.java
api/src/test/java/org/openmrs/test/StartModuleExecutionListener.java
web/src/test/java/org/openmrs/annotation/OpenmrsProfileExcludeFilterWithModulesTest.java

`@OpenmrsProfile` loads Spring resources conditionally based on missing module(s)
https://issues.openmrs.org/browse/TRUNK-5213
`git pull --rebase upstream 1.9.x`.

TRUNK-5213: @OpenmrsProfile loads Spring resources conditionally based on missing module(s) 

---

api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java

The String.replace() method currently used takes two char values, so it only ever replaces one character with another (possibly multiple times, 'though).
The StringUtils.replace() method, on the other hand, takes String values as the search string and replacement, so it can replace longer substrings.
Hence, this can be replaced with StringUtils.replace as a solution to the above-mentioned bug.
TRUNK-5047 Replace duplication in UserServiceImpl by StringUtils

TRUNK-5047: Replace duplication in UserServiceImpl class by StringUtils

---

web/src/main/java/org/openmrs/web/filter/startuperror/StartupErrorFilter.java

Remove unused log from StartupErrorFilter
see https://issues.openmrs.org/browse/GCI-178
No? Unsure? -> execute command …

GCI-178: Remove unused log from StartupErrorFilter

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java

TRUNK-5123 getConceptByName should immediately return concept if only one matching concept
transformNamesToConcept now returns a LinkedHashSet to remove duplicate concepts,
and use this fact that every element is indeed unique in getConceptByName.
see https://issues.openmrs.org/browse/TRUNK-5123

TRUNK-5123 Change signature of transformNamesToConcepts to LinkedHashSet

---

web/src/main/java/org/openmrs/module/web/ModuleServlet.java

Changed ModuleServlet Logger to private static final
Issue: https://issues.openmrs.org/browse/GCI-182

GCI-182 ModuleServlet Logger should be "private static final"

---

web/src/main/java/org/openmrs/module/web/filter/ModuleFilterMapping.java

https://issues.openmrs.org/browse/GCI-190
GCI-190 ModuleFilterMapping Logger should be "private static final"

GCI-190: ModuleFilterMapping Logger should be "private static final"

---

api/src/test/java/org/openmrs/ObsTest.java
api/src/test/java/org/openmrs/test/MigrateDataSet.java

Since JDK8 we have more effcient class StringBuilder

[GCI-142] Replace StringBuffer with StringBuilder

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
api/src/main/java/org/openmrs/layout/LayoutTemplate.java
api/src/main/java/org/openmrs/util/databasechange/SourceMySqldiffFile.java
api/src/test/java/org/openmrs/LocationTest.java
api/src/test/java/org/openmrs/PersonTest.java
api/src/test/java/org/openmrs/api/ConceptServiceTest.java
api/src/test/java/org/openmrs/api/OrderSetServiceTest.java
api/src/test/java/org/openmrs/api/db/hibernate/HibernateObsDAOTest.java
api/src/test/java/org/openmrs/api/impl/PatientServiceImplTest.java
api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java

I've replaced Arrays.asList() (with one element) with .singletonList()
Using Arrays.asList() with one argument creates new List with allocated memory for 10! elements. Instead of this, .singletonList() allocates memory just for one element. So it saves a lot of memory :)

[GCI-142] Create List of one element by Arrays.singletonList()

---

api/src/main/java/org/openmrs/Allergies.java
api/src/main/java/org/openmrs/Encounter.java
api/src/main/java/org/openmrs/Form.java
api/src/main/java/org/openmrs/Role.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
api/src/main/java/org/openmrs/module/ModuleFactory.java
api/src/main/java/org/openmrs/module/ModuleUtil.java
api/src/main/java/org/openmrs/util/DatabaseUpdater.java
api/src/main/java/org/openmrs/util/Graph.java
api/src/test/java/org/openmrs/OrderTest.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java
api/src/test/java/org/openmrs/api/OrderSetServiceTest.java
web/src/main/java/org/openmrs/web/Listener.java

I've replaced Collection.addAll() call with passing collection's content to it's constructor
I didn't find addresses Sonar issue, but IntelliJ Inspector gave me that hint.
I hope it's redundant to do this:
`List<> list = new ArrayList<>();
list.addAll(someCollection);`
Rather, I would do it just in List constructor

[GCI-142] Delete redundant Collection.addAll() call (replaced with constructor)

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java
api/src/main/java/org/openmrs/module/ModuleFactory.java
api/src/main/java/org/openmrs/util/HandlerUtil.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java
api/src/test/java/org/openmrs/comparator/PatientIdentifierTypeDefaultComparatorTest.java
api/src/test/java/org/openmrs/util/UserByNameComparatorTest.java

We don't have to call Collections.sort helper method to sort collections. We can call sort() directly on it.

[GCI-142] Replace Collections.sort() with List.sort()

---

api/src/main/java/org/openmrs/module/ModuleFactory.java

Issue: https://issues.openmrs.org/browse/GCI-237
I see that this call should never be null in normal conditions. Therefore, I am using Objects.requireNonNull() to throw NPE if it's null.

[GCI-237] Guarantee moduleFolder.listFiles() to be non-null

---

api/src/main/java/org/openmrs/Cohort.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java

Issue: https://issues.openmrs.org/browse/TRUNK-5248
It's cleaner to call isEmpty() on a collection rather than checking if size() == 0.

[TRUNK-5248] Use isEmpty() than size() == 0

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateLocationDAO.java

Issue: https://issues.openmrs.org/browse/TRUNK-5249
I've replaced new Long() call with Long.valueOf() because it is more effcient

[TRUNK-5249] Replace Long constructor with Long.valueOf call

---

api/src/main/java/org/openmrs/Form.java
api/src/main/java/org/openmrs/Obs.java
api/src/main/java/org/openmrs/PersonName.java
api/src/main/java/org/openmrs/api/context/Daemon.java
api/src/main/java/org/openmrs/api/db/hibernate/ChainingInterceptor.java
api/src/main/java/org/openmrs/scheduler/SchedulerUtil.java
api/src/main/java/org/openmrs/util/DoubleRange.java
api/src/test/java/org/openmrs/PersonNameTest.java
api/src/test/java/org/openmrs/api/ConceptServiceTest.java
api/src/test/java/org/openmrs/api/OrderSetServiceTest.java
api/src/test/java/org/openmrs/util/DoubleRangeTest.java

I've removed redundant value unboxing, like: valueBoolean.booleanValue(), because valueBoolean is already type of Boolean. Reduces complexity

[GCI-142] Removed redundant value unboxing

---

api/src/main/java/org/openmrs/util/OpenmrsUtil.java

Issue: https://issues.openmrs.org/browse/GCI-240

[GCI-240] Make sure folder.listFiles() is not null before looping

---

api/src/main/java/org/openmrs/Person.java

Issue: https://issues.openmrs.org/browse/TRUNK-5255

[TRUNK-5255] Use getDead() instead of isDead()

---

api/src/test/java/org/openmrs/api/CohortServiceTest.java

Issue: https://issues.openmrs.org/browse/TRUNK-5257

[TRUNK-5257] Use getCohortsContainingPatientId() instead of depreceated method

---

pom.xml

Sonarqube was migrated, upgraded to Jetstream. 
I managed to get a green build running 'sonar:sonar': https://ci.openmrs.org/browse/RELEASE-ZOTS-16/log
I changed the plugin following: https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Maven
Apparently the 'incremental' mode doesn't exist anymore.

Upgrading sonar

---

pom.xml
web/pom.xml

Ticket: https://issues.openmrs.org/browse/TRUNK-5204

TRUNK-5204 . Removed unused jstl dependency

---

api/src/test/java/org/openmrs/PersonAddressTest.java
api/src/test/java/org/openmrs/api/db/hibernate/DropMillisecondsHibernateInterceptorTest.java
api/src/test/java/org/openmrs/scheduler/SchedulerServiceTest.java
api/src/test/java/org/openmrs/util/DateUtilTest.java

Issue: https://issues.openmrs.org/browse/TRUNK-5284

[TRUNK-5284] Replace 'l' Long literal with 'L' to avoid mistakes

---

.editorconfig
.gitignore

IntelliJ, Visual Studio Code and other IDEs/Editors support editorconfig
files out of the box, others like Eclipse, Atom, Sublime, Vim need a
plugin.
should help to reduce the spaces/tabs mess we are
currently seeing.
http://editorconfig.org/#overview
see https://issues.openmrs.org/browse/TRUNK-5298

TRUNK-5298 Add .editorconfig to force use of tabs in IDEs

---

api/src/test/java/org/openmrs/api/impl/GlobalLocaleListTest.java

added tests to assert current behavior of globalPropertyChanged before
we take out the try/catch
in support of #2556
see https://issues.openmrs.org/browse/TRUNK-5060

TRUNK-5060 Add test for globalPropertyChanged

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateProviderDAO.java
api/src/test/java/org/openmrs/api/ProviderServiceTest.java

Ticket: https://issues.openmrs.org/browse/TRUNK-5332

TRUNK-5332: HibernateProviderDAO.getCountOfProviders handles more than one match.

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateProviderDAO.java
api/src/test/java/org/openmrs/api/ProviderServiceTest.java

TRUNK-5332: HibernateProviderDAO.getCountOfProviders throws an exception when there are more than one match
https://issues.openmrs.org/browse/TRUNK-5332

TRUNK-5332: Backport on 2.1.x

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateProviderDAO.java
api/src/test/java/org/openmrs/api/ProviderServiceTest.java

TRUNK-5332: HibernateProviderDAO.getCountOfProviders throws an exception when there are more than one match
https://issues.openmrs.org/browse/TRUNK-5332

TRUNK-5332: Backport on 2.0.x

---

api/src/main/java/org/openmrs/ConditionVerificationStatus.java

In this PR, I Introduce an Enum for what we've historically called "diagnosis certainty" and FHIR refers to as [ConditionVerificationStatus](https://www.hl7.org/fhir/valueset-condition-ver-status.html).
The enum is set up to only support a subset of the FHIR statuses:
- Provisional - This is a tentative diagnosis i.e still a candidate that is under consideration.
- Confirmed - There is sufficient diagnostic and/or clinical evidence to treat this as a confirmed condition.
see https://issues.openmrs.org/browse/TRUNK-5336

TRUNK-5336: Introduce an Enum for "diagnosis certainty" (ConditionVerificationStatus)

---

api/src/main/java/org/openmrs/module/MandatoryModuleException.java
api/src/main/java/org/openmrs/module/ModuleFactory.java
api/src/main/java/org/openmrs/util/OpenmrsUtil.java

in favor of javas native String.join or apache commons StringUtils.join
when the iterable does not extend CharSequence
see https://issues.openmrs.org/browse/TRUNK-5368

TRUNK-5368 Deprecate OpenmrsUtil.join

---

api/src/main/java/org/openmrs/module/ModuleFactory.java

inline private method ModuleFactory.getModuleFromFile
since it does not add any value. (It is private and only used once.)
It simply catches ModuleExceptions, adds logging that
replicates whats inside the Exception and rethrows the ModuleException.
The same information will be visible in the log of the ModuleException
which causes the exception to be logged twice.
see https://issues.openmrs.org/browse/TRUNK-5377

TRUNK-5377 Remove redundant logging on failed module start

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
api/src/main/resources/liquibase-update-to-2.2.xml
api/src/main/resources/org/openmrs/api/db/hibernate/Concept.hbm.xml
api/src/test/resources/org/openmrs/api/include/ConceptServiceTest-initialConcepts.xml
api/src/test/resources/org/openmrs/api/include/ConceptServiceTest-numerics.xml
api/src/test/resources/org/openmrs/api/include/ObsServiceTest-initial.xml
api/src/test/resources/org/openmrs/api/include/PatientServiceTest-mergePatientWithExistingObsHavingGroupMember.xml
api/src/test/resources/org/openmrs/hl7/include/ORUTest-initialData.xml
api/src/test/resources/org/openmrs/include/standardTestDataset.xml

Changed the concept_numeric database field "precise" to "allow_decimal", updated the associated Hibernate mapping files, and updated all test data files that referenced the "precise" field to instead reference "allow_decimal".
see https://issues.openmrs.org/browse/TRUNK-5333

TRUNK-5333 Rename concept_numeric DB field "precise" to "allow_decimal"

---

api/src/test/java/org/openmrs/api/AdministrationServiceUnitTest.java

see https://issues.openmrs.org/browse/TRUNK-5065

TRUNK-5065: Add tests to AdministrationServiceImpl

---

api/src/main/java/org/openmrs/PersonName.java

TRUNK-4929 PersonName.compareTo should be controlled by a global property
According to Darius Jazayeri, a new comparator class should be used instead of a global property control system, however, that class is already implemented with PersonByNameComparator. Therefore, it was determined that the TODO comment should be removed, and the ticked closed. I removed the comment so that the ticket can be closed.
see https://issues.openmrs.org/browse/TRUNK-4929

TRUNK-4929: PersonName.compareTo should be controlled by a global property

---

api/src/main/java/org/openmrs/util/OpenmrsConstants.java

I added a global property LOGIN URL to hold the default login URL and be accessible publicly.
see https://issues.openmrs.org/browse/TRUNK-5367 …

TRUNK-5367: Create URL global property on OpenMRS core

---

api/src/main/java/org/openmrs/Condition.java
api/src/main/java/org/openmrs/api/impl/ConditionServiceImpl.java

Changed 3 files for this task:
* api/src/main/java/org/openmrs/Condition.java
* api/src/main/java/org/openmrs/api/impl/ConditionServiceImpl.java
* api/src/main/resources/org/openmrs/api/db/hibernate/Condition.hbm.xml
See https://issues.openmrs.org/browse/TRUNK-5373
added all formatting changes to my …

TRUNK-5373: Refactor the condition save logic.

---

api/src/main/resources/org/openmrs/module/dtd/config-1.0.dtd
api/src/main/resources/org/openmrs/module/dtd/config-1.1.dtd
api/src/main/resources/org/openmrs/module/dtd/config-1.2.dtd
api/src/main/resources/org/openmrs/module/dtd/config-1.3.dtd
api/src/main/resources/org/openmrs/module/dtd/config-1.4.dtd
api/src/main/resources/org/openmrs/module/dtd/config-1.5.dtd

* add the DTD files for the config.xml in versions 1.0-1.5 to the
resources of org/openmrs/module/dtd so they are under version control,
can easily be found, edited and uploaded back to resource.openmrs.org
* add elements that were not declared and thus made the DTDs invalid and
not useful for devs writing their config.xml
dwr
* add missing elements judging from legacyui dwr element in config.xml
* create (param, include*) always has a param and can have 0-N include's
param and include are empty elements with required attributes
* convert has one optional param child
mappingFiles
* fix the mappingFiles quantifier since it should only occur Zero or One
time thus use `?`. mappingFiles itself can have multiple whitespace
separated filenames
require_modules
* be more strict on …

TRUNK-5399 Add and fix config xml dtd files 1-0.1.5

---

api/src/main/resources/liquibase-update-to-2.2.xml
api/src/main/resources/org/openmrs/api/db/hibernate/Condition.hbm.xml
api/src/test/resources/org/openmrs/api/db/hibernate/include/HibernateConditionDAOTestDataSet.xml
api/src/test/resources/org/openmrs/api/include/ConditionServiceImplTest-SetupCondition.xml
api/src/test/resources/org/openmrs/api/include/DiagnosisServiceImplTest-SetupDiagnosis.xml

Added liquibase changeset to add a new conditions table or modify an existing one.  …

TRUNK-5338 Add changeset to create or modify conditions table

---

api/src/main/java/org/openmrs/util/OpenmrsConstants.java

TRUNK-5033 Public Static Fields Should Be Final
3 fields that are present in the OpenMRSConstants Class have been
changed to final.
see https://issues.openmrs.org/browse/TRUNK-5033 …

TRUNK-5033

---

api/src/main/java/org/openmrs/api/context/Daemon.java
api/src/main/java/org/openmrs/notification/impl/AlertServiceImpl.java

Issue : https://issues.openmrs.org/browse/TRUNK-5189.
This initial commit is not yet perfect, I just need your guidance @dkayiwa to complete this issue. 
Currently the alert is made by the daemon User, but there are 2 broken tests. In the [AlertServiceTest](https://github.com/openmrs/openmrs-core/blob/master/api/src/test/java/org/openmrs/notification/AlertServiceTest.java) but what has beat my understanding is that, when I comment out other tests and run one by one, they all pass fine. This has made me to anticipate that there are some thread conflicts. Could you please review my changes and direct me of what to do.
cc. @ssmusoke , @djazayeri etc.

TRUNK-5189: Used Daemon User to create an Alert

---

api/src/main/java/org/openmrs/Patient.java
api/src/main/java/org/openmrs/PatientIdentifier.java
api/src/test/java/org/openmrs/PatientTest.java

Added since annotations, made patient identifier clonable, ensured cloned patients identifiers refer to correct patient. Related to [Pull Request 2691](https://github.com/openmrs/openmrs-core/pull/2691)
see https://issues.openmrs.org/browse/TRUNK-5408

TRUNK-5408 Patient Constructor that takes in Patient (Revision)

---

api/src/test/java/org/openmrs/api/AdministrationServiceTest.java

https://issues.openmrs.org/browse/TRUNK-5417
AdministrationServiceTest.java was changed so that it does not assume that exactly 21 global properties exist when running the tests:
> getAllGlobalProperties_shouldReturnAllGlobalPropertiesInTheDatabase
> purgeGlobalProperty_shouldDeleteGlobalPropertyFromDatabase
The tests now count how many global properties exist immediately prior, and after, the code under test.
https://issues.openmrs.org/browse/TRUNK-5417
Related discussion: https://talk.openmrs.org/t/openmrs-core-build-failure/15008
- [x ] I ran `mvn clean package` right before creating this pull …

TRUNK-5417 AdministrationServiceTest should count global properties correctly

---

api/src/main/java/org/openmrs/api/UserService.java
api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java
api/src/main/resources/emailTemplate.properties
api/src/main/resources/messages.properties
api/src/test/java/org/openmrs/api/UserServiceTest.java

Add possibility for sending email with activation key 
- [x ] I have **added tests** to cover my changes. (If you refactored
No? -> write tests …

Added send mail functionality to send token via mail

---

api/src/main/resources/liquibase-update-to-2.0.xml

I've modified bad changesets which caused ValidationError during upgrading following this <a href="https://wiki.openmrs.org/display/docs/How+to+Modify+a+Bad+Changeset">Wiki page</a>. 
Reopened the pull request because the first one wasn't based on master. It also needs to be backported to other versions after it's merged.
JIRA: <a href="https://issues.openmrs.org/browse/TRUNK-5304">TRUNK-5304</a>
GCI: <a href="https://codein.withgoogle.com/dashboard/task-instances/4591487401590784/">Task Instance</a>

TRUNK-5304: Upgrade from 1.10.6 to 1.11.8 fails because of inconsistent changeset

---

api/src/main/java/org/openmrs/Allergies.java
api/src/main/java/org/openmrs/DosingInstructions.java
api/src/main/java/org/openmrs/FormResource.java
api/src/main/java/org/openmrs/FreeTextDosingInstructions.java
api/src/main/java/org/openmrs/GlobalProperty.java

One of my changes from my PR #2780
Removing APIException
Sonar errors:-
https://goo.gl/3386fk
https://goo.gl/kLi4JP
https://goo.gl/KFE81t
https://goo.gl/1UVjLa
https://goo.gl/rR5MEx
https://goo.gl/27NHJX
https://goo.gl/vv1gza
https://goo.gl/g3AWcX
https://goo.gl/ZKkQ9U
Task Instance https://codein.withgoogle.com/dashboard/task-instances/6187644498214912/

GCI-142: Removed APIException

---

api/src/main/java/org/openmrs/api/db/ConceptDAO.java

I have updated all functions with respect to the Java code conventions, such as including the Javadoc comments on top of public functions. I have also followed the pull request conventions. I have followed code review by @lluismf and @suthagar23. :)
However, getConceptUuids and getConceptReferenceTermsBySource is not included in ConceptService. I was not able to properly document these functions, given that these are not documented in ConceptService. 
See https://issues.openmrs.org/browse/TRUNK-3787
See https://codein.withgoogle.com/dashboard/task-instances/4852850187304960/
(If you refactored existing code that was well tested you do not have to add tests)

TRUNK-3787: Refactored ConceptDAO.java

---

api/src/main/java/org/openmrs/ProgramWorkflowState.java

https://issues.openmrs.org/browse/TRUNK-5491
**The problem**
While running tests for HTMLFormEntry, when one runs only the tests for EnrollProgramTagTest (rather than the full suite), all of the tests which attempt to modify entities in the database fail with `org.hibernate.AssertionFailure: null id in org.openmrs.PatientState entry (don't flush the Session after an exception occurs)`.
The failure occurs because of a log statement which logs the entity in [AuditableInterceptor](https://github.com/openmrs/openmrs-core/blob/9e474b6613b347a4fa68e08a4c6ac067f466dd1f/api/src/main/java/org/openmrs/api/db/hibernate/AuditableInterceptor.java#L108). This log statement ends up calling `org.openmrs.ProgramWorkflowState.toString`, which calls `Concept.getName()`, which apparently triggers a Hibernate …

TRUNK-5491: PatientWorkflowState.toString should not hit the database

---

pom.xml

Upgraded library com.h2database:h2 from 1.4.197 - 1.4.199
https://issues.openmrs.org/browse/TRUNK-5512

 TRUNK-5512: Upgrade com.h2database:h2

---

pom.xml

Upgrade the org.apache.commons:commons-lang3 from 3.6.0 to 3.9.0 and handle any Backward Compatibility issues
https://issues.openmrs.org/browse/TRUNK-5500

TRUNK-5500:Upgrade org.apache.commons:commons-lang3 library

---

pom.xml

Upgrade library org.javassist:javassist from 3.22.0-GA to 3.25.0-GA
TRUNK-5544:Upgrade org.javassist:javassist
I upgraded the org.javassist:javassist library from 3.22.0-GA to 3.25.0-GA
I also included the mysql connector in my api pom with the scope as test because the tests fail with out it...errors shown here https://pastebin.com/nNxrKv1d
https://issues.openmrs.org/browse/TRUNK-5544

TRUNK-5544:Upgraded the javassist from 3.22.0-GA to 3.25.0-GA

---

.travis.yml
api/src/main/java/org/openmrs/Drug.java
api/src/main/resources/liquibase-update-to-2.3.xml
api/src/main/resources/org/openmrs/api/db/hibernate/Drug.hbm.xml

link:https://issues.openmrs.org/browse/TRUNK-5411?src=confmacro
Trunk-5411:Add doseLimitUnits field to Drug

Trunk-5411:Add doseLimitUnits field to Drug

---

api/src/main/java/org/openmrs/Encounter.java
api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
api/src/test/java/org/openmrs/EncounterTest.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java

Hi @mogoodrich , here is the PR for backporting Encounter. getAllFlattenedObs() methods to 2.2.x. I will wait until all Travis tests complete and I will merge this PR. Thanks!

TRUNK-5438, backport encounter get all flattened obs

---

api/src/main/java/org/openmrs/api/context/Context.java
api/src/main/java/org/openmrs/api/context/DaoAuthenticationScheme.java

Backported from eac7f315a668bc2d02824a6f50c9ee2e817ddc9f
* TRUNK-381 : Context to be the single source of truth of the ContextDAO instance
* TRUNK-381 : Removing unused ContextDAO local variable
Ticket : https://issues.openmrs.org/browse/TRUNK-381

TRUNK-381: DaoAuthenticationScheme to return ContextDAO from Context.

---

api/src/main/resources/liquibase-update-to-2.3.xml

As part of this PR following things are done:
Jira ticket: https://issues.openmrs.org/browse/TRUNK-5672
Talk Thread: https://talk.openmrs.org/t/admin-user-doesnt-have-a-username/25145/

TRUNK-5672 | Add liquibase changesets to populate username for admin user

---

pom.xml

I Upgraded library commons sub-Libraries as below     
1. commons-fileupload:commons-fileupload … 1.3.3  to 1.4
2. commons-io:commons-io … 2.5  to 2.6
3. commons-validator:commons-validator … 1.4.0 to 1.6
https://issues.openmrs.org/browse/TRUNK-5517 …

TRUNK-5517 Upgrade commons Libraries

---

api/src/main/java/org/openmrs/BaseOpenmrsObject.java
api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneAnalyzerFactory.java
api/src/main/resources/hibernate.cfg.xml

TRUNK-5675 Lucene Analyzer Defs should be provided programatically
https://issues.openmrs.org/browse/TRUNK-5675
Moves the Lucene Analyzer Definitions out of BaseOpenmrsObject annotations and into a factory class.

TRUNK-5675  Lucene Analyzer Defs should be provided programatically

---

pom.xml

I upgraded the Hibernate  version from 4.3.9.Final to 4.3.10.Final
thus  upgrading the following 3 Sub Libraries
org.hibernate:hibernate-c3p0 … 4.3.9.Final -> 4.3.10.Final
org.hibernate:hibernate-core … 4.3.9.Final -> 4.3.10.Final
org.hibernate:hibernate-ehcache … 4.3.9.Final ->  4.3.10.Final
also I upgraded
org.hibernate:hibernate-validator … 4.2.0.Final -> 6.0.16.Final
org.hibernate:hibernate-search-orm … 5.1.2.Final -> 5.3.0.Final
I have worked on this issue 
https://issues.openmrs.org/browse/TRUNK-5499

TRUNK-5499-Upgrading the Hibernate Library from 4.3.9.Final to 4.3.10.Final

---

api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java

I've fixed some typos in the javadoc comments in ConceptServiceImplTest file
see https://issues.openmrs.org/browse/TRUNK-5690 …

TRUNK-5690 Fix typos in Javadoc comments in ConceptServiceImplTest file

---

api/src/main/java/org/openmrs/CohortMembership.java

Deep-copied the Getters and Setters to fix 4 instances of the following issue.
- [`L40`-new org.openmrs.CohortMembership(Integer, Date) may expose internal representation by storing an externally mutable object into CohortMembership.startDate](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=2589c367-f0c7-41bf-accf-48638c030ce2&open=2589c367-f0c7-41bf-accf-48638c030ce2)
- [`L97`-org.openmrs.CohortMembership.getStartDate() may expose internal representation by returning CohortMembership.startDate](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=0fc389b2-c1d1-4060-8168-3f84de21d627&open=0fc389b2-c1d1-4060-8168-3f84de21d627)
- [`L101`-org.openmrs.CohortMembership.setStartDate(Date) may expose internal representation by storing an externally …

[GCI-142] Fix various memory leaks.

---

api/src/main/resources/liquibase-update-to-2.3.xml
api/src/main/resources/liquibase-update-to-2.4.xml

link:https://issues.openmrs.org/browse/TRUNK-5650

Trunk-5650:Add parent order group to order group

---

api/src/main/java/org/openmrs/BaseConceptMap.java

Check bad code practices through Findbugs or Sonar and fix those issues. (Exposing internal representations of mutable objects in setters)
No? -> figure out why and add the fix to …

GCI-142 Check bad code practices through Findbugs or Sonar and fix those issues.

---

license-header.txt

Corrected punctuation

---

api/pom.xml
pom.xml
web/pom.xml

Trunk-5551 Upgraded xerces:xercesImpl
**Description of what I changed**
upgraded the library xerces:xercesImpl from 2.8.0 to 2.12.0
**Issue I worked on**
https://issues.openmrs.org/browse/TRUNK-5551

Trunk-5551 Upgrade xerces:xercesImpl

---

api/src/main/java/org/openmrs/validator/ValidateUtil.java
api/src/test/java/org/openmrs/api/ProgramWorkflowServiceTest.java
api/src/test/java/org/openmrs/validator/ValidateUtilTest.java

Made changes to ValidateUtil in order to be able to override dynamic placeholders in error messages. For eg., {0} should be replaced with the appropriate argument being passed for that attribute.
see https://issues.openmrs.org/browse/TRUNK-5555
No? -> …

TRUNK-5555: Fix validation message for length of ConceptDrug name

---

api/src/main/java/org/openmrs/liquibase/ChangeLogDetective.java
api/src/test/java/org/openmrs/liquibase/ChangeLogDetectiveTest.java

Log details of un-run change sets.
This pull request provides additional logging when the OpenMRS database is updated. The additional log entries are limited to no more than 10 and un-run change sets are logged for 1.9.x Liquibase snapshot files only.
The additional logging was used to debug the database initialisation of the reference application and will help when other users report similar issues.
- [ x ] My pull request only contains **ONE single commit**
- [ x ] My IDE is configured to follow the [**code style**]- [ ] I have **added tests** to cover my changes. (If you refactored
- [ x ] I ran `mvn clean package` right before creating this pull request and
- [ x ] All new and …

TRUNK-4830 Avoid running legacy liquibase changesets

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.3.x.xml

This is a small followup commit on [work done on linking Conditions to an Encounter](https://github.com/openmrs/openmrs-core/commit/53e4d9ce7b94b4c6e7cb0f7b817244664d3c0124).
See ticket for details: https://issues.openmrs.org/browse/TRUNK-5728

TRUNK-5728: Using a unique FK constraint name for the 'encounter_id' column in the 'conditions' table

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml

Followup commit for adding [this liquibase changeset](https://github.com/openmrs/openmrs-core/blob/master/api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.3.x.xml#L96-L111) to liquibase-update-to-latest-2.4.x.xml 
See ticket for details: https://issues.openmrs.org/browse/TRUNK-5728

TRUNK-5728: Adding liquibase changeset that introduces 'encounter_id' column on conditions table to liquibase-update-to-latest-2.4.x.xml

---

api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java

This has been tested by putting the `initializeLazyPropertiesForConcept` method in our module activator. After that we didn't face the issue for last two days.
Issue Link: https://issues.openmrs.org/browse/TRUNK-5740
OpenMRS Talk: https://talk.openmrs.org/t/random-lazy-initialization-while-making-encounter-post-with-full-representation-as-response/28427

TRUNK-5740 | Initialize lazy properties while caching for True,False and unknown concepts.

---

api/src/main/java/org/openmrs/module/ModuleUtil.java

Explicitly set the context classloader to be the module's classloader
before calling willRefreshContext.
https://issues.openmrs.org/browse/FM2-184
No? -> I'm not sure how this can be unit tested, tbh. 

FM2-184: Set context classloader to be module's classloader.

---

api/src/main/java/org/openmrs/User.java

I changing User to extend BaseOpenmrsObject from BaseOpenmrsMetadata   and added the Auditable and Retireable interfaces to implement. Then added the following fields : creator, dateCreated, changedBy, dateChanged, retiredBy, retireReason, retired, and dateRetired.
https://issues.openmrs.org/browse/TRUNK-5665

TRUNK-5665: User should not extend extend BaseOpenmrsMetadata

---

api/src/main/resources/org/openmrs/api/db/hibernate/OrderSet.hbm.xml

This PR simply removes the discriminator property defined within the OrderSet.hbm.xml file. This property does not seem to be needed and prevents subclasses of OrderSet to be defined and saved due to it's presence in this file.

TRUNK-5877: Invalid discriminator for OrderSet

---

api/src/main/resources/org/openmrs/api/db/hibernate/OrderGroup.hbm.xml

Removes incorrect discriminator column from OrderGroup.hbm.xml
This is the same fix that we had to make to OrderSet.hbm.xml in TRUNK-5877, likely introduced incorrectly at the same time.

TRUNK-5897: Remove discriminator from OrderGroup.hbm.xml

---

api/src/main/java/org/openmrs/liquibase/LiquibaseProvider.java
web/src/main/java/org/openmrs/web/filter/update/DatabaseUpdaterWrapper.java
web/src/main/java/org/openmrs/web/filter/update/UpdateFilterModel.java
web/src/test/java/org/openmrs/web/filter/update/UpdateFilterModelTest.java

TRUNK-5817: Migrate web and webapp package tests to Junit 5

---

api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

This commit ensures that AOP validation checks are not bypassed by ensuring that Orders are saved via the full call to Context.getOrderService() rather than directly.

TRUNK-5920 - Saving Order Groups fails to validate underlying Orders

---

pom.xml

I upgraded openmrs core 2.2.0  branch from version2.3.0-SNAPSHOT to 2.3.3-SNAPSHOT
https://issues.openmrs.org/browse/TRUNK-5966

TRUNK-5966: Correct next development version for 2.3.x branch

---

api/src/main/java/org/openmrs/api/context/Daemon.java
api/src/main/java/org/springframework/core/JdkVersion.java

I have overwritten the default constructors to prevent the creation of an instance of the utility class.
see https://issues.openmrs.org/browse/TRUNK-5935

TRUNK-5935: Utility classes should not have public constructors

---

api/src/main/java/org/openmrs/BaseChangeableOpenmrsData.java
api/src/main/java/org/openmrs/BaseChangeableOpenmrsMetadata.java
api/src/main/resources/liquibase-core-data.xml
api/src/main/resources/liquibase-update-to-latest-from-1.9.x.xml
api/src/main/resources/liquibase-update-to-latest.xml
api/src/test/java/org/openmrs/util/databasechange/Database1_9_7UpgradeIT.java
api/src/test/java/org/openmrs/util/databasechange/DatabaseUpgradeTestUtil.java
liquibase/README.md

OpenMRS components such as openmrs-standalone continue to use legacy Liquibase change log files in their build process. 
The legacy Liquibase change log files are:
- api/src/main/resources/liquibase-schema-only.xml
- api/src/main/resources/liquibase-core-data.xml
- api/src/main/resources/liquibase-update-to-latest.xml
This pull request ensures that the legacy Liquibase change log files reference the **latest** snapshot files.
see https://issues.openmrs.org/browse/TRUNK-4830
- [  ] I have **added tests** to cover my changes. (If you refactored
- [ x ] I ran `mvn clean package` right before …

TRUNK-4830 refactor legacy Liquibase changelog files

---

api/src/main/java/org/openmrs/liquibase/ChangeLogDetective.java
api/src/test/java/org/openmrs/liquibase/ChangeLogDetectiveDatabaseIT.java

Use 1.9.x as default snapshot version if the snapshot version that was used to initialise OpenMRS cannot be identified.
This change [fixes an issue regarding the Platform 2.4 Release](https://talk.openmrs.org/t/platform-2-4-release-to-dos-and-release-discussions-thread/30616). Please search for:
_all the PIH EMR instances were initialized with OpenMRS 1.9 or later, but some of our other instances (and many others) date back to way before that_
see https://issues.openmrs.org/browse/TRUNK-4830
- [ x ] I have **added tests** to cover my changes. (If you refactored
- [ x ] I ran `mvn clean package` …

TRUNK-4830: Use 1.9.x as default snapshot version

---

api/src/test/java/org/openmrs/util/H2DatabaseIT.java
web/src/main/java/org/openmrs/web/Listener.java
web/src/main/java/org/openmrs/web/filter/initialization/DatabaseDetective.java
web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
web/src/test/java/org/openmrs/web/filter/initialization/DatabaseDetectiveIT.java
web/src/test/java/org/openmrs/web/filter/initialization/DatabaseDetectiveTest.java
web/src/test/resources/org/openmrs/liquibase/liquibase-changelog-tables.xml

Check for empty database before assessing database updates.
`org.openmrs.web.Listener#setupNeeded()` now checks for empty databases.
see https://issues.openmrs.org/browse/TRUNK-4830
- [ x ] I have **added tests** to cover my changes. (If you refactored
- [ x ] I ran `mvn clean package` right before creating this pull request and
- [ x ] All new and existing **tests passed**.
- [ x ] My pull request is **based on the latest changes** of the 2.4.x branch.

TRUNK-4830 check for empty database before assessing database updates

---

api/src/main/java/org/openmrs/aop/LoggingAdvice.java

https://issues.openmrs.org/browse/TRUNK-3276
This reduces the log level of LoggingAdvice messages by one notch. Setter messages are now logged at DEBUG and getter messages at TRACE.

TRUNK-3276 LoggingAdvice too verbose

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.5.x.xml

Dropped non-null constraint from column cohort_member.start_date
see https://issues.openmrs.org/browse/TRUNK-6001

TRUNK-6001: Drop non-null constraint from column cohort_member.start_date

---

liquibase/src/main/java/org/openmrs/liquibase/Main.java
liquibase/src/test/java/org/openmrs/liquibase/AbstractSnapshotTunerTest.java
liquibase/src/test/java/org/openmrs/liquibase/CoreDataTunerTest.java
liquibase/src/test/java/org/openmrs/liquibase/SchemaOnlyTunerTest.java

liquibase package changes for replacing path constructions using separator char
see https://issues.openmrs.org/browse/TRUNK-5134
- [x ] I have **added tests** to cover my changes. (If you refactored …

TRUNK-5134: Replace path constructions using separator char

---

api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

This modified the logic within OrderService.saveOrder to consider the order to be retrospective if the date activated of that order is prior to the current date (time excluded).

TRUNK-6002: Encounters should appropriately save retrospective orders

---

api/src/main/java/org/openmrs/BaseDosingInstructions.java
api/src/main/java/org/openmrs/DosingInstructions.java
api/src/main/java/org/openmrs/FreeTextDosingInstructions.java
api/src/main/java/org/openmrs/SimpleDosingInstructions.java
api/src/test/java/org/openmrs/SimpleDosingInstructionsTest.java

https://issues.openmrs.org/browse/TRUNK-5992
See Talk thread here:  https://talk.openmrs.org/t/duration-and-auto-expire-date-on-orders/32006/2
The effect of this is to set the autoExpireDate if both duration and durationUnits are specified.  Unlike the previous behavior, this will happen for both Simple _and_ FreeText Dosing Instructions and will also happen if refills are specified on the order.

TRUNK-5992: Order Service should always set autoExpireDate if duration is set.

---

api/src/main/java/org/openmrs/util/OpenmrsUtil.java

TRUNK-6004: Remove Redundant Comment TODO finish function
https://issues.openmrs.org/browse/TRUNK-6004
I removed the redundant comment TODO finish function.

TRUNK-6004: Remove Redundant Comment TODO finish function

---

api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

This PR is against the 2.3.x branch.  If approved, I will up-port to 2.4.x and master.  This removes the validation within the Order Service that prevents saving an Order Frequency if it is in use.  See TRUNK-6006 for details.

TRUNK-6006:  OrderService prevents saving Order Frequencies

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
api/src/test/java/org/openmrs/api/db/hibernate/HibernatePatientDAOTest.java

Fixed issues with SQLException while trying to get patients with duplicated names. I've also added tests for this functionality.
see https://issues.openmrs.org/browse/TRUNK-6008

TRUNK-6008: Fix HibernatePatientDAO.getDuplicatePatientsByAttributes

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
api/src/test/java/org/openmrs/api/db/hibernate/HibernatePatientDAOTest.java

This PR fixes `HibernatePatientDAO.getDuplicatePatientsByAttributes` method by sorting passed attributes before building an SQL query. It also adds more unit tests for `identifier` and `includeVoided` attributes. It also adds random order to passed attributes in tests to make sure they aren't flaky.
see https://issues.openmrs.org/browse/TRUNK-6010 …

TRUNK-6010: HibernatePatientDAOTest should test getting duplicated patients by identifier and includeVoided

---

api/src/main/java/liquibase/ext/sqlgenerator/core/ModifyColumnChange.java
api/src/main/java/org/openmrs/util/ClassLoaderFileOpener.java
api/src/main/java/org/openmrs/util/databasechange/SourceMySqldiffFile.java
api/src/main/resources/META-INF/services/liquibase.change.Change
api/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType
api/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
api/src/test/java/liquibase/ext/change/core/InsertWithUuidDataChangeDatabaseIT.java
api/src/test/java/liquibase/ext/sqlgenerator/core/ModifyColumnGeneratorTest.java
api/src/test/java/org/openmrs/BaseFormRecordableOpenmrsDataTest.java
api/src/test/java/org/openmrs/util/databasechange/ClassLoaderFileOpenerTest.java
api/src/test/java/org/openmrs/util/databasechange/Database1_9_7UpgradeIT.java
api/src/test/java/org/openmrs/util/databasechange/DatabaseUpgradeTestUtil.java
pom.xml

[TRUNK-6013 - Upgrade to Liquibase 4](https://issues.openmrs.org/browse/TRUNK-6013)
Upgrades Core to using Liquibase 4. This should resolve the issue mentioned [here](https://talk.openmrs.org/t/typecasting-error-during-openmrs-setup/31816) and allow us to continue updating the MySQL driver.
Tested against both Jetty and Tomcat. …

TRUNK-6013 - Upgrade to Liquibase 4

---

api/src/main/java/org/openmrs/api/DiagnosisService.java
api/src/main/java/org/openmrs/api/db/DiagnosisDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateDiagnosisDAO.java
api/src/main/java/org/openmrs/api/impl/DiagnosisServiceImpl.java
api/src/test/java/org/openmrs/api/db/hibernate/HibernateDiagnosisDAOTest.java
api/src/test/java/org/openmrs/api/impl/DiagnosisServiceImplTest.java
api/src/test/resources/org/openmrs/api/include/DiagnosisServiceImplTest-SetupDiagnosis.xml
api/src/test/resources/org/openmrs/api/include/HibernateDiagnosisDAOTestDataset.xml

Creates two new methods in the `DiagnosisService` and corresponding DAOs:
- `getDiagnosesByEncounter`
- `getDiagnosesByVisit`
Each of these methods can filter by diagnoses that are primary or confirmed.
This backports the behaviour for `Visit`s in https://github.com/icrc-psousa/openmrs-module-emrapi/blob/RA-1714/api-2.2/src/main/java/org/openmrs/module/emrapi/diagnosis/EmrDiagnosisDAOImpl2_2.java into `openmrs-core` and introduces the same behaviour with regard to `Encounter`s.
This PR deprecates `DiagnosisService#getPrimaryDiagnoses` as the behaviour is now contained in `DiagnosisService#getDiagnosesByEncounter` which allows filtering for primary diagnoses; the same goes for `DiagnosisDAO#getDiagnoses`. I did not remove the methods for backwards compatibility reasons. …

TRUNK-5999: Add more filtering options to Diagnosis service

---

api/src/main/java/org/openmrs/Diagnosis.java
api/src/main/java/org/openmrs/DiagnosisAttribute.java
api/src/main/java/org/openmrs/DiagnosisAttributeType.java
api/src/main/java/org/openmrs/api/DiagnosisService.java
api/src/main/java/org/openmrs/api/db/DiagnosisDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateDiagnosisDAO.java
api/src/main/java/org/openmrs/api/impl/DiagnosisServiceImpl.java
api/src/main/java/org/openmrs/util/PrivilegeConstants.java
api/src/main/resources/hibernate.cfg.xml
api/src/main/resources/org/openmrs/api/db/hibernate/DiagnosisAttribute.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/DiagnosisAttributeType.hbm.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.5.x.xml
api/src/test/java/org/openmrs/api/impl/DiagnosisServiceImplTest.java
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java
api/src/test/resources/org/openmrs/api/include/DiagnosisServiceImplTest-DiagnosisAttributes.xml

see https://issues.openmrs.org/browse/TRUNK-6038
Changed the Diagnosis class to extend `BaseCustomizableData<DiagnosisAttribute>` and implemented the `FormRecordable` interface.
Added the `String formNamespaceAndPath` field to the Diagnosis class and constructor and implemented the required methods from the `FormRecordable` interface. i.e `getFormFieldNamespace()`, `getFormFieldPath()` and `setFormField()`.
Created the `DiagnosisAttribute` and `DiagnosisAttributeType` classes with the required getter and setter methods. 
Added the required methods to the `DiagnosisService` interface.
`List<DiagnosisAttributeType> getAllDiagnosisAttributeTypes()` 
`DiagnosisAttributeType getDiagnosisAttributeTypeById(Integer id)` 
`DiagnosisAttributeType getDiagnosisAttributeTypeByUuid(String uuid)` …

TRUNK-6038:Add Diagnosis Attribute to data model

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.5.x.xml
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java

see https://issues.openmrs.org/browse/TRUNK-5736

TRUNK-5736: Delete user who has changed their password.

---

api/src/main/java/org/openmrs/Diagnosis.java
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.5.x.xml
api/src/test/java/org/openmrs/api/impl/DiagnosisServiceImplTest.java
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java
api/src/test/resources/org/openmrs/api/include/DiagnosisServiceImplTest-SetupDiagnosis.xml
api/src/test/resources/org/openmrs/api/include/HibernateDiagnosisDAOTestDataset.xml

I added `name="dx_rank"` to the `rank` field in the Diagnosis class. 
I added the changeset to `liquibase-update-to-latest-2.5.x.xml` for renaming column rank to `dx_rank` because rank is a reserved word in MySQL 8.0.2 and later. 
I incremented the `CHANGE_SET_COUNT_FOR_GREATER_THAN_2_1_X` to **890** in the `DatabaseUpdaterDatabaseIT` class. 
Modified dataset files `DiagnosisServiceImplTest-SetupDiagnosis.xml` and `HibernateDiagnosisDAOTestDataset.xml` to reflect the new column name so that the `DiagnosisServiceImplTests` and `HibernateDiagnosisDAOTests` would still pass. 
see https://issues.openmrs.org/browse/TRUNK-6044

TRUNK-6044:Avoid using MySQL reserved word; rank as column name.

---

api/src/main/java/org/openmrs/api/impl/PersonServiceImpl.java

**Description of what I changed**
I removed
if (relationship.getVoided()) {
return relationship;
}
relationship.setVoided(true);
if (relationship.getVoidedBy() == null) {
relationship.setVoidedBy(Context.getAuthenticatedUser());
}
if (voidReason != null) {
relationship.setVoidReason(voidReason);
}
relationship.setDateVoided(new Date());
return Context.getPersonService().saveRelationship(relationship);
which is already being called via AOP the Relationship and fixed the methods to effectively return null.
**Issue I worked on**
https://issues.openmrs.org/browse/TRUNK-5151

TRUNK-5151: Remove body of voidRelationship

---

api/src/main/java/org/openmrs/api/ConceptService.java
api/src/main/java/org/openmrs/api/db/ConceptDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
api/src/main/resources/ehcache-api.xml
api/src/test/java/org/openmrs/api/ConceptServiceTest.java
api/src/test/java/org/openmrs/api/cache/OpenmrsCacheManagerFactoryBeanTest.java

…g using spring cache
Based on feedback from @rkorytkowski , here is an attempt at solving the same problem using a Spring cache.  This actually does perform better than the earlier Lucene approach (and could likely be improved further in the future).
This adds one new service method to retrieve concept ids by mapping, the results of which are cached.  This is done this way as only service methods have the cache annotation picked up, and also I wanted to avoid caching any Hibernate-managed objects to avoid any lazy loading exceptions.
This has the implementation of the List<Concept> getConceptsByMapping iterate across the conceptIds returned by List<Integer> getConceptIdsByMapping, and load the matching concepts.
Performance testing shows considerable improvement.  Testing the loading of …

TRUNK-5557: Improve performance of ConceptService.getConceptsByMapping

---

webapp/pom.xml

Reverts openmrs/openmrs-core#3945 
Because of this error on startup: java.lang.NoClassDefFoundError: javax/security/auth/message/config/RegistrationListener

Revert "maven(deps): bump cargo-maven3-plugin from 1.9.8 to 1.9.9"

---

liquibase/pom.xml
liquibase/src/test/java/org/openmrs/liquibase/AbstractSnapshotTunerTest.java
liquibase/src/test/java/org/openmrs/liquibase/CoreDataTunerTest.java
liquibase/src/test/java/org/openmrs/liquibase/SchemaOnlyTunerTest.java

TRUNK-4830 add missing junit dependency and fix unit test in module liquibase
see https://issues.openmrs.org/browse/TRUNK-4830
- [  ] I have **added tests** to cover my changes. (If you refactored
- [ x ] I ran `mvn clean package` right before creating this pull request and
- [ x ] All new and existing **tests passed**.
- [ x ] My pull request is **based on the latest changes** of the master branch.

TRUNK-4830 add missing junit dependency and fix unit tests

---

web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
web/src/main/java/org/openmrs/module/web/filter/ModuleFilterDefinition.java
web/src/main/java/org/openmrs/module/web/filter/ModuleFilterMapping.java
web/src/main/java/org/openmrs/web/Listener.java

This ensures that module filters are loaded in a defined order as outlined [in this Talk post](https://talk.openmrs.org/t/architecture-proposal-module-filter-load-order/35397).
see https://issues.openmrs.org/browse/TRUNK-6054
No? Unsure? -> execute command `git pull --rebase upstream …

TRUNK-6054: Ensure module filters are loaded in an appropriate order

---

api/src/main/java/org/openmrs/Condition.java
api/src/main/java/org/openmrs/api/ConditionService.java
api/src/main/java/org/openmrs/api/db/ConditionDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConditionDAO.java
api/src/main/java/org/openmrs/api/impl/ConditionServiceImpl.java
api/src/test/java/org/openmrs/api/db/hibernate/HibernateConditionDAOTest.java
api/src/test/java/org/openmrs/api/impl/ConditionServiceImplTest.java

This changes the `saveCondition()` method to conform with the rules defined [in this Talk thread](https://talk.openmrs.org/t/conditon-list-proposed-changes-to-savecondition-api/29451).
In order to maintain compatibility with EMR API, `saveCondition()` actually handles not just the logic of adding a new condition or modifying an existing condition, but also voiding or unvoiding an existing condition.
see https://issues.openmrs.org/browse/TRUNK-5888
added all formatting …

TRUNK-5888: Fix business logic errors in saveCondition() method

---

api/pom.xml
pom.xml

I don't know what changed between the 2.3.x branch and the 2.4.x branch to make this happen, but I get a test failure in 2.4.x without this commit.  It seems that the java mail implementation does not exist, just the api, and this leads to a failure in this unit test:
```
[ERROR] Failures: 
[ERROR]   UserServiceTest.setUserActivationKey_shouldCreateUserActivationKey:1518 Unexpected exception type thrown ==> expected: <org.openmrs.notification.MessageException> but was: <java.lang.NoClassDefFoundError>
```
@dkayiwa  / @ibacher - this should fix the 2.4.x build

TRUNK-6063 - Fix to get broken unit test working in 2.4.x+

---

api/src/main/java/org/openmrs/api/UserService.java
api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/test/java/org/openmrs/api/UserServiceTest.java

This PR is against the 2.3.x branch, and ensures that the user's default locale is used to generate the localized email subject and message that is sent out in response to a password reset request.

TRUNK-6069 - Password reset email should be localized to the user

---

api/src/main/java/org/openmrs/util/DatabaseUpdater.java

This PR is against the 2.5.x branch.  Once approved and merged it will need to be ported to the master branch.

TRUNK-6078: Custom changeset classes in modules fail on 2.5.x+

---

api/pom.xml
pom.xml

jackson starting from [2.12](https://github.com/FasterXML/jackson-databind/blob/6497f1b35ee917b4095d580082ecc4c3f03088ec/src/main/java/com/fasterxml/jackson/databind/util/BeanUtil.java#L297) version onwards needs dependency of `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` to process Java 8 date/time. 
[https://bahmni.atlassian.net/browse/BAH-2274](https://bahmni.atlassian.net/browse/BAH-2274) …

Siva Reddy | BAH-2274 | Support for Java8 DateTime in jackson

---

api/src/main/java/org/openmrs/api/context/Context.java
api/src/main/java/org/openmrs/api/context/UserContext.java
api/src/test/java/org/openmrs/api/context/ContextTest.java
api/src/test/java/org/openmrs/util/LocationUtilityTest.java

This fixes a bug where `refreshUserContext()` was always setting the user location to the user's default location. Basically, the user's location will now be set to their default location only when logging in or if no session location has been set.
see https://issues.openmrs.org/browse/TRUNK-6141 …

TRUNK-6141: Updating User in UserContext should not unset location

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.6.x.xml
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java

Java field Diagnosis.rank is marked as not nullable via the JPA annotations but encounter_diagnosis.dx_rank column is missing the not null constraint in the database. So this adds not null constraint to encounter_diagnosis.dx_rank column.
see https://issues.openmrs.org/browse/TRUNK-6081 …

TRUNK-6081: Add not null constraint to encounter_diagnosis.dx_rank

---

api/src/test/java/org/openmrs/obs/BinaryStreamHandlerTest.java
api/src/test/java/org/openmrs/obs/MediaHandlerTest.java

After an upgrade to junit 5 two tests were disabled due to an error affecting windows. The cause of the error is the same in both tests, a typo resulting in an attempt to close the same stream twice. This PR fixes that and enables the tests for windows again.
see https://issues.openmrs.org/browse/TRUNK-5876
No? -> figure out why and add the fix to your commit. It is your responsibility to make …

TRUNK-5876: Fix saveObs_shouldRetrieveCorrectMimetype tests on windows

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateContextDAO.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java

Added 'security.waitingTimeUnlockAccountAfterLockout' Globap property which configures for how long in minutes the account is blocked after a number of failed login attempts. 
The number of failed attempts is already configurable via: security.allowedFailedLoginsBeforeLockout
https://issues.openmrs.org/browse/TRUNK-6082

TRUNK-6082: Make failed login lockout timeout configurable

---

api/src/main/resources/org/openmrs/api/db/hibernate/DrugReferenceMap.hbm.xml
api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java

Failing unit test and fix that allows the unit test to pass.

TRUNK-6164 - Fix to enable adding new drug reference maps during drug creation

---

api/src/main/java/org/openmrs/CodedOrFreeText.java
api/src/main/java/org/openmrs/Condition.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConditionDAO.java
api/src/main/java/org/openmrs/api/impl/ConditionServiceImpl.java
api/src/test/java/org/openmrs/ConditionTest.java
api/src/test/java/org/openmrs/api/impl/ConditionServiceImplTest.java

This makes the following changes to conditions:
* Fixes the ConditionService#saveCondition method to only void and recreate if a Condition has changed
* Fixes the ConditionService#saveCondition method to not exclude updates to properties when a Condition is voided
* Fixes the ConditionService#saveCondition method to not exclude updates to properties when a Condition is unvoided
* Fixes the ConditionService#getAllConditions(Patient) method to exclude voided Conditions
* Adds missing hashcode and equals methods to CodedOrFreeText
* Add new method to Condition to compare whether it matches another Condition
see https://issues.openmrs.org/browse/TRUNK-6171

TRUNK-6171: Address inconsistency issues with ConditionService

---

api/src/test/java/org/openmrs/validator/VisitValidatorTest.java

Fix the StackOver flow error in the VisitValidatorTest.
TRUNK-6177 Fix the StackOver flow error in the VisitValidatorTest.
Description of what I changed
I flushed the sessions in the failing tests to eliminate the stackoverflow error.
- [ x] I ran `mvn clean package` right before creating this …

TRUNK-6177 Fix the StackOver flow error in the VisitValidatorTest.

---

api/pom.xml
api/src/test/java/org/openmrs/module/dtd/ConfigXmlBuilder.java
api/src/test/java/org/openmrs/module/dtd/DtdTestValidator.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_0.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_1.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_2.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_3.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_4.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_5.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_6.java
pom.xml

Adds tests to validate config dtds for versions 1.0-1.6
see https://issues.openmrs.org/browse/TRUNK-5490

TRUNK-5490: Add DTD config tests

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.0.x.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.1.x.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.5.x.xml
liquibase/pom.xml
pom.xml

Upgraded liquibase core and liquibase plugin to version 4.8.0. See the jira ticket below to review attached logs from manual testing.
There was a breaking change in version 4.7.0. This isn't shown in the github release notes but you can find them here - https://docs.liquibase.com/start/release-notes/home.html. See below
----------------------------------
**Breaking Changes**
[[PR#2228](https://github.com/liquibase/liquibase/pull/2228)] [[Nathan Voxland](https://github.com/nvoxland)] Handle the fact that FK names are not always unique. Fixes [PR#2227](https://github.com/liquibase/liquibase/issues/2227). When using the foreignKeyConstraintExists precondition, you must now specify foreignKeyTableName. See also: [PR#2565](https://github.com/liquibase/liquibase/pull/2565) fixing …

TRUNK-6155: Upgrade 2.7 Platform to Liquibase 4.8.0

---

api/src/main/java/org/openmrs/ConceptName.java
api/src/test/java/org/openmrs/api/db/ConceptDAOTest.java
api/src/test/resources/org/openmrs/api/include/ConceptServiceTest-accents.xml

This updates the Lucene analyzer configuration for ConceptName to include the ASCIIFoldingFilterFactory which enables diacritic-insensitive searching
see https://issues.openmrs.org/browse/TRUNK-6210

Trunk 6210 Concept Searching should be "diacritic-insensitive"

---

.github/workflows/build.yaml
api/src/main/java/org/openmrs/api/context/UserContext.java
api/src/test/java/org/openmrs/api/context/UserContextTest.java

`getDefaultLocationId()` now supports the `defaultLocation` property if the value is a UUID instead of an integer
see https://issues.openmrs.org/browse/TRUNK-6209

TRUNK-6209: defaultLocation should handle UUIDs as well as location ids

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateAdministrationDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateUtil.java
api/src/main/java/org/openmrs/api/db/hibernate/MatchMode.java
api/src/test/java/org/openmrs/OpenmrsTestsTest.java
api/src/test/java/org/openmrs/api/AdministrationServiceTest.java
api/src/test/java/org/openmrs/api/db/hibernate/MatchModeTest.java

I am initiating the migration of the Hibernate Criteria API to the JPA Criteria API, starting with the HibernateAdministrationDAO class. This task represents the first in a series of pull requests aimed at systematically updating our DAOs.
Additionally, I've incorporated several new tests and confirmed their compatibility with the existing Hibernate Criteria implementation. This pre-validation step is to ensure that our transition to the JPA Criteria API is regression-free.
A small change I made was to `shouldHaveTestAnnotationWhenStartingWithShould` to handle tests with the `ParameterizedTest` annotation
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the …

TRUNK-6202 Replace Hibernate Criteria API with JPA Criteria API for HibernateAdministrationDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateProviderDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateProviderDAO class. This class had a little more complexity than previous migrations and could do with a closer look during the review.
No? Unsure? -> …

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateProviderDAO

---

api/src/main/java/org/openmrs/hl7/db/hibernate/HibernateHL7DAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateHL7DAO class. There was a lot of test coverage missing in this class that I have not added yet. It didn't seem to follow the same pattern as the other DAOs where there is an xml set up to initialize mocks in the database. If we need to cover these missing tests before merging I may need some guidance on this.
added all formatting …

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateHL7DAO

---

api/src/main/java/org/openmrs/validator/ObsValidator.java

On O3 if you try to void an obsGroup all is `Obs` it will fail with:
- ['Obs #1551302' failed to validate with reason: error.noValue, valueText: Cannot be empty or null]
This is due to the fact that all in `Obs` inside the `obsGroup` have already been voided and does not recognize it as an obsGroup.
Note: Please add this development to version 2.5.x
see https://openmrs.atlassian.net/browse/TRUNK-6219 …

TRUNK-6219: Obs should be considered a group if it ever had group members

---

api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java

Refactor PatientServiceImpl.getIdentifierValidator(String pivClassName) to throw an exception when the identifier class is not found, instead of returning the default lunch validator.
see https://issues.openmrs.org/browse/TRUNK-1992 …

TRUNK-1992:  patientServiceImpl.getIdentifierValidator(String pivClassName) shouldn't return default Luhn validator

---

api/src/main/java/org/openmrs/util/LocaleUtility.java
api/src/test/java/org/openmrs/util/LocaleUtilityTest.java

LocaleUtility#fromSpecification parses language tags in the format en_USinto Java locales. This is the format used for Locales in versions of Java up to Java 6. With Java 7, Java began supporting standard BCP-47 language tags (en-US) as well as the underscore variant.
see https://openmrs.atlassian.net/browse/TRUNK-6216
No? -> figure out why and add the fix to your commit. It is your responsibility …

TRUNK-6216: LocaleUtility#fromSpecification should be updated to support BCP-47 language tags.

---

api/src/main/java/org/openmrs/module/ModuleFileParser.java
api/src/main/resources/org/openmrs/module/dtd/README.md
api/src/main/resources/org/openmrs/module/dtd/config-1.6.dtd
api/src/main/resources/org/openmrs/module/dtd/config-1.7.dtd
api/src/test/java/org/openmrs/module/ModuleFileParserTest.java
api/src/test/java/org/openmrs/module/ModuleFileParserUnitTest.java

TRUNK-4004 (#923) added extremely useful functionality to allow modules to declare that the need to start before any arbitrary modules. However, the existence of this feature was never exposed through the DTDs and there were no tests for the parser for this feature, so this commit rounds things out a bit.
A note on the implementation:
To get the DTD to work without going absolutely insane, the DTD actually declares the support for `start_before_module` as opposed to the original `module`. The support for `start_before_module` is added in this PR, so in older versions it may be necessary to use the `module` key instead of `start_before_module`. (The issue is that DTDs have a hard time with namespacing and the root element of config.xml is already called `module`).
see …

TRUNK-4004: Expose start_before_modules functionality better

---

liquibase/src/main/java/org/openmrs/liquibase/AbstractSnapshotTuner.java
liquibase/src/main/java/org/openmrs/liquibase/Main.java
liquibase/src/test/java/org/openmrs/liquibase/AbstractSnapshotTunerTest.java
liquibase/src/test/java/org/openmrs/liquibase/CoreDataTunerTest.java
liquibase/src/test/java/org/openmrs/liquibase/MainTest.java
liquibase/src/test/java/org/openmrs/liquibase/SchemaOnlyTunerTest.java

The following SAXReader features have been configured in order to properly restrict xml external entity references in order to prevent xxe attacks and other security concerns:
1. `http://apache.org/xml/features/disallow-doctype-decl`: This disables the processing of Document Type Definitions (DTDs) which can be exploited for **XXE** attacks.
2. `http://xml.org/sax/features/external-general-entities`: This disables the loading of external general entities, another way to launch **XXE** attacks.
3. `http://xml.org/sax/features/external-parameter-entities`: This disables the processing of external parameter entities which is another way to perform **XXE** attacks.
see https://issues.openmrs.org/browse/TRUNK-6041 …

TRUNK-6041: Proper Restriction of XML External Entity Reference to prevent XXE attacks

---

api/src/main/java/org/openmrs/ConceptAttributeType.java
api/src/main/java/org/openmrs/VisitAttributeType.java
api/src/main/java/org/openmrs/api/db/hibernate/envers/OpenmrsRevisionEntity.java
api/src/main/java/org/openmrs/api/db/hibernate/envers/OpenmrsRevisionEntityListener.java
api/src/main/java/org/openmrs/person/PersonMergeLog.java
api/src/main/resources/hibernate.default.properties
api/src/test/java/org/openmrs/util/databasechange/ValidateHibernateMappingsDatabaseIT.java

I have enabled logging for tables that were omitted in the last PR. To identify these tables, I used the following SQL script to detect which tables lack corresponding audit tables:
```
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'openmrs'
AND table_name NOT LIKE '%_AUD'
AND table_name NOT IN (
SELECT SUBSTRING_INDEX(table_name, '_AUD', 1)
FROM information_schema.tables
WHERE table_schema = 'openmrs'
AND table_name LIKE '%_AUD'
);
```
Here are the tables currently without audit tables:
-  OpenMRSRevisionEntity: This is a custom Hibernate Envers revision entity and does not require an audit table.
-  concept_proposal_tag_map: Lacks a corresponding Hibernate entity or mapping.
-  report_object: Lacks a corresponding Hibernate entity or mapping.
-  user_property: …

OMRS-131: Detailed Audit Logging (Updated)

---

.github/workflows/scorecard.yml

The purpose of this PR is to fix: https://github.com/openmrs/openmrs-core/actions/runs/9995004178/job/27626138324

(chore) Revert ossf/scorecard-action version

---

api/src/main/java/org/openmrs/api/AdministrationService.java
api/src/main/java/org/openmrs/api/impl/AdministrationServiceImpl.java
api/src/main/java/org/openmrs/serialization/SimpleXStreamSerializer.java
api/src/main/resources/applicationContext-service.xml
api/src/test/java/org/openmrs/api/AdministrationServiceTest.java
api/src/test/java/org/openmrs/serialization/SimpleXStreamSerializerTest.java
pom.xml

see https://issues.openmrs.org/browse/TRUNK-6188

TRUNK-6188 Upgrade xstream and migrate to whitelisting

---

api/src/main/java/org/openmrs/util/databasechange/DuplicateEncounterTypeNameChangeSet.java

fix the typo `processsing` -> `processing` in logging messages

Fix typo in logging messages

---

startup.sh

See https://openmrs.atlassian.net/browse/TRUNK-6248
See https://openmrs.slack.com/archives/C02PYQD5D0A/p1721160589093129

TRUNK-6248: Backend Docker should not fail starting if curl command is failing

---

webapp/src/main/webapp/WEB-INF/web.xml

Resolve 3.3.2

---

bamboo-specs/bamboo.yml

Adding maven.development.version and build.release.type variables to Bamboo

---

api/src/main/java/org/openmrs/module/Module.java
api/src/main/java/org/openmrs/module/ModuleClassLoader.java
api/src/main/java/org/openmrs/module/ModuleFileParser.java
api/src/main/resources/org/openmrs/module/dtd/config-2.0.dtd
api/src/test/java/org/openmrs/module/ModuleClassLoaderTest.java
api/src/test/java/org/openmrs/module/ModuleExtensionsTest.java
api/src/test/java/org/openmrs/module/ModuleFileParserTest.java
api/src/test/java/org/openmrs/module/ModuleUtilTest.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_0.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_1.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_2.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_3.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_4.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_5.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_6.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V2_0.java

This PR updates the logic to use globs instead of regex when matching conditional resources. This logic is only applied to config versions 2.0 and onwards, earlier config.xml versions will still use regex. 
The default pattern is `glob:**/%s` to make it agnostic to absolute paths, allowing users to focus on matching relative paths instead.
This change also includes adding the config.xml version to the `Module` class as `configVersion` to allow us to check if we should use glob or regex logic. This PR also uses the `ModuleUtil.matchRequiredVersions` function as this seems to work well for configVersions that only have two parts like 2.0. 
I tried to add parameterized tests to cover different glob input patterns and config versions, please let me know if  you notice any other patterns that …

TRUNK-6252: Conditional resource path should be interpreted as a globs

---

api/src/main/java/org/openmrs/PatientIdentifierType.java

see https://openmrs.atlassian.net/browse/TRUNK-6293

TRUNK-6293 - Patient IdentifierType description should be length 65535 in the Hibernate annotation

---

api/src/main/java/org/openmrs/module/ModuleUtil.java
api/src/test/java/org/openmrs/module/ModuleUtilTest.java

TRUNK-5208 compareVersion orders SNAPSHOT version before regular one
That means a version string like "1.2.3-SNAPSHOT" is ordered before version string "1.2.3".
Also update javadoc and give more descriptive names to variables.
see https://issues.openmrs.org/browse/TRUNK-5208
- [ x ] I have **added tests** to cover my changes. (If you refactored …

TRUNK-5208 ModuleUtil compareVersions should sort a SNAPSHOT version as "less than"

---

api/src/main/java/org/openmrs/api/StorageService.java
api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
api/src/main/java/org/openmrs/api/storage/BaseStorageService.java
api/src/main/java/org/openmrs/api/storage/LocalStorageService.java
api/src/main/java/org/openmrs/api/storage/ObjectMetadata.java
api/src/main/java/org/openmrs/api/storage/StorageServiceCondition.java
api/src/main/java/org/openmrs/api/stream/StreamDataService.java
api/src/main/java/org/openmrs/api/stream/StreamDataWriter.java
api/src/main/java/org/openmrs/obs/handler/AbstractHandler.java
api/src/main/java/org/openmrs/obs/handler/BinaryDataHandler.java
api/src/main/java/org/openmrs/obs/handler/BinaryStreamHandler.java
api/src/main/java/org/openmrs/obs/handler/ImageHandler.java
api/src/main/java/org/openmrs/obs/handler/MediaHandler.java
api/src/main/java/org/openmrs/obs/handler/TextHandler.java
api/src/main/resources/applicationContext-service.xml
api/src/test/java/org/openmrs/api/EncounterServiceTest.java
api/src/test/java/org/openmrs/api/ObsServiceTest.java
api/src/test/java/org/openmrs/api/StorageServiceTest.java
api/src/test/java/org/openmrs/obs/AbstractHandlerTest.java
api/src/test/java/org/openmrs/obs/BinaryDataHandlerTest.java
api/src/test/java/org/openmrs/obs/BinaryStreamHandlerTest.java
api/src/test/java/org/openmrs/obs/ImageHandlerTest.java
api/src/test/java/org/openmrs/obs/MediaHandlerTest.java
api/src/test/java/org/openmrs/obs/TextHandlerTest.java

see https://issues.openmrs.org/browse/TRUNK-6304
- [x ] All new and existing **tests passed**.
No? -> figure out why and …

TRUNK-6304 Refactor code to use Storage Service

---

webapp/pom.xml

Reverts openmrs/openmrs-core#4964

Revert "maven(deps): bump org.eclipse.jetty:jetty-maven-plugin from 9.4.35.v20201120 to 11.0.25"

---

webapp/src/main/webapp/WEB-INF/web.xml

This PR adds a multipart filter to 2.5x branch since the recent addition of XSS Filter fails without this filter added. The issue started happening after the [addition](https://github.com/openmrs/openmrs-module-legacyui/commit/7662c7200fb83e475af3506a9b583b2fd2d6b270) of XSSFilter for security reasons. The changes added here is basically a back port of the changes from 2.6.x versions into 2.5.x versions. Reference commit [here](https://github.com/openmrs/openmrs-core/commit/619885fe62a02b60b22cea2446375ae9e1c03361).
see https://issues.openmrs.org/browse/TRUNK-6331

TRUNK-6331 Add. Multipart filter to fix issues with file uploads due to XSS Filter

---

README.md

TRUNK-6373: Add instructions for running Jetty and Cargo on custom ports
Updated the `README.md` to include clear instructions for:
- Running Jetty on a custom port using `-Djetty.http.port`
- Running Cargo on the default port using `mvn cargo:run`
- Running Cargo on a custom port using `-Dcargo.servlet.port`
These changes help developers understand how to run the OpenMRS application on ports other than the default ones.
see https://issues.openmrs.org/browse/TRUNK-6373

TRUNK-6373: updatedReadme

---

Dockerfile

Upgraded Tomcat from 9.0.107 to 10.1.16 in the Dockerfile as part of TRUNK-6388.

TRUNK-6388: Upgrade Tomcat to 10.1.16

---

api/src/main/java/org/openmrs/util/OpenmrsConstants.java

Added two global properties. One allows creating a limit to how long after encounter creation the encounter can be edited. By default there remains no limit. The other allows specifying privileges of users that are allowed to override the time limit.
These are going to be used in the O3 frontend. Eventually they should be respected by the APIs as well.
https://openmrs.atlassian.net/browse/O3-4957
Is this project not set up with an .editorconfig file or post-commit hook?
It's a GP
Haha wait this is what does the formatting; what's the first checkbox for???
N/A

O3-4957: Add global properties for encounter editing time restriction

---

README.md

I updated the **README.md** file to replace the indirect links for:
- *Getting Started as a Developer*
- *How To Configure Your IDE*
Previously, these links redirected to intermediate pages that only contained the final resource URL. This change makes the links point directly to the intended resources, removing the unnecessary intermediate step.
see https://openmrs.atlassian.net/browse/TRUNK-6404

TRUNK-6404: Update README links to point directly to resources

---

api/src/main/java/org/openmrs/aop/AuthorizationAdvice.java
api/src/main/java/org/openmrs/api/UserService.java
api/src/main/java/org/openmrs/api/context/Daemon.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java
api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/test/java/org/openmrs/api/db/UserDAOTest.java

This adds guards to the `HibernateUserDao` for all calls that can change a user's password to ensure that they are called from the `UserService` class. I've also modified the `Daemon` class to use a slightly different mechanism to look-up the caller primarily because the `SecurityManager`, and hence the `OpenmrsSecurityManager` are deprecated.
N.B. There's a better for this available in Java 9+ using the `StackTraceWalker` machinery, but since in the 2.x branches we still support Java 8, I'm going to do this as two PRs, one here for 2.8.x and backporting if we opt to and a second PR for 3.x where we can use the Java 9 APIs. (The `StackTraceWalker` allows the lazy-loading of stack frames using the stream API; the technique used here—as with the technique of using a …

TRUNK-6435: Password resets must go through service API
