openmrs/openmrs-core

- web/src/test/java/org/openmrs/web/patient/PatientDashboardGraphControllerTest.java
> Update test to work with unordered JSON.

- web/src/test/java/org/openmrs/web/servlet/DownloadDictionaryServletTest.java
Updated the line break tests to properly test with any ordering of the line content
Fixes TRUNK-4593, TRUNK-4594
> Updated tests to work with any line ordering

- api/src/main/java/org/openmrs/Obs.java
- api/src/main/java/org/openmrs/api/ProgramWorkflowService.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientSetDAO.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/LocationServiceImpl.java
- api/src/main/java/org/openmrs/hl7/handler/ADTA28Handler.java
- api/src/main/java/org/openmrs/hl7/handler/ORUR01Handler.java
- api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
- api/src/main/java/org/openmrs/module/ModuleUtil.java
- api/src/main/java/org/openmrs/patient/impl/BaseHyphenatedIdentifierValidator.java
- api/src/main/java/org/openmrs/util/OpenmrsClassLoader.java
I'm completing GCI-09 with this pull request. `openmrs-api` tests pass (25 skipped by JUnit).
> GCI-09 from user hexafraction

- api/src/main/java/org/openmrs/Cohort.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientSetDAO.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- api/src/test/java/org/openmrs/api/ActiveListServiceTest.java
- api/src/test/java/org/openmrs/api/AdministrationServiceTest.java
- api/src/test/java/org/openmrs/api/ConceptServiceTest.java
- api/src/test/java/org/openmrs/api/ObsServiceTest.java
- api/src/test/java/org/openmrs/api/PatientServiceTest.java
- api/src/test/java/org/openmrs/api/ProviderServiceTest.java
- api/src/test/java/org/openmrs/api/VisitServiceTest.java
- api/src/test/java/org/openmrs/propertyeditor/DrugEditorTest.java
- api/src/test/java/org/openmrs/scheduler/SchedulerServiceTest.java
- web/src/main/java/org/openmrs/web/controller/concept/ConceptStopWordListController.java
- web/src/main/java/org/openmrs/web/dwr/DWRObsService.java
- web/src/main/java/org/openmrs/web/servlet/AbstractGraphServlet.java
- web/src/main/java/org/openmrs/web/servlet/ConceptRedirectServlet.java
- web/src/main/java/org/openmrs/web/servlet/QuickReportServlet.java
- web/src/main/java/org/openmrs/web/servlet/SummaryServlet.java
- web/src/test/java/org/openmrs/web/controller/form/FieldFormControllerTest.java
- web/src/test/java/org/openmrs/web/dwr/ProviderListItemTest.java
api/src/test/java/org/openmrs/report/ReportSchemaXmlTest.java was already removed after @azuro's commit
> https://github.com/openmrs/openmrs-core/pull/1175/ | Use static method Integer.valueOf instead of constructor: new Integer

- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- web/src/main/java/org/openmrs/module/web/taglib/ExtensionPopupMenuTag.java
- web/src/main/java/org/openmrs/web/taglib/ListPickerTag.java
http://issues.openmrs.org/browse/GCI-9
Objective of this commit is to replace Math.random() with a Random object at several instances.
> Using Random nextInt() instead of Math.random()

- api/src/main/java/org/openmrs/PersonName.java
- api/src/main/java/org/openmrs/api/context/Context.java
- api/src/main/java/org/openmrs/api/context/Daemon.java
- api/src/main/java/org/openmrs/api/context/ServiceContext.java
- api/src/main/java/org/openmrs/hl7/handler/ORUR01Handler.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/reporting/export/DataExportFunctions.java
- api/src/main/java/org/openmrs/reporting/export/DataExportUtil.java
- api/src/main/java/org/openmrs/reporting/export/RowPerObsDataExportReportObject.java
- api/src/main/java/org/openmrs/util/DatabaseUpdater.java
- api/src/main/java/org/openmrs/util/MemoryLeakUtil.java
- web/src/main/java/org/openmrs/web/Listener.java
- web/src/main/java/org/openmrs/web/controller/concept/ConceptClassListController.java
- web/src/main/java/org/openmrs/web/controller/concept/ConceptDatatypeListController.java
- web/src/main/java/org/openmrs/web/controller/encounter/LocationListController.java
- web/src/main/java/org/openmrs/web/controller/form/FormListController.java
- web/src/main/java/org/openmrs/web/controller/patient/MergePatientsFormController.java
- web/src/main/java/org/openmrs/web/controller/program/StateConversionListController.java
- web/src/main/java/org/openmrs/web/controller/user/PrivilegeListController.java
- web/src/main/java/org/openmrs/web/taglib/FieldGenTag.java
In this pull:
-Removed Redundant null checks
-Used logger utility instead of Throwable.printStackTrace()
-Eradicated race conditions on lazy static initializations.
-Corrected improper equals() operations.
-Fixed: Invocation of toString on an array
> GCI - 9 #1

- api/src/main/java/org/openmrs/PersonName.java
- api/src/main/java/org/openmrs/api/context/Context.java
- api/src/main/java/org/openmrs/api/context/Daemon.java
- api/src/main/java/org/openmrs/api/context/ServiceContext.java
- api/src/main/java/org/openmrs/hl7/handler/ORUR01Handler.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/reporting/export/DataExportFunctions.java
- api/src/main/java/org/openmrs/reporting/export/DataExportUtil.java
- api/src/main/java/org/openmrs/reporting/export/RowPerObsDataExportReportObject.java
- api/src/main/java/org/openmrs/util/DatabaseUpdater.java
- api/src/main/java/org/openmrs/util/MemoryLeakUtil.java
- web/src/main/java/org/openmrs/web/Listener.java
- web/src/main/java/org/openmrs/web/controller/concept/ConceptClassListController.java
- web/src/main/java/org/openmrs/web/controller/concept/ConceptDatatypeListController.java
- web/src/main/java/org/openmrs/web/controller/encounter/LocationListController.java
- web/src/main/java/org/openmrs/web/controller/form/FormListController.java
- web/src/main/java/org/openmrs/web/controller/patient/MergePatientsFormController.java
- web/src/main/java/org/openmrs/web/controller/program/StateConversionListController.java
- web/src/main/java/org/openmrs/web/controller/user/PrivilegeListController.java
- web/src/main/java/org/openmrs/web/taglib/FieldGenTag.java
Reverts openmrs/openmrs-core#1186
> Revert "GCI - 9 #1"

- api/src/test/java/org/openmrs/annotation/OpenmrsProfileExcludeFilterTest.java
- api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java
https://issues.openmrs.org/browse/TRUNK-4578
> TRUNK-4578 Ignore tests based on OpenMRS version and modules

- api/src/main/resources/liquibase-update-to-latest.xml
https://issues.openmrs.org/browse/TRUNK-4573
> TRUNK-4573 Improve migration of concept name tags to types

- api/src/main/java/org/openmrs/layout/web/LayoutTemplate.java
- api/src/main/java/org/openmrs/scheduler/Schedule.java
- api/src/main/java/org/openmrs/util/AttributableDate.java
- web/src/main/java/org/openmrs/module/web/ModuleResourcesServlet.java
- web/src/main/java/org/openmrs/web/OpenmrsCookieThemeResolver.java
- web/src/main/java/org/openmrs/web/controller/customdatatype/CustomValueController.java
- web/src/main/java/org/openmrs/web/controller/person/AddPersonController.java
- web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
- web/src/main/java/org/openmrs/web/filter/startuperror/StartupErrorFilter.java
- web/src/main/java/org/openmrs/web/filter/update/UpdateFilter.java
- web/src/main/java/org/openmrs/web/taglib/ForEachDrugOrderTag.java
Fixed:
-- Constants should be declared "final static" rather than merely "final"
Ticket: https://issues.openmrs.org/browse/GCI-9
> Constants should be declared 'final static' rather than merely 'final'

- api/src/main/java/org/openmrs/api/db/hibernate/ChainingInterceptor.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/propertyeditor/ConceptAnswersEditor.java
- api/src/main/java/org/openmrs/propertyeditor/ConceptSetsEditor.java
- web/src/main/java/org/openmrs/web/attribute/WebAttributeUtil.java
https://issues.openmrs.org/browse/GCI-9
> Moved left curly braces to the ends of lines of code

- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
Ticket: https://issues.openmrs.org/browse/GCI-9
> Array designators "[]" should be on the type, not the variable

- web/src/main/java/org/openmrs/web/controller/ConceptFormController.java
- web/src/test/java/org/openmrs/web/controller/ConceptFormControllerTest.java
Made changes in the ConceptFormBackingObject class to add concept id to answers while parsing them.
Added a test case as well.
> TRUNK-4582: Set Concept for all ConceptAnswers

- api/src/main/java/org/openmrs/PatientIdentifierType.java
- api/src/main/java/org/openmrs/api/PersonService.java
- api/src/main/java/org/openmrs/hl7/handler/ORUR01Handler.java
- api/src/main/java/org/openmrs/util/MemoryLeakUtil.java
- api/src/main/java/org/openmrs/util/UpgradeUtil.java
- web/src/main/java/org/openmrs/web/controller/patient/ShortPatientFormController.java
- web/src/main/java/org/openmrs/web/taglib/FieldGenTag.java
https://issues.openmrs.org/browse/TRUNK-4632
> TRUNK-4632 Dodgy - Redundant nullcheck of value known to be non-null

- api/src/main/java/org/openmrs/api/context/Context.java
- web/src/main/java/org/openmrs/web/controller/patient/MergePatientsFormController.java
@rkorytkowski  https://issues.openmrs.org/browse/TRUNK-4633
> Trunk 4633

- api/src/main/java/org/openmrs/api/ConceptService.java
- api/src/main/java/org/openmrs/api/ObsService.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
@rkorytkowski https://issues.openmrs.org/browse/TRUNK-4634
> Trunk 4634

- api/src/main/java/org/openmrs/layout/name/NameTemplate.java
- web/src/main/java/org/openmrs/layout/web/name/NameTemplate.java
- web/src/main/java/org/openmrs/web/controller/person/PersonFormController.java
@rkorytkowski https://issues.openmrs.org/browse/TRUNK-4643
> TRUNK-4643 "Performance - Method concatenates strings using + in a loop"

- web/src/main/java/org/openmrs/scheduler/web/controller/SchedulerFormController.java
@rkorytkowski https://issues.openmrs.org/browse/TRUNK-4650
> TRUNK-4650 "Multithreaded correctness - Static DateFormat"

- api/src/main/java/org/openmrs/hl7/handler/ORUR01Handler.java
- web/src/main/java/org/openmrs/web/controller/concept/ConceptClassListController.java
- web/src/main/java/org/openmrs/web/controller/concept/ConceptDatatypeListController.java
- web/src/main/java/org/openmrs/web/controller/encounter/LocationListController.java
- web/src/main/java/org/openmrs/web/controller/form/FormListController.java
- web/src/main/java/org/openmrs/web/controller/program/StateConversionListController.java
- web/src/main/java/org/openmrs/web/controller/user/PrivilegeListController.java
https://issues.openmrs.org/browse/TRUNK-4612
> TRUNK-4612 Correctness - Call to equals() comparing different types

- release-test/src/main/java/org/openmrs/steps/EditUserPasswordSteps.java
I run the tests and everything went normal and the running
time of the tests has no noticeable difference.
Signed-off-by: Yousef Hamza <jo.adam.93@gmail.com>
> TODO: hard coded to the first row of the users search result

- release-test/src/main/java/org/openmrs/steps/EditUserPasswordSteps.java
Reverts openmrs/openmrs-core#1436
> Revert "TODO: hard coded to the first row of the users search result"

- web/src/main/java/org/openmrs/layout/web/address/AddressSupport.java
- web/src/main/resources/openmrs-servlet.xml
- web/src/test/java/org/openmrs/layout/web/address/AddressSupportTest.java
- web/src/test/java/org/openmrs/layout/web/name/NameSupportTest.java
> TRUNK-3849: fix classcastexception on class mismatch with db

- api/src/test/java/org/openmrs/util/HttpClientTest.java
Reverts openmrs/openmrs-core#1408
> Revert "TRUNK-4522: Fix HttpClientTest test on JVM 1.8."

- api/src/main/java/org/openmrs/activelist/ActiveListItem.java
Fill javadoc for ActiveListItem.
> TRUNK-3175: Fill javadoc for ActiveListItem class.

- api/src/main/java/org/openmrs/activelist/Problem.java
Fill Problem javadocs.
https://issues.openmrs.org/browse/TRUNK-3178.
> TRUNK 3178: Fill Problem class javadoc.

- api/src/main/java/org/openmrs/util/OpenmrsConstants.java
- web/pom.xml
- web/src/main/java/org/openmrs/web/filter/GZIPFilter.java
- web/src/main/java/org/openmrs/web/filter/GZIPRequestStream.java
- web/src/main/java/org/openmrs/web/filter/GZIPRequestWrapper.java
- web/src/test/java/org/openmrs/web/filter/update/GZIPFilterTest.java
- web/src/test/java/org/openmrs/web/filter/update/UpdateFilterTest.java
@rkorytkowski https://issues.openmrs.org/browse/TRUNK-4646
> TRUNK-4646 Support compressed requests

- api/src/main/java/org/openmrs/ConceptAnswer.java
- api/src/main/java/org/openmrs/ConceptSet.java
- api/src/main/java/org/openmrs/PatientState.java
- api/src/main/java/org/openmrs/PersonAddress.java
- api/src/main/java/org/openmrs/activelist/Problem.java
- api/src/main/java/org/openmrs/attribute/BaseAttribute.java
@rkorytkowski https://issues.openmrs.org/browse/TRUNK-4639
> TRUNK-4639 extra fix

- web/src/main/java/org/openmrs/web/filter/update/UpdateFilter.java
- web/src/main/java/org/openmrs/web/filter/util/FilterUtil.java
Closing the DB resource properly in UpdateFilter and FilterUtil.
Edits on: https://github.com/openmrs/openmrs-core/pull/1455
Ticket: https://issues.openmrs.org/browse/TRUNK-4615
> TRUNK-4615 Method may fail to close database resource

- api/src/main/java/org/openmrs/api/FormService.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java
- api/src/test/java/org/openmrs/api/FormServiceTest.java
- api/src/test/resources/org/openmrs/api/include/FormServiceTest-multipleForms-formFields.xml
https://issues.openmrs.org/browse/TRUNK-3195
> TRUNK-3195: creating JUnit Test for validate behavior of HibernateFormDAO.getFormCriteria

- api/src/main/java/org/openmrs/Provider.java
- api/src/main/java/org/openmrs/api/ProviderService.java
- api/src/main/java/org/openmrs/validator/ProviderValidator.java
- api/src/test/java/org/openmrs/BaseCustomizableMetadataTest.java
- api/src/test/java/org/openmrs/ProviderTest.java
- api/src/test/java/org/openmrs/api/EncounterServiceTest.java
- api/src/test/java/org/openmrs/api/ProviderServiceTest.java
- api/src/test/java/org/openmrs/hl7/handler/ORUR01HandlerTest.java
- api/src/test/java/org/openmrs/validator/ProviderValidatorTest.java
- api/src/test/resources/org/openmrs/api/include/ProviderServiceTest-initial.xml
- web/src/main/java/org/openmrs/web/controller/provider/ProviderFormController.java
- web/src/main/java/org/openmrs/web/dwr/ProviderListItem.java
- web/src/test/java/org/openmrs/web/controller/provider/ProviderFormControllerTest.java
- web/src/test/java/org/openmrs/web/dwr/ProviderListItemTest.java
- webapp/src/main/webapp/WEB-INF/view/admin/provider/providerForm.jsp
Creating a new pull request. Please review
https://issues.openmrs.org/browse/TRUNK-3382
Sorry for that many broken PRs. Had some problems with rebasing. I hope I get rid of it finally.
> TRUNK-3382 Modify provider.getName() method so that it only looks at provider.person.name

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
https://issues.openmrs.org/browse/TRUNK-4682
> TRUNK-4682: Replace JDBC with Hibernate native query

- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
https://issues.openmrs.org/browse/TRUNK-4684
> TRUNK-4684:Replace JDBC with Hibernate native query

- api/src/main/java/org/openmrs/util/MemoryLeakUtil.java
https://issues.openmrs.org/browse/TRUNK-4586
> TRUNK-4586: Warning During Compilation - KeepAliveCache

- .travis.yml
Updating Travis CI config for IRC notifications to use NOTICE and more detail
> Updating Travis CI config for IRC notifications

- api/src/main/java/org/openmrs/obs/ComplexData.java
- api/src/main/java/org/openmrs/obs/handler/BinaryDataHandler.java
- api/src/main/java/org/openmrs/obs/handler/BinaryStreamHandler.java
- api/src/main/java/org/openmrs/obs/handler/ImageHandler.java
- api/src/main/java/org/openmrs/obs/handler/MediaHandler.java
- api/src/main/java/org/openmrs/obs/handler/TextHandler.java
- web/src/main/java/org/openmrs/web/WebConstants.java
- web/src/main/java/org/openmrs/web/controller/observation/handler/WebBinaryDataHandler.java
- web/src/main/java/org/openmrs/web/controller/observation/handler/WebBinaryStreamHandler.java
- web/src/main/java/org/openmrs/web/controller/observation/handler/WebHandlerUtils.java
- web/src/main/java/org/openmrs/web/controller/observation/handler/WebImageHandler.java
- web/src/main/java/org/openmrs/web/controller/observation/handler/WebTextHandler.java
- web/src/main/java/org/openmrs/web/servlet/ComplexObsServlet.java
Fixed the trivial ones; mostly coding standard related & doc. issues.
> TRUNK-2136: Code review issues

- api/src/main/java/org/openmrs/api/db/OrderDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java
- api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
https://issues.openmrs.org/browse/TRUNK-4680
> TRUNK-4680: Do not use DatabaseUtil.executeSQL

- webapp/src/main/webapp/WEB-INF/view/admin/users/roleForm.jsp
As mentioned in https://github.com/openmrs/openmrs-core/pull/1491#issuecomment-99366568
> TRUNK-4497 Role link bug fix

- webapp/pom.xml
https://issues.openmrs.org/browse/TRUNK-4703
> TRUNK-4703 fix jetty-maven-plugin configuration

- api/src/main/java/org/openmrs/api/OrderService.java
- api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
- api/src/test/java/org/openmrs/api/OrderServiceTest.java
Updated @should statements in OrderService to describe the changed expectations that a check for order same-ness only applies to drug orders; 
Wrote unit tests for updated expectations; 
Updated OrderServiceImple.saveOrder to implement the changed expectations.
> TRUNK-4699

- api/src/main/java/org/openmrs/util/PrivilegeConstants.java
- web/src/main/java/org/openmrs/web/controller/maintenance/SearchIndexController.java
- web/src/test/java/org/openmrs/web/controller/maintenance/SearchIndexControllerTest.java
- webapp/src/main/webapp/WEB-INF/messages.properties
- webapp/src/main/webapp/WEB-INF/view/admin/maintenance/localHeader.jsp
- webapp/src/main/webapp/WEB-INF/view/admin/maintenance/searchIndex.jsp
* create a controller to handle requests for displaying a search index view and for rebuilding the search index; 
* create a JSP for the search index view; create a privilege for managing the search index; 
* create properties for the messages on the search index view;
* unit tests for controller.
> TRUNK-4717: Rebuild search index when server is running

- api/src/main/java/org/openmrs/util/DoubleRange.java
- api/src/test/java/org/openmrs/util/DoubleRangeTest.java
Repeating a [previous](https://github.com/openmrs/openmrs-core/pull/1505) pull request after I was pointed to the proper community guidelines.
> TRUNK-4723: Add more @shoulds and junit test cases for DoubleRange.java

- api/src/main/java/org/openmrs/Person.java
- api/src/main/resources/liquibase-update-to-latest.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/Person.hbm.xml
- api/src/test/java/org/openmrs/PersonTest.java
- api/src/test/java/org/openmrs/api/db/hibernate/HibernatePersonDAOTest.java
- api/src/test/resources/org/openmrs/api/db/hibernate/include/HibernatePersonDAOTest-people.xml
https://issues.openmrs.org/browse/TRUNK-4727
> Trunk 4727 | Adding new birthtime column in person table.

- web/src/main/java/org/openmrs/web/controller/maintenance/SearchIndexController.java
- web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
- web/src/test/java/org/openmrs/web/controller/maintenance/SearchIndexControllerTest.java
Could You please merge it with fixed formatting?
> TRUNK-4717 Fix formatting

- api/src/main/java/org/openmrs/api/EncounterService.java
- api/src/test/java/org/openmrs/api/EncounterServiceTest.java
Make the EncounterService#getEncounters @should contract regarding
modification date filtering more exact.
> TRUNK-4571: Fix javadoc on EncounterService#getEncounters

- api/src/main/resources/liquibase-update-to-latest.xml
https://issues.openmrs.org/browse/TRUNK-4737
Please review
> TRUNK-4737 Remove liquibase changeset that doesn't belong

- api/src/main/java/org/openmrs/util/DoubleRange.java
- api/src/test/java/org/openmrs/util/DoubleRangeTest.java
This should address some long-standing comments on an earlier [commit](https://github.com/owolabileg/openmrs-core/commit/deeeee515195b60e08ffbc489826f8104e27b77a#commitcomment-11675019)
> TRUNK-4723: fixing test names to match what they really test

- web/src/main/java/org/openmrs/web/controller/UncaughtExceptionController.java
> TRUNK-4408: Change Logging Advice so that it doesn't log all exceptions

- api/src/main/java/org/openmrs/scheduler/timer/TimerSchedulerServiceImpl.java
Updated deprecated saveTask call to saveTaskDefinition.
> Fix for TRUNK-4731

- web/src/main/java/org/openmrs/module/web/ModuleResourcesServlet.java
https://issues.openmrs.org/browse/TRUNK-4739
Formatting was broken and fixed automatically by maven. Please merge corrected.
> TRUNK-4739 fix formatting

- release-test/pom.xml
This change removes an error in eclipse
> starting to fix eclipse build

- api/src/main/java/org/openmrs/validator/UserValidator.java
- api/src/test/java/org/openmrs/validator/UserValidatorTest.java
- web/src/main/java/org/openmrs/web/controller/user/UserFormController.java
- web/src/test/java/org/openmrs/web/controller/user/UserFormControllerTest.java
- extended UserValidator class to validate inner Person instance as well
- extended and fixed unit tests w.r.t. this change
> Fixing bug that showing database stack traces when user input fields too long - TRUNK-4539

- api/pom.xml
- pom.xml
- test/pom.xml
- tools/pom.xml
- web/pom.xml
- webapp/pom.xml
changed OpenMRS version across all pom.xml  
JIRA link : https://issues.openmrs.org/browse/TRUNK-4751
> TRUNK-4751 - Change openmrs-core master version to 2.0.0-SNAPSHOT

- webapp/src/main/webapp/WEB-INF/view/portlets/addPersonForm.jsp
addPersonForm.jsp should check if entered age>=120 to avoid inconsistent with the next step's "Nonsensical date" error
> addPersonForm.jsp should check if entered age>=120 to avoid inconsistent with the next step's "Nonsensical date" error

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/test/java/org/openmrs/api/ConceptServiceTest.java
- api/src/test/resources/org/openmrs/api/include/ConceptServiceTest-words.xml
https://issues.openmrs.org/browse/TRUNK-4763
> TRUNK-4673: List<ConceptSearchResult> getConcepts(String phrase... can return the same concept twice

- api/src/main/java/org/openmrs/AllergyType.java
- api/src/main/java/org/openmrs/util/PrivilegeConstants.java
- api/src/main/java/org/openmrs/util/databasechange/MigrateAllergiesChangeSet.java
- api/src/main/resources/liquibase-update-to-latest.xml
Changes following review
- move database change set to right folder
- remove some comments
> TRUNK-4747

- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientSetDAO.java
- api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
- web/src/main/java/org/openmrs/web/dwr/DWRPatientService.java
A few private methods removed according to Sonar rules
> Sonar:Unused private method should be removed

- api/src/main/java/org/openmrs/api/UserService.java
- api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
- api/src/test/java/org/openmrs/api/UserServiceTest.java
- api/src/test/resources/org/openmrs/api/include/UserServiceTest-changePasswordAction.xml
- webapp/src/main/webapp/WEB-INF/messages.properties
Added method to change user's password if one has correct privilege.
Also modified method changePassword(String pw1, String pw2) to
take either current password or answer to secret question when changing password.
PR for: https://issues.openmrs.org/browse/TRUNK-3871
> TRUNK-3871: Added back changePassword(User u, String pw)

- api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
Update the changePassword method to delegate to the new updatePassword
utility method
> Update changePassword(User user, String newPassword)

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/test/java/org/openmrs/api/db/hibernate/HibernateConceptDAOTest.java
- api/src/test/resources/org/openmrs/api/db/hibernate/include/HibernateConceptTestDataSet.xml
https://issues.openmrs.org/browse/TRUNK-4796
> TRUNK-4796 | Drug name search should accept special characters

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/test/java/org/openmrs/api/db/hibernate/HibernateConceptDAOTest.java
- api/src/test/resources/org/openmrs/api/db/hibernate/include/HibernateConceptTestDataSet.xml
Reverts openmrs/openmrs-core#1616
> Revert "TRUNK-4796 | Drug name search should accept special characters"

- webapp/src/main/webapp/WEB-INF/messages_fr.properties
This is a fix for the following bug: https://issues.openmrs.org/browse/TRUNK-4670
We used the changes previously made by sdale28 here: https://github.com/openmrs/openmrs-core/pull/1490
As I understand, there were some failed tests preventing the above pull request from being approved. We removed a few duplicated keys and the tests are now passing. We also reordered some of the keys into a more consistent order.
Apologies for not commenting on the official JIRA bug, but I had issues logging in.
> TRUNK-4670 Translated Create New Patient form into French

- api/src/main/java/org/openmrs/api/context/Context.java
- api/src/main/java/org/openmrs/api/db/ContextDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateContextDAO.java
Added a new method to update the search index asynchronously.
> TRUNK-4769 : Add updateSearchIndexAsync method to Context

- webapp/src/main/webapp/index.htm
https://issues.openmrs.org/browse/TRUNK-4786
> TRUNK-4786: Add a Platform 2.0 is running page

- webapp/src/main/webapp/index.htm
Created a user interface wiki page and added the link to the default openmrs 2.0 index.htm
> https://issues.openmrs.org/browse/TRUNK-4786

- api/src/main/java/org/openmrs/Address.java
- api/src/main/java/org/openmrs/Location.java
- api/src/main/java/org/openmrs/PersonAddress.java
- api/src/main/java/org/openmrs/validator/LocationValidator.java
- api/src/main/java/org/openmrs/validator/PersonAddressValidator.java
- api/src/main/resources/liquibase-update-to-latest.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/Location.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/PersonAddress.hbm.xml
- api/src/test/java/org/openmrs/validator/LocationValidatorTest.java
- api/src/test/java/org/openmrs/validator/PersonAddressValidatorTest.java
https://issues.openmrs.org/browse/TRUNK-4750
> TRUNK-4750: Added custom address fields to PersonAddress and Location

- api/src/main/java/org/openmrs/Cohort.java
- api/src/main/java/org/openmrs/Obs.java
- api/src/main/java/org/openmrs/Program.java
- api/src/main/java/org/openmrs/module/Module.java
> Trunk 4659

- api/src/main/java/org/openmrs/api/OrderService.java
- api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
- api/src/test/java/org/openmrs/OrderEntryIntegrationTest.java
@djazayeri @angshu Created saveRetrospectiveOrder method which will delegate the responsibility to save() method.
> TRUNK-4782 : Retrospective edit of Orders

- api/src/test/java/org/openmrs/module/ModuleActivatorTest.java
@dkayiwa  The test was doing assertion in wrong way.
> TRUNK-4678 : Fix shouldStopDependantModulesOnStopModule test

- api/src/main/java/org/openmrs/api/db/hibernate/AuditableInterceptor.java
The mistakes in entrySet iterator in for loop causes error durning "mvn clean install"
> Fixing mistakes in for loop

- web/pom.xml
- web/src/main/java/org/openmrs/web/WebUtil.java
Introduce contextual encoding methods to WebUtil which are delegated to OWASP Encoder. REPORT-492.
> FIX-FOR-REPORT-492-Introduced WebUtil methods delegated to OWASP Encoder.

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateLocationDAO.java
- api/src/main/java/org/openmrs/messagesource/impl/CachedMessageSource.java
- web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
Removed inefficient use of keySet iterator instead of entrySet
Replaced inefficient new Long(long) constructor with Long.valueOf(long)
> GCI-90: Fix three critical issues on OpenMRS sonarqube.

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateAdministrationDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateNoteDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/main/java/org/openmrs/notification/AlertService.java
- api/src/main/java/org/openmrs/scheduler/SchedulerUtil.java
- api/src/main/java/org/openmrs/scheduler/TaskDefinition.java
- api/src/main/java/org/openmrs/util/Format.java
- api/src/main/java/org/openmrs/util/Reflect.java
- api/src/main/java/org/openmrs/util/databasechange/MigrateAllergiesChangeSet.java
- api/src/main/java/org/openmrs/validator/UserValidator.java
- web/src/main/java/org/openmrs/web/filter/startuperror/StartupErrorFilterModel.java
Removed Useless imports.
Added method override for compareTo() and equals() methods.
@robbyoconnor, Sir I squashed both commits as you requested.
> GCI-9: Fix bad code practices from Sonar

- api/src/main/java/org/openmrs/customdatatype/SerializingCustomDatatype.java
https://issues.openmrs.org/browse/TRUNK-4807
> TRUNK-4807: Improve the implementation of SerializingCustomDatatype.validate

- api/src/main/java/org/openmrs/module/Module.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/util/CycleException.java
- api/src/main/java/org/openmrs/util/Graph.java
- web/src/main/java/org/openmrs/module/web/controller/ModuleListController.java
Module architecture fails to populate aware_of modules in ModuleClassLoader if they start in the wrong order - TRUNK-4487
> Module architecture fails to populate aware_of modules in ModuleClassLoader if they start in the wrong order - TRUNK-4487

- webapp/src/main/webapp/WEB-INF/view/admin/patients/shortPatientForm.jsp
Originally, the shortPatient form used form select to fetch locations. Replacing with spring binder solved the issue.
> LUI-32 fixed by replacing form select with spring bind tag

- api/src/main/java/org/openmrs/BaseOpenmrsObject.java
- api/src/test/java/org/openmrs/BaseOpenmrsObjectTest.java
Trunk-3844-Correct BaseOpenmrsObject equals
> Correct BaseOpenmrsObject equals

- webapp/src/main/webapp/WEB-INF/view/admin/patients/shortPatientForm.jsp
**Issue**: [TRUNK-4814](https://issues.openmrs.org/browse/TRUNK-4814)
**Fix**: fixed by replacing form select with spring bind tag
***Note***: Credit goes to @seekme94 for the work he has done
> Fix for TRUNK-4814: Error creating patient for large location IDs >1000

- api/src/main/resources/liquibase-update-to-latest.xml
Reverts openmrs/openmrs-core#1736
> Revert "Trunk 4813"

- web/src/main/java/org/openmrs/web/WebConstants.java
- web/src/main/java/org/openmrs/web/controller/LoginController.java
Attempt Fix for [TRUNK-4817](https://issues.openmrs.org/browse/TRUNK-4817)
> Redirect user when logged in away from login page if already authenticated

- api/src/main/java/org/openmrs/validator/ObsValidator.java
- api/src/test/java/org/openmrs/validator/ObsValidatorTest.java
The required functionality does exist. Also a test is there.
Only remaining work here seems to be to improve the test.
Please close the ticket afterwards.
> TRUNK-1861: improved OpsValidatorTest

- api/src/main/java/org/openmrs/api/db/ContextDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateContextDAO.java
- api/src/main/java/org/openmrs/logic/LogicService.java
- api/src/main/java/org/openmrs/messagesource/MutableMessageSource.java
- api/src/main/java/org/openmrs/messagesource/impl/MessageSourceServiceImpl.java
https://issues.openmrs.org/browse/TRUNK-208
> TRUNK-208: Fix Transactions Across Service Methods

- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/test/java/org/openmrs/module/ModuleFactoryTest.java
https://issues.openmrs.org/browse/APPTEST-53
Fix of branch-name=ticket-name in reference to #1765.
> APPTEST-53: Added tests for ModuleFactory in new test class ModuleFactoryTest

- api/src/main/java/org/openmrs/api/impl/PatientSetServiceImpl.java
- api/src/test/java/org/openmrs/api/PatientSetServiceTest.java
Added new test cases in file /api/src/test/java/org/openmrs/api/PatientSetServiceTest.java.
Added annotations for corresponding methods in file /api/src/main/java/org/openmrs/api/impl/PatientSetServiceImpl.java.
> APPTEST-54: Add tests for PatientSetServiceImpl

- api/src/main/java/org/openmrs/Concept.java
- api/src/test/java/org/openmrs/ConceptTest.java
Adding unit test for previously un-tested methods (business logic).
> TRUNK-4861 adding unit test to ConceptTest

- webapp/src/main/webapp/errorhandler.jsp
see https://issues.openmrs.org/browse/TRUNK-4862
> TRUNK-4862 Resolve syntax error in errorhandler.jsp

- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/test/java/org/openmrs/module/ModuleFactoryTest.java
This PR goes with the following JIRA Ticket
https://issues.openmrs.org/browse/APPTEST-59
> APPTEST-59: Added tests for multi module loading

- api/src/main/java/org/openmrs/Person.java
- api/src/test/java/org/openmrs/PersonTest.java
Adding more unit test in PersonTest to cover previously uncovered method in Person.java
> TRUNK-4855 adding more unit test to PersonTest

- web/src/main/java/org/openmrs/web/controller/LoginController.java
Added name for LoginController bean. Because it was conflicting with LoginController in rwandaprimarycare module.
> Final Fix for TRUNK-4817. Added functional controller for login page

- web/src/main/java/org/openmrs/web/WebConstants.java
- web/src/main/java/org/openmrs/web/controller/LoginController.java
- web/src/test/java/org/openmrs/web/controller/LoginControllerTest.java
see https://issues.openmrs.org/browse/TRUNK-4859
> TRUNK-4859 Add redirect url parameter to login page

- api/src/main/java/org/openmrs/module/ModuleUtil.java
Add javadoc explanation about the meaning of the allowed required version
ranges in methods matchRequiredVersions and checkRequiredVersion
> Clarify ModuleUtil javadoc of matching version methods

- api/src/main/java/org/openmrs/module/ModuleUtil.java
- api/src/test/java/org/openmrs/module/ModuleUtilTest.java
added ModuleUtil.isOpenmrsVersionInVersions() but need review and help in how to best write the tests that I annotated with '@Ignore'
see https://issues.openmrs.org/browse/TRUNK-4941
> TRUNK-4941 Add ModuleUtil.isOpenmrsVersionInVersions()

- api/src/main/java/org/openmrs/util/OpenmrsConstants.java
concept.causeOfDeath, concept.patientDied and concept.reasonOrderStopped have no longer default values
see https://issues.openmrs.org/browse/TRUNK-4776?filter=-1
> TRUNK-4776: Incorrect Global Properties for CIEL

- api/src/main/resources/org/openmrs/api/db/hibernate/Visit.hbm.xml
- api/src/test/java/org/openmrs/api/VisitServiceTest.java
> TRUNK-4937 | Save visit should not cascade save encounter

- README.md
Add coveralls.io badge to readme to show current coverage
see https://issues.openmrs.org/browse/TRUNK-1916
> TRUNK-1916 Add coveralls.io badge to readme

- api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
- api/src/test/java/org/openmrs/api/EncounterServiceTest.java
- api/src/test/resources/org/openmrs/api/include/EncounterServiceTest-saveObsHierarchyTests.xml
see https://issues.openmrs.org/browse/TRUNK-4965
> TRUNK-4965 | Fix for NPE while saving encounter with complex obs

- api/src/main/java/org/openmrs/api/context/Context.java
Added clearSession() after OpenSession() 
- [x ] My pull request only contains one single commit.
- [ x] My pull request is based on the latest master branch
- [ x] I ran `mvn clean package` right before creating this pull request and
- [x ] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
…pplying liquibase changesets
> TRUNK-4959 Clean Hibernate session after applying liquibase changesets

- webapp/src/main/webapp/WEB-INF/view/authorizationHandlerInclude.jsp
- webapp/src/main/webapp/WEB-INF/view/uncaughtException.jsp
Backport of https://github.com/openmrs/openmrs-module-legacyui/commit/c9bb7b8ba008573568f46cb2d09ca987d309683d to 1.11.x branch
> RA-974 - do not log stack trace when non-authenticated user tries to access the login page

- api/src/main/java/org/openmrs/api/cache/CacheConfig.java
- api/src/main/java/org/openmrs/api/cache/OpenmrsCacheManagerFactoryBean.java
This PR contains only two javadoc comments
see https://issues.openmrs.org/browse/TRUNK-4971
> TRUNK-4971 added JavaDocs

- api/src/main/java/org/openmrs/api/ProgramWorkflowService.java
https://issues.openmrs.org/browse/TRUNK-4935
TRUNK-4935: Removed TODO line at Line 459 of ProgramWorkflowService.java
I removed the  TODO line at Line 459 of ProgramWorkflowService.java.Please review my work and get back to me thanks
> TRUNK-4935: Removed TODO line at Line 459 of ProgramWorkflowService.java

- api/src/main/java/org/openmrs/obs/handler/ImageHandler.java
@dkayiwa , if please have a look, and if you're ok I'll PR on higher versioned branches soon after.
> TRUNK-4977: ImageHandler to delete trailing 0-byte files.

- api/src/main/java/org/openmrs/Cohort.java
- api/src/main/java/org/openmrs/CohortMembership.java
- api/src/main/java/org/openmrs/api/CohortService.java
- api/src/main/java/org/openmrs/api/context/Context.java
- api/src/main/java/org/openmrs/api/db/CohortDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateCohortDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
- api/src/main/java/org/openmrs/api/handler/PatientDataUnvoidHandler.java
- api/src/main/java/org/openmrs/api/handler/PatientDataVoidHandler.java
- api/src/main/java/org/openmrs/api/impl/CohortServiceImpl.java
- api/src/main/java/org/openmrs/util/databasechange/UpdateCohortMemberIds.java
- api/src/main/java/org/openmrs/validator/CohortValidator.java
- api/src/main/resources/hibernate.cfg.xml
- api/src/main/resources/liquibase-update-to-2.1.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/Cohort.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/CohortMembership.hbm.xml
- api/src/test/java/org/openmrs/api/CohortServiceTest.java
- api/src/test/java/org/openmrs/validator/CohortValidatorTest.java
- api/src/test/resources/org/openmrs/api/include/CohortServiceTest-cohort.xml
Added CohortMember object to include membership details of Cohort Members. The cohort_member table has two additional columns start_date and end_date.
see https://issues.openmrs.org/browse/TRUNK-4906
> TRUNK-4906 Expanded Cohort details

- api/src/main/java/org/openmrs/ConceptName.java
- api/src/main/java/org/openmrs/ConceptNameTag.java
- api/src/main/java/org/openmrs/FormResource.java
- api/src/main/java/org/openmrs/GlobalProperty.java
- api/src/main/resources/liquibase-update-to-2.1.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/ConceptClass.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/ConceptName.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/ConceptNameTag.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/ConceptSource.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/FormResource.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/GlobalProperty.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/PatientIdentifierType.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/RelationshipType.hbm.xml
Added new attributes to classes, added new mappings to Hibernate files, added corresponding Liquibase patches
see https://issues.openmrs.org/browse/TRUNK-4730
> TRUNK-4730 Verify that all relevant domain objects have changed_by and date_changed fields

- api/src/main/java/org/openmrs/api/PatientService.java
TRUNK-4933 Create pull request to remove TODO comments from core code
Removed TODO's from PatientService.java
https://issues.openmrs.org/browse/TRUNK-4933?jql=labels%20%3D%20gci2016
> TRUNK-4933 Create pull request to remove TODO comments from core code

- api/src/main/java/org/openmrs/Allergen.java
- api/src/main/java/org/openmrs/Encounter.java
- api/src/main/java/org/openmrs/Obs.java
- api/src/main/java/org/openmrs/api/AdministrationService.java
- api/src/main/java/org/openmrs/api/cache/CachePropertiesUtil.java
- api/src/main/java/org/openmrs/api/cache/OpenmrsCacheManagerFactoryBean.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderSetDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/OrderSetServiceImpl.java
- api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
- api/src/main/java/org/openmrs/messagesource/MutableMessageSource.java
- api/src/main/java/org/openmrs/messagesource/impl/MutableResourceBundleMessageSource.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/notification/AlertService.java
- api/src/main/java/org/openmrs/scheduler/TaskDefinition.java
- api/src/main/java/org/openmrs/util/OpenmrsClassLoader.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- api/src/main/java/org/openmrs/util/Security.java
- api/src/main/java/org/openmrs/validator/CohortValidator.java
- web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
GCI-142: Fixed bad code practices by removing unused imports
> GCI-142: Fix bad code practices through Sonar

- api/src/main/java/org/openmrs/api/DatatypeService.java
https://issues.openmrs.org/browse/TRUNK-4927
Please checkout this and see if all is ok
:TRUNK-4927
> Removed line 46 of DatatypeService.java:

- api/src/main/java/org/openmrs/api/AdministrationService.java
Removed the TODO line in line 297. Please check and let me know if any changes are to be made.
JIRA ISSUE: https://issues.openmrs.org/browse/TRUNK-4930
> TRUNK-4930 AdministrationService.getPresentationLocales() should return a List<Locale>

- pom.xml
> Excluding list-repos-using-refapp-import.txt for license header check

- api/src/main/java/org/openmrs/Person.java
- api/src/test/java/org/openmrs/PersonTest.java
Formatting fix for merged pull request https://github.com/openmrs/openmrs-core/pull/1908
https://issues.openmrs.org/browse/TRUNK-4925
> TRUNK-4925 Deep copy all collections in Person - formatting fix

- api/src/main/java/org/openmrs/customdatatype/datatype/ConceptDatatype.java
Made it so that  ConceptDatatype.doGetTextSummary()  checks whether concept is null. NullPointerException fixed. 
However getting the following error.  This might be a problem with the version of JUnit. Please check and let me know any changes that are to be made.
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.openmrs.customdatatype.datatype.ConceptDatatypeTest.doGetTextSummary_shouldReturnDefaultSummary(ConceptDatatypeTest.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at …
> TRUNK 4879 NullPointerException at org.openmrs.api.customdatatype.datatype.ConceptDatatype#doGetTextSummary

- api/src/main/java/org/openmrs/api/GlobalPropertyListener.java
Removed TODO as the feature is already implemented (mentioned in comment of issue)
see https://issues.openmrs.org/browse/TRUNK-4931
> TRUNK-4931 All listeners should be notified of global property name changes

- CONTRIBUTING.md
- api/src/main/java/org/openmrs/Cohort.java
- api/src/main/java/org/openmrs/Concept.java
- api/src/main/java/org/openmrs/PersonName.java
- api/src/main/java/org/openmrs/annotation/AuthorizedAnnotationAttributes.java
- api/src/main/java/org/openmrs/attribute/Attribute.java
- api/src/main/java/org/openmrs/logic/Duration.java
- api/src/main/java/org/openmrs/notification/impl/MessageServiceImpl.java
Corrected typos/grammatical errors as stated by the GCI description 
> GCI Identify typo or grammar errors in OpenMRS core

- api/src/main/java/org/openmrs/logic/result/Result.java
Removing useless TODO statement since the unnecessary methods had been eliminate
see https://issues.openmrs.org/browse/TRUNK-5001
> TRUNK-5001: Removed unnecessary TODO statement

- api/src/main/java/org/openmrs/hl7/HL7Util.java
Removed unused TODO element since we need to do anything special for removable media
see https://issues.openmrs.org/browse/TRUNK-4999
> TRUNK-4999: Removed unnecessary TODO

- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
https://issues.openmrs.org/browse/TRUNK-4992
Please check the validity of this.
> TRUNK-4992:Removed Line 385 of PatientServiceImpl.java

- api/src/main/java/org/openmrs/BaseCustomizableData.java
> TRUNK-4998: deleted the TODO lines 92 and 93

- api/src/main/java/org/openmrs/hl7/handler/ADTA28Handler.java
Removed TODO.
see https://issues.openmrs.org/browse/TRUNK-4997
> TRUNK-4997: Add a global property that enables different behavior here

- api/src/main/java/org/openmrs/api/impl/LocationServiceImpl.java
Removed TODO as requested. 
see https://issues.openmrs.org/browse/TRUNK-4989
> TRUNK-4989: Throw an exception if there is no location to fall back on

- api/src/main/java/org/openmrs/module/ModuleFactory.java
Added an ifExists check to ModuleFactory before loading module file.
see https://issues.openmrs.org/browse/TRUNK-5005
> TRUNK-5005: ModuleFactoryTest Error

- api/src/main/java/org/openmrs/Concept.java
- api/src/main/java/org/openmrs/PersonName.java
- api/src/main/java/org/openmrs/attribute/Attribute.java
- api/src/main/java/org/openmrs/notification/impl/MessageServiceImpl.java
> Fix the Typos/Grammatical errors 

- api/src/main/java/org/openmrs/logic/result/Result.java
https://issues.openmrs.org/browse/TRUNK-5002
Please Check this out
> TRUNK-5002:Removed Line 763 of Result.java

- api/src/main/java/org/openmrs/api/handler/BaseRetireHandler.java
- api/src/main/java/org/openmrs/util/NaturalStrings.java
> Minor Grammar/Typo fixes 

- puppet/modules/apt/manifests/backports.pp
- puppet/modules/apt/templates/50unattended-upgrades.erb
- tools/src/main/java/org/openmrs/tools/doclet/ShouldTaglet.java
> Typo and grammatical errors fixed?

- web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
- web/src/main/java/org/openmrs/web/filter/util/ErrorMessageConstants.java
- web/src/test/java/org/openmrs/web/test/BaseWebContextSensitiveTest.java
Google Code-In task "Identify 3 typo/grammar errors in OpenMRS core and create pull requests to fix them (OpenMRS)". I have fixed 3 typos across 3 different files in the source code. 2 of them involve comments and 1 of them involves a logging/debugging statement. I have ensured that my fork is based on the latest master branch and it contains only 1 commit. 
Google Code-In: "Identify 3 typo/grammar errors in OpenMRS core and create pull requests to fix them (OpenMRS)"
> Google Code-In:"Identify 3 typo/grammar errors"

- README.md
> GCI typo/grammar fix

- puppet/modules/apt/templates/50unattended-upgrades.erb
> Fixed some gramamatical errors/typos in the documentation

- api/src/main/java/org/openmrs/validator/PersonValidator.java
- api/src/test/java/org/openmrs/validator/PersonValidatorTest.java
TRUNK-4867 Check if deathdate before birthdate
Added tests and working validatior 
see https://issues.openmrs.org/browse/TRUNK-4867
> TRUNK-4867 Check if deathdate before birthdate

- api/src/main/java/org/openmrs/Concept.java
- api/src/main/java/org/openmrs/Patient.java
- api/src/main/java/org/openmrs/Person.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/PersonServiceImpl.java
- api/src/main/java/org/openmrs/module/Module.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/module/ModuleUtil.java
- web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
- web/src/main/java/org/openmrs/web/filter/update/UpdateFilter.java
GCI Fixed some bad code practices through Sonar; mainly replacing `.size()==0` with `.isEmpty()`. I have run `clean package` after every 2 files being changed, and my travis is also green.
> GCI-142 Fix Sonar bad code practices

- api/src/main/java/org/openmrs/Allergy.java
- api/src/main/java/org/openmrs/Concept.java
- api/src/main/java/org/openmrs/Drug.java
- api/src/main/java/org/openmrs/Encounter.java
- api/src/main/java/org/openmrs/api/ConceptNameType.java
- api/src/main/java/org/openmrs/api/ConceptService.java
- api/src/main/java/org/openmrs/api/db/EncounterDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/DbSession.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/obs/ComplexObsHandler.java
- api/src/main/java/org/openmrs/util/ClassLoaderFileOpener.java
- api/src/main/java/org/openmrs/util/databasechange/AddConceptMapTypesChangeset.java
- api/src/main/java/org/openmrs/util/databasechange/ConceptValidatorChangeSet.java
- api/src/test/java/org/openmrs/BaseOpenmrsObjectTest.java
- api/src/test/java/org/openmrs/ConceptTest.java
- api/src/test/java/org/openmrs/api/AdministrationServiceTest.java
- api/src/test/java/org/openmrs/api/ConceptServiceTest.java
- api/src/test/java/org/openmrs/api/EncounterServiceTest.java
- api/src/test/java/org/openmrs/api/db/ContextDAOTest.java
- api/src/test/java/org/openmrs/util/DrugsByNameComparatorTest.java
Fixes spelling errors in code comments and javadocs.
> Fixes typo/spelling errors in comments

- api/src/main/java/org/openmrs/api/db/hibernate/ImmutableOrderInterceptor.java
- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
- api/src/main/resources/messages.properties
- api/src/test/java/org/openmrs/api/PatientServiceTest.java
see https://issues.openmrs.org/browse/TRUNK-5010
> TRUNK-5010 Able to merge patients with discontinued orders

- api/src/test/java/org/openmrs/api/PatientServiceTest.java
see https://issues.openmrs.org/browse/TRUNK-5010
`git pull --rebase upstream 2.0.x`.
> TRUNK-5010 | Test case updates as per code review suggestions

- api/src/main/java/org/openmrs/api/context/UserContext.java
- api/src/test/java/org/openmrs/api/context/ContextTest.java
> TRUNK-5018 Update locale of user while logging in

- api/src/main/java/org/openmrs/Cohort.java
- api/src/main/java/org/openmrs/Concept.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
Removed redundant null-checks as pointed out by the sonar
see https://issues.openmrs.org/browse/TRUNK-5039
> TRUNK-5039 Remove redundant null checks

- api/src/main/java/org/openmrs/aop/LoggingAdvice.java
- api/src/main/java/org/openmrs/util/HttpClient.java
Replaced '\n' in String.format() expressions with '%n'
see https://issues.openmrs.org/browse/TRUNK-5044
> TRUNK-5044 Use platform agnostic newlines in string formatting

- pom.xml
- properties.xml
Seems, that most of the xml indents are tabs. To fix the broken
code indent I've converted the spaces into tabs.
If it is important for you to have a ticket for cleanup commits you can use this patch as a base for your cleanup. I was just looking for a pom example and I followed the pathfinder rule :)
> Fixed whitespaces

- webapp/src/main/webapp/WEB-INF/view/admin/patients/shortPatientForm.jsp
Hi @dkayiwa , here is the pull request for this small change.
> LUI-32, display the selected identifier location

- web/src/main/java/org/openmrs/web/controller/patient/ShortPatientFormValidator.java
- web/src/test/java/org/openmrs/web/controller/patient/ShortPatientFormValidatorTest.java
@mseaton , sorry for the previous request. My pull request is only one line of code. Thanks!
> TRUNK-3274, when checking for duplicate addresses ignore voided entries

- api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/FormServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/PersonServiceImpl.java
- web/src/main/java/org/openmrs/web/filter/GZIPFilter.java
see https://issues.openmrs.org/browse/TRUNK-5035
> TRUNK-5035: Use Boolean.valueOf to test strings

- api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
see https://issues.openmrs.org/browse/TRUNK-5058
> TRUNK-5058 : Extract private method in ObsServiceImpl.saveExistingObs

- .gitignore
remove velocity.log files which were unintentionally added and ignore
.log files via .gitignore
see https://issues.openmrs.org/browse/TRUNK-5078
> TRUNK-5078 Remove velocity.log files

- api/src/main/java/org/openmrs/OpenmrsMetadata.java
comments
TRUNK-4928: Removed "TODO:Support localized names and descriptions" 
Removed the sentence from the comment as directed
- [ x] My pull request only contains one single commit.
- [ x] My pull request is based on the latest master branch
- [ x] I ran `mvn clean package` right before creating this pull request and
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] All new and existing tests passed.
> TRUNK-4928: Removed "TODO:Support localized names and descriptions" from

- pom.xml
Update checkstyle maven plugin
see https://issues.openmrs.org/browse/TRUNK-5081
> TRUNK-5081 Update checkstyle maven plugin

- checkstyle.xml
merged our existing checkstyle.xml with google's
* removed their checks for tabs since we use tabs
* added NPathComplexity since it was already actived on codacy
* added CustomImportOrder rule using the Eclipse defaults
* changed the default severity to warning
* explicitly set the severity of rules we had before to error
* MagicNumber is an error but ignored for annotations
* reduced NestedIfDepth to 4 since that smells
* reduced NestedTryDepth to 2 since that smells
see https://issues.openmrs.org/browse/TRUNK-5085
> TRUNK-5085 Merge checkstyle rules with google's

- checkstyle.xml
Fix license header in checkstyle.xml
see https://issues.openmrs.org/browse/TRUNK-5085
> TRUNK-5085 Fix license header in checkstyle.xml

- README.md
add sections
* on how to build
* get started as a developer
* documentation
* contributing
* connecting with the community
* issues
* license
* add a logo
* add a table of content to easily navigate
> add infos and love to readme

- README.md
add section on openmrs SDK to readme with link in the toc
> add section on openmrs SDK to readme

- checkstyle.xml
* added rule of EqualsAvoidNull to checkstyle which was configured in the
codacy UI using the PMD checker
* adjusted the value of the MethodLength to 75 as was on codacy PMD
> add rule from codacy PMD and adjust value

- checkstyle.xml
- ruleset.xml
* updated checkstyle.xml so its rules do not overlap with rules defined
in PMD
* extracted PMD rules from codacy and added them to ruleset.xml so
codacy uses the PMD rules from the repository
see https://issues.openmrs.org/browse/TRUNK-5091
> TRUNK-5091 Add PMD rules

- api/src/main/java/org/openmrs/api/handler/RequiredDataHandler.java
- api/src/main/java/org/openmrs/module/MandatoryModuleException.java
- api/src/main/java/org/openmrs/module/OpenmrsCoreModuleException.java
- tools/src/main/java/org/openmrs/tools/doclet/ShouldTaglet.java
* remove imports only needed because of javadocs by replacing them with
fully qualified names
* reorder imports
see https://issues.openmrs.org/browse/TRUNK-5086
> TRUNK-5086 Remove unused imports and reorder

- api/src/test/java/org/openmrs/api/db/hibernate/HibernateOrderDAOTest.java
- api/src/test/java/org/openmrs/order/OrderUtilTest.java
- api/src/test/java/org/openmrs/util/DoubleRangeTest.java
replace deprecated junit.framework with org.junit in tests
> Replace deprecated junit.framework with org.junit

- api/src/main/java/org/openmrs/Cohort.java
- api/src/main/java/org/openmrs/Person.java
- api/src/main/java/org/openmrs/PersonAddress.java
- api/src/main/java/org/openmrs/PersonAttribute.java
- api/src/main/java/org/openmrs/PersonName.java
- api/src/main/java/org/openmrs/annotation/AuthorizedAnnotationAttributes.java
- api/src/main/java/org/openmrs/aop/RequiredDataAdvice.java
- api/src/main/java/org/openmrs/api/context/Context.java
- api/src/main/java/org/openmrs/api/context/ServiceContext.java
- api/src/main/java/org/openmrs/api/db/hibernate/ChainingInterceptor.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateCohortDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java
- api/src/main/java/org/openmrs/api/handler/PatientDataUnvoidHandler.java
- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/VisitServiceImpl.java
- api/src/main/java/org/openmrs/hl7/handler/ORUR01Handler.java
- api/src/main/java/org/openmrs/notification/MessageService.java
- api/src/main/java/org/openmrs/notification/Template.java
- api/src/main/java/org/openmrs/notification/impl/MessageServiceImpl.java
- api/src/main/java/org/openmrs/util/OpenmrsClassScanner.java
- api/src/main/java/org/openmrs/util/Reflect.java
- api/src/main/java/org/openmrs/util/VelocityExceptionHandler.java
- api/src/test/java/org/openmrs/OpenmrsTestsTest.java
- api/src/test/java/org/openmrs/api/ConceptServiceTest.java
- api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java
- api/src/test/java/org/openmrs/util/ExceptionUtilTest.java
- api/src/test/java/org/openmrs/util/ReflectTest.java
Remove leftover SuppressWarnings annotations which have been
left over after refactorings that got rid of the expressions causing
the warning that this annotation should suppress. Remove them so we do
get warnings from now on again!
see https://issues.openmrs.org/browse/TRUNK-5102
> TRUNK-5102 Remove leftover suppresswarnings

- api/src/main/java/org/openmrs/api/db/hibernate/PersonSearchCriteria.java
Replace deprecated hibernate Criteria.LEFT_JOIN by JoinType.LEFT_OUTER_JOIN
> Replace deprecated Criteria.LEFT_JOIN

- api/src/main/java/org/openmrs/api/ConceptService.java
- api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java
TRUNK-5066 : Add tests to ConceptServiceImpl
Added tests to ConceptServiceImpl to increase coverage
see https://issues.openmrs.org/browse/TRUNK-5066
> TRUNK 5066 : Add tests to ConceptServiceImpl

- api/src/main/java/org/openmrs/api/ObsService.java
- api/src/main/java/org/openmrs/api/db/ObsDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateObsDAO.java
- api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
- api/src/test/java/org/openmrs/api/ObsServiceTest.java
- api/src/test/resources/org/openmrs/api/include/ObsServiceTest-RevisionObs.xml
TRUNK-5109 Enhance ObsService to provie getRevisionObs
- [x ] My pull request only contains one single commit.
- [x ] My pull request is based on the latest master branch
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
> TRUNK-5109 Added getRevisionObs on obsService

- api/src/main/java/org/openmrs/api/impl/PersonServiceImpl.java
> TRUNK-5055 : Removed duplication in PersonServiceImpl.getPersonAttributeTypes

- README.md
github changed the way markdown are rendered, see
https://githubengineering.com/a-formal-spec-for-github-markdown/
* fixed the toc
> fix readme after github markdown changes

- api/src/test/java/org/openmrs/api/PatientServiceTest.java
remove unused private helper method PatientServiceTest.assertEqualsInt
> Remove unused PatientServiceTest.assertEqualsInt

- api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
TRUNK-5057 : Extracted private methods in OrderServiceImpl.saveOrder
see https://issues.openmrs.org/browse/TRUNK-5057
> TRUNK-5057 :Extracted private methods in OrderServiceImpl.saveOrder

- api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
- api/src/test/java/org/openmrs/api/PatientServiceTest.java
- api/src/test/resources/org/openmrs/api/include/PatientServiceTest-mergePatientWithExistingObsHavingGroupMember.xml
Removing all existing obs with obs-group in encouter recursively and adding new obs with obs-group recursively.
see https://issues.openmrs.org/browse/TRUNK-5112
> TRUNK-5112: Obs Group fix after Patient Merge.

- .github/PULL_REQUEST_TEMPLATE.md
as new devs creating PRs seem to have trouble
formatting their code, creating a single commit, adding tests, running
their changes and tests through the build process I
* tried to clarify the language/structure of the PR template
* added instructions to the checklist so that if a new devs has doubts
directly has the right resource at hand to check the box in the end
> add instructions to checklist in PR template

- api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
Replace use of deprecated isPatient
> Replace use of deprecated isPatient

- api/src/main/java/org/openmrs/Person.java
- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
Replace use of deprecated isBirthdateEstimated
> Replace use of deprecated isBirthdateEstimated

- api/src/main/java/org/openmrs/api/handler/PersonSaveHandler.java
Replace use of deprecated isDead
> Replace use of deprecated isDead

- api/src/main/java/org/openmrs/util/ConceptMapTypeComparator.java
Replace use of deprecated ConceptMapType.isHidden
> Replace use of deprecated ConceptMapType.isHidden

- api/src/main/java/org/openmrs/Obs.java
Replace use of deprecated ConceptNumeric.isAllowDecimal
> Replace use of deprecated ConceptNumeric.isAllowDecimal

- pom.xml
remove declaration of dependency com.google.lamdaj from root pom
it was not referenced in any other pom.
> Remove unreference google.lamdaj from root pom

- api/src/test/java/org/openmrs/validator/EncounterValidatorTest.java
* add tests to EncounterValidatorTest for when validation is given null or
instance of class other than Encounter
* arrange test implementations in a arrange, act, assert style (or what
we often called the given,when,then) so its clear to see whats been
tested and what the outcome should be
> Add tests to EncounterValidatorTest

- api/src/test/java/org/openmrs/validator/PersonNameValidatorTest.java
* arrange test implementations in a arrange, act, assert style (or what
we often called the given,when,then) so its clear to see whats been
tested and what the outcome should be
* remove unnecessary throws Exception from method declarations
> Extract setUp in PersonNameValidatorTest

- api/src/test/java/org/openmrs/validator/CohortValidatorTest.java
* add tests to assert IllegalArgumentException is thrown when
validating null or an instance other than Cohort
> Cleanup and add tests to CohortValidatorTest

- api/src/test/java/org/openmrs/validator/ConceptAttributeTypeValidatorTest.java
* split tests for null, empty, whitespace name since they are
independent
* add assertions for error code so we ensure that when devs refactor
the code the user will still get the excpected error message
* move happy path tests to the end, which makes side by side reading of
code and test easy
> Cleanup and add tests to ConceptAttributeTypeValidatorTest

- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/test/java/org/openmrs/api/db/hibernate/HibernatePatientDAOTest.java
- Add test for getPatientIdentifiers with a list of
PatientIdentifierTypes.
- Add test for getPatientIdentifiers with a list of Patients.
- @vixus0 @galund
No? -> figure out why and …
> TRUNK-248: Add junit tests for HibernatePatientDAO

- api/src/main/java/org/openmrs/propertyeditor/LocationEditor.java
- api/src/test/java/org/openmrs/propertyeditor/LocationEditorTest.java
Refactoring LocationEditor to get text if text not null and improving test coverage
Authors: @DataMinerUK @matmoore …
> TRUNK-248 Add tests for junit TODOs

- api/src/test/java/org/openmrs/validator/ConceptValidatorTest.java
* fix failing test validate_shouldFailIfAnyNameIsAnEmptyString
had wrong assertion
* extract duplicate test setup into setUp method
* make conceptService a member and autowire it
* make concept cd4Count and weight members since they are used multiple
times
* arrange tests in arrange, act, assert way so reading is easier
* add test for when getNames() returns empty list
* fix validate_shouldFailIfTheObjectParameterIsNull
which expects an IAE but from the validator. However the call to
new BindException(null, "concept");
fails since the target object must not be null
> Fix and clean ConceptValidatorTest

- api/src/test/java/org/openmrs/api/PatientServiceTest.java
- Test the case where a null reason is passed
- Test the case where a PatientIdentifierType is successfully retired
that the object is modified setting expected attributes
@annashipman @davbo @TheDoubleK
No? -> …
> TRUNK-248: Add tests for retirePatientIdentifierType

- api/src/main/resources/liquibase-update-to-2.1.xml
Added migration task
https://issues.openmrs.org/browse/TRUNK-5140
> TRUNK-5140|Increase the size of the obs.value_complex column to be ~1000

- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
see https://issues.openmrs.org/browse/TRUNK-5045
> TRUNK-5045: Extract private methods in PatientServiceImpl.savePatient

- api/src/main/java/org/openmrs/Concept.java
Fix: Instead of replacing the collection, clear the elements from old collection
and add all the new collection elements so that the old collection does not become orphan.
see https://issues.openmrs.org/browse/TRUNK-5144
No? -> …
> TRUNK-5144| saving a coded concept throws exception

- api/src/test/java/org/openmrs/api/PersonServiceTest.java
TRUNK-5064 Add tests to PersonServiceImpl
see https://issues.openmrs.org/browse/TRUNK-5064 …
> TRUNK-5064 Add tests to PersonServiceImpl

- api/src/test/java/org/openmrs/api/PersonServiceTest.java
added tests for retireRelationshipType
see https://issues.openmrs.org/browse/TRUNK-5064
No? Unsure? -> execute command …
> TRUNK-5064 Add test to PersonServiceImpl

- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
- api/src/test/java/org/openmrs/api/PatientServiceImplUnitTest.java
- api/src/test/java/org/openmrs/api/PatientServiceTest.java
Improves coverage slightly
see https://issues.openmrs.org/browse/TRUNK-5069
No? Unsure? -> execute command `git pull …
> Write tests for PatientServiceImpl.checkPatientIdentifiers

- api/src/main/java/org/openmrs/api/impl/PersonServiceImpl.java
> TRUNK-5117 Refactor PersonServiceImpl.getPersonAttributeTypes

- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
- api/src/test/java/org/openmrs/api/PatientServiceImplUnitTest.java
- api/src/test/java/org/openmrs/api/PatientServiceTest.java
Added even more tests to make sure exceptions really return with the same message as before (wasn't sure if that's displayed anywhere). Also fixed formatting of imports that was not rule-conform in my last merge request, sorry :-)
see https://issues.openmrs.org/browse/TRUNK-5069
added all formatting …
> Refactor checkPatientIdentifiers: 10 years later, Java8 streams \o/

- api/src/test/java/org/openmrs/api/PatientServiceTest.java
- api/src/test/java/org/openmrs/api/impl/PatientServiceImplTest.java
It's just too much craziness to test this without the ability to mock Context - so using PowerMock runner for this one, although that will prevent jacoco from realising that the test coverage increased...
No? -> …
> Starting tests for PatientServiceImpl.processDeath

- api/src/test/java/org/openmrs/api/PersonServiceTest.java
see https://issues.openmrs.org/browse/TRUNK-5064
> TRUNK-5064 Clean tests of voidRelationship

- api/src/test/java/org/openmrs/api/PersonServiceTest.java
* add tests for retirePersonAttributeType
* add tests for unretirePersonAttributeType
see https://issues.openmrs.org/browse/TRUNK-5064 …
> TRUNK-5064 Add tests for retirePersonAttributeType

- api/src/test/java/org/openmrs/propertyeditor/PatientEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/VisitEditorTest.java
* added tests to properly test all branches of Visit and PatientEditor
> Add tests to VisitEditor, PatientEditor

- api/src/test/java/org/openmrs/propertyeditor/BasePropertyEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/ConceptEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/ConceptNameEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/OrderEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/PatientEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/PersonAttributeEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/UserEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/VisitEditorTest.java
* create BasePropertyEditorTest which covers all branches of the
typical OpenMRS PropertyEditor implementation
* start extending a few existing EditorTests to remove duplication and increase
coverage
see https://issues.openmrs.org/browse/TRUNK-5139
No? -> …
> TRUNK-5139 Create a base test for PropertyEditors

- api/src/test/java/org/openmrs/propertyeditor/DrugEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/EncounterEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/PersonEditorTest.java
* adapt EncounterEditorTest
* adapt DrugEditorTest
* adapt PersonEditorTest
see https://issues.openmrs.org/browse/TRUNK-5139 …
> TRUNK-5139 Adapt more EditorTests

- api/src/test/java/org/openmrs/propertyeditor/ConceptAnswerEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/ConceptAttributeTypeEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/ConceptDatatypeEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/ConceptNumericEditorTest.java
- api/src/test/java/org/openmrs/propertyeditor/OrderEditorTest.java
let
ConceptAnswerEditorTest.java
ConceptAttributeTypeEditorTest.java
ConceptDatatypeEditorTest.java
ConceptNumericEditorTest.java
OrderEditorTest.java
extend BasePropertyEditorTest to reduce duplication and increase
coverage
> TRUNK-5139 Adapt more PropertyEditorTests

- api/src/test/java/org/openmrs/api/UserServiceTest.java
Added tests for create_user, dry-ed out the test class a bit and refactored some of the code in create_user …
> TRUNK-248 tests for create_user; some refactoring

- api/src/test/java/org/openmrs/propertyeditor/LocationAttributeTypeEditorTest.java
see https://issues.openmrs.org/browse/TRUNK-5139
> TRUNK-5139 Add test for LocationAttributeTypeEditor

- api/src/main/java/org/openmrs/api/impl/VisitServiceImpl.java
> TRUNK-5050 : Reduce nesting in VisitServiceImpl.stopVisits

- api/src/main/java/org/openmrs/api/impl/VisitServiceImpl.java
> TRUNK-5051 : Extract getVisitTypesToStop from VisitServiceImpl.stopVisits

- api/src/main/java/org/openmrs/api/impl/VisitServiceImpl.java
No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash 
multiple commits into one
(https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And
+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure 
your code works.
No? Unsure? -> execute command `git pull …
> TRUNK-5052 : Extract methods from getVisitTypesToStop

- api/src/main/java/org/openmrs/api/ProgramWorkflowService.java
- api/src/main/java/org/openmrs/api/db/ProgramWorkflowDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateProgramWorkflowDAO.java
- api/src/main/java/org/openmrs/api/impl/ProgramWorkflowServiceImpl.java
- api/src/test/java/org/openmrs/api/ProgramWorkflowServiceTest.java
add ProgramWorkflow getWorkflow(Integer) in
ProgramWorkflowService
ProgramWorkflowServiceDAO
HibernateProgramWorkflowServiceDAO
ProgramWorkflowServiceImpl
see https://issues.openmrs.org/browse/TRUNK-5156
> TRUNK-5156 Add ProgramWorkflowService.getWorkflow(Integer)

- api/src/main/java/org/openmrs/api/ProgramWorkflowService.java
- api/src/main/java/org/openmrs/api/db/ProgramWorkflowDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateProgramWorkflowDAO.java
- api/src/main/java/org/openmrs/api/impl/ProgramWorkflowServiceImpl.java
- api/src/test/java/org/openmrs/api/ProgramWorkflowServiceTest.java
see https://issues.openmrs.org/browse/TRUNK-5155
> TRUNK-5155 Add ProgramWorkflowService.getState(Integer)

- api/src/main/java/org/openmrs/propertyeditor/ProgramWorkflowEditor.java
- api/src/test/java/org/openmrs/propertyeditor/ProgramWorkflowEditorTest.java
the catch block will never be reached since getByUuid() just returns
null if nothing is found. The exception in the try block is normally
thrown by Integer.valueOf() if the text is a uuid and not a number
* use getState(Integer) first to try to get the ProgramWorkflow by
its id
* is text is not an Integer, the exception in Integer.valueOf will lead
to the catch block being executed which then tries to fetch by the uuid
* added tests
see https://issues.openmrs.org/browse/TRUNK-5157
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes …
> TRUNK-5157 ProgramWorkflowEditor tries to get state by uuid twice

- api/src/main/java/org/openmrs/Allergen.java
- api/src/main/java/org/openmrs/User.java
- api/src/main/java/org/openmrs/api/impl/AdministrationServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
- api/src/main/java/org/openmrs/customdatatype/datatype/ConceptDatatype.java
- api/src/main/java/org/openmrs/module/ModuleUtil.java
- api/src/main/java/org/openmrs/validator/OrderValidator.java
- api/src/main/java/org/openmrs/validator/PatientValidator.java
Merged collapsable if statements.
see https://issues.openmrs.org/browse/TRUNK-5034
- [x ] I ran `mvn clean …
> TRUNK-5034 Merge Collapsable if statements

- api/src/main/java/org/openmrs/hl7/handler/ORUR01Handler.java
Remove unused temp variables, shown to us by sonar. One was removed and
the other was used in an if statement, therefore was in use.
see https://issues.openmrs.org/browse/TRUNK-5043 …
> TRUNK-5043

- api/src/test/java/org/openmrs/propertyeditor/ProviderEditorTest.java
* ignore test for when trying to get a Provider of non existing ID
since this is an issue TRUNK-5153
> TRUNK-5139 Adapt test of ProviderEditor

- api/src/test/resources/log4j.xml
see https://issues.openmrs.org/browse/TRUNK-5163
> TRUNK-5163 Disable logs during tests

- api/src/main/java/org/openmrs/api/db/hibernate/AuditableInterceptor.java
- api/src/main/java/org/openmrs/messagesource/impl/CachedMessageSource.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/util/databasechange/ConceptValidatorChangeSet.java
- web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
TRUNK-5040 fix for inefficient use of map
Fix for inefficient use of map
see https://issues.openmrs.org/browse/TRUNK-5040 …
> TRUNK-5040 fix for inefficient use of map

- pom.xml
Updated the pom.xml to exclude 
see https://issues.openmrs.org/browse/TRUNK-5133
My pull request only contains **ONE single commit**
> TRUNK-5133: Excluded activation.jar file from core

- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
I worked on this bug, and made all changes mentioned in the description.
-Extracted method - ensureConceptMapTypeIsSet, ensurePreferredNameForLocale
-Inline a temporary variable
Did not add any tests, only refactored 
I also completed the following: 
> Trunk-5063 Extract private method in ConceptServiceImpl.saveConcept

- api/src/test/java/org/openmrs/OrderTest.java
Split test methods of Order Test - shouldIsDiscontinued and shouldCheckIfOrderIsActive into smaller tests.
Also, added a setup method, for instantiating the date and order objects. 
Removed the TODO split into smaller tests
see https://issues.openmrs.org/browse/TRUNK-5131
> TRUNK-5131: Split tests OrderTest.shouldIsDiscontinued and shouldCheckIfOrderIsActive

- web/src/test/java/org/openmrs/web/filter/startuperror/StartupErrorFilterTest.java
add StartupErrorFilterTest since it didnt exist,
use PowerMockRunner as the filter calls static methods
> Add StartupErrorFilterTest

- api/src/main/java/org/openmrs/api/context/ServiceContext.java
- api/src/main/java/org/openmrs/messagesource/impl/DefaultMessageSourceServiceImpl.java
- api/src/test/java/org/openmrs/messagesource/impl/DefaultMessageSourceServiceImplTest.java
see https://issues.openmrs.org/browse/TRUNK-5180
> Trunk 5180

- api/src/main/java/org/openmrs/api/impl/ProgramWorkflowServiceImpl.java
I added two helper methods to perform various checks on the workflow program and status, and pulled code from the saveProgram() method for those methods.
see https://issues.openmrs.org/browse/TRUNK-5053
existing code that was well tested you do not have to …
> TRUNK-5053 Refactor ProgramWorkflowServicesImpl.saveProgram

- api/src/main/java/org/openmrs/BaseCustomizableMetadata.java
> TRUNK-4924: Removed TODO from BaseCustomizableMetadata class

- api/src/main/java/org/openmrs/Person.java
- api/src/test/java/org/openmrs/PersonTest.java
- api/src/test/java/org/openmrs/api/PatientServiceTest.java
- api/src/test/java/org/openmrs/api/PersonServiceTest.java
I checked for the value of DeathDate passed to the setDeathDate method and called the setDead method with a true parameter if the DeathDate value was not null. I also included the test which was found in the issue's description to make sure it passed. For the objects that called setDeathDate method with a null value, i passed a new Concept() as a parameter to the object's setCauseOfDeath method.
TRUNK-4868 Setting a deathdate does not call setDead()
https://issues.openmrs.org/browse/TRUNK-4868?filter=-1
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the …
>  TRUNK-4868 Setting a deathdate does not call setDead()

- pom.xml
upgrade apache commons-lang3 version to 3.6
see https://issues.openmrs.org/browse/TRUNK-5178
> TRUNK-5178 upgrade apache commons-lang3 version to 3.6

- pom.xml
update commons-io to 2.5
see https://issues.openmrs.org/browse/TRUNK-5179
> TRUNK-5179 update commons-io to 2.5

- pom.xml
Update apache commons-fileupload
see https://issues.openmrs.org/browse/TRUNK-5191
> TRUNK-5191 Update apache commons-fileupload

- api/pom.xml
- pom.xml
Removed unused dependencies asm, asm-commons, asm-util
see https://issues.openmrs.org/browse/TRUNK-5199
> TRUNKT-5199 Remove unused dependencies asm, asm-commons, asm-util

- api/pom.xml
- pom.xml
Remove unused dependency cglib-nodep
see https://issues.openmrs.org/browse/TRUNK-5200
> TRUNK-5200 Remove unused dependency cglib-nodep

- pom.xml
Update apache beanutils
see https://issues.openmrs.org/browse/TRUNK-5192
> TRUNK-5192 Update apache beanutils

- pom.xml
- test/pom.xml
Remove unused dependency xmlunit
see https://issues.openmrs.org/browse/TRUNK-5203
> TRUNK-5203 Remove unused dependency xmlunit

- api/src/test/java/org/openmrs/validator/ConceptAttributeTypeValidatorTest.java
- api/src/test/java/org/openmrs/validator/PersonNameValidatorTest.java
Extract test strings exceeding property lenghts in variables
see https://issues.openmrs.org/browse/TRUNK-5206
> TRUNK-5206 Extract test strings exceeding property lenghts in variables

- api/src/main/java/org/openmrs/propertyeditor/ConceptMapTypeEditor.java
- api/src/main/java/org/openmrs/propertyeditor/ConceptReferenceTermEditor.java
- api/src/main/java/org/openmrs/propertyeditor/PersonEditor.java
Ticket TRUNK-5223 issue is problem with Add New User always throws
exception of null string pointer.
Resolved it by revert the code back to commit
acf93745f5ce982d762974b5a0138feed1020e39
see https://issues.openmrs.org/browse/TRUNK-5223 …
> TRUNK-5223: Add New User always throws exception of null string pointer instead of returns blank ("") character.

- pom.xml
TRUNK-5094.
Location : https://issues.openmrs.org/browse/TRUNK-5094
Work done: I changed the POM.xml. Upgraded from 2.6 to 3.0 license-maven-plugin.
> I have changed the license-maven-plugin version to 3.0.

- api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
- Extracted the following methods from the main EncounterServiceImpl.saveEncounter() method
1. failIfDeniedToEdit(Encounter encounter)
2. createVisitForNewEncounter(Encounter encounter)
3. requirePrivilege(Encounter encounter)
- Moved temp variables closely to where they are actually used
see https://issues.openmrs.org/browse/TRUNK-5062
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your …
> TRUNK-5062: Extract private method in EncounterServiceImpl.saveEncounter()

- api/src/main/java/org/openmrs/OrderGroup.java
- api/src/test/java/org/openmrs/OrderGroupTest.java
see https://issues.openmrs.org/browse/TRUNK-5224 …
> Order Group order_group_id foreign key is Null TRUNK-5224

- pom.xml
.. as it won't be on the same machine as CI
Related to ITSM-4042, migrating CI to a new server.
> Change sonar URL

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
https://issues.openmrs.org/browse/GCI-207
> GCI-207: Rename immed_parents in HibernateConceptDAO to match convention

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateAdministrationDAO.java
Fixed `IdentifierTpye` spelling and made it comply with naming
conventions
see https://issues.openmrs.org/browse/GCI-206 …
> GCI-206: Rename IdentifierType in HibernateAdministrationDAO

- web/src/main/java/org/openmrs/web/controller/PseudoStaticContentController.java
Changed PseudoStaticContentController Logger from being `protected final` to `private static final`
see https://issues.openmrs.org/browse/GCI-175 …
> GCI-175: Make PseudoStaticContentController Logger private static final

- web/src/main/java/org/openmrs/web/DispatcherServlet.java
https://codein.withgoogle.com/dashboard/task-instances/5146309797347328/ …
> GCI-187: DispatcherServlet Logger should be "private static final"

- web/src/main/java/org/openmrs/web/filter/StartupFilter.java
Issue: https://issues.openmrs.org/browse/GCI-195
> [GCI-195] Throw APIException instead of RuntimeException

- web/src/main/java/org/openmrs/module/web/filter/ModuleFilterMapping.java
Issue: https://issues.openmrs.org/browse/GCI-191
> GCI-191. Replace the synchronized class "Vector" by an unsynchronized one such as "ArrayList" or "LinkedList".

- web/src/main/java/org/openmrs/web/WebConstants.java
See https://issues.openmrs.org/browse/GCI-202
> GCI-202: Add a private constructor to WebConstants

- api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
The auth_role variable on line https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java#L569 and this line https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java#L601 should be renamed to authRole to match our naming conventions on this page. https://wiki.openmrs.org/display/docs/Java+Conventions#JavaConventions-NamingConventions
see https://issues.openmrs.org/browse/GCI-205
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the …
> GCI-205 Rename auth_role in UserServiceImpl to match our convention

- web/src/main/java/org/openmrs/module/web/filter/ModuleFilterDefinition.java
I replaced the synchronized class "Vector" with an unsynchronized one: "ArrayList"
see https://issues.openmrs.org/browse/GCI-185 …
> GCI-185: Replace the synchronized class "Vector" by an unsynchronized one such as "ArrayList" or "LinkedList".

- web/src/main/java/org/openmrs/web/filter/util/FilterUtil.java
Hi, I changed few lines, replaced strings with constant variable.
https://issues.openmrs.org/browse/GCI-201
No? Unsure? …
> GCI-201: Replaced duplicated strings with constant variable.

- web/src/main/java/org/openmrs/web/StaticDispatcherServlet.java
Hi, I changed the Logger to a "private static final" and replaced the parameter of getLogger to
"StaticDispatcherServlet.class".
https://issues.openmrs.org/browse/GCI-174
No? -> figure out why and add the fix to your commit. It …
> GCI-174: StaticDispatcherServlet Logger should be "private static final"

- api/src/main/java/org/openmrs/PersonAttribute.java
- api/src/main/java/org/openmrs/api/context/Daemon.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateAdministrationDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java
- api/src/main/java/org/openmrs/api/impl/AdministrationServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/OrderSetServiceImpl.java
- api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
- api/src/main/java/org/openmrs/patient/impl/BaseHyphenatedIdentifierValidator.java
- api/src/main/java/org/openmrs/patient/impl/LuhnIdentifierValidator.java
- api/src/main/java/org/openmrs/util/DrugsByNameComparator.java
- api/src/main/java/org/openmrs/util/Security.java
- web/src/main/java/org/openmrs/web/filter/GZIPFilter.java
- web/src/main/java/org/openmrs/web/filter/update/UpdateFilter.java
- web/src/test/java/org/openmrs/web/test/WebTestHelper.java
> [GCI-142] Deleted redundant local variables

- api/src/main/java/org/openmrs/aop/LoggingAdvice.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
- api/src/main/java/org/openmrs/logic/LogicTransform.java
- api/src/main/java/org/openmrs/module/ModuleClassLoader.java
- api/src/main/java/org/openmrs/util/DoubleRange.java
- web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
- web/src/main/java/org/openmrs/web/filter/update/UpdateFilter.java
StringBuilder.append() is more effcient (and takes less memory) in chained concatenations or in loops.
> [GCI-142] Replaced String concatenation with StringBuilder.append()

- api/src/main/java/org/openmrs/annotation/AuthorizedAnnotationAttributes.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateSessionFactoryBean.java
- api/src/main/java/org/openmrs/obs/handler/ImageHandler.java
I've replaced manu array to collection copy (e.g. in for loop) with Collections.addAll.
It is simpler and cleaner :)
> [GCI-142] Replace manual array to collection copy with Collections.addAll()

- api/src/main/java/org/openmrs/Patient.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateSerializedObjectDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateSessionFactoryBean.java
- api/src/main/java/org/openmrs/util/OpenmrsConstants.java
Related to #2400 
Adding elements to collection with .addAll() is cleaner than doing it in loop.
> [GCI-142] Replaced Collection iteration with bulk operation

- api/src/main/java/org/openmrs/api/impl/PersonServiceImpl.java
- api/src/main/java/org/openmrs/layout/LayoutTemplate.java
- api/src/main/java/org/openmrs/migration/MigrationHelper.java
- api/src/main/java/org/openmrs/module/ModuleFileParser.java
- api/src/main/java/org/openmrs/util/OpenmrsClassLoader.java
- api/src/main/java/org/openmrs/util/OpenmrsConstants.java
- web/src/main/java/org/openmrs/web/Listener.java
- web/src/main/java/org/openmrs/web/filter/GZIPFilter.java
I've replaced occurencies of String.indexOf() with String.contains() which produces more human-readable code and reduces complexity
> [GCI-142] Replaced String.indexOf() with String.contains()

- api/src/main/java/org/openmrs/DrugOrder.java
- api/src/main/java/org/openmrs/PatientIdentifier.java
- api/src/main/java/org/openmrs/PersonAttribute.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/migration/MigrationHelper.java
- api/src/main/java/org/openmrs/module/Module.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/module/ModuleFileParser.java
- api/src/main/java/org/openmrs/module/ModuleUtil.java
- api/src/main/java/org/openmrs/util/MemoryLeakUtil.java
- api/src/main/java/org/openmrs/util/databasechange/AddConceptMapTypesChangeset.java
- api/src/main/java/org/openmrs/util/databasechange/ConvertOrderersToProviders.java
- api/src/main/java/org/openmrs/util/databasechange/CreateCodedOrderFrequencyForDrugOrderFrequencyChangeset.java
- api/src/main/java/org/openmrs/util/databasechange/CreateDiscontinueOrders.java
- api/src/main/java/org/openmrs/util/databasechange/DisableTriggersChangeSet.java
- api/src/main/java/org/openmrs/util/databasechange/EnableTriggersChangeSet.java
- api/src/main/java/org/openmrs/util/databasechange/EncryptSecretAnswersChangeSet.java
- api/src/main/java/org/openmrs/util/databasechange/GenerateUuid.java
- api/src/main/java/org/openmrs/util/databasechange/MigrateDrugOrderFrequencyToCodedOrderFrequencyChangeset.java
- api/src/main/java/org/openmrs/util/databasechange/MigrateDrugOrderUnitsToCodedDoseUnitsChangeset.java
- api/src/main/java/org/openmrs/util/databasechange/MoveDeletedHL7sChangeSet.java
- api/src/main/java/org/openmrs/util/databasechange/UpdateLayoutAddressFormatChangeSet.java
- api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java
- web/src/main/java/org/openmrs/web/Listener.java
- web/src/main/java/org/openmrs/web/filter/StartupFilter.java
- web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
- web/src/main/java/org/openmrs/web/filter/initialization/TestInstallUtil.java
I've collapsed identicall "catch" blocks because there is no sense in writing the same thing twice :)
> GCI-142 Collapse identical catch blocks

- api/src/main/java/org/openmrs/Concept.java
- api/src/main/java/org/openmrs/Encounter.java
- api/src/main/java/org/openmrs/Obs.java
- api/src/main/java/org/openmrs/User.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateAdministrationDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java
- api/src/main/java/org/openmrs/module/ModuleClassLoader.java
- api/src/main/java/org/openmrs/util/MemoryAppender.java
- api/src/main/java/org/openmrs/util/OpenmrsClassLoader.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- api/src/main/java/org/openmrs/util/Security.java
- api/src/main/java/org/openmrs/util/databasechange/AddConceptMapTypesChangeset.java
- api/src/main/java/org/openmrs/util/databasechange/ConceptValidatorChangeSet.java
- api/src/main/java/org/openmrs/util/databasechange/DuplicateEncounterRoleNameChangeSet.java
- api/src/main/java/org/openmrs/util/databasechange/DuplicateEncounterTypeNameChangeSet.java
- api/src/main/java/org/openmrs/util/databasechange/DuplicateLocationAttributeTypeNameChangeSet.java
- api/src/test/java/org/openmrs/api/ProviderServiceTest.java
- api/src/test/java/org/openmrs/patient/impl/LuhnIdentifierValidatorTest.java
- tools/src/main/java/org/openmrs/tools/doclet/ShouldTaglet.java
I've replaced for and while loops with foreach, it gives us more cleaner code and reduces complexity
> [GCI-142] For and while loop replaced with foreach

- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- api/src/test/java/org/openmrs/test/MigrateDataSet.java
Since JDK7 we have nice try-with-resources, so we do not have to close Resources in "finally" blocks
> [GCI-142] Use java 7 Automatic Resource Managment (try-with-resources)

- api/src/main/java/org/openmrs/Obs.java
- api/src/main/java/org/openmrs/module/ModuleClassLoader.java
- web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
RemoveIf() is another great method from Stream API that deletes item if some condition is true :)
> [GCI-142] Replace code with removeIf()

- web/src/main/java/org/openmrs/web/filter/util/FilterUtil.java
FilterUtil class constructor was changed from public to private.
Added following line:
`	private FilterUtil() {
}`
https://issues.openmrs.org/browse/GCI-200 …
> GCI-200: Added a private constructor to FilterUtil

- api/src/main/java/org/openmrs/Concept.java
- api/src/main/java/org/openmrs/Obs.java
- api/src/main/java/org/openmrs/api/context/ServiceContext.java
- web/src/main/java/org/openmrs/web/Listener.java
- web/src/main/java/org/openmrs/web/filter/update/UpdateFilter.java
Removed class fields shadowing
https://issues.openmrs.org/browse/GCI-142
> [GCI-142] Removed class fields shadowing

- api/src/main/java/org/openmrs/api/context/Context.java
- api/src/main/java/org/openmrs/customdatatype/datatype/DateDatatype.java
- api/src/main/java/org/openmrs/scheduler/SchedulerConstants.java
- api/src/main/java/org/openmrs/util/DatabaseUtil.java
- api/src/main/java/org/openmrs/validator/ObsValidator.java
- web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
I've changed modifiers ordering in 6 files
https://issues.openmrs.org/browse/GCI-142
This change has no technical impact, but can increase code's readability for developers.
Link to sonar rule: https://rules.sonarsource.com/java/tag/convention/RSPEC-1124
> [CG-142] Corrected modifiers order

- web/src/main/java/org/openmrs/web/filter/util/ErrorMessageConstants.java
I have changed ErrorMessageConstants.java file, to be precise, I have added private constructor. Utility classes should not have public constructors.
see https://issues.openmrs.org/browse/GCI-173
No? -> figure out why and add the …
> [GCI-173] Adding a private constructor to ErrorMessageConstants.java

- api/src/main/java/org/openmrs/util/databasechange/AddConceptMapTypesChangeset.java
Issue: https://issues.openmrs.org/browse/TRUNK-5240
> [TRUNK-5240] Delete unused block of code

- web/src/main/java/org/openmrs/web/Listener.java
Issue: https://issues.openmrs.org/browse/GCI-236
> [GCI-236] Make sure file.listFiles() is not null before looping

- api/src/main/java/org/openmrs/util/databasechange/MigrateAllergiesChangeSet.java
Issue: https://issues.openmrs.org/browse/TRUNK-5244
> [TRUNK-5244] Use PreparedStatement to prevent SQL Injection

- api/src/main/java/org/openmrs/Concept.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/ObsServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
- api/src/main/java/org/openmrs/layout/LayoutTemplate.java
- api/src/main/java/org/openmrs/layout/address/AddressSupport.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/propertyeditor/ConceptSetsEditor.java
- api/src/test/java/org/openmrs/hl7/handler/ORUR01HandlerTest.java
Issue: https://issues.openmrs.org/browse/TRUNK-5245
Replaced the synchronized class "Vector" by an unsynchronized "ArrayList"
> [TRUNK-5245] Replace Vector collections with ArrayList

- api/src/main/java/org/openmrs/api/context/Context.java
Issue: https://issues.openmrs.org/browse/TRUNK-5246
I've corrected lazy initialization of two static fields so they can be accesses from any thread.
> [TRUNK-5246] Thread-safety: corrected lazy initialization of static field

- web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
- web/src/main/java/org/openmrs/web/filter/util/FilterUtil.java
Issue: https://issues.openmrs.org/browse/TRUNK-5247
I've closed one more Resource in finally block and changed if statement to close another resource every time. Sonar would warn otherwise.
> [TRUNK-5247] Close Resources in finally block

- web/src/main/java/org/openmrs/web/filter/util/CustomResourceLoader.java
Link to the issue: https://issues.openmrs.org/browse/GCI-183
> GCI-183: Introduce a new variable instead of reusing the parameter "filename".

- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
- api/src/main/java/org/openmrs/util/Security.java
Issue: https://issues.openmrs.org/browse/TRUNK-5243
I've deleted some unused code.
> [TRUNK-5243] Delete redundant declarations

- api/src/main/java/org/openmrs/Encounter.java
- api/src/main/java/org/openmrs/api/context/ServiceContext.java
- api/src/main/java/org/openmrs/messagesource/impl/CachedMessageSource.java
- api/src/main/java/org/openmrs/messagesource/impl/MutableResourceBundleMessageSource.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
computeIfAbsent() is great Stream API method that checks for element's existence in Collection, and if it doesn't exist, does some work. I think it is well explained here https://stackoverflow.com/questions/19278443/how-do-i-use-the-new-computeifabsent-function/19283210#19283210
> [GCI-142] Replace code with computeIfAbsent()

- api/src/main/java/org/openmrs/Cohort.java
- api/src/main/java/org/openmrs/Concept.java
- api/src/main/java/org/openmrs/Encounter.java
- api/src/main/java/org/openmrs/ProgramWorkflow.java
- api/src/main/java/org/openmrs/api/context/ServiceContext.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateUtil.java
- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
- api/src/main/java/org/openmrs/comparator/PatientIdentifierTypeDefaultComparator.java
- api/src/main/java/org/openmrs/migration/MigrationHelper.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/module/ModuleFileParser.java
- api/src/main/java/org/openmrs/module/SqlDiffFileParser.java
- api/src/main/java/org/openmrs/module/UpdateFileParser.java
- api/src/main/java/org/openmrs/scheduler/tasks/TaskThreadedInitializationWrapper.java
- api/src/main/java/org/openmrs/util/DatabaseUtil.java
- api/src/main/java/org/openmrs/util/NaturalStrings.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- api/src/test/java/org/openmrs/api/OrderServiceTest.java
- api/src/test/java/org/openmrs/api/PatientServiceTest.java
- api/src/test/java/org/openmrs/api/context/DaemonTest.java
- api/src/test/java/org/openmrs/api/db/hibernate/HibernatePatientDAOTest.java
- api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java
- api/src/test/java/org/openmrs/test/matchers/HasFieldErrors.java
- api/src/test/java/org/openmrs/validator/ConceptAttributeTypeValidatorTest.java
- web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
- web/src/main/java/org/openmrs/web/Listener.java
It is cleaner way to deal with anonymous classes since JDK8 so why not use it? :)
> [GCI-142] Lambdas and Method references instead of anonymous classes

- api/src/main/java/org/openmrs/api/ConceptNameType.java
- api/src/main/java/org/openmrs/api/impl/OrderSetServiceImpl.java
- api/src/main/java/org/openmrs/util/OpenmrsMemento.java
- api/src/test/java/org/openmrs/util/ProviderByPersonNameComparatorTest.java
- api/src/test/java/org/openmrs/util/UserByNameComparatorTest.java
Issue: https://issues.openmrs.org/browse/TRUNK-5253
> [TRUNK-5253] Delete unnecessary semicolons

- api/src/main/java/org/openmrs/api/SerializationService.java
- api/src/main/java/org/openmrs/api/context/Context.java
- api/src/main/java/org/openmrs/api/context/ServiceContext.java
- api/src/main/java/org/openmrs/api/impl/SerializationServiceImpl.java
- api/src/main/java/org/openmrs/serialization/OpenmrsSerializer.java
- api/src/main/java/org/openmrs/serialization/SimpleXStreamSerializer.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
Issue: https://issues.openmrs.org/browse/TRUNK-5252
> [TRUNK-5252] Remove explicit Object extension in type parameter

- api/src/main/java/org/openmrs/hl7/HL7InQueueProcessor.java
Issue: https://issues.openmrs.org/browse/GCI-247
> [GCI-247] Synchronize on Object rathen than Boolean

- api/src/main/java/org/openmrs/util/HttpClient.java
Replaced this line https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/util/HttpClient.java#L78
with
rd = new BufferedReader(new InputStreamReader(connection.getInputStream(), "UTF-8"));
Background Information:  Using classes and methods that rely on the default system encoding can result in code that works fine in its "home" environment. But that code may break for customers who use different encodings in ways that are extremely difficult to diagnose and nearly, if not completely, impossible to reproduce when it's time to fix them.
see https://issues.openmrs.org/browse/GCI-210
No? Unsure? …
> GCI-210 HttpClient should not rely on default encoding for InputStreamReader

- web/src/main/java/org/openmrs/module/web/ModuleServlet.java
* GCI 181
Move this trailing comment on the previous empty line.
https://issues.openmrs.org/browse/GCI-181
* GCI-181:[Moved Trailing Comment]
Moved Trailing comment to previous line
see https://issues.openmrs.org/browse/GCI-181
- [x ] I have **added …
> GCI 181: Moved Trailing Comment

- web/src/main/java/org/openmrs/web/filter/GZIPResponseWrapper.java
GCI-194: Remove useless parentheses from GZIPResponseWrapper
see https://issues.openmrs.org/browse/GCI-194
No? Unsure? …
> GCI-194: Remove useless parentheses from GZIPResponseWrapper

- api/src/main/java/org/openmrs/Allergen.java
- api/src/main/java/org/openmrs/Allergy.java
- api/src/main/java/org/openmrs/AllergyReaction.java
- api/src/main/java/org/openmrs/ConceptName.java
- api/src/main/java/org/openmrs/ProgramWorkflow.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/logic/LogicTransform.java
- api/src/main/java/org/openmrs/logic/result/Result.java
- api/src/main/java/org/openmrs/messagesource/impl/MutableResourceBundleMessageSource.java
- api/src/main/java/org/openmrs/module/Module.java
- api/src/main/java/org/openmrs/module/ModuleConditionalResource.java
- api/src/main/java/org/openmrs/util/DoubleRange.java
- api/src/main/java/org/openmrs/util/Format.java
- api/src/main/java/org/openmrs/util/HandlerUtil.java
- api/src/main/java/org/openmrs/util/LocaleUtility.java
- api/src/main/java/org/openmrs/validator/RequireNameValidator.java
- api/src/test/java/org/openmrs/ObsTest.java
- api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java
- web/src/main/java/org/openmrs/module/web/filter/ModuleFilterMapping.java
- web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
- webapp/src/test/java/org/openmrs/MessagePropertiesFilesTest.java
I've simplified few "if" statements and deleted unnecessary "return" statements
> [GCI-142] Simplified "if" statements

- api/src/main/java/org/openmrs/module/ModuleClassLoader.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
- web/src/main/java/org/openmrs/web/Listener.java
Issue: https://issues.openmrs.org/browse/TRUNK-5241
I've replaced every dangerous call to nullable variable with Objects.requireNonNull() so it is guaranteed to be non-null.
> [TRUNK-5241] Handle null pointer dereferences

- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/FormServiceImpl.java
- web/src/main/java/org/openmrs/web/WebUtil.java
Issue: https://issues.openmrs.org/browse/TRUNK-5250
> [TRUNK-5250] Method parameters shouldn't be reassigned

- api/src/main/java/org/openmrs/FormResource.java
Issue: https://issues.openmrs.org/browse/GCI-218
> [GCI-218] Add serialVersionUID field to FormResource

- api/src/main/java/org/openmrs/PatientIdentifier.java
- api/src/main/java/org/openmrs/PersonAddress.java
- api/src/main/java/org/openmrs/PersonName.java
Issue: https://issues.openmrs.org/browse/TRUNK-5254
> [TRUNK-5254] Use getPreferred() instead of isPreferred()

- api/src/test/java/org/openmrs/api/CohortServiceTest.java
Issue: https://issues.openmrs.org/browse/TRUNK-5256
> [TRUNK-5256] Use getCohortByName() instead of getCohort()

- api/src/main/java/org/openmrs/module/ModuleClassLoader.java
Issue: https://issues.openmrs.org/browse/GCI-239
> [GCI-239] Check is listFiles null before looping

- api/src/main/java/org/openmrs/module/ModuleFactory.java
see: https://issues.openmrs.org/browse/TRUNK-5258
> [TRUNK-5258] Replace anonymous type with lambda expression

- web/src/main/java/org/openmrs/web/filter/GZIPResponseWrapper.java
Remove this method: https://github.com/openmrs/openmrs-core/blob/master/web/src/main/java/org/openmrs/web/filter/GZIPResponseWrapper.java#L106-L108
Background Information: Methods should not be empty
see https://issues.openmrs.org/browse/GCI-193
No? -> …
> GCI-193 Remove empty method setContentLength from GZIPResponseWrapper

- api/src/main/java/org/openmrs/module/ModuleFileParser.java
Renamed bytes_read in HibernateAdministrationDAO to match the naming conventions on this page.
https://wiki.openmrs.org/display/docs/Java+Conventions#JavaConventions-NamingConventions
see https://issues.openmrs.org/browse/GCI-208 …
> GCI-208 Rename bytes_read in HibernateAdministrationDAO to match our convention

- web/src/main/java/org/openmrs/web/filter/update/UpdateFilterModel.java
GCI-199 Remove unused class variables from UpdateFilterModel
Removed headerTemplate, footerTemplate, superuserrole, and setupPageUrl as they are not used anywhere.
See https://issues.openmrs.org/browse/GCI-199
No? -> figure out …
> GCI-199: Remove unused class variables from UpdateFilterModel

- api/src/main/java/org/openmrs/Concept.java
- api/src/main/java/org/openmrs/Obs.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java
- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
- api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
- api/src/main/java/org/openmrs/layout/LayoutTemplate.java
- api/src/main/java/org/openmrs/layout/address/AddressSupport.java
- api/src/main/java/org/openmrs/module/ModuleClassLoader.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/util/HandlerUtil.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- api/src/test/java/org/openmrs/comparator/PatientIdentifierTypeDefaultComparatorTest.java
- api/src/test/java/org/openmrs/hl7/handler/ORUR01HandlerTest.java
- api/src/test/java/org/openmrs/util/UserByNameComparatorTest.java
- web/src/main/java/org/openmrs/web/Listener.java
https://issues.openmrs.org/browse/TRUNK-5262
> [Trunk 5262] Remove unused imports

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
https://issues.openmrs.org/browse/TRUNK-5261
> [TRUNK-5261] Replace anonymous type with lambda expression

- web/src/main/java/org/openmrs/web/filter/GZIPResponseStream.java
Changed #L155
From : return (this.closed);
To: return this.closed;
GCI-177 Remove those useless parentheses from GZIPResponseStream
Changed #L155
From : return (this.closed);
To: return this.closed;
https://issues.openmrs.org/browse/GCI-177
No? -> execute …
> GCI-177 Remove those useless parentheses from GZIPResponseStream

- api/src/main/java/org/openmrs/util/HandlerUtil.java
https://issues.openmrs.org/browse/TRUNK-5260
> [TRUNK-5260] Replace anonymous type with lambda expression

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateProviderDAO.java
Replace load() methods with get() method.
see https://issues.openmrs.org/browse/TRUNK-5153
> TRUNK-5153 : Replace load() method with get() method.

- api/src/main/java/org/openmrs/PersonName.java
- api/src/test/java/org/openmrs/layout/name/NameTemplateTest.java
- api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java
- api/src/test/resources/TestingApplicationContext.xml
Issue: https://issues.openmrs.org/browse/TRUNK-344
I've made also few changes to NameSupport so it may be reusable and pass all tests
> [TRUNK-344] PersonName.getFullName() should use the configured nameLayout

- web/src/main/java/org/openmrs/web/Listener.java
Issue: https://issues.openmrs.org/browse/TRUNK-5242
Deleted duplicated declaration of Logger variable, this class should have only one field Logger which should be private static final.
> [TRUNK-5242] Remove duplication of Logger

- api/src/main/java/org/openmrs/FormField.java
- api/src/main/java/org/openmrs/PatientIdentifier.java
- api/src/main/java/org/openmrs/PersonAttribute.java
- api/src/main/java/org/openmrs/PersonAttributeType.java
- api/src/main/java/org/openmrs/PersonName.java
- api/src/main/java/org/openmrs/comparator/PatientIdentifierTypeDefaultComparator.java
- api/src/main/java/org/openmrs/module/VersionComparator.java
- api/src/main/java/org/openmrs/util/ConceptMapTypeComparator.java
- api/src/main/java/org/openmrs/util/DrugsByNameComparator.java
- api/src/main/java/org/openmrs/util/MetadataComparator.java
- api/src/main/java/org/openmrs/util/PersonByNameComparator.java
- api/src/main/java/org/openmrs/util/ProviderByPersonNameComparator.java
- api/src/main/java/org/openmrs/util/UserByNameComparator.java
Issue: https://issues.openmrs.org/browse/GCI-261
> [GCI-261] Implement Serializable in Comparators

- api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
- api/src/main/java/org/openmrs/module/ModuleFileParser.java
- api/src/main/java/org/openmrs/module/ModuleUtil.java
- api/src/main/java/org/openmrs/obs/handler/TextHandler.java
- api/src/main/java/org/openmrs/util/DatabaseUpdater.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- api/src/main/java/org/openmrs/util/databasechange/CreateCodedOrderFrequencyForDrugOrderFrequencyChangeset.java
- api/src/main/java/org/openmrs/util/databasechange/MigrateConceptReferenceTermChangeSet.java
- api/src/main/java/org/openmrs/util/databasechange/SourceMySqldiffFile.java
- web/src/main/java/org/openmrs/web/Listener.java
- web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
- web/src/main/java/org/openmrs/web/filter/initialization/TestInstallUtil.java
Issue: https://issues.openmrs.org/browse/GCI-262
> [GCI-262] Change default encoding to "UTF-8"

- api/src/main/java/org/openmrs/api/impl/LocationServiceImpl.java
Issue: https://issues.openmrs.org/browse/TRUNK-5059
> [TRUNK-5059] Remove duplication in LocationService.getDefaultLocation

- api/src/main/java/org/openmrs/util/HttpClient.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- api/src/main/java/org/openmrs/util/Security.java
- api/src/test/java/org/openmrs/util/OpenmrsUtilTest.java
- web/src/main/java/org/openmrs/web/filter/StartupFilter.java
- web/src/main/java/org/openmrs/web/filter/initialization/TestInstallUtil.java
- web/src/main/java/org/openmrs/web/filter/util/CustomResourceLoader.java
- web/src/main/java/org/springframework/http/converter/json/MappingJacksonHttpMessageConverter.java
Issue: https://issues.openmrs.org/browse/TRUNK-5265
> [TRUNK-5265] Replace "UTF-8" String literals with StandardCharsets.UTF_8

- api/src/test/java/org/openmrs/validator/FieldValidatorTest.java
> [TRUNK-5270] Replace Boolean constructor with wrapper object

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java
- api/src/main/java/org/openmrs/api/impl/LocationServiceImpl.java
- api/src/main/java/org/openmrs/logic/result/Result.java
- api/src/main/java/org/openmrs/util/FormUtil.java
- api/src/test/java/org/openmrs/ConceptTest.java
- api/src/test/java/org/openmrs/PersonTest.java
- api/src/test/java/org/openmrs/api/AdministrationServiceTest.java
- api/src/test/java/org/openmrs/api/FormServiceTest.java
- api/src/test/java/org/openmrs/api/ObsServiceTest.java
- api/src/test/java/org/openmrs/api/ProviderServiceTest.java
- api/src/test/java/org/openmrs/scheduler/SchedulerServiceTest.java
- api/src/test/java/org/openmrs/scheduler/timer/TimerSchedulerServiceImplTest.java
> [TRUNK-5272] Remove unnecessary boxing of Integer, Long, Double

- api/src/main/java/org/openmrs/api/impl/AdministrationServiceImpl.java
- api/src/main/java/org/openmrs/util/databasechange/ConceptValidatorChangeSet.java
- web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
Issue: https://issues.openmrs.org/browse/GCI-263
> [GCI-263] Rename variables names to comply with naming conventions

- api/src/main/java/org/openmrs/Encounter.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
- api/src/main/java/org/openmrs/layout/LayoutTemplate.java
- api/src/test/java/org/openmrs/PersonTest.java
- api/src/test/java/org/openmrs/module/ModuleFactoryTest.java
- api/src/test/java/org/openmrs/validator/ConceptNameTagValidatorTest.java
Issue: https://issues.openmrs.org/browse/TRUNK-5267
> [TRUNK-5267] Delete redundant local variables

- api/src/main/java/org/openmrs/util/databasechange/BooleanConceptChangeSet.java
- api/src/main/java/org/openmrs/util/databasechange/ConceptValidatorChangeSet.java
- api/src/main/java/org/openmrs/util/databasechange/CreateDiscontinueOrders.java
Issue: https://issues.openmrs.org/browse/TRUNK-5277
> [TRUNK-5277] Collapse identical 'catch' branches

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateLocationDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneQuery.java
- api/src/main/java/org/openmrs/collection/CollectionPart.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/main/java/org/openmrs/propertyeditor/ConceptSetsEditor.java
- api/src/test/java/org/openmrs/scheduler/SchedulerUtilTest.java
- api/src/test/java/org/openmrs/validator/FieldValidatorTest.java
Issue: https://issues.openmrs.org/browse/TRUNK-5275
> [TRUNK-5275] Delete unnecessary value boxing

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateUtil.java
- api/src/main/java/org/openmrs/migration/MigrationHelper.java
- api/src/main/java/org/openmrs/module/ModuleClassLoader.java
- api/src/main/java/org/openmrs/module/ModuleFileParser.java
- api/src/main/java/org/openmrs/module/SqlDiffFileParser.java
- api/src/main/java/org/openmrs/module/UpdateFileParser.java
- api/src/main/java/org/openmrs/util/DatabaseUtil.java
- api/src/main/java/org/openmrs/util/Security.java
- api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java
- web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
- web/src/main/java/org/openmrs/web/Listener.java
- web/src/main/java/org/openmrs/web/filter/update/UpdateFilterModel.java
Issue: https://issues.openmrs.org/browse/TRUNK-5274
> [TRUNK-5274] Delete unused imports

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateAdministrationDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java
- api/src/main/java/org/openmrs/api/impl/AdministrationServiceImpl.java
- api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
- api/src/main/java/org/openmrs/util/Graph.java
Issue: https://issues.openmrs.org/browse/TRUNK-5276
> [TRUNK-5276] Explicit type can be replaced with diamond syntax

- api/src/main/java/org/openmrs/PersonAddress.java
- api/src/main/java/org/openmrs/api/db/hibernate/PatientSearchCriteria.java
- api/src/main/java/org/openmrs/module/Extension.java
- api/src/main/java/org/openmrs/util/UpgradeUtil.java
- api/src/test/java/org/openmrs/ObsTest.java
- api/src/test/java/org/openmrs/api/db/hibernate/HibernatePersonDAOTest.java
> [TRUNK-5271] Replace StringBuffer/StringBuilder with String in simple statements

- api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
- api/src/main/java/org/openmrs/module/ModuleFactory.java
Issue: https://issues.openmrs.org/browse/TRUNK-5278
> [TRUNK-5278] Delete redundant local variables

- pom.xml
Update JUNIT to 4.12 from 4.11
see https://issues.openmrs.org/browse/TRUNK-5194
> TRUNK 5194 - Update junit to 4.12

- api/src/test/java/org/openmrs/test/matchers/HasGlobalErrorsTest.java
Issue: https://issues.openmrs.org/browse/TRUNK-5287
> [TRUNK-5287] Delete redundant String constructor call

- api/src/main/java/org/openmrs/hl7/handler/ADTA28Handler.java
Issue: https://issues.openmrs.org/browse/TRUNK-5286
> [TRUNK-5286] Delete redundant String.toString() call

- api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
https://issues.openmrs.org/browse/TRUNK-5048?filter=-1
modified the code so that  UserServiceImpl.getUsers  is reached
- [ x] My pull request is **based on the latest changes** of the master branch.
> TRUNK-5048 Code in UserServiceImpl.getUsers might not be reached

- api/src/main/java/org/openmrs/util/NaturalStrings.java
Issue: https://issues.openmrs.org/browse/TRUNK-5268
Old PR: https://github.com/openmrs/openmrs-core/pull/2511
> [TRUNK-5268] Replace lambda expression with method reference

- api/src/main/java/org/openmrs/api/context/Context.java
Issue: https://issues.openmrs.org/browse/TRUNK-5292
> [TRUNK-5292] Call to toStrring() on array

- api/src/main/java/org/openmrs/PatientIdentifier.java
- api/src/main/java/org/openmrs/PersonAttribute.java
- api/src/test/java/org/openmrs/api/ObsServiceTest.java
- api/src/test/java/org/openmrs/api/ProgramWorkflowServiceTest.java
- api/src/test/java/org/openmrs/module/ModuleUtilTest.java
Issue: https://issues.openmrs.org/browse/TRUNK-5295
> [TRUNK-5295] Delete redundant array creation for calling varargs method

- api/src/test/java/org/openmrs/api/VisitServiceTest.java
https://issues.openmrs.org/browse/TRUNK-5147?jql=assignee%20in%20(madushan)
TRUNK - 5147 Add tests to VisitService, addeded Test cases to purgeVisit method according to reveiws.
- [x ] I have **added tests** to cover my changes. (If you refactored
- [x ] My pull request is **based on the latest changes** of the master …
> TRUNK-5147 Add tests to VisitService

- api/src/test/java/org/openmrs/api/VisitServiceTest.java
refactored VisitServiceTest
* used java.util.Calendar constants instead of literals
* split up tests testing multiple test cases
* used field for visitService instead of getting over and over again from the Context
* extracted duplicate code into private helper method
see https://issues.openmrs.org/browse/TRUNK-5147
> TRUNK-5147 Refactoring VisitServiceTest

- api/src/main/java/org/openmrs/notification/NotificationConstants.java
- api/src/main/java/org/openmrs/scheduler/SchedulerConstants.java
- api/src/main/java/org/openmrs/util/OpenmrsConstants.java
- web/src/main/java/org/openmrs/web/WebConstants.java
JIRA TICKET LINK- https://issues.openmrs.org/browse/TRUNK-5033?filter=-1
TRUNK-5033 Public static fields should be final
I modified public static variables into public static final
Checklist: I completed these to help reviewers :)
My pull request only contains ONE single commit
My IDE is configured to follow the code style of this project.
I have added tests to cover my changes. (If you refactored
I ran mvn clean package right before creating this pull request and
All new and existing tests passed.
My pull request is based on the latest changes of the master branch.
> TRUNK-5033 Public static fields should be final

- api/src/main/java/org/openmrs/PersonName.java
Issue: https://issues.openmrs.org/browse/TRUNK-5285
> [TRUNK-5285] Delete boxing of already boxed value

- pom.xml
see https://issues.openmrs.org/browse/TRUNK-5300
> TRUNK-5300 Update test db h2

- pom.xml
see https://issues.openmrs.org/browse/TRUNK-5125
> TRUNK-5125 Update dbUnit version

- api/pom.xml
- checkstyle-suppressions.xml
* remove checkstyle-suppressions which are not needed anymore
* remove antlr plugin running arden from api pom
see https://issues.openmrs.org/browse/TRUNK-5301
> TRUNK-5301 Remove org.openmrs.arden resources

- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/test/java/org/openmrs/validator/ObsValidatorTest.java
Issue: https://issues.openmrs.org/browse/TRUNK-5289
> [TRUNK-5289] Replace String concatenation in loop with StringBuilder

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java
Issue: https://issues.openmrs.org/browse/TRUNK-5291
> [TRUNK-5291] Use ArrayList constructor instead of iteration

- api/src/main/java/org/openmrs/BaseCustomizableData.java
- api/src/main/java/org/openmrs/BaseCustomizableMetadata.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateObsDAO.java
- api/src/main/java/org/openmrs/layout/LayoutTemplate.java
- api/src/main/java/org/openmrs/messagesource/impl/MutableResourceBundleMessageSource.java
- api/src/main/java/org/openmrs/util/Reflect.java
- api/src/test/java/org/openmrs/test/MigrateDataSet.java
Issue: https://issues.openmrs.org/browse/TRUNK-5293
> [TRUNK-5293] Delete statements with empty body

- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneQuery.java
- api/src/main/java/org/openmrs/util/OpenmrsConstants.java
- api/src/test/java/org/openmrs/api/db/PatientDAOTest.java
- Added a global property for patient identifier search match.
- Added support for patient identifier 'start' and 'anywhere' match. The default exact match behavior is maintained.
- Included unit tests.
see https://issues.openmrs.org/browse/TRUNK-5231
- [x …
> TRUNK-5231 Lucene support for partial patient identifier searches

- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
- api/src/main/java/org/openmrs/util/OpenmrsUtil.java
- api/src/test/java/org/openmrs/test/matchers/HasFieldErrors.java
- api/src/test/java/org/openmrs/validator/ConceptAttributeTypeValidatorTest.java
Issue: https://issues.openmrs.org/browse/TRUNK-5273
> [TRUNK-5273] Simplify stream API call chains

- api/src/main/java/org/openmrs/Provider.java
- api/src/main/java/org/openmrs/validator/VisitValidator.java
Issue: https://issues.openmrs.org/browse/TRUNK-5290
> [TRUNK-5290] StringBuilder can be replaced with String in simple calls

- api/src/main/java/org/openmrs/util/ConceptMapTypeComparator.java
Issue: https://issues.openmrs.org/browse/TRUNK-5283
> [TRUNK-5283] compare() method can be used to compare primitives

- api/src/main/java/org/openmrs/module/ModuleUtil.java
- api/src/test/java/org/openmrs/aop/RequiredDataAdviceTest.java
Issue: https://issues.openmrs.org/browse/TRUNK-5296
> [TRUNK-5296] Delete redundant type arguments

- api/src/test/java/org/openmrs/ConceptTest.java
- api/src/test/java/org/openmrs/api/EncounterServiceTest.java
- api/src/test/java/org/openmrs/api/FormServiceTest.java
- api/src/test/java/org/openmrs/api/PatientServiceTest.java
- api/src/test/java/org/openmrs/api/PersonServiceTest.java
https://issues.openmrs.org/browse/TRUNK-5037?filter=-1
Description of what I changed
Replaced use of synchronized class Vector with ArrayList
Checklist: I completed these to help reviewers :)
[ x] My pull request only contains ONE single commit
[x ] My IDE is configured to follow the code style of this project.
[ x] I have added tests to cover my changes. (If you refactored
[x ] I ran mvn clean package right before creating this pull request and
[ x] All new and existing tests passed.
[ x] My pull request is based on the latest changes of the master branch.
> TRUNK-5037 Replace use of synchronized class Vector with ArrayList

- api/src/main/java/org/openmrs/api/impl/GlobalLocaleList.java
see https://issues.openmrs.org/browse/TRUNK-5060
> TRUNK-5060: globalPropertyChanged catches all exceptions

- api/src/test/java/org/openmrs/api/ProgramWorkflowServiceUnitTest.java
https://issues.openmrs.org/browse/TRUNK-5068?filter=-1
TRUNK - 5068 Add tests to ProgramWorkFlowService, Added test case to check whether it null concept throws error
- [ x] I ran `mvn clean package` right before creating this pull request and
- [ x] My pull request is **based on the latest changes** of the master branch.
> TRUNK - 5068 Add tests to ProgramWorkFlowService

- api/src/test/java/org/openmrs/api/ProgramWorkflowServiceUnitTest.java
https://issues.openmrs.org/browse/TRUNK-5068
Added tests to ProgramWorkflowService
> TRUNK-5068 Add tests to ProgramWorkflowService

- api/src/test/java/org/openmrs/api/AdministrationServiceUnitTest.java
https://issues.openmrs.org/browse/TRUNK-5065
Added test cases for branches in AdministrationServiceImpl
> TRUNK-5065 Add tests to AdministrationServiceImpl

- api/pom.xml
- api/src/main/java/org/openmrs/PatientProgram.java
- api/src/main/java/org/openmrs/PatientProgramAttribute.java
- api/src/main/java/org/openmrs/ProgramAttributeType.java
- api/src/main/java/org/openmrs/api/ProgramWorkflowService.java
- api/src/main/java/org/openmrs/api/db/ProgramWorkflowDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateProgramWorkflowDAO.java
- api/src/main/java/org/openmrs/api/impl/ProgramWorkflowServiceImpl.java
- api/src/main/resources/hibernate.cfg.xml
- api/src/main/resources/liquibase-update-to-2.2.xml
- api/src/main/resources/liquibase-update-to-latest.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/PatientProgram.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/PatientProgramAttribute.hbm.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/ProgramAttributeType.hbm.xml
- api/src/test/java/org/openmrs/api/ProgramWorkflowServiceTest.java
- api/src/test/resources/org/openmrs/api/include/ProgramAttributesDataset.xml
- Add service layer and DAO changes for ProgramWorkflowService and ProgramWorkflowDAO classes.
- Add changes in BahmniPatientProgram to PatientProgram
[TRUNK-4755 ](https://issues.openmrs.org/browse/TRUNK-4755)
> TRUNK-4755 Implementing Program Enrollment Attributes

- api/src/main/java/org/openmrs/CodedOrFreeText.java
Added 1 file for this task:
* api/src/main/java/org/openmrs/CodedOrFreeText.java
See https://issues.openmrs.org/browse/TRUNK-5335 …
> TRUNK-5335: Add CodedOrFreeText convenience class to Java API.

- api/src/main/java/org/openmrs/ConditionClinicalStatus.java
Added 1 file for this task:
- api/src/main/java/org/openmrs/api/ConditionClinicalStatus.java
see https://issues.openmrs.org/browse/TRUNK-5337
No? -> figure out why and add the fix to your commit. It is your responsibility to make …
> TRUNK-5337: Introduce an Enum for condition status

- webapp/src/main/webapp/index.htm
[[PLAT-30] Bundle the Add-On manager OWA within the Platform](https://issues.openmrs.org/browse/PLAT-30)
Modified the `Index.htm` to provide a link to the Add On manager OWA
* [[PLAT-30]](https://issues.openmrs.org/browse/PLAT-30) …
> [PLAT-30] Bundle the Add-On manager OWA within the Platform

- pom.xml
- webapp/pom.xml
upgrade mysql jdbc connector we ship with the war
see https://issues.openmrs.org/browse/TRUNK-5356
> TRUNK-5356 Upgrade mysql:mysql-connector-java

- api/src/main/java/org/openmrs/Condition.java
- api/src/main/java/org/openmrs/validator/ConditionValidator.java
- api/src/main/resources/hibernate.cfg.xml
- api/src/main/resources/liquibase-update-to-2.2.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/Condition.hbm.xml
- api/src/test/java/org/openmrs/validator/ConditionValidatorTest.java
Added the condition domain object for the core module
The following files were added to this task:
- api/src/main/java/org/openmrs/Condition.java
- api/src/main/java/org/openmrs/validator/ConditionValidator.java
- api/src/main/resources/org/openmrs/api/db/hibernate/Condition.hbm.xml
- api/src/test/java/org/openmrs/ConditionTest.java
- api/src/test/java/org/openmrs/validator/ConditionValidatorTest.java
The following files were modified in this task:
- api/src/main/resources/hibernate.cfg.xml …
> TRUNK-5338 Add condition domain object

- api/src/main/java/org/openmrs/Condition.java
- api/src/main/resources/liquibase-update-to-2.2.xml
Added foreign key constraints to liquibase changeset
The following files were changed
No? -> figure out why and add the fix to …
> TRUNK-5338 Add foreign key constraints to liquibase changeset

- api/src/main/java/org/openmrs/Diagnosis.java
- api/src/main/java/org/openmrs/Encounter.java
- api/src/main/java/org/openmrs/validator/DiagnosisValidator.java
- api/src/main/resources/liquibase-update-to-2.2.xml
- api/src/main/resources/messages.properties
- api/src/main/resources/org/openmrs/api/db/hibernate/Diagnosis.hbm.xml
- api/src/test/java/org/openmrs/validator/DiagnosisValidatorTest.java
Added the __Diagnosis domain object__ for the core module
The following files were added to this task:
- api/src/main/java/org/openmrs/Diagnosis.java
- api/src/main/java/org/openmrs/validator/DiagnosisValidator.java
- api/src/main/resources/org/openmrs/api/db/hibernate/Diagnosis.hbm.xml
The following files were updated for this task:
- api/src/main/java/org/openmrs/Encounter.java
- api/src/main/resources/hibernate.cfg.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/Encounter.hbm.xml
see https://issues.openmrs.org/browse/TRUNK-5339
No? Unsure? -> [configure …
> TRUNK-5339: Introduce a new Diagnosis domain object

- api/src/main/java/org/openmrs/api/db/ConditionDAO.java
In this PR I create a ConditionDAO.java interface as copied from [here](https://github.com/openmrs/openmrs-module-emrapi/blob/9257dcd31d4d7af72742e78337662988b1edb463/condition-list/src/main/java/org/openmrs/module/emrapi/conditionslist/db/ConditionDAO.java).
see https://issues.openmrs.org/browse/TRUNK-5348
> TRUNK-5348: Create Condition data access interface.

- api/src/main/java/org/openmrs/api/ConditionService.java
- api/src/main/java/org/openmrs/util/PrivilegeConstants.java
Added 1 file for this task:
* api/src/main/java/org/openmrs/api/ConditionService.java
Changed 1 file for this task:
* api/src/main/java/org/openmrs/util/PrivilegeConstants.java
See https://issues.openmrs.org/browse/TRUNK-5347
No? …
> TRUNK-5347: Add CondtionService class

- api/src/main/java/org/openmrs/util/PrivilegeConstants.java
Changed 1 file for this task:
* api/src/main/java/org/openmrs/util/PrivilegeConstants.java
See https://issues.openmrs.org/browse/TRUNK-5347
No? -> figure out why and add the fix to your commit. It is your responsibility to make …
> TRUNK-5347: Refactor PrivilegeConstants to adhere to conventions.

- api/src/main/java/org/openmrs/api/db/DiagnosisDAO.java
This PR Creates a Diagnosis data access interface
see https://issues.openmrs.org/browse/TRUNK-5351
No? Unsure? -> …
> TRUNK-5351: Create Diagnosis data access interface.

- api/src/main/java/org/openmrs/api/DiagnosisService.java
- api/src/main/java/org/openmrs/util/PrivilegeConstants.java
Create DiagnosisService interface
see https://issues.openmrs.org/browse/TRUNK-5346
No? Unsure? -> execute command `git …
> TRUNK-5346: Create DiagnosisService interface

- api/src/main/resources/liquibase-update-to-2.2.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/Condition.hbm.xml
Added the embedded CodedOrFreeText component to condition object. The following files were changed
- api/src/main/resources/org/openmrs/api/db/hibernate/Condition.hbm.xml
added all formatting changes …
> TRUNK-5338 Add embedded CodedOrFreeText component

- api/src/main/java/org/openmrs/api/db/DiagnosisDAO.java
This PR adds a getDiagnosisByUuid method to the Diagnosis data access interface
see https://issues.openmrs.org/browse/TRUNK-5351 …
> Adds a getDiagnosisByUuid method.

- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneQuery.java
- api/src/main/java/org/openmrs/util/OpenmrsConstants.java
- api/src/test/java/org/openmrs/api/db/PatientDAOTest.java
see https://issues.openmrs.org/browse/TRUNK-5231
No? Unsure? -> execute command `git pull --rebase upstream 2.1.x`
> TRUNK-5231: Backporting to 2.1.x

- api/src/main/java/org/openmrs/api/ConditionService.java
- api/src/main/java/org/openmrs/util/PrivilegeConstants.java
Changed 2 files for this task:
* api/src/main/java/org/openmrs/api/ConditionService.java
* api/src/main/java/org/openmrs/util/PrivilegeConstants.java
See https://issues.openmrs.org/browse/TRUNK-5347
No? -> figure out why and add …
> TRUNK-5347: Add unvoidCondition and purgeCondition methods.

- api/src/main/java/org/openmrs/api/DiagnosisService.java
- api/src/main/java/org/openmrs/util/PrivilegeConstants.java
Add methods to unvoid and purge diagnoses
see https://issues.openmrs.org/browse/TRUNK-5346 …
> TRUNK-5346: Add unvoidDiagnoses and purgeDiagnoses methods

- api/src/main/java/org/openmrs/api/db/DiagnosisDAO.java
see https://issues.openmrs.org/browse/TRUNK-5351
> TRUNK-5351: Adds method for deleting a diagnosis

- api/src/main/java/org/openmrs/api/db/ConditionDAO.java
In this PR, I add a method to delete a condition.
see https://issues.openmrs.org/browse/TRUNK-5348
> TRUNK-5348: Add a method to delete a condition.

- api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
Added missing comma in order by clause
see https://issues.openmrs.org/browse/TRUNK-5359
No? Unsure? -> execute command …
> Fixed TRUNK-5359

- api/src/main/java/org/openmrs/api/db/ConditionDAO.java
In this PR, i add a new method called getCondition(Integer conditionId) which gets a condition by id.
see https://issues.openmrs.org/browse/TRUNK-5348
> TRUNK-5348: Add a new method called getCondition(Integer conditionId).

- api/src/main/java/org/openmrs/api/ConditionService.java
Changed 1 file for this task:
* api/src/main/java/org/openmrs/api/ConditionService.java
See https://issues.openmrs.org/browse/TRUNK-5347 …
> TRUNK-5347: Add getCondition method to ConditionService.

- api/src/main/java/org/openmrs/api/DiagnosisService.java
Add getDiagnosis method
see https://issues.openmrs.org/browse/TRUNK-5346
No? Unsure? -> execute command `git pull …
> TRUNK-5346: Add getDiagnosis method

- api/src/main/java/org/openmrs/Condition.java
- api/src/main/java/org/openmrs/api/db/ConditionDAO.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateConditionDAO.java
- api/src/main/resources/applicationContext-service.xml
- api/src/main/resources/liquibase-update-to-2.2.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/Condition.hbm.xml
- api/src/test/java/org/openmrs/api/db/hibernate/HibernateConditionDAOTest.java
- api/src/test/resources/org/openmrs/api/db/hibernate/include/HibernateConditionDAOTestDataSet.xml
Create a HibernateConditionDAO as copied from [here](https://github.com/openmrs/openmrs-module-emrapi/blob/9257dcd31d4d7af72742e78337662988b1edb463/condition-list/src/main/java/org/openmrs/module/emrapi/conditionslist/db/ConditionDAO.java)
[TRUNK-5349](https://issues.openmrs.org/browse/TRUNK-5349) …
> TRUNK-5349: Create Condition data access implementation

- api/src/main/java/org/openmrs/api/context/Context.java
- api/src/main/java/org/openmrs/api/context/ServiceContext.java
- api/src/main/java/org/openmrs/api/impl/ConditionServiceImpl.java
- api/src/main/java/org/openmrs/validator/ConditionValidator.java
- api/src/main/resources/applicationContext-service.xml
- api/src/main/resources/messages.properties
- api/src/test/java/org/openmrs/api/impl/ConditionServiceImplTest.java
- api/src/test/java/org/openmrs/validator/ConditionValidatorTest.java
- api/src/test/resources/org/openmrs/api/include/ConditionServiceImplTest-SetupCondition.xml
Implemented the Condition Service Interface
The following files were modified
- api/src/main/java/org/openmrs/api/context/Context.java
- api/src/main/java/org/openmrs/api/context/ServiceContext.java
- api/src/main/resources/applicationContext-service.xml
- api/src/main/java/org/openmrs/validator/ConditionValidator.java
- api/src/test/java/org/openmrs/validator/ConditionValidatorTest.java
- api/src/main/resources/messages.properties
The following files were added
- api/src/main/java/org/openmrs/api/impl/ConditionServiceImpl.java
- api/src/test/java/org/openmrs/api/impl/ConditionServiceImplTest.java
- api/src/test/resources/org/openmrs/api/include/ConditionServiceImplTest-SetupCondition.xml
see https://issues.openmrs.org/browse/TRUNK-5354 …
> TRUNK-5354: Add implementation of condition service interface

- api/src/main/java/org/openmrs/Diagnosis.java
- api/src/main/resources/hibernate.cfg.xml
- api/src/main/resources/liquibase-update-to-2.2.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/Diagnosis.hbm.xml
Added Diagnosis hibernate mapping file to **hibernate.cfg.xml file**
see https://issues.openmrs.org/browse/TRUNK-5339 …
> TRUNK-5339: Adds the Diagnosis hibernate mapping file to the hibernate.cfg.xml file

- api/src/main/java/org/openmrs/Diagnosis.java
- api/src/main/java/org/openmrs/api/db/hibernate/HibernateDiagnosisDAO.java
- api/src/main/resources/applicationContext-service.xml
- api/src/main/resources/liquibase-update-to-2.2.xml
- api/src/main/resources/org/openmrs/api/db/hibernate/Diagnosis.hbm.xml
- api/src/test/java/org/openmrs/api/db/hibernate/HibernateDiagnosisDAOTest.java
- api/src/test/resources/org/openmrs/api/include/HibernateDiagnosisDAOTestDataset.xml
Create Diagnosis data access implementation
[TRUNK-5352](https://issues.openmrs.org/browse/TRUNK-5352)
No? Unsure? -> …
> TRUNK-5352: Create Diagnosis data access implementation

- api/src/main/java/org/openmrs/module/Module.java
see https://issues.openmrs.org/browse/TRUNK-5369
> TRUNK-5369 Refactor Module.getExtensions

- api/src/test/java/org/openmrs/api/PatientServiceTest.java
https://issues.openmrs.org/browse/TRUNK-5069
Description of what I changed
Added tests to PatientServiceImpl
Checklist: I completed these to help reviewers :)
[x] My pull request only contains ONE single commit
[x] My IDE is configured to follow the code style of this project.
[x] I have added tests to cover my changes. (If you refactored
[x] I ran mvn clean package right before creating this pull request and
[x] All new and existing tests passed.
[x] My pull request is based on the latest changes of the master branch.
> TRUNK-5069 Add tests to PatientServiceImpl

- api/src/main/java/org/openmrs/module/ModuleFactory.java
- api/src/test/java/org/openmrs/module/ModuleFileParserTest.java
- api/src/test/java/org/openmrs/module/ModuleFileParserUnitTest.java
ModuleFileParser was not well tested, moved existing tests into class  "ModuleFileParserUnitTest" and added ModuleFileParserTest using DB to test most cases.
> Test ModuleFileParser

- api/src/test/java/org/openmrs/util/OpenmrsUtilTest.java
- api/src/test/java/org/openmrs/util/OpenmrsUtilUnitTest.java
see https://issues.openmrs.org/browse/TRUNK-5087
> TRUNK-5087 : Add tests to OpenmrsUtil

- api/src/main/resources/liquibase-update-to-2.2.xml
The following file was modified:
`api/src/main/resources/liquibase-update-to-2.2.xml` …
> TRUNK-5338: Make verification_status field nullable for the condition table

- api/src/main/resources/liquibase-update-to-2.2.xml
Add liquibase changeset to migrate data to the new condition table
The following file(s) was modified: 
see https://issues.openmrs.org/browse/TRUNK-5360
No? -> figure out why …
> TRUNK-5360: Add changeset to migrate data to the new condition table

- api/src/test/java/org/openmrs/api/FormServiceTest.java
I have added some test cases for getAllForms() and getForm() methods which were not covered before in the FormServiceTest Class.
see https://issues.openmrs.org/browse/TRUNK-5061 …
> TRUNK-5061 Added some test cases for FormServiceTest Class

- web/src/test/java/org/openmrs/module/filter/ModuleFilterDefinitionTest.java
I added a new test file with unit tests for ModuleFilterDefinition.java, since before there was zero coverage for the file. I tested the retrieveFilterDefinitions() method which is used to parse through an XML file and return a list of objects. This method had lots of nested conditionals that were untested. These tests should now achieve 100% coverage of the tested method. 
see https://issues.openmrs.org/browse/TRUNK-5389
existing code that …
> TRUNK-5389: Create new test cases for ModuleFilterDefinition.java

- api/src/main/resources/liquibase-update-to-2.2.xml
Make condition_id field nullable
see https://issues.openmrs.org/browse/TRUNK-5339
No? Unsure? -> execute command `git …
> TRUNK-5339: Make condition_id field nullable

- api/src/test/java/org/openmrs/api/impl/PatientServiceImplTest.java
see https://issues.openmrs.org/browse/TRUNK-5401
> TRUNK-5401 Remove powermock from PatientServiceImplTest

- web/src/test/java/org/openmrs/web/WebDaemonTest.java
> Adding WebDaemonTest to increase test coverage

- api/src/main/java/org/openmrs/Condition.java
Changed 1 files for this task:
* api/src/main/java/org/openmrs/Condition.java
See https://issues.openmrs.org/browse/TRUNK-5373 …
> TRUNK-5373: Add null check for coded conditions.

- api/src/main/java/org/openmrs/attribute/BaseAttribute.java
See [this thread on Openmrs Talk](https://talk.openmrs.org/t/handling-jpa-annotations-for-baseattribute/17873)
See https://issues.openmrs.org/browse/TRUNK-5402
@wluyima hope I got it right this time :-)
> - Annotated BaseAttribute. See

- findbugs-include.xml
- pom.xml
see https://issues.openmrs.org/browse/TRUNK-5083
> TRUNK-5083 Add FindBugs rules and maven plugin

- api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java
- api/src/test/java/org/openmrs/api/UserServiceTest.java
- api/src/test/java/org/openmrs/hl7/HL7ServiceTest.java
- api/src/test/resources/org/openmrs/api/include/UserServiceTest.xml
Ticket : https://issues.openmrs.org/browse/TRUNK-3895
> TRUNK-3895: Filtered out Daemon User from related API Search methods
