api/src/main/java/org/openmrs/PatientIdentifierType.java
api/src/main/java/org/openmrs/api/db/PatientDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java
api/src/test/java/org/openmrs/api/impl/PatientServiceImplTest.java
api/src/test/resources/org/openmrs/api/include/PatientServiceTest-findPatients.xml

(1) Set the test `shouldGetPatientsByIdentifierAndIdentifierType` in PatientServiceTest live as it was described in the Jira-ticket 
(2)  Added into HibernatePatientDAO the method `findPatients(String query, List<PatientIdentifierType> identifierTypes,.....)`
(3) Refactored a bit of code of the methods `getPatientIdentifierLuceneQuery` to improve the code with regards to the changes in TRUNK-5395 and TRUNK-5396
(4) Added annotations to the PatientIdentifierType class
(5) Some merges have been added because my branch was not up to date. I am sorry about that
see https://issues.openmrs.org/browse/TRUNK-5395
and https://issues.openmrs.org/browse/TRUNK-5396
No? -> [read …

Fixing TRUNK-5395 & TRUNK-5396

---

api/src/main/java/org/openmrs/Patient.java
api/src/test/java/org/openmrs/PatientTest.java

Added constructor for Patient that takes in a patient and creates a clone and appropriate test
see https://issues.openmrs.org/browse/TRUNK-5408 …

TRUNK-5408 Patient Constructor that takes in Patient

---

webapp/src/main/webapp/index.htm

[PLAT-30: Bundle the Add On manager OWA within the Platform](https://issues.openmrs.org/browse/PLAT-30)
Modified the Index.htm to remove the link to the Add On manager OWA
[PLAT-30](https://issues.openmrs.org/browse/PLAT-30)
No? …

PLAT-30: Bundle the Add On manager OWA within the Platform

---

api/src/main/java/org/openmrs/Order.java
api/src/main/java/org/openmrs/api/OrderService.java
api/src/main/java/org/openmrs/api/db/hibernate/ImmutableOrderInterceptor.java
api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
api/src/main/resources/liquibase-update-to-2.2.xml
api/src/main/resources/org/openmrs/api/db/hibernate/Order.hbm.xml
api/src/test/java/org/openmrs/OrderEntryIntegrationTest.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

Resolving TRUNK-5400 - Add Orders.fulfillerStatus and Orders.fulfillerComment
https://issues.openmrs.org/browse/TRUNK-5400
- Added the attributes to the Order object
- Made the attributes changeable 
- Added set() and getter() and made sure clone, and so on is still working
- Added a public method that allowed to change the status and comment of an order. This method was also added to the interface
- Added a test case to make sure all changes worked
see https://issues.openmrs.org/browse/TRUNK-5400
and for the discussion on https://talk.openmrs.org/t/adding-order-status-to-orders/17928/31 …

TRUNK-5400 - Add Orders.fulfillerStatus and Orders.fulfillerComment

---

api/src/main/java/org/openmrs/Person.java
api/src/main/java/org/openmrs/validator/PersonValidator.java
api/src/main/resources/liquibase-update-to-2.2.xml
api/src/main/resources/messages.properties
api/src/main/resources/org/openmrs/api/db/hibernate/Person.hbm.xml
api/src/test/java/org/openmrs/validator/PersonValidatorTest.java

Fixing TRUNK-5405 - Support free-text cause of death in the data model
https://issues.openmrs.org/browse/TRUNK-5405
I added the attribute cause_of_death_non_coded to the "Person" class and adapted the business logic as requested in the ticket
see https://issues.openmrs.org/browse/TRUNK-5405
added all …

TRUNK-5405 - Support free-text cause of death in the data model

---

api/src/main/java/org/openmrs/UserSessionListener.java
api/src/main/java/org/openmrs/api/UserService.java
api/src/main/java/org/openmrs/api/context/UserContext.java
api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/test/java/org/openmrs/api/db/ContextDAOTest.java

see discussion at: https://talk.openmrs.org/t/context-hasprivilege-is-too-busy/19237/2
https://issues.openmrs.org/browse/TRUNK-5416

TRUNK-5416: Added UserSessionListener

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java
api/src/main/java/org/openmrs/parameter/OrderSearchCriteria.java
api/src/main/java/org/openmrs/parameter/OrderSearchCriteriaBuilder.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

https://issues.openmrs.org/browse/TRUNK-5424

TRUNK-5424: Post commit code review updates

---

api/src/main/java/org/openmrs/util/PrivilegeConstants.java

https://issues.openmrs.org/browse/TRUNK-5433

TRUNK-5433: Added @AddOnStartup annotations where missing

---

api/src/main/resources/messages_fr.properties

Added French translations for Provider messages

---

api/src/main/java/org/openmrs/person/PersonMergeLog.java

I have added version id to PersonMergeLog class, which implements Serializable interface.
https://issues.openmrs.org/browse/GCI-222 …

GCI-222: Added version id to Serializable PersonMergeLog

---

api/src/main/resources/applicationContext-service.xml

Removed property settings code in applicationContect-service.xml file because it was commented out and wasn't being used. This goes against the coding conventions.
see https://issues.openmrs.org/browse/TRUNK-5436
No? -> figure …

TRUNK-5436 Remove code in ApplicationContext.xml file

---

api/src/main/java/org/openmrs/GlobalProperty.java

I added a serialVersionUID field to GlobalProperty.java since it implements the Serializable class. Now able to deserialize objects that were serialized in a previous instance of the class since the ID will not change across instances (a static/class variable).
see https://issues.openmrs.org/browse/GCI-221 …

GCI-221: Added serial version ID to GlobalProperty.java

---

api/src/main/java/org/openmrs/Concept.java
api/src/main/java/org/openmrs/annotation/AuthorizedAnnotationAttributes.java
api/src/main/java/org/openmrs/aop/RequiredDataAdvice.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateAdministrationDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateCohortDAO.java

Here's a fix of one of the Sonar issues. I was asked to divide one PR into the several problems I solve. This one fixes the problem of duplicating strings by defining them as constants.
https://issues.openmrs.org/browse/GCI-142
No need in posting task instance since it's already approved

GCI-142: String literals should not be duplicated

---

api/src/main/java/org/openmrs/Concept.java
api/src/main/java/org/openmrs/module/ModuleClassLoader.java
api/src/main/java/org/openmrs/module/ModuleFactory.java
api/src/main/java/org/openmrs/module/ModuleFileParser.java
api/src/main/java/org/openmrs/module/UpdateFileParser.java

Here's a fix of one of the Sonar issues. I was asked to divide one PR into the several problems I solve. This one fixes the problem by relocating those comments which are at the end of lines
https://issues.openmrs.org/browse/GCI-142
No need in posting task instance since it's already approved

GCI-142: Comments should not be located at the end of lines of code

---

api/src/main/java/org/openmrs/Cohort.java

Changed stream usage to filter->findFirst->get. Error handling might need to be changed as the function now returns a NoSuchElement error instead of the previous IndexOutOfBound. I'm still waiting for a response from a mentor on how I should deal with this issue.
see https://issues.openmrs.org/browse/TRUNK-5435
No? -> write tests and add them to this commit `git add . && git …

TRUNK-5435: Improve Java 8 streams usage on Cohort.getActiveMembership(Patient)

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java

https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=AWT7U3IOoPwAqlrbRYix&open=AWT7U3IOoPwAqlrbRYix
File: **/src/main/java/org/openmrs/api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java**
Fixed "identifierTypes.size() < 1" to "identifierTypes.isEmpty()"
No? -> write tests and add them to this …

GCI-142: Fixed bad coding practices (#5)

---

api/src/main/java/org/openmrs/api/OrderContext.java

https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=a07f9ee2-03dd-4a29-8dbf-4e6cac3f7919&open=a07f9ee2-03dd-4a29-8dbf-4e6cac3f7919
file: **/src/main/java/org/openmrs/api/OrderContext.java**
Made code easier to read by changing "return contextAttributes = new HashMap<>();" into two lines
No? -> write tests and add …

GCI-142: Fixed bad coding practices (#4)

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java

Using Collection.isEmpty() makes the code more readable. Also the time complexity of any isEmpty() method implementation should be 0(1) whereas some implementations of size() can be 0(n).
Task Instance- https://codein.withgoogle.com/dashboard/task-instances/5671543834148864/
No? -> write tests and add them to this commit `git add . && …

GCI-142 Check bad code practices through Findbugs or Sonar and fix them

---

api/src/main/java/org/openmrs/ConceptProposal.java

Removed the unused private log field which was declared but not used in the program.
Task Instance- https://codein.withgoogle.com/dashboard/task-instances/5671543834148864/##
No? -> …

 GCI-142 Check bad code practices through Findbugs or Sonar and fix them

---

api/src/main/java/org/openmrs/Concept.java
api/src/main/java/org/openmrs/ConceptName.java
api/src/main/java/org/openmrs/ConceptSet.java
api/src/main/java/org/openmrs/Obs.java
api/src/main/java/org/openmrs/Patient.java
api/src/main/java/org/openmrs/Person.java
api/src/main/java/org/openmrs/Role.java

Moved the comments to the previous line as they should not be there at the end of the line. 
Task Instance- https://codein.withgoogle.com/dashboard/task-instances/5671543834148864/## …

GCI-142 Check bad code practices through Findbugs or Sonar and fix them.

---

api/src/main/java/org/openmrs/aop/AuthorizationAdvice.java
api/src/main/java/org/openmrs/api/context/Context.java
api/src/main/java/org/openmrs/api/context/UserContext.java
api/src/main/java/org/openmrs/scheduler/TaskFactory.java
api/src/main/java/org/openmrs/util/OpenmrsClassLoader.java
api/src/main/java/org/openmrs/validator/EncounterValidator.java
api/src/main/java/org/openmrs/validator/FieldValidator.java
api/src/main/java/org/openmrs/validator/PatientValidator.java
api/src/main/java/org/openmrs/validator/ProviderValidator.java
web/src/main/java/org/openmrs/web/filter/initialization/TestInstallUtil.java

I changed several logging messages to match current coding conventions. In particular, I used parameterized logging instead of string concatenation.
https://issues.openmrs.org/browse/TRUNK-5437

TRUNK-5437 Use parametrized messages while logging.

---

web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java

I've reordered modifiers to comply with the convention.

GCI-142: Reordered modifiers to comply with the convention

---

api/src/main/java/org/openmrs/layout/address/AddressSupport.java
api/src/main/java/org/openmrs/module/ModuleClassLoader.java

I made some loggers `private static final`.

GCI-142: Made loggers private static final

---

api/src/main/java/org/openmrs/Duration.java

I've added missing curly braces.

GCI-142: Added missing curly braces

---

api/src/main/java/org/openmrs/api/ProgramWorkflowService.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
api/src/main/java/org/openmrs/api/impl/ConditionServiceImpl.java
api/src/main/java/org/openmrs/api/impl/DiagnosisServiceImpl.java
api/src/main/java/org/openmrs/module/MandatoryModuleException.java
api/src/main/java/org/openmrs/module/ModuleFactory.java
api/src/main/java/org/openmrs/validator/ConditionValidator.java

GCI-142: Removed useless imports

---

api/src/main/java/org/openmrs/PersonAddress.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConditionDAO.java
api/src/main/java/org/openmrs/layout/name/NameSupport.java
api/src/main/java/org/openmrs/order/OrderUtil.java

GCI-142: Removed unused loggers

---

api/src/main/java/org/openmrs/Order.java

I've removed an empty statement.

GCI-142: Removed empty statement

---

api/src/main/java/org/openmrs/validator/VisitValidator.java

I've removed unecessary boxing/unboxing of a primitive value.

GCI-142: Removed unecessary boxing/unboxing of primitive value

---

api/src/main/java/org/openmrs/util/OpenmrsConstants.java

I've modified the code to use already defined constants.

GCI-142: Used already defined constants instead of duplicating string literals

---

api/src/main/java/org/openmrs/api/OrderContext.java

The issue in `OrderContext.java` (inlined assigment in return expression) was partially fixed by another student, leaving an unecessary return statement so I've decided to remove it.

GCI-142: Removed unecessary return statement

---

api/src/main/java/org/openmrs/Concept.java

I've extracted an assignment out of an expression.

GCI-142: Extracted assigment out of an expression

---

api/src/main/java/org/openmrs/Concept.java

https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=7c9917f2-dd44-4926-bd18-8989e5dc40e0&open=7c9917f2-dd44-4926-bd18-8989e5dc40e0
File: **src/main/java/org/openmrs/Concept.java**
Refactored code to remove unnecessary nested statements …

GCI-142: Fixed bad coding practices (#3)

---

api/src/main/java/org/openmrs/BaseCustomizableData.java
api/src/main/java/org/openmrs/BaseCustomizableMetadata.java

https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=57a8e500-7780-4ba7-a022-391285a242a6&open=57a8e500-7780-4ba7-a022-391285a242a6
File: **src/main/java/org/openmrs/BaseCustomizableData.java**
Refactored code to remove nested statements for readability
--------------------------------
https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=3ae21593-2f6a-409a-9d00-1d67cbf9080a&open=3ae21593-2f6a-409a-9d00-1d67cbf9080a
File: **src/main/java/org/openmrs/BaseCustomizableMetadata.java**
Refactored code to remove nested statements for readability
No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into …

GCI-142: Fixed bad coding practices(#1)

---

api/src/main/java/org/openmrs/aop/AuthorizationAdvice.java

One of my changes from my PR #2780
Defined a constant instead of duplicating
Task Instance https://codein.withgoogle.com/dashboard/task-instances/6187644498214912/

GCI-142: Defined a constant instead of duplicating

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java
api/src/test/java/org/openmrs/api/db/hibernate/HibernateFormDAOTest.java
api/src/test/resources/org/openmrs/api/db/hibernate/include/HibernateFormDAOTestDataSet.xml

Work done :  Fixed Form search criteria bug of filtering forms against <code>containingAllFormFields</code> argument. I also added unit test confirming this.
Ticket : https://issues.openmrs.org/browse/TRUNK-5430

Trunk-5430: Form Search Criteria doesn't work as expected

---

api/src/main/java/org/openmrs/Cohort.java
api/src/test/java/org/openmrs/CohortTest.java

I added three methods to the Cohort class as well as test cases to verify their functionality according to the issue. This issue is a subtask that is  part of a larger number of related sub-tasks all related by https://issues.openmrs.org/browse/TRUNK-5379. 
Basically this functionality allows a user to request if a certain active member exists in the cohort and retrieve the number of active ones.
https://issues.openmrs.org/browse/TRUNK-5453 …

Resolving TRUNK-5453 - Method extension for interactions at Cohort level

---

api/src/main/java/org/openmrs/Cohort.java
api/src/test/java/org/openmrs/CohortTest.java
api/src/test/java/org/openmrs/api/CohortServiceTest.java

https://issues.openmrs.org/browse/TRUNK-5450
This issue is a sub-ticket of: [TRUNK-5379](https://issues.openmrs.org/browse/TRUNK-5379 )which is concerned with changing size(), contains(), isEmpty() in a way that it reflects more the intuitive behaviour.  [Design nodes](https://notes.openmrs.org/2018-10-15-Design-Forum) have been created and the talk discussion appears to be here: [Talk thread](https://talk.openmrs.org/t/design-forum-2018-10-15-resolving-design-inconsistencies-in-cohort-membership-trunk-5379/20115/7)
I changed the just named methods accordingly and created test cases to verify the behaviour. 
see https://issues.openmrs.org/browse/TRUNK-5450
No? -> [read …

Trunk-5450 - Java Collections functionality of memberships

---

api/src/main/java/org/openmrs/hl7/handler/ADTA28Handler.java
api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
api/src/main/java/org/openmrs/util/OpenmrsClassLoader.java
api/src/main/java/org/openmrs/util/OpenmrsUtil.java

Ticket : https://issues.openmrs.org/browse/TRUNK-5266

TRUNK-5266: Remove unecessary  keywords

---

api/src/test/java/org/openmrs/test/matchers/HasGlobalErrors.java

Used a different stream operation to simplify the logic in *HasGlobalErrors*
see https://issues.openmrs.org/browse/TRUNK-5470

TRUNK-5470 Simplify detection of global error

---

api/src/main/java/org/openmrs/ProviderAttribute.java
api/src/main/java/org/openmrs/api/PasswordException.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java
api/src/main/java/org/openmrs/api/impl/SerializationServiceImpl.java
api/src/main/java/org/openmrs/collection/ListPart.java
api/src/main/java/org/openmrs/module/ModuleClassLoader.java
api/src/main/java/org/openmrs/patient/impl/LuhnIdentifierValidator.java
api/src/main/java/org/openmrs/util/OpenmrsClassScanner.java
api/src/main/java/org/openmrs/util/OpenmrsUtil.java
api/src/main/java/org/openmrs/util/Reflect.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java
api/src/test/java/org/openmrs/obs/BinaryDataHandlerTest.java
api/src/test/java/org/openmrs/obs/BinaryStreamHandlerTest.java
api/src/test/java/org/openmrs/obs/ImageHandlerTest.java
api/src/test/java/org/openmrs/obs/MediaHandlerTest.java
api/src/test/java/org/openmrs/obs/TextHandlerTest.java
api/src/test/java/org/openmrs/serialization/JavaSerializationTest.java

Removed not needed castings reported by IntelliJ.
see https://issues.openmrs.org/browse/TRUNK-5468

TRUNK-5468 Remove not needed casts

---

api/src/main/java/org/openmrs/hl7/handler/ADTA28Handler.java
api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java

A detailed description is in the [ticket](https://issues.openmrs.org/browse/TRUNK-5476)
see https://issues.openmrs.org/browse/TRUNK-5476

TRUNK-5476 Refactor the way gender constants are maintained

---

api/src/test/java/org/openmrs/util/NaturalStringsTest.java

[Sonar complains about low test coverage of NaturalStrings](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=AWCgDm2hvsycEPA9_YmY&open=AWCgDm2hvsycEPA9_YmY)
I'm pretty sure I didn't cover all of the cases, but this commit should bring coverage to a healthy level 💪 
see https://issues.openmrs.org/browse/TRUNK-5474

TRUNK-5474 Add unit tests for NaturalStrings class

---

api/src/main/java/org/openmrs/Allergy.java
api/src/main/resources/liquibase-update-to-2.0.xml
api/src/main/resources/liquibase-update-to-2.3.xml
api/src/main/resources/liquibase-update-to-latest.xml
api/src/main/resources/org/openmrs/api/db/hibernate/Allergy.hbm.xml

I renamed allergy.comment to allergy.comments.
see https://issues.openmrs.org/browse/TRUNK-5334 …

TRUNK-5334: Rename allergy.comment to allergy.comments

---

CONTRIBUTING.md

Under CONTRIBUTING.md, at Contributing(Step-by-Step) point number 3, changed the 'out' to 'to', to easy understanding and making the line simple enough

Edit to CONTRIBUTING.md

---

api/src/main/java/org/openmrs/FormField.java

https://issues.openmrs.org/browse/GCI-217

GCI-217: Boxed value is unboxed and then immediately reboxed in org.openmrs.FormField.getRequired()

---

api/src/main/java/org/openmrs/Condition.java
api/src/main/java/org/openmrs/module/ModuleConditionalResource.java
api/src/main/java/org/openmrs/util/databasechange/MigrateConceptReferenceTermChangeSet.java

Removing duplicated logic that does the object equality check that treats null values as equal.
Small refactoring that will simplify code and remove duplication.
see https://issues.openmrs.org/browse/TRUNK-5475
It's simple refactoring. Did not add tests for it.

TRUNK-5475 Removing duplicated logic of Objects.equals

---

web/src/main/java/org/openmrs/web/WebUtil.java

Ticket : https://issues.openmrs.org/browse/TRUNK-5127

TRUNK-5127: Remove unused private variable

---

web/src/main/java/org/openmrs/web/Listener.java

Removed commented out code in Listener.java
see https://issues.openmrs.org/browse/GCI-214 …

GCI-214: removed commented code

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java

Removed commented out code in HibernateFormDAO
see https://issues.openmrs.org/browse/GCI-215 …

GCI-215: removed commented code from HibernateFormDAO.java

---

api/src/main/java/org/openmrs/ConceptNumeric.java

Replaced primitive boolean with the class to prevent immediate reboxing, in ConceptNumeric.java.
see https://issues.openmrs.org/browse/GCI-216 …

GCI-216: Replaced primitive boolean with the class to prevent immediate reboxing

---

api/src/main/java/org/openmrs/Cohort.java

GCI-243: Using Collection.isEmpty() to test for emptiness
Using Collection.isEmpty() to test for emptiness, instead Collection.size() == 0.
see https://issues.openmrs.org/browse/GCI-243
No? -> figure out why and add the fix to …

GCI-243: Using Collection.isEmpty() to test for emptiness

---

api/src/main/java/org/openmrs/util/HttpClient.java
api/src/main/java/org/openmrs/util/HttpUrl.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java
api/src/main/resources/applicationContext-service.xml
api/src/test/java/org/openmrs/util/HttpUrlTest.java

Handle server redirections in HttpClient and update implementationId urls.
see https://issues.openmrs.org/browse/TRUNK-5384

TRUNK-5384: Handle server redirections in HttpClient and update implementationId urls.

---

api/src/main/java/org/openmrs/Encounter.java
api/src/main/resources/hibernate.cfg.xml
api/src/main/resources/org/openmrs/api/db/hibernate/Encounter.hbm.xml

Reverts openmrs/openmrs-core#2908

Revert "TRUNK-5493 Replace Encounter hbm mapping file with annotations"

---

pom.xml

I updated the library version from com.thoughtworks.xstream:xstream … 1.4.3 to 1.4.11.1
https://issues.openmrs.org/browse/TRUNK-5554

TRUNK-5554:Upgrade the xstream Library

---

pom.xml

I upgraded library org.azeckoski:reflectutils from 0.9.14 to 0.9.20
https://issues.openmrs.org/browse/TRUNK-5531

TRUNK-5531:Upgrade org.azeckoski:reflectutils

---

pom.xml

**Issue worked on:** https://issues.openmrs.org/browse/TRUNK-5526

TRUNK-5526: Upgrade net.sf.ehcache:ehcache

---

pom.xml

**Issue worked on:** https://issues.openmrs.org/browse/TRUNK-5533

TRUNK-5533: Upgrade com.fasterxml.jackson.core:jackson Libraries

---

pom.xml

**Issue worked on:** https://issues.openmrs.org/browse/TRUNK-5503

TRUNK-5503:Upgrade ca.uhn.hapi: Libraries

---

pom.xml

**Issue worked on:** https://issues.openmrs.org/browse/TRUNK-5550

TRUNK-5550: Upgrade org.slf4j Libraries

---

pom.xml

I upgraded library org.hamcrest Sub Libraries below
1. org.hamcrest:hamcrest-core … 1.3 -> 2.1
2.  org.hamcrest:hamcrest-library … 1.3 -> 2.1
https://issues.openmrs.org/browse/TRUNK-5537

TRUNK-5537:Upgrade org.hamcrest Libraries

---

pom.xml

I upgraded library log4j:log4j from 1.2.15 to 1.2.17
https://issues.openmrs.org/browse/TRUNK-5525?filter=-1

TRUNK-5525:Upgrade log4j:log4j

---

pom.xml

see https://issues.openmrs.org/browse/TRUNK-5536
- [x ] I have **added tests** to cover my changes. (If you refactored …

Upgrade org.dbunit:dbunit Trunk 5536

---

api/src/main/java/org/openmrs/FullTextSessionFactory.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateContextDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneQuery.java

see https://issues.openmrs.org/browse/TRUNK-5559

TRUNK-5559 - Add FullTextSessionFactory class which is exposed as a spring bean

---

api/pom.xml

TRUNK-5558:Adding mysql-connector for test
https://issues.openmrs.org/browse/TRUNK-5558
I added mysql-connector to the openmrs-api with scope as test. …

TRUNK-5558:Adding mysql-connector for test

---

api/pom.xml
pom.xml

see https://issues.openmrs.org/browse/TRUNK-5560

TRUNK-5560 - Add aspectj and aspectjweaver dependencies to core

---

api/src/main/java/org/openmrs/validator/PersonValidator.java
api/src/test/java/org/openmrs/validator/PersonValidatorTest.java

TRUNK-5473 - Refactor PersonValidator#validate method
This PR is highly inspired by (https://github.com/openmrs/openmrs-core/pull/2804) Thanks for the good previous work.
- PersonValidator#validate  simplified by creating sub-methods for validatePersonAddresses, validatePersonNames and validatePersonHasAtLeastOneNonVoidedName
- I added all validate methods into PersonValidator and not as suggested by previous work into the Person class
- I am not sure how the PersonValidator should deal with a Null in a personAddress.  I made it to simply continue without failing. See here fore more details: https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/validator/PersonAddressValidator.java#L67
see https://issues.openmrs.org/browse/TRUNK-5473
(the number above, next to …

TRUNK-5473 - Refactor PersonValidator#validate method

---

api/src/main/java/org/openmrs/OrderSet.java
api/src/main/resources/liquibase-update-to-2.3.xml
api/src/main/resources/org/openmrs/api/db/hibernate/OrderSet.hbm.xml

**Issue worked on**: [Add Category field to OrderSet](https://issues.openmrs.org/browse/TRUNK-5413)

TRUNK-5413: Add Category field to OrderSet

---

pom.xml

**Issue worked on:** https://issues.openmrs.org/browse/TRUNK-5548

TRUNK-5548: Upgrade org.powermock Libraries

---

api/src/main/java/org/openmrs/FullTextSessionFactory.java
api/src/main/java/org/openmrs/api/db/DelegatingFullTextSession.java
api/src/main/java/org/openmrs/api/db/FullTextQueryAndEntityClass.java
api/src/main/java/org/openmrs/api/db/FullTextQueryCreatedEvent.java
api/src/main/java/org/openmrs/api/db/FullTextSessionFactory.java
api/src/main/java/org/openmrs/api/db/FullTextSessionFactoryImpl.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateContextDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneQuery.java

…whenever a new full text query object is created.
see https://issues.openmrs.org/browse/TRUNK-5559
No? Unsure? -> …

TRUNK-5559 Implemented a mechanism so that listeners can be notified whenever a new full text query object is created

---

api/src/main/java/org/openmrs/Encounter.java
api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
api/src/test/java/org/openmrs/EncounterTest.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java

Hi @mogoodrich , thank you for reviewing these changes!

Trunk 5438

---

api/src/main/java/org/openmrs/Encounter.java

Thanks @dkayiwa for pointing out this helpful annotation.

TRUNK-5438, add annotation @since

---

api/src/main/java/org/openmrs/api/context/DaoAuthenticationScheme.java

Ticket : https://issues.openmrs.org/browse/TRUNK-381

TRUNK-381 : Follow up commit to package-scope getContextDAO()

---

api/src/main/java/org/openmrs/api/context/DaoAuthenticationScheme.java

Ticket : https://issues.openmrs.org/browse/TRUNK-381

TRUNK-381: DaoAuthenticationScheme#getContextDAO() to be protected.

---

api/src/main/resources/liquibase-update-to-2.0.xml

see https://issues.openmrs.org/browse/TRUNK-5659

TRUNK-5659 Fix incorrect pre-conditions

---

api/src/main/resources/org/openmrs/module/dtd/cinfig-1.6.dtd

link:https://issues.openmrs.org/browse/TRUNK-5403
Add and fix config xml dtd file 1.6

Trunk-5403:fix config.xml dtd file version 1.6

---

api/src/main/resources/org/openmrs/module/dtd/config-1.6.dtd

link: https://issues.openmrs.org/browse/TRUNK-5403
Add and fix config xml dtd file 1.6

Trunk-5403:Add and fix config xml data file 1.6

---

api/src/main/resources/liquibase-update-to-2.3.xml
api/src/main/resources/org/openmrs/api/db/hibernate/Condition.hbm.xml

link:https://issues.openmrs.org/browse/TRUNK-5663
Added date_changed column to conditions table

Trunk-5663:Add date_changed column to conditions table

---

api/src/main/java/org/openmrs/api/ConditionService.java
api/src/main/java/org/openmrs/api/db/ConditionDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConditionDAO.java
api/src/main/java/org/openmrs/api/impl/ConditionServiceImpl.java
api/src/test/java/org/openmrs/api/db/hibernate/HibernateConditionDAOTest.java
api/src/test/java/org/openmrs/api/impl/ConditionServiceImplTest.java
api/src/test/resources/org/openmrs/api/db/hibernate/include/HibernateConditionDAOTestDataSet.xml
api/src/test/resources/org/openmrs/api/include/ConditionServiceImplTest-SetupCondition.xml
api/src/test/resources/org/openmrs/api/include/DiagnosisServiceImplTest-SetupDiagnosis.xml

show inactive conditions
see https://issues.openmrs.org/browse/TRUNK-5657
No? Unsure? -> execute command `git pull …

RA-1625: Adding ability to get all conditions

---

README.md

Update URL link on line 134
There is no previous PR or issue related. There is no break on code …

Update URL link on line 134

---

api/src/main/java/org/openmrs/api/db/ConceptDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java
api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
api/src/test/java/org/openmrs/api/ConceptServiceTest.java

Ticket: https://issues.openmrs.org/browse/TRUNK-5683

TRUNK-5683: getConceptsByClass(ConceptClass) to use Hibernate Criteria.

---

api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneAnalyzerFactory.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java
api/src/test/resources/org/openmrs/api/include/PatientServiceTest-findPatientsAccents.xml

https://issues.openmrs.org/browse/TRUNK-5681
This adds the [ASCIIFoldingFilterFactory](https://lucene.apache.org/core/4_10_0/analyzers-common/index.html?org/apache/lucene/analysis/miscellaneous/ASCIIFoldingFilter.html) to the Lucene search analyzers.

TRUNK-5681 Patient search should be insensitive to accents

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java
api/src/main/java/org/openmrs/parameter/OrderSearchCriteria.java
api/src/main/java/org/openmrs/parameter/OrderSearchCriteriaBuilder.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

Hi @mogoodrich , here is the PR for filtering out DISCONTINUE orders. Thanks.

TRUNK-5687, filter out DISCONTINUE orders

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java
api/src/main/java/org/openmrs/parameter/OrderSearchCriteria.java
api/src/main/java/org/openmrs/parameter/OrderSearchCriteriaBuilder.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

@mogoodrich , here is the backporting to 2.3.x. Thanks!

TRUNK-5687, backport excludeDiscontinueOrders to 2.3.x

---

api/src/main/java/org/openmrs/OrderGroup.java
api/src/main/resources/liquibase-update-to-2.3.xml
api/src/main/resources/org/openmrs/api/db/hibernate/OrderGroup.hbm.xml

link:https://issues.openmrs.org/browse/TRUNK-5650
Add parent order group to order group

Trunk-5650:Add parent order group to order group

---

api/src/main/java/org/openmrs/Patient.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java

Fix problem with auditable parameters inherited from BaseOpenmrsData
No? …

TRUNK-5492: Replace Person and Patient hbm mapping file with annotation

---

api/src/main/java/org/openmrs/Condition.java

GCI 142: Check bad code practices through Findbugs or Sonar and fix those issues.
I've fixed this [issue](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=AWNO-D_JSNPHhr6Gt-Lc&open=AWNO-D_JSNPHhr6Gt-Lc) as pointed by Sonar.
I've renamed *condition* object to *conditionToBeChecked*
No? -> write tests and add …

GCI 142: Refactored Object name to uncover global version - 2

---

api/src/main/java/org/openmrs/OrderGroup.java
api/src/main/resources/liquibase-update-to-2.4.xml
api/src/main/resources/liquibase-update-to-latest.xml
api/src/main/resources/org/openmrs/api/db/hibernate/OrderGroup.hbm.xml

link:https://issues.openmrs.org/browse/TRUNK-5653
Added order group reason to order group

Trunk-5653:Add order group reason to order group

---

api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java

Tests for ConceptServiceImpl#saveConceptProposal have been added to ConceptServiceImplTest.
see https://issues.openmrs.org/browse/GCI-322
No? -> figure out why and add the fix to your commit. It is your responsibility to make …

GCI-322 - Write tests for ConceptServiceImpl.saveConceptProposal

---

api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java

I have added tests to cover getConceptNameTagByName method of ConceptServiceImpl class in ConceptServiceImplTest file
see https://issues.openmrs.org/browse/GCI-325 …

GCI-325 Write tests for ConceptServiceImpl.getConceptNameTagByName

---

api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java

Tests for ConceptServiceImpl#saveDrug have been added to ConceptServiceImplTest.
see https://issues.openmrs.org/browse/GCI-321 …

GCI-321 - Write tests from ConceptServiceImpl.saveDrug

---

api/src/main/java/org/openmrs/CohortMembership.java

Added curly braces and indented the code properly in order to solve the following two issues at `L162`
- [Missing curly brace](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=AW5r7d5zX_1wboXLs5bH&open=AW5r7d5zX_1wboXLs5bH)
- [At most one statement is allowed per line, but 2 statements were found on this line.](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=AW5r7d5zX_1wboXLs5bI&open=AW5r7d5zX_1wboXLs5bI)
- [ [GCI-142] Check bad code practices through Findbugs or Sonar and fix those issues.](https://issues.openmrs.org/browse/GCI-142)
- [GCI Task Link](https://codein.withgoogle.com/tasks/5662964531593216/)
No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to …

[GCI-142] Check bad code practices through Findbugs or Sonar and fix those issues- 1.

---

api/src/main/java/org/openmrs/api/impl/LocationServiceImpl.java

Check bad code practices through Findbugs or Sonar and fix those issues. (Load of known null value) …

GCI-142 Check bad code practices through Findbugs or Sonar and fix those issues. (1)

---

api/src/main/java/org/openmrs/BaseConceptMap.java

Check bad code practices through Findbugs or Sonar and fix those issues. (Exposing internal representation of mutable objects in getters) …

GCI-142 Check bad code practices through Findbugs or Sonar and fix those issues.

---

api/src/main/java/org/openmrs/Condition.java

GCI-142: Check bad code practices through Findbugs or Sonar and fix those issues.
I've fixed some memory leaks as indicated by the Sonar :
- [issue 1](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=AWGtPQ4reC2CQ1jcfcWi&open=AWGtPQ4reC2CQ1jcfcWi)
- [issue 2](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=AWHiqMHLs_CtjRdw4sjQ&open=AWHiqMHLs_CtjRdw4sjQ)
- [issue 3](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=AWGtPQ4reC2CQ1jcfcWh&open=AWGtPQ4reC2CQ1jcfcWh)
- [issue 4](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=AWGtPQ4reC2CQ1jcfcWj&open=AWGtPQ4reC2CQ1jcfcWj)
- [issue 5](https://sonar.openmrs.org/project/issues?id=org.openmrs%3Aopenmrs&issues=AWHiqMHLs_CtjRdw4sjP&open=AWHiqMHLs_CtjRdw4s …

GCI-142: Check bad code practices through Sonar and fix those issues - 1

---

api/src/main/java/org/openmrs/Attributable.java
api/src/main/java/org/openmrs/Concept.java
api/src/main/java/org/openmrs/Location.java
api/src/main/java/org/openmrs/User.java
api/src/main/java/org/openmrs/util/AttributableDate.java

Deprecated the methods `Attributable#findPossibleValues()` and `Attributable#getPossibleValues()`
see https://issues.openmrs.org/browse/TRUNK-5699 …

TRUNK-5699 Deprecate Attributable#findPossibleValues() and Attributable#getPossibleValues()

---

api/src/main/java/org/openmrs/scheduler/SchedulerService.java
api/src/main/java/org/openmrs/scheduler/db/SchedulerDAO.java
api/src/main/java/org/openmrs/scheduler/db/hibernate/HibernateSchedulerDAO.java
api/src/main/java/org/openmrs/scheduler/timer/TimerSchedulerServiceImpl.java
api/src/test/java/org/openmrs/scheduler/SchedulerServiceTest.java

link:
https://issues.openmrs.org/browse/TRUNK-5710

Trunk-5710:Implement the getByUniqueId(String uniqueId) in SchedulerService.java

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateConditionDAO.java

Correctly imported ConditionService.java and also removed code duplication
see https://issues.openmrs.org/browse/TRUNK-5657 …

TRUNK-5657 : Unable to display inactive conditions

---

api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/main/resources/messages.properties

see https://issues.openmrs.org/browse/TRUNK-5726

TRUNK-5726: Use Lambda expressions in UserServiceImpl#checkPrivileges(Role).

---

api/src/test/java/org/openmrs/api/ProgramWorkflowServiceTest.java

see https://issues.openmrs.org/browse/TRUNK-5068

TRUNK-5068: Add tests to ProgramWorkflowService

---

api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/main/resources/messages.properties
api/src/test/java/org/openmrs/api/UserServiceTest.java

https://issues.openmrs.org/browse/TRUNK-5146
in this ticket , created a subclass checkSuperUserRole and modified it whith checkPrivilege. Added some tests for that
cc @ibacher 
No? -> …

TRUNK-5146: Use Java streams in UserServiceImpl#checkPrivileges(User)

---

tools/src/main/resources/eclipse/OpenMRSFormatter.xml

Enables disabling the Eclipse formatter for block of code using:
```java
// @formatter:off
// unformatted code goes here
// @formatter:on
```
see https://issues.openmrs.org/browse/TRUNK-5729
No? -> figure out why and add the fix …

TRUNK-5729: Support disabling the code formatter

---

api/src/main/java/org/openmrs/api/OrderService.java
api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

link:https://issues.openmrs.org/browse/TRUNK-5739

Trunk-5739:Expand updateOrderFulfillerStatus to also set accession number

---

api/src/main/java/org/openmrs/Condition.java
api/src/main/java/org/openmrs/Encounter.java
api/src/main/java/org/openmrs/api/ConditionService.java
api/src/main/java/org/openmrs/api/EncounterService.java
api/src/main/java/org/openmrs/api/db/ConditionDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConditionDAO.java
api/src/main/java/org/openmrs/api/impl/ConditionServiceImpl.java
api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.3.x.xml
api/src/test/java/org/openmrs/EncounterTest.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java
api/src/test/java/org/openmrs/api/impl/ConditionServiceImplTest.java
api/src/test/resources/org/openmrs/api/include/ConditionServiceImplTest-SetupCondition.xml

Linking Condition to the Encounter domain. Checkout this [talk thread](https://talk.openmrs.org/t/patient-conditions-and-encounters) for more details.
see https://issues.openmrs.org/browse/TRUNK-5728

TRUNK-5728: Condition to be linked to an Encounter

---

api/src/main/java/org/openmrs/Condition.java
api/src/main/java/org/openmrs/Encounter.java
api/src/main/java/org/openmrs/api/ConditionService.java
api/src/main/java/org/openmrs/api/EncounterService.java
api/src/main/java/org/openmrs/api/db/ConditionDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateConditionDAO.java
api/src/main/java/org/openmrs/api/impl/ConditionServiceImpl.java
api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
api/src/main/resources/liquibase-update-to-2.3.xml
api/src/test/java/org/openmrs/EncounterTest.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java
api/src/test/java/org/openmrs/api/impl/ConditionServiceImplTest.java
api/src/test/resources/org/openmrs/api/include/ConditionServiceImplTest-SetupCondition.xml

Community ticket: https://issues.openmrs.org/browse/TRUNK-5728

TRUNK-5728: Back-porting work on linking Conditions to an Encounter to 2.3.x

---

api/src/main/java/org/openmrs/util/Security.java

Deprecated Security.encrypt/decrypt methods
see https://issues.openmrs.org/projects/TRUNK/issues/TRUNK-5207?filter=allopenissues …

TRUNK-5207: Deprecate Security.encrypt/decrypt methods

---

api/src/main/java/org/openmrs/Concept.java

Description of what i changed.
Replace use of conditional logging with slf4j parameterized messages 
Issue worked on:
https://issues.openmrs.org/browse/TRUNK-5115

TRUNK-5115: Replace use of conditional logging with slf4j parameterized messages

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml

Added liquibase changeset to add fuzzystrmatch extension for postgresql
see https://issues.openmrs.org/browse/TRUNK-5752

TRUNK-5752, Soundex Support for PostgreSQL

---

pom.xml

The idea is upgrade org.dbunit dependencie to the latest version .
This imply this change : 
org.dbunit:dbunit:2.6.0 --> 2.7.0
see https://issues.openmrs.org/browse/TRUNK-5775

TRUNK-5775:  Upgrade org.dbunit

---

pom.xml

The idea is to Upgrade Org.aspectj  dependency  to the latest version .
This imply this change :
org.aspectj:aspectjrt:1.9.4 --> 1.9.5
org.aspectj:aspectjweaver:1.9.4 --> 1.9.5 
see https://issues.openmrs.org/browse/TRUNK-5774
No? Unsure? -> execute command `git pull --rebase upstream …

TRUNK-5774: Upgrade org.aspectj 

---

pom.xml

this sub-task is to upgrade this dependencies:
jakarta.xml.bind:jakarta.xml.bind-api:2.3.2 --> 3.0.0-RC3
see https://issues.openmrs.org/browse/TRUNK-5772

TRUNK-5772:  Upgrade jakarta.xml.bind-api from 2.3.2 to 3.0.0-RC3

---

pom.xml

The idea is to Upgrade joda-time library  to the latest version
joda-time:joda-time:2.10.5 --> 2.10.6
see https://issues.openmrs.org/browse/TRUNK-5777

TRUNK-5777: Upgrade joda-time from 2.10.5 to 2.10.6

---

pom.xml

I change the version of the following dependencies :
commons-beanutils:commons-beanutils:1.9.3 --> 1.9.4
commons-io:commons-io:2.6 --> 2.7
org.apache.commons:commons-lang3:3.9 -->3.10
see https://issues.openmrs.org/browse/TRUNK-5769 …

TRUNK-5769:  Upgrade commons libraries

---

pom.xml

i have change the following  dependencies version  :
org.slf4j:slf4j-api:1.7.28 --> 1.7.30
org.slf4j:jcl-over-slf4j:1.7.28 -->1.7.30
org.slf4j:log4j-over-slf4j:1.7.28 -->1.7.30
see https://issues.openmrs.org/browse/TRUNK-5770
No? Unsure? -> execute command `git pull --rebase upstream …

TRUNK-5770: Upgrade slf4jVersion from 1.7.28 to 1.7.30

---

pom.xml

I change the version of the following dependencies :
com.fasterxml.jackson.core:jackson-core:2.9.8 --> 2.11.0
com.fasterxml.jackson.core:jackson-annotations:2.9.8 --> 2.11.0
com.fasterxml.jackson.core:jackson-databind:2.9.10.4 --> 2.11.0
see https://issues.openmrs.org/browse/TRUNK-5771
No? …

TRUNK-5771: Upgrade com.fasterxml.jackson.core to 2.11.0

---

pom.xml

i made the following change on liquibase-core 
org.liquibase:liquibase-core:3.8.9 --> 3.10.0
see https://issues.openmrs.org/browse/TRUNK-5776

TRUNK-5776: Upgrade liquibase-core from 3.8.9 to 3.10.0

---

pom.xml

The goal is to update the following dependencies:
org.apache.logging.log4j:log4j-core:2.12.1 -->2.13.3
org.apache.logging.log4j:log4j-slf4j-impl:2.12.1 -->2.13.3
org.apache.logging.log4j:log4j-1.2-api:2.12.1 -->2.13.3
see https://issues.openmrs.org/browse/TRUNK-5759 …

TRUNK-5759: Upgrade log4jVersion from 2.12.1 to 2.13.3

---

pom.xml

The idea is to  upgrade the com.thoughtworks.xstream to the latest version .
com.thoughtworks.xstream:xstream:1.4.11.1 --> 1.4.12
see https://issues.openmrs.org/browse/TRUNK-5778

TRUNK-5778: Upgrade com.thoughtworks.xstream 

---

api/pom.xml
api/src/main/java/org/openmrs/util/MemoryAppender.java
api/src/main/java/org/openmrs/util/ThreadSafeCircularFifoQueue.java
api/src/test/java/org/openmrs/util/MemoryAppenderTest.java
api/src/test/java/org/openmrs/util/ThreadSafeCircularFifoQueueTest.java
pom.xml

This is a fix for TRUNK-5113. It turns out that every time the logger configuration is reset, a new `MemoryAppender` ended up being created, which resulted in a situation where the `MemoryAppender` attached to a given logger might be attached to a `MemoryAppender` with no messages, even if messages were being logged to a different `MemoryAppender` instance.
This PR fixes this by changing the `MemoryAppender` for log4j2 to use a single backing queue per appender name. This means that, in effect, all versions of the `MemoryAppender` share a single buffer. This is necessary to ensure that messages can be successfully read from the `MemoryAppender`.
see https://issues.openmrs.org/browse/TRUNK-5113
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Yo …

TRUNK-5113: Fix MemoryAppender to use a shared buffer-per-name

---

pom.xml

I made this change
com.h2database:h2:1.4.199: -->1.4.200
see https://issues.openmrs.org/browse/TRUNK-5780

TRUNK-5780: Upgrade com.h2database from h2:1.4.199 to h2:1.4.200

---

api/src/main/java/org/openmrs/EncounterType.java
api/src/main/resources/hibernate.cfg.xml
api/src/main/resources/org/openmrs/api/db/hibernate/EncounterType.hbm.xml
api/src/test/java/org/openmrs/api/OrderServiceTest.java

Reverts openmrs/openmrs-core#3259

Revert "TRUNK-5801: Switch EncounterType to use JPA Annotations"

---

liquibase/README.md

Correct Liquibase Documentation
see https://issues.openmrs.org/browse/TRUNK-5820

TRUNK-5820, Correct Liquibase Documentation

---

api/src/main/resources/org/openmrs/api/db/hibernate/ConceptMap.hbm.xml

Corrected the sequence name.
see https://issues.openmrs.org/browse/TRUNK-5800

TRUNK-5800, Map concept_reference_map sequence correctly

---

api/pom.xml
pom.xml
web/pom.xml

Upgrade library javax API sub-libraries below 
javax.mail:mail … 1.4.1 -> 1.5.0-b01
javax.servlet:javax.servlet-api … 3.0.1 -> 4.0.1
javax.servlet:jsp-api … 2.0 -> 2.0.public_draft
javax.servlet:jstl … 1.1.2 -> 1.2
javax.validation:validation-api … 1.0.0.GA -> 2.0.1.Final
see https://issues.openmrs.org/browse/TRUNK-5521 …

    TRUNK-5521: Upgrade javax Libraries

---

pom.xml

I made this change
postgresql:postgresql:42.2.13 --> 42.2.14
see https://issues.openmrs.org/browse/TRUNK-5779

TRUNK-5779 :Upgrade PostgreSQL Connector from 42.2.13 to 42.2.14

---

api/src/test/java/org/openmrs/notification/db/hibernate/HibernateAlertDAOTest.java
api/src/test/resources/org/openmrs/api/db/hibernate/include/HibernateAlertDAOTestDataSet.xml

Ticket ID
https://issues.openmrs.org/browse/TRUNK-5101
Description
wrote tests for HibernateAlertDAO

TRUNK 5101: Add Tests for HibernateAlertDAO

---

api/pom.xml
pom.xml

This Sun-task is to migrate  Migrate From org.glassfish.jaxb to com.sun.xml.bind  this imply this change:
org.glassfish.jaxb:jaxb-runtime:2.3.2 --> com.sun.xml.bind:jaxb-impl:3.0.0-M4
see https://issues.openmrs.org/browse/TRUNK-5773 …

TRUNK-5773: Migrate From org.glassfish.jaxb to com.sun.xml.bind

---

api/src/test/java/org/openmrs/LocationTest.java
api/src/test/java/org/openmrs/util/databasechange/Database1_9_7UpgradeIT.java

The PR  is to replace all the remaining  Junit4 assertThat with Hamcrest assertThat:
org.junit.Assert.assertThat --> org.hamcrest.MatcherAssert.assertThat
see https://issues.openmrs.org/browse/TRUNK-5812

TRUNK-5812:Replace all Junit4 assertThat with Hamcrest assertThat

---

api/src/test/java/org/openmrs/api/context/ContextMockHelper.java
pom.xml

This PR update the version of Mockito-core
org.mockito :mockito-core:2.28.2 -->3.3.3
see https://issues.openmrs.org/browse/TRUNK-5814

TRUNK-5814: Upgrade mockito-core from 2.28.2 to 3.3.3

---

api/src/test/java/org/openmrs/AllergiesTest.java
api/src/test/java/org/openmrs/ConceptTest.java
api/src/test/java/org/openmrs/DurationTest.java
api/src/test/java/org/openmrs/ObsTest.java
api/src/test/java/org/openmrs/OrderTest.java
api/src/test/java/org/openmrs/validator/AllergyValidatorTest.java
api/src/test/java/org/openmrs/validator/CohortValidatorTest.java
api/src/test/java/org/openmrs/validator/ConceptMapTypeValidatorTest.java
api/src/test/java/org/openmrs/validator/ConceptNameTagValidatorTest.java
api/src/test/java/org/openmrs/validator/ConceptReferenceTermValidatorTest.java
api/src/test/java/org/openmrs/validator/ConceptValidatorTest.java
api/src/test/java/org/openmrs/validator/ConditionValidatorTest.java
api/src/test/java/org/openmrs/validator/DrugValidatorTest.java
api/src/test/java/org/openmrs/validator/EncounterValidatorTest.java
api/src/test/java/org/openmrs/validator/ObsValidatorTest.java
api/src/test/java/org/openmrs/validator/OrderFrequencyValidatorTest.java
api/src/test/java/org/openmrs/validator/OrderTypeValidatorTest.java
api/src/test/java/org/openmrs/validator/PatientIdentifierValidatorTest.java
api/src/test/java/org/openmrs/validator/PatientProgramValidatorTest.java
api/src/test/java/org/openmrs/validator/PersonValidatorTest.java
api/src/test/java/org/openmrs/validator/ValidateUtilTest.java
api/src/test/java/org/openmrs/validator/VisitValidatorTest.java

TRUNK-5813:  Replace all ExpectedException Rules and the @Test(expected..)

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml

Updated the sequence value to hold the correct value. Also, verified the change on running OpenMRS core instance on PostgreSQL.
see https://issues.openmrs.org/browse/TRUNK-5832

TRUNK-5832, Unable to create new Patient Identifier Type in PostgreSQL

---

api/src/test/java/org/openmrs/util/databasechange/Database1_9_7UpgradeIT.java

TRUNK-5813 Replace all ExpectedException Rules and the @Test(expected..)

---

api/src/main/resources/org/openmrs/api/db/hibernate/PersonMergeLog.hbm.xml

Mapped the sequence correctly.
see https://issues.openmrs.org/browse/TRUNK-5831

TRUNK-5831, Unable to merge Patients in PostgreSQL

---

api/src/test/java/org/openmrs/api/ObsServiceTest.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java
api/src/test/java/org/openmrs/api/OrderSetServiceTest.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java
api/src/test/java/org/openmrs/api/PersonServiceTest.java
api/src/test/java/org/openmrs/api/ProgramWorkflowServiceTest.java
api/src/test/java/org/openmrs/api/ProgramWorkflowServiceUnitTest.java
api/src/test/java/org/openmrs/api/ProviderServiceTest.java
api/src/test/java/org/openmrs/api/UserServiceTest.java
api/src/test/java/org/openmrs/api/VisitServiceTest.java

TRUNK-5813 Replace all ExpectedException Rules and the @Test(expected…)

---

api/src/test/java/org/openmrs/api/AdministrationServiceTest.java
api/src/test/java/org/openmrs/api/AdministrationServiceUnitTest.java
api/src/test/java/org/openmrs/api/ConceptServiceTest.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java
api/src/test/java/org/openmrs/api/LocationServiceTest.java
api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java
api/src/test/java/org/openmrs/api/impl/PatientServiceImplTest.java
api/src/test/java/org/openmrs/customdatatype/datatype/RegexValidatedTextTest.java

    TRUNK-5813: Replace all ExpectedException Rules and the @Test(expected..)

---

api/src/test/java/org/openmrs/module/ModuleFactoryTest.java
api/src/test/java/org/openmrs/module/ModuleFileParserTest.java
api/src/test/java/org/openmrs/module/ModuleFileParserUnitTest.java
api/src/test/java/org/openmrs/module/ModuleTest.java
api/src/test/java/org/openmrs/module/ModuleUtilIT.java
api/src/test/java/org/openmrs/module/ModuleUtilTest.java

TRUNK-5813: Replace all ExpectedException Rules and the @Test(expected…)

---

api/pom.xml
api/src/test/java/org/openmrs/OpenmrsTestsTest.java
api/src/test/java/org/openmrs/ProviderTest.java
api/src/test/java/org/openmrs/RoleTest.java
api/src/test/java/org/openmrs/TestOrderTest.java
api/src/test/java/org/openmrs/UserTest.java

TRUNK-5816: Migrate unit tests to Junit5

---

api/src/test/java/org/openmrs/OrderGroupTest.java
api/src/test/java/org/openmrs/OrderTypeTest.java
api/src/test/java/org/openmrs/PatientProgramTest.java
api/src/test/java/org/openmrs/PatientStateTest.java
api/src/test/java/org/openmrs/PatientTest.java
api/src/test/java/org/openmrs/PersonAddressTest.java
api/src/test/java/org/openmrs/PersonNameTest.java

TRUNK-5816: Migrate api package tests to Junit 5

---

api/src/main/resources/org/openmrs/api/db/hibernate/Concept.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/ConceptAttribute.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/ConceptAttributeType.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/EncounterProvider.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/EncounterRole.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/FormResource.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/Provider.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/ProviderAttribute.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/ProviderAttributeType.hbm.xml

Properly Mapped the sequences.
see https://issues.openmrs.org/browse/TRUNK-5843

TRUNK-5843 Properly Map sequences via hibernate

---

api/src/test/java/org/openmrs/api/handler/BaseRetireHandlerTest.java
api/src/test/java/org/openmrs/api/handler/BaseUnretireHandlerTest.java
api/src/test/java/org/openmrs/api/handler/BaseUnvoidHandlerTest.java
api/src/test/java/org/openmrs/api/handler/BaseVoidHandlerTest.java
api/src/test/java/org/openmrs/api/handler/ConceptNameSaveHandlerTest.java
api/src/test/java/org/openmrs/api/handler/ExistingOrNewVisitAssignmentHandlerTest.java
api/src/test/java/org/openmrs/api/handler/ExistingVisitAssignmentHandlerTest.java
api/src/test/java/org/openmrs/api/handler/OpenmrsMetadataSaveHandlerTest.java
api/src/test/java/org/openmrs/api/handler/OpenmrsObjectSaveHandlerTest.java
api/src/test/java/org/openmrs/api/handler/PatientDataUnvoidHandlerTest.java
api/src/test/java/org/openmrs/api/handler/PatientDataVoidHandlerTest.java
api/src/test/java/org/openmrs/api/handler/PersonSaveHandlerTest.java
api/src/test/java/org/openmrs/api/handler/PersonUnvoidHandlerTest.java
api/src/test/java/org/openmrs/api/handler/PersonVoidHandlerTest.java
api/src/test/java/org/openmrs/api/handler/RequireVoidReasonVoidHandlerTest.java
api/src/test/java/org/openmrs/api/handler/RequiredReasonVoidSaveHandlerTest.java
api/src/test/java/org/openmrs/api/impl/ConditionServiceImplTest.java
api/src/test/java/org/openmrs/api/impl/DiagnosisServiceImplTest.java
api/src/test/java/org/openmrs/api/impl/GlobalLocaleListTest.java

TRUNK-5816: Migrate unit tests to Junit5 

---

api/src/test/java/org/openmrs/util/ExceptionUtilTest.java
api/src/test/java/org/openmrs/util/FormatTest.java
api/src/test/java/org/openmrs/util/GlobalPropertiesTestHelper.java
api/src/test/java/org/openmrs/util/GraphTest.java
api/src/test/java/org/openmrs/util/HandlerUtilTest.java
api/src/test/java/org/openmrs/util/HttpClientTest.java
api/src/test/java/org/openmrs/util/HttpUrlTest.java
api/src/test/java/org/openmrs/util/LocaleUtilityTest.java
api/src/test/java/org/openmrs/util/LocationUtilityTest.java
api/src/test/java/org/openmrs/util/Log4JCompatibilityTest.java
api/src/test/java/org/openmrs/util/MemoryAppenderTest.java
api/src/test/java/org/openmrs/util/NaturalStringsTest.java
api/src/test/java/org/openmrs/util/OpenmrsSecurityManagerTest.java
api/src/test/java/org/openmrs/util/OpenmrsUtilUnitTest.java
api/src/test/java/org/openmrs/util/PersonByNameComparatorTest.java
api/src/test/java/org/openmrs/util/ProviderByPersonNameComparatorTest.java
api/src/test/java/org/openmrs/util/ReflectTest.java
api/src/test/java/org/openmrs/util/SecurityTest.java
api/src/test/java/org/openmrs/util/UpgradeUtilTest.java
api/src/test/java/org/openmrs/util/UserByNameComparatorTest.java

TRUNK-5816: Migrate unit tests to Junit5 5

---

api/src/main/java/org/openmrs/util/DatabaseUtil.java

My task was to find outdated "todo" entries. I found one and removed it.
see https://issues.openmrs.org/browse/TRUNK-5849

TRUNK-5849: Delete unnecessary "todo"

---

api/src/test/java/org/openmrs/ConceptTest.java
api/src/test/java/org/openmrs/DrugTest.java
api/src/test/java/org/openmrs/DurationTest.java
api/src/test/java/org/openmrs/EncounterTest.java
api/src/test/java/org/openmrs/ObsBehaviorTest.java
api/src/test/java/org/openmrs/OpenmrsTestAnnotationsTest.java
api/src/test/java/org/openmrs/OrderEntryIntegrationTest.java
api/src/test/java/org/openmrs/PatientTest.java
api/src/test/java/org/openmrs/PersonAttributeTest.java
api/src/test/java/org/openmrs/PersonTest.java
api/src/test/java/org/openmrs/SimpleDosingInstructionsTest.java

TRUNK-5816:  Migrate api package tests to Junit 5

---

web/src/main/java/org/openmrs/web/filter/util/FilterUtil.java

I changed the variable type from object to primitive. Following Java Conventions.
see https://issues.openmrs.org/browse/TRUNK-5860

TRUNK-5860: Change of object type to primitive

---

api/src/main/java/org/openmrs/hl7/impl/HL7ServiceImpl.java

I changed the variable type from object to primitive. Following Java Conventions.
see https://issues.openmrs.org/browse/TRUNK-5858

TRUNK-5858: Change of object type to primitive

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml

Added a liquibase change set to add uuid-ossp extension.
see https://issues.openmrs.org/browse/TRUNK-5864

TRUNK-5864 UUID functions support for PostgreSQL

---

api/src/main/java/org/openmrs/Allergy.java
api/src/main/java/org/openmrs/CohortMembership.java
api/src/main/java/org/openmrs/Drug.java
api/src/main/java/org/openmrs/Obs.java
api/src/main/java/org/openmrs/Order.java
api/src/main/java/org/openmrs/OrderGroup.java
api/src/main/java/org/openmrs/RelationshipType.java
api/src/main/java/org/openmrs/api/ObsService.java
api/src/main/java/org/openmrs/api/OrderService.java
api/src/main/java/org/openmrs/api/UserService.java
api/src/main/java/org/openmrs/api/context/Daemon.java
api/src/main/java/org/openmrs/api/context/DaoAuthenticationScheme.java
api/src/main/java/org/openmrs/api/context/UserContext.java
api/src/main/java/org/openmrs/api/impl/ProgramWorkflowServiceImpl.java
api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/main/java/org/openmrs/customdatatype/datatype/BaseMetadataDatatype.java
api/src/main/java/org/openmrs/customdatatype/datatype/ConceptDatatype.java
api/src/main/java/org/openmrs/hl7/db/HL7DAO.java
api/src/main/java/org/openmrs/logic/LogicContext.java
api/src/main/java/org/openmrs/scheduler/db/hibernate/HibernateSchedulerDAO.java
api/src/main/java/org/openmrs/scheduler/tasks/AlertReminderTask.java
api/src/main/java/org/openmrs/util/Graph.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java
api/src/main/java/org/openmrs/util/OpenmrsUtil.java
api/src/main/java/org/openmrs/util/Security.java
web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
web/src/main/java/org/openmrs/web/filter/update/UpdateFilter.java

My goal was to find broken links, typos in argument names, more arguments than in reality. My goal was not to supplement Javadoc in all classes. All the problems I found have been fixed.
see https://issues.openmrs.org/browse/TRUNK-5847 …

TRUNK-5847: Javadoc improvement

---

api/src/main/java/org/openmrs/module/UpdateFileParser.java

I changed the variable type from object to primitive. Following Java Conventions.
see https://issues.openmrs.org/browse/TRUNK-5854

TRUNK-5854: Change of object type to primitive

---

api/src/test/java/org/openmrs/api/PersonServiceTest.java

Ticket ID
https://issues.openmrs.org/browse/TRUNK-5064
Description
Added untested methods for PersonServiceImpl

TRUNK-5064:Added untested methods for PersonServiceImpl

---

api/src/test/java/org/openmrs/annotation/OpenmrsProfileExcludeFilterTest.java
api/src/test/java/org/openmrs/annotation/OpenmrsProfileIncludeFilterTest.java
api/src/test/java/org/openmrs/api/db/ContextDAOTest.java
api/src/test/java/org/openmrs/api/db/EncounterDAOTest.java
api/src/test/java/org/openmrs/api/db/PatientDAOTest.java
api/src/test/java/org/openmrs/api/db/PersonDAOTest.java
api/src/test/java/org/openmrs/api/db/ProgramWorkflowDAOTest.java
api/src/test/java/org/openmrs/api/db/SerializedObjectDAOTest.java
api/src/test/java/org/openmrs/api/db/UserDAOTest.java

TRUNK-5816: Migrate api package tests to Junit5 5

---

api/src/test/java/org/openmrs/api/ConceptServiceTest.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java
api/src/test/java/org/openmrs/api/LocationServiceTest.java
api/src/test/java/org/openmrs/api/ObsServiceTest.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java
api/src/test/java/org/openmrs/api/OrderSetServiceTest.java
api/src/test/java/org/openmrs/api/PatientServiceAllergyTest.java
api/src/test/java/org/openmrs/api/PersonServiceTest.java
api/src/test/java/org/openmrs/api/ProgramWorkflowServiceTest.java
api/src/test/java/org/openmrs/api/UserServiceTest.java
api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java
api/src/test/java/org/openmrs/hl7/handler/ORUR01HandlerTest.java

TRUNK-5816: Migrate api package tests to Junit5 4

---

api/src/test/java/org/openmrs/OrderTest.java
api/src/test/java/org/openmrs/util/OpenmrsUtilTest.java
api/src/test/java/org/openmrs/validator/PatientValidatorTest.java
api/src/test/java/org/openmrs/validator/PersonMergeLogValidatorTest.java
api/src/test/java/org/openmrs/validator/PersonValidatorTest.java

TRUNK-5816: Migrate api package tests to Junit5 

---

api/src/test/java/org/openmrs/api/PatientServiceTest.java

TRUNK-5816 : Migrate api package tests to Junit 5 (PatientServiceTest)

---

api/src/test/java/org/openmrs/api/UserServiceTest.java

TRUNK-5816: Migrate api package tests to Junit 5 (UserServiceTest)

---

api/src/test/java/org/openmrs/module/ModuleActivatorTest.java
api/src/test/java/org/openmrs/module/ModuleInteroperabilityTest.java
api/src/test/java/org/openmrs/test/jupiter/BaseModuleActivatorTest.java

TRUNK-5816: Migrate api package tests to Junit5 (BaseModuleActivatorTest)

---

api/src/test/java/org/openmrs/obs/ImageHandlerTest.java

TRUNK-5816: Migrate api package tests to Junit 5 (AbstractHandlerTest/PowerMock)

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml

Created an alias function for UUID generation similar to MySQL
see https://issues.openmrs.org/browse/TRUNK-5870

TRUNK-5870 Create Wrapper UUID function for PostgreSQL similar to MySQL

---

api/src/test/java/org/openmrs/obs/BinaryStreamHandlerTest.java

TRUNK-5816: Migrate api package tests to Junit (BinaryStreamHandlerTest/PowerMock)

---

api/src/test/java/org/openmrs/obs/BinaryDataHandlerTest.java

TRUNK-5816: Migrate api package tests to Junit 5 (BinaryDataHandlerTest/PowerMock)

---

api/src/test/java/org/openmrs/obs/AbstractHandlerTest.java

TRUNK-5816: Migrate api package tests to Junit (AbstractHandlerTest/PowerMock)

---

web/pom.xml
web/src/test/java/org/openmrs/web/WebDaemonTest.java
web/src/test/java/org/openmrs/web/WebUtilTest.java
web/src/test/java/org/openmrs/web/test/WebTestHelper.java

TRUNK-5817: Migrate web and webapp package tests to Junit 5

---

web/pom.xml
web/src/test/java/org/openmrs/web/WebDaemonTest.java
web/src/test/java/org/openmrs/web/WebUtilTest.java
web/src/test/java/org/openmrs/web/context/AltAuthSchemeContextTest.java
web/src/test/java/org/openmrs/web/filter/update/GZIPFilterTest.java
web/src/test/java/org/openmrs/web/filter/update/UpdateFilterTest.java
web/src/test/java/org/openmrs/web/filter/update/util/FilterUtilTest.java
web/src/test/java/org/openmrs/web/test/BaseWebContextSensitiveTest.java
web/src/test/java/org/openmrs/web/test/WebTestHelper.java

TRUNK-5817 : Migrate web and webapp package tests to Junit 5

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateProgramWorkflowDAO.java
api/src/test/java/org/openmrs/api/db/ProgramWorkflowDAOTest.java

I changed the query for fetching Program Workflow states to order the returned list of PatientPrograms by enrollment date in chronological order.
see https://issues.openmrs.org/browse/TRUNK-5702

TRUNK-5702: Order Patient Programs By Enrollment Date

---

web/src/test/java/org/openmrs/module/filter/ModuleFilterDefinitionTest.java

TRUNK-5817 Migrate web and webapp package tests to Junit 5 (ModuleFilterDefinitionTest)

---

api/pom.xml
api/src/main/java/org/openmrs/Person.java
api/src/main/java/org/openmrs/PersonName.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/PersonLuceneQuery.java
api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneAnalyzerFactory.java
api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneAnalyzers.java
api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneQuery.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java
api/src/test/java/org/openmrs/api/PersonServiceTest.java
api/src/test/resources/org/openmrs/api/include/PersonServiceTest-names.xml
pom.xml

see https://issues.openmrs.org/browse/TRUNK-5724
which is a sub-task of https://issues.openmrs.org/browse/TRUNK-5680 to make everything deployable easier and introduce smaller changes
The talk thread discussing approach logic and so on can be found here: https://talk.openmrs.org/t/soundex-search-in-lucenequeries/26068
Please have a look there before asking for my changes!
- [X ] I have **added tests** to cover my changes. (If you refactored …

TRUNK-5724: Refactor getSimilarPeople to use Lucene

---

api/src/main/java/org/openmrs/layout/name/NameTemplate.java

I changed the variable type from object to primitive. Following Java Conventions.
see https://issues.openmrs.org/browse/TRUNK-5857

TRUNK-5857: Change of object type to primitive

---

api/src/main/java/org/springframework/core/JdkVersion.java

The file from the version using Spring Framework 4 includes only java to version 9. I added information about newer versions of java. Currently, they are versions up to 14.
see https://issues.openmrs.org/browse/TRUNK-5839

TRUNK-5839: Add information about newer Java versions than 9

---

web/src/test/java/org/openmrs/web/filter/startuperror/StartupErrorFilterTest.java

TRUNK-5817: Migrate web and webapp package tests to Junit 5 (StarupErrorFilterTest)

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java

…reSQL
In case of PostgreSQL, on use of session.saveOrUpdate(..) , only the sequence gets increased and no insert statement are issued by hibernate. So, I had to flush the session in order to avoid the null pointer exception being throw for LoginCredential.
see https://issues.openmrs.org/browse/TRUNK-5826 …

TRUNK-5826: Fix error when creating user on Postgres

---

api/src/main/java/org/openmrs/OrderGroup.java
api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
api/src/main/resources/org/openmrs/api/db/hibernate/OrderGroup.hbm.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java

Llink:https://issues.openmrs.org/browse/TRUNK-5652?src=confmacro

TRUNK-5652:Add NestedOrderGroups to OrderGroup

---

api/src/main/java/org/openmrs/liquibase/ChangeLogDetective.java

I changed the way the list was created and the values from another collection were copied to it. Now the list is created and filled with one command. The speed of operation remains the same.
see https://issues.openmrs.org/browse/TRUNK-5855 …

TRUNK-5855: Simplify the list creation process

---

api/src/main/java/org/openmrs/OrderSet.java
api/src/main/java/org/openmrs/OrderSetAttribute.java
api/src/main/java/org/openmrs/OrderSetAttributeType.java
api/src/main/java/org/openmrs/api/OrderSetService.java
api/src/main/java/org/openmrs/api/db/OrderSetDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderSetDAO.java
api/src/main/java/org/openmrs/api/impl/OrderSetServiceImpl.java
api/src/main/java/org/openmrs/util/PrivilegeConstants.java
api/src/main/resources/hibernate.cfg.xml
api/src/main/resources/org/openmrs/api/db/hibernate/OrderSet.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/OrderSetAttribute.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/OrderSetAttributeType.hbm.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java

link:https://issues.openmrs.org/browse/TRUNK-5835

TRUNK-5835:OrderSetAttribute implementation

---

api/src/test/java/org/openmrs/test/jupiter/BaseContextSensitiveTest.java

TRUNK-5816 Merged tests execution listeners

---

api/src/main/java/liquibase/ext/datatype/core/PostgreSQLUuidType.java
api/src/main/java/org/openmrs/validator/OrderFrequencyValidator.java
api/src/main/resources/org/openmrs/api/db/hibernate/OrderFrequency.hbm.xml

TRUNK-5887 Validation error when starting Reference Metadata
1. Mapped the sequence correctly
2. Trimmed the extra 2 spaces that are returned in case of PostgreSQL while doing the comparison. So that no validation error occurs.
see https://issues.openmrs.org/browse/TRUNK-5887
No? Unsure? …

TRUNK-5887 Validation error when starting Reference Metadata module on PostgreSQL

---

api/src/main/java/org/openmrs/api/OrderSetService.java
api/src/test/java/org/openmrs/api/OrderSetServiceTest.java
api/src/test/resources/org/openmrs/api/include/OrderSetServiceTest-attributes.xml

link:https://issues.openmrs.org/browse/TRUNK-5835

Trunk 5835:OrderSetAttribute Implementation 

---

api/pom.xml

dom4j is vulnerable according to https://github.com/openmrs/openmrs-core/network/alert/pom.xml/dom4j:dom4j/open
but we do not even use it, so let's just remove it

Remove unused dom4j

---

pom.xml

Upgrade library postgresql:postgresql from 42.2.13 to 42.2.14
https://issues.openmrs.org/browse/TRUNK-5553

TRUNK-5553:Upgrade postgresql:postgresql

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml

Updated the sequence values to correct ones.
see https://issues.openmrs.org/browse/TRUNK-5901

TRUNK-5901 Error scheduling task via SysAdmin OWA on PostgreSQL

---

pom.xml

Also refactors Lucene to use a property.
@teleivo I don't know if this is the best way to document the dependencies. Please let me know what you think!

Add some notes on dependencies

---

web/src/test/java/org/openmrs/web/filter/update/UpdateFilterModelTest.java

TRUNK-5817: Migrate web and webapp package tests to Junit 5(UpdateFilterModelTest)

---

web/pom.xml

TRUNK-5817: Migrate web and webapp package tests to Junit 5(Exclusion of Powermock)

---

web/src/test/java/org/openmrs/web/test/jupiter/BaseModuleWebContextSensitiveTest.java

TRUNK-5817 Migrate web and webapp package tests to Junit 5(BaseModuleWebContextSensitiveTest)

---

api/pom.xml
pom.xml
test/pom.xml
web/pom.xml

TRUNK-5818 Enable module devs to write Junit 4 & 5 tests

---

api/src/test/resources/org/openmrs/api/db/hibernate/include/HibernateAlertDAOTestDataSet.xml

see https://issues.openmrs.org/browse/TRUNK-5914

TRUNK-5914:  openmrs-core tests currently failing

---

liquibase/pom.xml
pom.xml

Bump liquibase

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateSerializedObjectDAO.java

Changed like to eq.
see https://issues.openmrs.org/browse/TRUNK-5917

TRUNK-5917 Boolean Like comparison not allowed in PostgreSQL

---

api/src/main/java/liquibase/ext/datatype/core/PostgreSQLBlobType.java

PostgreSQL provides two types to handle binary large data which are oid and bytea. Liquibase maps columns of type longblob to type bytea in PostgreSQL but Hibernate maps java.sql.Blob type to oid in PostgreSQL. For consistency with Hibernate ORM we need to map longblob to oid type. If we don't do this then an error is raised when exporting metadata with logs: https://pastebin.com/3uWyi7eV . 
see https://issues.openmrs.org/browse/TRUNK-5921
added all formatting changes …

TRUNK-5921 Custom longblob type for PostgreSQL

---

pom.xml

Reverts openmrs/openmrs-core#3448

Revert "maven(deps): bump hibernate-validator from 5.4.0.Final to 6.1.5.Final"

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java

Problem is presence of orderby does not affect aggregate function in mysql but in postgresql it does. So whereever you are counting you need to remove order clause in criteria. The SQL query that gets executed is :
select count(*) as y0_ from visit this_ where this_.patient_id=? and not exists (select 1 from encounter where this_.visit_id=visit_id) and this_.voided=? order by this_.date_started desc, this_.visit_id desc
So had to remove order by clause and there is no direct way to get rid of it. I referred https://stackoverflow.com/questions/2370221/remove-dynamically-an-ordering-to-the-result-set-in-org-hibernate-criteria  
see https://issues.openmrs.org/browse/TRUNK-5807
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the …

TRUNK-5807, Exception thrown in console on saving Patient in PostgreSQL

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java

I deleted two unused local variables, corrected four invalid JavaDoc links, and removed two outdated JavaDoc links.
see https://issues.openmrs.org/browse/TRUNK-5939

TRUNK-5939: Remove unused variable and correct JavaDoc links

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneQuery.java
api/src/main/java/org/openmrs/util/ThreadSafeCircularFifoQueue.java

I deleted empty statements.
see https://issues.openmrs.org/browse/TRUNK-5938

TRUNK-5938: Remove empty statements

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateAdministrationDAO.java

Added batch execution
see https://issues.openmrs.org/browse/TRUNK-5927

Trunk 5927 Removed liquibase dependency for sequence update

---

api/src/main/java/org/openmrs/module/ModuleClassLoader.java
api/src/main/java/org/openmrs/util/HandlerUtil.java

see https://issues.openmrs.org/browse/TRUNK-5942

TRUNK-5942 Adding curly braces to Control structures

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java

see https://issues.openmrs.org/browse/TRUNK-5956
- [x ] All new and existing **tests passed**. …

TRUNK-5956: Removed redundant Boolean literals

---

api/src/main/java/org/openmrs/util/OpenmrsUtil.java
webapp/src/main/webapp/WEB-INF/web.xml

I changed the `getFileMimeType()` to `getFileMimeType(File file)` in the OpenmrsUtil class and made changes to other classes to use the same by swapping the line `String mimeType = getServletContext().getMimeType(f.getName());` to this:
`String mimeType = OpenmrsUtil.getFileMimeType(f);`
Issue I worked on
https://issues.openmrs.org/browse/TRUNK-5898

TRUNK-5898:Add suppose for JSON MIME Type

---

api/src/main/java/org/openmrs/validator/AlertValidator.java
api/src/test/java/org/openmrs/validator/AlertValidatorTest.java

Trunk-5132: setting condition for null AlertValidator message check consistency just as that of EncounterValidator and making it readable
see https://issues.openmrs.org/browse/TRUNK-5132
No? -> figure out why and add the fix to …

TRUNK-5132:AlertValidator throws NotReadablePropertyException given null

---

webapp/src/main/webapp/WEB-INF/web.xml

Fixed the Javascript with a valid MIME mapping on the web.xm.
https://issues.openmrs.org/browse/TRUNK-5712

TRUNK-5898: Add suppose for JSON MIME Type

---

api/src/main/java/org/openmrs/BaseChangeableOpenmrsData.java
api/src/main/java/org/openmrs/BaseChangeableOpenmrsMetadata.java
api/src/main/java/org/openmrs/ConceptSource.java

I removed methods that can be inherited.
see https://issues.openmrs.org/browse/TRUNK-5958

TRUNK-5958: Overriding methods should do more than simply call the same method in the super class

---

api/src/main/java/org/openmrs/obs/handler/ImageHandler.java
api/src/test/java/org/openmrs/obs/ImageHandlerTest.java

I added a ByteArrayInputStream to provide images as byte arrays.
https://issues.openmrs.org/browse/TRUNK-5737

TRUNK-5737: ImageHandler to support saving from byte arrays.

---

api/src/main/resources/liquibase-update-to-2.3.xml

TRUNK-5821

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.3.x.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml

https://issues.openmrs.org/browse/TRUNK-5821

---

api/src/main/java/org/openmrs/api/context/Context.java
api/src/main/java/org/openmrs/util/MemoryAppender.java

see https://issues.openmrs.org/browse/TRUNK-5955
- [] I have **added tests** to cover my changes. (If you refactored
- [x ] All new and existing **tests passed**.
No? -> figure out why and …

TRUNK-5955 Modifiers should be declared in the correct order

---

api/pom.xml
liquibase/pom.xml
pom.xml
test/pom.xml
tools/pom.xml
web/pom.xml
webapp/pom.xml

link:https://issues.openmrs.org/browse/TRUNK-5965

TRUNK-5965:Upgrade core to 2.5.0-SNAPSHOT

---

pom.xml

This pull request removes a hard-coded version of a dependency.
There is no issue for this change, please c.f. https://github.com/openmrs/openmrs-core/pull/3519#issuecomment-677817199
- [ x ] I ran `mvn clean package` right before creating this pull request and
- [ x ] All new and existing **tests passed**.
- [ x ] My pull request is **based on the latest changes** of the master branch.

WOLF-123 use variable instead of hard-coded version

---

api/pom.xml
pom.xml
test/pom.xml
tools/pom.xml
web/pom.xml
webapp/pom.xml

I upgraded openmrs core 2.2.0 branch from version2.3.0-SNAPSHOT to 2.3.3-SNAPSHOT
https://issues.openmrs.org/browse/TRUNK-5966

TRUNK-5966:Correct next development version for 2.3.x branch

---

api/src/main/java/liquibase/ext/change/core/InsertWithUuidDataChange.java

I simplified the if condition.
see https://issues.openmrs.org/browse/TRUNK-5932

TRUNK-5932: Case insensitive string comparisons should be made without intermediate upper or lower casing

---

api/src/main/java/liquibase/ext/sqlgenerator/core/ModifyColumnGenerator.java
web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java

I have simplified returning a value.
see https://issues.openmrs.org/browse/TRUNK-5933

TRUNK-5933: Return of boolean expressions should not be wrapped into an "if-then-else" statement

---

api/src/main/java/liquibase/ext/sqlgenerator/core/ModifyColumnGenerator.java
api/src/main/java/org/openmrs/util/MemoryAppender.java
api/src/main/java/org/openmrs/util/ThreadSafeCircularFifoQueue.java
api/src/main/java/org/openmrs/validator/UserValidator.java

I merged "if" statements.
see https://issues.openmrs.org/browse/TRUNK-5934

TRUNK-5934: Collapsible "if" statements should be merged

---

api/src/main/java/org/openmrs/liquibase/ChangeLogDetective.java

I changed the variable name according to the convention.
see https://issues.openmrs.org/browse/TRUNK-5937

TRUNK-5937: Local variable name should comply with a naming convention

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePatientDAO.java
api/src/main/java/org/openmrs/obs/handler/AbstractHandler.java

I deleted unnecessary temporary variables.
see https://issues.openmrs.org/browse/TRUNK-5957

TRUNK-5957: Local variables should not be declared and then immediately returned

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/PersonLuceneQuery.java
api/src/main/java/org/openmrs/api/db/hibernate/search/LuceneQuery.java
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.4.x.xml
api/src/test/java/org/openmrs/api/PersonServiceTest.java
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java

This PR is a successor of https://github.com/openmrs/openmrs-core/pull/3152 now targeting the 3 names component as well.  Please have a look to is before starting the review.
A discussion emerges in in case you need more details regarding the implementation strategy: https://talk.openmrs.org/t/soundex-search-in-lucenequeries/26068/37?u=fruether
@ibacher In case you start testing may use this PR since it as well contains the 3-names search functionality.
see https://issues.openmrs.org/browse/TRUNK-5746
No? -> write tests and add them to this commit …

TRUNK-5746: Refactor getSimilar to use Lucene for 3 names

---

api/src/main/java/org/openmrs/util/OpenmrsUtil.java

see https://issues.openmrs.org/browse/TRUNK-5969

TRUNK-5969: Wrong default directory on Windows

---

api/src/test/java/org/openmrs/api/db/PatientDAOTest.java

link:https://issues.openmrs.org/browse/TRUNK-3253
Added junit test for searching on voided patients

TRUNK-3253: Add junit test for searching on voided patients

---

web/src/main/java/org/openmrs/web/Listener.java

Removed the old 'hacky' code and some comments related to it.
see https://issues.openmrs.org/browse/TRUNK-5177
No? …

TRUNK-5177: Removed pre ServletContext.getContextPath() code

---

api/src/main/java/org/openmrs/Concept.java
api/src/test/java/org/openmrs/ConceptTest.java

see https://issues.openmrs.org/browse/TRUNK-5382

TRUNK-5382: Extra utility method for excluding retired concepts while fetching setmembers

---

api/src/main/java/org/openmrs/Condition.java
api/src/main/java/org/openmrs/Encounter.java
api/src/test/java/org/openmrs/EncounterTest.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java

see https://issues.openmrs.org/browse/TRUNK-5970

TRUNK-5970: Encounter to handle voided conditions.

---

api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java
api/src/test/java/org/openmrs/test/jupiter/BaseContextSensitiveTest.java

https://issues.openmrs.org/browse/TRUNK-5980
cc @mks-d @dkayiwa

TRUNK-5980: BaseContextSensitiveTest to allow further protected overrides.

---

liquibase/pom.xml
pom.xml
test/pom.xml

hamcrest as of 2.x ships what was previously in hamcrest-core and
hamcrest-library in a single jar at artifact coordinate
org.hamcrest:hamcrest
So as of 2.x you only need to depend on the org.hamcrest:hamcrest.
Since JUnit 4 depends on hamcrest-core we need to follow these steps
http://hamcrest.org/JavaHamcrest/distributables#upgrading-from-hamcrest-1x
https://github.com/hamcrest/JavaHamcrest/issues/224#issuecomment-449760045
to make sure also hamcrest-core is updated. The dependency on
hamcrest-core can be removed once JUnit 4 support is dropped.
see https://issues.openmrs.org/browse/TRUNK-5982
existing code …

TRUNK-5982 Adapt to new hamcrest packaging

---

api/src/test/java/org/openmrs/test/BaseContextMockTest.java
api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java
api/src/test/java/org/openmrs/test/BaseModuleContextSensitiveTest.java
api/src/test/java/org/openmrs/test/StartModuleExecutionListener.java
web/src/test/java/org/openmrs/web/test/BaseModuleWebContextSensitiveTest.java

see https://issues.openmrs.org/browse/TRUNK-5844

TRUNK-5844 Deprecate Junit 4 helpers

---

pom.xml

spring provides a bill of materials that already manages all the
artifacts released under springframework. This ensures versions are kept
in sync. Exclusions cannot be stated in an import so they have to be
provided explicitly.
see https://issues.openmrs.org/browse/TRUNK-5981
No? Unsure? …

TRUNK-5981 Manage spring dependencies via spring BOM

---

api/pom.xml
liquibase/pom.xml
pom.xml
test/pom.xml
tools/pom.xml
web/pom.xml
webapp/pom.xml

link:https://issues.openmrs.org/browse/TRUNK-5983

TRUNK-5983:Upgrade core in 2.4.x to 2.4.1-SNAPSHOT

---

pom.xml

Reverts openmrs/openmrs-core#3678

Revert "maven(deps-dev): bump mysql-connector-java from 8.0.22 to 8.0.23"

---

api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
api/src/main/java/org/openmrs/customdatatype/datatype/DateDatatype.java
api/src/main/java/org/openmrs/module/Extension.java
api/src/main/java/org/openmrs/module/ModuleFactory.java
api/src/main/java/org/openmrs/module/ModuleFileParser.java
api/src/main/java/org/openmrs/util/AttributableDate.java
api/src/test/java/org/openmrs/module/ModuleFileParserUnitTest.java
web/src/main/java/org/openmrs/web/filter/initialization/InitializationWizardModel.java

**Pull request title**
TRUNK-5936:Constant names should comply with a naming convention
**Jira Issue Number: Jira Issue Title**
TRUNK-5936:Constant names should comply with a naming convention
**Description of what I changed**
Rename all constants according to a naming convention
**Issue I worked on**
https://issues.openmrs.org/browse/TRUNK-5936 …

TRUNK-5936:Constant names should comply with a naming convention

---

api/src/main/java/org/openmrs/util/OpenmrsUtil.java

Add javadoc to getMemoryAppender()

---

api/src/main/java/org/openmrs/scheduler/SchedulerUtil.java
web/src/main/java/org/openmrs/module/web/WebModuleUtil.java

I've tracked down a couple of places where its possible for OpenMRS to try to get the `SchedulerService` even though the `SchedulerService` has either been evicted from the cache of services or not yet been started. I'm not sure this is all of them, but hopefully this should quite down those errors.
see https://issues.openmrs.org/browse/TRUNK-5994 …

TRUNK-5994: Scheduler Service occasionally logs an error during startup or shutdown

---

README.md

Updated links in the [Developer Guidelines](https://github.com/openmrs/openmrs-core#developer-guides) section
see https://issues.openmrs.org/browse/TRUNK-5995

TRUNK-5995: Update developer guidelines links

---

api/src/main/java/org/openmrs/util/OpenmrsUtil.java

Simplify OpenmrsUtil.isStringInArray method by returning true immediately when found matching string
see https://issues.openmrs.org/browse/TRUNK-5850

TRUNK-5850: Simplify the code of the OpenmrsUtil class

---

api/src/main/java/org/openmrs/api/impl/DiagnosisServiceImpl.java

Simplify DiagnosisServiceImpl.getUniqueDiagnoses method by replacing while loop with Collection.removeIf
see https://issues.openmrs.org/browse/TRUNK-5859

TRUNK-5859: Simplify the DiagnosisServiceImpl class code

---

api/src/main/java/org/openmrs/util/HttpClient.java

A simple method extraction applied to lower the complexity of the code.
see https://issues.openmrs.org/browse/TRUNK-5668
This is a simple method extraction so I have not added new tests.

TRUNK-5668 Improve complexity of 'post' method

---

api/src/main/java/org/openmrs/module/ModuleClassLoader.java
api/src/main/java/org/openmrs/util/OpenmrsUtil.java
api/src/test/java/org/openmrs/obs/ImageHandlerTest.java
api/src/test/java/org/openmrs/obs/MediaHandlerTest.java
web/src/main/java/org/openmrs/web/Listener.java
web/src/main/java/org/openmrs/web/filter/initialization/TestInstallUtil.java
web/src/test/java/org/openmrs/module/web/WebModuleUtilTest.java
web/src/test/java/org/openmrs/web/test/WebModuleActivatorTest.java

I have replaced instances of File.separatorChar and System.getProperty("file.separator") by utilizing the Paths and Path classes within Java. 
**note that I failed to make a change in one file located in this directory: api/src/test/java/org/openmrs/OpenmrsTestsTest.java
https://issues.openmrs.org/browse/TRUNK-5134
- [ X] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [X ] I have **added tests** to cover my changes. (If you refactored
------------------------> …

TRUNK-5134: Replace path constructions using separator char

---

api/src/main/java/org/openmrs/api/impl/EncounterServiceImpl.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java

TRUNK-5996:  Orders are not correctly voided when an Encounter is voided

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/PersonLuceneQuery.java
api/src/test/java/org/openmrs/api/PersonServiceTest.java

This PR is part of a series of commits that wants to enable the Soundex search for Lucene queries within Person search. In this PR I am going to change one of the previous refactorings to use lucene scores.  This dicussion regarding the changes can be found on Talk
https://talk.openmrs.org/t/soundex-search-in-lucenequeries/26068/56
see https://issues.openmrs.org/browse/TRUNK-5974
No? -> figure out …

TRUNK-5974 - Use of lucene score for two name queries

---

api/src/main/java/org/openmrs/api/impl/LocationServiceImpl.java

TRUNK-6003: Make getLocationsByTag method null safe

---

api/src/main/java/org/openmrs/api/db/PersonDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
api/src/main/java/org/openmrs/api/impl/PersonServiceImpl.java
api/src/test/java/org/openmrs/api/db/PersonDAOTest.java

… if "searchable" property is saved

TRUNK-6007

---

api/src/main/java/org/openmrs/util/DatabaseUpdater.java
api/src/main/java/org/openmrs/util/DatabaseUtil.java
api/src/test/java/org/openmrs/test/MigrateDataSet.java
api/src/test/java/org/openmrs/util/H2DatabaseIT.java
api/src/test/java/org/openmrs/util/databasechange/ValidateHibernateMappingsDatabaseIT.java
web/src/main/java/org/openmrs/web/filter/initialization/DatabaseDetective.java
web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java

Removes uses of `Class.forName()` to instantiate JDBC drivers.
see https://issues.openmrs.org/browse/TRUNK-6009

TRUNK-6009: Remove use of Class.forName() to load db drivers

---

api/src/main/java/org/openmrs/util/Reflect.java

Simplified Reflect.getInheritedFields method by using Collection.removeIf
see https://issues.openmrs.org/browse/TRUNK-5851

TRUNK-5851: Simplify the Reflect class code

---

api/src/main/java/org/openmrs/liquibase/ChangeLogVersionFinder.java

TRUNK-5856: Simplify ChangeLogVersionFinder.getSnapshotCombinations method by using ArrayList constructor with parameter
see https://issues.openmrs.org/browse/TRUNK-5856

TRUNK-5856: Simplification of the ChangeLogVersionFinder class code

---

api/src/main/java/org/openmrs/PatientProgram.java
api/src/main/java/org/openmrs/api/context/ServiceContext.java
api/src/main/java/org/openmrs/api/db/ProgramWorkflowDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateProgramWorkflowDAO.java
api/src/main/java/org/openmrs/layout/LayoutTemplate.java
api/src/main/java/org/openmrs/util/UpgradeUtil.java
api/src/main/java/org/openmrs/util/databasechange/DuplicateEncounterRoleNameChangeSet.java
api/src/main/java/org/openmrs/util/databasechange/DuplicateEncounterTypeNameChangeSet.java
api/src/main/java/org/openmrs/util/databasechange/DuplicateLocationAttributeTypeNameChangeSet.java
api/src/test/java/liquibase/ext/change/core/InsertWithUuidDataChangeDatabaseIT.java
api/src/test/java/org/openmrs/logic/result/ResultTest.java
api/src/test/java/org/openmrs/serialization/SimpleXStreamSerializerTest.java
liquibase/src/test/java/org/openmrs/liquibase/CoreDataTunerTest.java

Remove raw use of parameterized classes: List, LinkedHashSet, HashSet, Map, Set, Map.Entry
see https://issues.openmrs.org/browse/TRUNK-5848

TRUNK-5848: Remove raw use of parameterized class

---

api/src/main/java/org/openmrs/validator/PatientValidator.java
api/src/main/java/org/openmrs/validator/PersonValidator.java
api/src/test/java/org/openmrs/validator/PersonValidatorTest.java

https://issues.openmrs.org/browse/TRUNK-6012
Change the max age limit of 120 years to 140 years in openmrs-core
https://issues.openmrs.org/browse/TRUNK-6012

TRUNK-6012: Change the max age limit of 120 years to 140 years in openmrs-core

---

api/pom.xml
liquibase/pom.xml
pom.xml
test/pom.xml
tools/pom.xml
web/pom.xml
webapp/pom.xml

Updating Core Development Version  to 2.6.0-SNAPSHOT

---

api/src/main/java/org/openmrs/Location.java
api/src/main/resources/org/openmrs/api/db/hibernate/Location.hbm.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.5.x.xml
api/src/test/java/org/openmrs/api/LocationServiceTest.java
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java
api/src/test/resources/org/openmrs/api/include/LocationServiceTest-initialData.xml

Added `type` field with the type `Concept` to the `Location` class. 
see https://issues.openmrs.org/browse/TRUNK-6045

TRUNK-6045: Add `type` Concept field to Location

---

api/src/main/java/liquibase/ext/logging/slf4j/Slf4JLogService.java
api/src/main/java/liquibase/ext/logging/slf4j/Slf4JLogger.java
api/src/main/resources/META-INF/services/liquibase.logging.LogService

Restores logging messages from Liquibase to the OpenMRS log
see https://issues.openmrs.org/browse/TRUNK-6055

TRUNK-6055: Restore liquibase logging messages to the log

---

api/src/main/java/org/openmrs/util/OpenmrsUtil.java
api/src/test/java/org/openmrs/util/OpenmrsUtilTest.java

see https://issues.openmrs.org/browse/TRUNK-5482

TRUNK-5482 : Handled duplicates for Util method

---

api/src/main/java/org/openmrs/api/ConceptService.java
api/src/main/java/org/openmrs/api/impl/ConceptServiceImpl.java
api/src/test/java/org/openmrs/api/ConceptServiceTest.java
api/src/test/java/org/openmrs/api/UserServiceTest.java
api/src/test/resources/org/openmrs/include/standardTestDataset.xml

see https://issues.openmrs.org/browse/TRUNK-5655

TRUNK-5655: Added a utility method to get a Concept by it's identifier, name or map

---

api/src/main/java/org/openmrs/validator/UserValidator.java
api/src/main/resources/messages.properties
api/src/test/java/org/openmrs/validator/UserValidatorTest.java

TRUNK-6059 - UserValidator should ensure that email is unique

---

pom.xml
web/src/main/java/org/openmrs/web/filter/update/UpdateFilterModel.java

Reverts openmrs/openmrs-core#4000

Revert "maven(deps): bump springVersion from 5.2.14.RELEASE to 5.3.16"

---

.github/workflows/qa.yml

- [ x] My pull request is **based …

Rename event type from qa-initialSetup to qa

---

api/src/main/java/org/openmrs/api/UserService.java
api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/test/java/org/openmrs/api/UserServiceTest.java

Trunk 6069 24 x

---

api/src/main/java/org/openmrs/ConditionClinicalStatus.java

- Deprecated  HISTORY_OF 
- Added RECURRENCE, RELAPSE, REMISSION, RESOLVED
see https://issues.openmrs.org/browse/TRUNK-6039

TRUNK-6039: Diagnosis support for ConditionClinicalStatuses recurrence, relapse, remission, resolved

---

webapp/src/main/resources/log4j2.xml

PR against the 2.5.x branch.
See:  https://issues.openmrs.org/browse/TRUNK-6079

TRUNK-6079:  Suppress deprecation warnings from OpenMRS log

---

api/src/main/java/org/openmrs/api/db/hibernate/ImmutableObsInterceptor.java

TRUNK-6129: Explicitly allow Obs "groupMembers" to be mutable

---

api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java
api/src/test/java/org/openmrs/api/UserServiceTest.java
pom.xml

The host.url global property is inconsistent with usage in password reset API. This renames host.url to security.passwordResetUrl .
see https://issues.openmrs.org/browse/TRUNK-6066
I made the suggested changes proposed in the issue. BTW I am not sure from where a value gets set to [OpenmrsConstants#GP_HOST_URL](https://github.com/openmrs/openmrs-core/blob/8ae383b26d41d7714163315eb0c5e3555d7fb250/api/src/main/java/org/openmrs/util/OpenmrsConstants.java#L625).  Because its default value is "". 
https://github.com/openmrs/openmrs-core/blob/f469f2c5d501ccb5032618ccbb6e53c007838aab/api/src/main/java/org/openmrs/util/OpenmrsConstants.java#L709
However in the test [UserServiceTest#setUserActivationKey_shouldCreateUserActivationKey](https://github.com/openmrs/openmrs-core/blob/8486acd739bf92998e81 …

TRUNK-6066 Rename host.url global property

---

web/src/main/java/org/openmrs/web/Listener.java

See:  https://issues.openmrs.org/browse/TRUNK-6133
Interested in your thoughts on this PR @dkayiwa / @ibacher  / @mogoodrich

TRUNK-6133 - Expand Listener to implement HttpSessionListener

---

api/src/main/java/org/openmrs/PatientIdentifier.java

**Description of what I changed**
- Add @SortableField to identifier field
- This annotation allows the sort functionality on the "identifier" field from the PatientIdentifier.class
- JIRA card [https://bahmni.atlassian.net/browse/BAH-1947](https://bahmni.atlassian.net/browse/BAH-1947)
No? …

BAH-1947: Sort patient identifier in Lucene results

---

web/src/main/java/org/openmrs/web/Listener.java

Just tries to delay running any of the registered `HttpSessionListener`s until the context has been initialized. There's no `ApplicationContext` until setup is done, so there isn't much point. One thing this leaves hanging is that if Liquibase updates are needed, we'll still try to load `HttpSessionListener` before a context is available, but this is a rare occurrence and there's ultimately no actual harm done.
@mseaton Interested in your thoughts on this
see https://issues.openmrs.org/browse/TRUNK-6133
No? -> write tests and add them to this …

TRUNK-6133: Only run listeners after OpenMRS initialized

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java

This PR is against 2.5.x.  Will up-port to master if approved.

TRUNK-6147 - Secret question/answer are unusable after password change

---

api/pom.xml
pom.xml

see https://issues.openmrs.org/browse/TRUNK-6148

Packaging mail api implementation library into the war file

---

api/src/main/java/org/openmrs/logging/OpenmrsConfigurationFactory.java

TRUNK-6152 - Support multiple log4j2 configuration files

---

api/pom.xml
liquibase/pom.xml
pom.xml
test/pom.xml
tools/pom.xml
web/pom.xml
webapp/pom.xml

During the release of 2.6.0-snapshot, core version has been updated to 2.7.0 in the pom file. 

Replaced 2.6.0-SNAPSHOT to 2.7.0-SNAPSHOT

---

api/src/main/java/org/openmrs/api/impl/UserServiceImpl.java
api/src/main/java/org/openmrs/notification/mail/MailMessageSender.java

This PR was authored, and will be initially merged against, the 2.5.x branch.  We can then up-port it to 2.6.x+.

TRUNK-6153 - Email messages are not sent with correct from address

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateContextDAO.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java

This PR adds a global property setting to make the user lockout time configurable to suit various implementation requirements.
see https://issues.openmrs.org/browse/TRUNK-6158

TRUNK-6158: Making User lockout time configurable

---

api/src/main/resources/org/openmrs/module/dtd/config-1.5.dtd
api/src/main/resources/org/openmrs/module/dtd/config-1.6.dtd

Commas were missing in config-1.5.dtd and config-1.6.dtd files resulting in parsing exceptions. This PR adds the missing commas. 
see https://issues.openmrs.org/browse/TRUNK-6142

TRUNK-6142 Adding missing commas to dtd files

---

Dockerfile

hecksums` folder
see https://issues.openmrs.org/browse/TRUNK-6166

TRUNK-6166: OpenMRS Docker image to create a mountable 'configuration_checksums' folder.

---

pom.xml

TRUNK-6175: Update Version of Joda Time Library

---

api/src/main/java/org/openmrs/Order.java

TRUNK-6176:  Add two new Order.FulfillerStatus values

---

api/src/main/java/org/openmrs/Order.java

TRUNK-6176: Add two new Order.FulfillerStatus values

---

api/src/main/java/org/openmrs/api/context/UserContext.java
api/src/test/java/org/openmrs/api/context/ContextTest.java
api/src/test/java/org/openmrs/util/LocationUtilityTest.java

see https://issues.openmrs.org/browse/TRUNK-6179
Note:  This PR is against 2.5.x, and will be up-ported to all later versions once approved and committed.

TRUNK-6179 - Authenticating should not override chosen location

---

api/src/main/java/org/openmrs/api/context/Context.java
api/src/main/java/org/openmrs/api/context/UserContext.java
api/src/test/java/org/openmrs/api/UserServiceTest.java
api/src/test/resources/org/openmrs/api/include/UserServiceTest.xml
pom.xml

see https://issues.openmrs.org/browse/TRUNK-6180

TRUNK-6180: Add locale to context after authentication.

---

api/src/main/java/org/openmrs/api/context/ServiceContext.java
api/src/test/java/org/openmrs/api/context/ServiceContextTest.java

Fixed a bug where a non-existent class being passed when adding a module service to the ServiceContext caused a deadlock between threads. The reason for this is that when the ApiException was triggered due to a ClassNotFoundException inside the ServiceContext, the ApiException constructor was attempting to fetch the MessageSourceService from the ServiceContext. This resulted in the deadlock when it happened during a context refresh.
This PR fixes it by using a different overloaded method in the APIException class that does not rely on the MessageSourceService. 
see https://issues.openmrs.org/browse/TRUNK-6174 …

TRUNK-6174: ModuleService should not block context refresh when called incorrectly via Spring

---

web/src/main/java/org/openmrs/web/Listener.java

This commit updates the loadCsrfGuardProperties method to enhance the loading of CSRF Guard properties. It first checks for the existence of the csrfguard.properties file in the `.OpenMRS` directory. If the file exists, its contents are loaded. Otherwise, the default values are loaded from the `/WEB-INF/csrfguard.properties` file. Additionally, properties starting with `org.owasp.csrfguard` from `openmrs-runtime.properties` are merged into the loaded properties. 
see https://issues.openmrs.org/browse/TRUNK-6185
No? -> write tests and add them to …

TRUNK-6185: Easier configuration of csrfguard.properties

---

api/src/main/java/org/openmrs/api/ProviderService.java
api/src/main/java/org/openmrs/api/db/ProviderDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateProviderDAO.java
api/src/main/java/org/openmrs/api/impl/ProviderServiceImpl.java
api/src/main/java/org/openmrs/util/PrivilegeConstants.java
api/src/main/java/org/openmrs/validator/ProviderAttributeTypeValidator.java
api/src/test/java/org/openmrs/api/ProviderServiceTest.java
api/src/test/java/org/openmrs/validator/ProviderAttributeTypeValidatorTest.java

The implemented behavior in this commit is that; - when you create an attribute with a name "test", you cannot create another one with the same name not until you retire the first one. When you retire "test", you create a new one with the name "test" since the existing one has been retired.
This implementation i believed comes out of the discussion we had in the draft pull request at https://github.com/openmrs/openmrs-core/pull/4374 that i will close to pave way for this one.
Below is the implementation in video.
https://github.com/openmrs/openmrs-core/assets/47120265/a7615434-c936-4a4d-8f0a-6c9f27cbbfc1
see https://issues.openmrs.org/browse/TRUNK-6189
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the …

TRUNK-6189: Provider Service class should provide ability to getProviderAttributeTypeByName

---

api/src/main/resources/org/openmrs/module/dtd/config-1.7.dtd
api/src/test/java/org/openmrs/module/dtd/ConfigXmlBuilder.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_0.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_1.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_2.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_3.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_4.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_5.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_6.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_7.java
web/src/main/java/org/openmrs/module/web/ModuleServlet.java
web/src/main/java/org/openmrs/module/web/WebModuleUtil.java
web/src/test/java/org/openmrs/module/web/WebModuleUtilTest.java

This PR introduces the ability for modules to define servlet initialization parameters within their config.xml. The key changes and enhancements include:
- **Support for Initialization Parameters**: Modules can now define initialization parameters for servlets in their config.xml.
- **DTD Updates**: The Document Type Definition (DTD) has been updated to accommodate the changes and provide validation.
- **Testing Improvements**:
- **Local DTDs for Testing**: Previously, our DTD tests relied on the server's DTDs. This approach posed challenges, especially when needing to update both the DTD and its corresponding tests in a single PR. This PR transitions the tests to use the DTDs stored in version control, ensuring consistency and ease of updates.
- **New Tests**: Tests have been added to:
- …

TRUNK-4673 Add support for init parameters for module servlets

---

api/src/main/java/org/openmrs/module/ModuleFileParser.java
api/src/test/java/org/openmrs/module/ModuleFileParserTest.java

After config.xml dtd version 1.7 it was missing from ModuleFileParser. See comment - https://github.com/openmrs/openmrs-core/pull/4415#issuecomment-1773936880
see https://issues.openmrs.org/browse/TRUNK-4673

TRUNK-4673 Add missing valid config.xml version

---

api/src/main/java/org/openmrs/liquibase/ChangeLogVersions.java
api/src/main/resources/liquibase-core-data.xml
api/src/main/resources/liquibase-schema-only.xml
api/src/main/resources/liquibase-update-to-latest.xml
api/src/main/resources/org/openmrs/liquibase/snapshots/core-data/liquibase-core-data-2.6.x.xml
api/src/main/resources/org/openmrs/liquibase/snapshots/schema-only/liquibase-schema-only-2.6.x.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.7.x.xml
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java

I added platform 2.6.x liquibase snapshot files
see https://issues.openmrs.org/browse/TRUNK-6207

TRUNK-6207: created platform 2.6 liquibase snapshot files

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateCohortDAO.java
api/src/test/java/org/openmrs/api/CohortServiceTest.java
api/src/test/resources/org/openmrs/api/include/CohortServiceOrderingTest-cohort.xml

This task is to migrate the deprecated hibernate criteria to jpa criteria for the `HibernateCohortDAO` class.
Additionally, I've incorporated several new tests and confirmed their compatibility with the existing Hibernate Criteria implementation.
I also created an additional XML to add some tests for result order validation, trying to change some of the Cohort names in the current xml failed a lot of tests so seemed more risky than creating a new xml for this purpose.
see https://issues.openmrs.org/browse/TRUNK-6202 
No? -> write tests and add …

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateCohortDAO

---

api/src/main/java/org/openmrs/layout/name/NameSupport.java
api/src/main/java/org/openmrs/util/OpenmrsConstants.java
api/src/test/java/org/openmrs/layout/name/NameTemplateTest.java
api/src/test/resources/org/openmrs/include/nameSupportTestDataSet.xml

Back-ported to 2.6.x from master commit, https://github.com/openmrs/openmrs-core/commit/7dec4a7d7190b0c7a74170e869a81c08c61fc6bd
see https://openmrs.atlassian.net/browse/TRUNK-6192

TRUNK-6192: NameSupport.java to provide for NameTemplate overriding via a GP

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateConditionDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateConditionDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateConditionDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateContextDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateUtil.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateContextDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateContextDAO 

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateDatatypeDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateDatatypeDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateDatatypeDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOpenmrsDataDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateOpenmrsDataDAO class. There is no usages of this class in core and no tests. As it has no bean or other setup I wasn't sure how to go about adding tests to it …

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateOpenmrsDataDAO

---

api/src/main/java/org/openmrs/api/impl/AdministrationServiceImpl.java
api/src/test/java/org/openmrs/api/AdministrationServiceTest.java

see https://issues.openmrs.org/browse/TRUNK-6206

TRUNK-6206: Global property specific privileges

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOpenmrsMetadataDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateOpenmrsMetadataDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateOpenmrsMetadataDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOpenmrsObjectDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateOpenmrsObjectDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateOpenmrsObjectDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateMedicationDispenseDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateMedicationDispenseDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateMedicationDispenseDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateSerializedObjectDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateSerializedObjectDAO class. The tests for it seem to be disabled with this annotation:
```
@Disabled("TRUNK-4704 Serialization.xstream module must be fixed to work with Hibernate 4")
@StartModule( { "org/openmrs/api/db/include/serialization.xstream-0.2.8-SNAPSHOT.omod" })
public class SerializedObjectDAOTest extends BaseContextSensitiveTest {
```
That ticket is closed so I am not sure what needs done to enable these tests.
existing code that was well tested you do not have to …

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateSerializedObjectDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderSetDAO.java
api/src/test/java/org/openmrs/api/OrderSetServiceTest.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateOrderSetDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateOrderSetDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateUserDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateUserDAO class

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateUserDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateVisitDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateVisitDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateVisitDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateProgramWorkflowDAO.java
api/src/test/java/org/openmrs/api/ProgramWorkflowServiceTest.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateProgramWorkflowDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateProgramWorkflowDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java
api/src/test/java/org/openmrs/api/FormServiceTest.java
api/src/test/java/org/openmrs/api/db/hibernate/HibernateFormDAOTest.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateFormDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateFormDAO

---

api/src/main/java/org/openmrs/scheduler/db/hibernate/HibernateSchedulerDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateSchedulerDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateSchedulerDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderDAO.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateOrderDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateOrderDAO

---

api/src/main/java/org/openmrs/notification/db/hibernate/HibernateAlertDAO.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateAlertDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateAlertDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateOrderSetDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernatePersonDAO.java
api/src/test/java/org/openmrs/api/db/hibernate/HibernatePersonDAOTest.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernatePersonDAOclass.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernatePersonDAO

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateObsDAO.java
api/src/test/java/org/openmrs/api/db/hibernate/HibernateObsDAOTest.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateObsDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateObsDAO

---

web/src/main/java/org/openmrs/web/Listener.java
web/src/main/java/org/openmrs/web/filter/StartupFilter.java

see https://issues.openmrs.org/browse/TRUNK-6198

TRUNK-6198: Add a REST endpoint to check status of the platform(backporting)

---

api/src/main/java/org/openmrs/api/db/hibernate/HibernateEncounterDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateFormDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/PatientSearchCriteria.java
api/src/main/java/org/openmrs/api/db/hibernate/PersonSearchCriteria.java
api/src/main/java/org/openmrs/api/db/hibernate/QueryResult.java
api/src/test/java/org/openmrs/api/EncounterServiceTest.java
api/src/test/java/org/openmrs/api/db/hibernate/PatientSearchCriteriaTest.java

This task is to migrate the deprecated hibernate criteria to jpa criteria for the HibernateEncounterDAO class.

TRUNK-6202 Replace Hibernate Criteria API with JPA for HibernateEncounterDAO

---

pom.xml

This is a followup commit in order to fix the failing test on the 2.6.x branch
see https://issues.openmrs.org/browse/TRUNK-6216

TRUNK-6216: Change apache-commons-lang3 version to 3.14.0

---

api/src/main/java/org/openmrs/module/ModuleUtil.java
web/src/main/java/org/openmrs/module/web/WebModuleUtil.java

See the issue
see https://issues.openmrs.org/browse/TRUNK-6226

TRUNK-6226: Fix potential zip-slips

---

pom.xml

see https://issues.openmrs.org/browse/TRUNK-5725

TRUNK-5725: upgrading hibernate validator from 5.4.3 to 6.1.2

---

api/src/main/java/org/openmrs/ConceptNumeric.java
api/src/main/java/org/openmrs/ConceptProposal.java
api/src/main/java/org/openmrs/ConceptStateConversion.java
api/src/main/java/org/openmrs/ConceptStopWord.java
api/src/main/java/org/openmrs/TestOrder.java
api/src/main/java/org/openmrs/api/db/ClobDatatypeStorage.java
api/src/main/java/org/openmrs/api/db/SerializedObject.java
api/src/main/java/org/openmrs/hl7/HL7InArchive.java
api/src/main/java/org/openmrs/hl7/HL7InError.java
api/src/main/java/org/openmrs/hl7/HL7InQueue.java
api/src/main/java/org/openmrs/hl7/HL7Source.java
api/src/main/java/org/openmrs/notification/Template.java
api/src/main/java/org/openmrs/scheduler/TaskDefinition.java

Enabled logging for several tables that were not included in the previous [PR](https://github.com/openmrs/openmrs-core/commit/2111f62acc036525fbf45b4e7b1f864503cad940)
Added @NotAudited to the `scheduler_task_config_property` table as it is similar to the `user_properties` table.
see https://openmrs.atlassian.net/browse/OMRS-131  …

OMRS-131: Detailed Audit Logging (Updated)

---

api/src/main/java/org/openmrs/api/context/Context.java
api/src/main/java/org/openmrs/api/db/ContextDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateContextDAO.java
api/src/test/java/org/openmrs/api/context/ContextTest.java

see https://issues.openmrs.org/browse/TRUNK-6047

TRUNK-6047: Add utility methods to invalidate database caches

---

api/src/main/java/org/openmrs/api/impl/PatientServiceImpl.java
api/src/main/java/org/openmrs/person/PersonMergeLogData.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java
api/src/test/java/org/openmrs/api/PersonServiceTest.java

TRUNK-6247: Merging Patients should not copy Patient Programs on "losing" patients

---

startup-init.sh

see https://openmrs.atlassian.net/browse/O3-3428

O3-3428: Update the DockerFile to support openmrs_spa

---

web/src/main/resources/openmrs-servlet.xml

Resolve 3.4.1

---

api/src/main/resources/org/openmrs/module/dtd/config-1.6.dtd
api/src/main/resources/org/openmrs/module/dtd/config-1.7.dtd

editing config-1.6 and config-1.7 to correct the specifications for conditionally loaded modules
Cc. @mseaton @ibacher 

TRUNK-6241: Fix DTD for conditional modules

---

api/src/main/java/org/openmrs/Concept.java
api/src/test/java/org/openmrs/ConceptTest.java

see: https://openmrs.atlassian.net/browse/TRUNK-6265

TRUNK-6265: Bugs in Concept.getPreferredName(Locale) method

---

api/src/main/java/org/openmrs/api/context/UserContext.java

This fixes the ConcurrentModificationException thrown in [UserContext.hasPrivilege](https://github.com/openmrs/openmrs-core/blob/117b775acf0bc7792eecb90819f9b81ecc17665b/api/src/main/java/org/openmrs/api/context/UserContext.java#L325) method.
see https://openmrs.atlassian.net/browse/TRUNK-6267 …

TRUNK-6267: Fixing the java.util.ConcurrentModificationException on hasPrivilege method

---

api/src/main/java/org/openmrs/ConceptNumeric.java
api/src/test/java/org/openmrs/ConceptNumericTest.java

- Setting and saving concept reference ranges in the same order as the user added
see https://openmrs.atlassian.net/browse/TRUNK-6268

TRUNK-6245: Saving concept reference ranges in order

---

api/src/main/java/org/openmrs/BaseCustomizableMetadata.java
api/src/main/java/org/openmrs/BaseFormRecordableOpenmrsData.java
api/src/main/java/org/openmrs/BaseOpenmrsData.java
api/src/main/java/org/openmrs/BaseOpenmrsMetadata.java
api/src/main/java/org/openmrs/BaseOpenmrsObject.java
api/src/main/java/org/openmrs/BaseReferenceRange.java
api/src/main/java/org/openmrs/attribute/BaseAttribute.java
api/src/main/java/org/openmrs/attribute/BaseAttributeType.java

This is an extension of https://github.com/openmrs/openmrs-core/pull/4620

TRUNK-6267: Making Mapped Supper Classes Auditable

---

api/src/main/java/org/openmrs/api/context/UserContext.java

Same fix as [this one](https://github.com/openmrs/openmrs-core/pull/4771), applied on the master branch.
see https://issues.openmrs.org/browse/TRUNK-6259

TRUNK-6259: fix concurrency issue when checking privileges

---

api/src/main/resources/hibernate.default.properties

Switched from MyIASM to InnoDB.  Hibernate doesn't use InnoDB with MySQL5Dialect so updated the dialect to MySQL57Dialect.
see https://openmrs.atlassian.net/browse/TRUNK-6273

TRUNK-6273: Switching to MySQL InnoDB engine for hbm2ddl

---

pom.xml

Reverts openmrs/openmrs-core#4764

Revert "maven(deps): bump log4jVersion from 2.24.0 to 2.24.1"

---

pom.xml

Reverts openmrs/openmrs-core#4743

Revert "maven(deps): bump log4jVersion from 2.22.1 to 2.24.0"

---

api/src/main/java/org/openmrs/api/context/Daemon.java

Clears the `daemonThreadUser` thread-local when each daemon thread execution ends.
No clearing this value means that threads can hold onto a "stale" value for the "daemon user". This causes some tests to fail when the "stale" value now refers to a row that has been removed from the database. It's also, in general, not a good idea to hold a reference to a Hibernate object in a thread as this can hold references to, e.g., the Hibernate session that created the object, and an unnecessary underlying DB connection.
see https://issues.openmrs.org/browse/TRUNK-6275
existing code that was well tested you do not have to …

TRUNK-6275: Follow-on: clear daemonThreadUser when thread execution is done

---

api/src/main/java/org/openmrs/BaseOpenmrsMetadata.java
api/src/main/java/org/openmrs/LocationAttributeType.java
api/src/main/java/org/openmrs/ProviderAttributeType.java
api/src/main/java/org/openmrs/VisitAttributeType.java
api/src/main/java/org/openmrs/attribute/BaseAttributeType.java
api/src/main/resources/org/openmrs/api/db/hibernate/DiagnosisAttributeType.hbm.xml
api/src/main/resources/org/openmrs/api/db/hibernate/ProgramAttributeType.hbm.xml

see https://openmrs.atlassian.net/browse/TRUNK-6274

TRUNK-6274: Fix Issues with Hibernate Envers Audit Table Generation for Specific Tables

---

api/src/test/java/liquibase/ext/change/core/InsertWithUuidDataChangeDatabaseIT.java
api/src/test/java/org/openmrs/liquibase/ChangeLogDetectiveDatabaseIT.java
api/src/test/java/org/openmrs/test/Containers.java
api/src/test/java/org/openmrs/util/DatabaseIT.java
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java
api/src/test/java/org/openmrs/util/databasechange/ValidateHibernateMappingsDatabaseIT.java
web/src/test/java/org/openmrs/web/filter/initialization/DatabaseDetectiveIT.java

see https://openmrs.atlassian.net/browse/TRUNK-6275

TRUNK-6275: Adding MySQL and Postgres support to ValidateHibernateMappingsDatabaseIT test

---

api/pom.xml
liquibase/pom.xml
pom.xml
test/pom.xml
tools/pom.xml
web/pom.xml
webapp/pom.xml

Update the version to 2.8.0-SNAPSHOT

---

bamboo-specs/bamboo.yml

Adding maven.development.version and build.release.type variables to Bamboo

---

bamboo-specs/bamboo.yml

Reverts openmrs/openmrs-core#4816

Revert "Adding maven.development.version and build.release.type variables to Bamboo"

---

api/pom.xml
liquibase/pom.xml
pom.xml
test/pom.xml
tools/pom.xml
web/pom.xml
webapp/pom.xml

Changing the version back to 2.7.0-SNAPSHOT

---

api/src/main/java/org/openmrs/validator/VisitValidator.java
api/src/test/java/org/openmrs/validator/VisitValidatorTest.java
api/src/test/resources/org/openmrs/validator/include/VisitValidatorTest.xml

Currently, you can’t end a visit if there’s already an active overlapping visit. While the UI prevents this with the new overlap logic, there are situations where it could still happen, like:
1. An instance was originally set to allow overlapping visits, but later changed to disallow them.
2. Retrospective visit data from a database migration or another integration.
To handle these cases, it makes sense to allow ending active visits even if they overlap, **if and only if**:
1. The visit being ended is currently active, **and**
2. Its start date hasn’t been modified.
see https://issues.openmrs.org/browse/TRUNK-6278
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit …

TRUNK-6278: Skip visit overlap validation when ending a visit

---

api/src/main/java/org/openmrs/module/Module.java
api/src/main/java/org/openmrs/module/ModuleClassLoader.java
api/src/main/java/org/openmrs/module/ModuleFileParser.java
api/src/main/java/org/openmrs/validator/VisitValidator.java
api/src/main/resources/org/openmrs/module/dtd/config-2.0.dtd
api/src/test/java/org/openmrs/module/ModuleClassLoaderTest.java
api/src/test/java/org/openmrs/module/ModuleExtensionsTest.java
api/src/test/java/org/openmrs/module/ModuleFileParserTest.java
api/src/test/java/org/openmrs/module/ModuleUtilTest.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_0.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_1.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_2.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_3.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_4.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_5.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V1_6.java
api/src/test/java/org/openmrs/module/dtd/ModuleConfigDTDTest_V2_0.java
api/src/test/java/org/openmrs/validator/VisitValidatorTest.java
api/src/test/resources/org/openmrs/validator/include/VisitValidatorTest.xml
pom.xml

Updating the branch for the beta-release

---

bamboo-specs/bamboo.yml

Temporally removing unit tests

---

Dockerfile

Currently if you try to mount the `/openmrs/data/complex_obs` directory to an external volume OpenMRS will be unable to write to it resulting in permission denied error when saving complex obs. …

Create a default complex_obs directory in the Docker image to allow mounting of the directory

---

api/pom.xml
liquibase/pom.xml
pom.xml
test/pom.xml
tools/pom.xml
web/pom.xml
webapp/pom.xml

Changing the development version to 2.7.0-SNAPSHOT

---

api/src/main/java/org/openmrs/api/context/ServiceContext.java

see https://issues.openmrs.org/browse/TRUNK-6287

TRUNK-6287: Fix Exception Propagation Issue in ServiceContext.getRegisteredComponent Method

---

api/src/main/java/org/openmrs/api/context/ServiceContext.java

(cherry picked from commit f0910d4443bdaf2180662af55d33f36e925efda5)

TRUNK-6287: Fix Exception Propagation Issue in ServiceContext.getRegisteredComponent Method (#4843)

---

pom.xml

Bumps `jacksonVersion` from 2.18.1 to 2.18.2.
Updates `com.fasterxml.jackson.core:jackson-core` from 2.18.1 to 2.18.2
- [Commits](https://github.com/FasterXML/jackson-core/compare/jackson-core-2.18.1...jackson-core-2.18.2)
Updates `com.fasterxml.jackson.core:jackson-annotations` from 2.18.1 to 2.18.2
- [Commits](https://github.com/FasterXML/jackson/commits)
Updates `com.fasterxml.jackson.core:jackson-databind` from 2.18.1 to 2.18.2
- [Commits](https://github.com/FasterXML/jackson/commits)
Updates `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` from 2.18.1 to 2.18.2
---
updated-dependencies:
- dependency-name: com.fasterxml.jackson.core:jackson-core dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: …

maven(deps): bump jacksonVersion from 2.18.1 to 2.18.2 (#4853)

---

api/src/main/java/org/openmrs/module/Module.java

Module class: Change 'since' version from '2.8.0' to '2.7.0'

---

api/src/main/java/org/openmrs/module/Module.java

(cherry picked from commit 5995f82acc0c6b9b86d398590b78df34388f213d)

Module class: Change 'since' version from '2.8.0' to '2.7.0' (#4868)

---

Dockerfile

This is a PR to backport a fix (https://github.com/openmrs/openmrs-core/commit/30d6b74050309c451516d973de7bb5e8c3f6c860) merged into master but needed in 2.6.x as well.

Create a default complex_obs directory in the Docker image to allow mounting of the directory (#4845)

---

api/src/main/resources/org/openmrs/liquibase/snapshots/core-data/liquibase-core-data-2.5.x.xml

TRUNK-6292: Changes to Liquibase files breaks OpenMRS startup

---

api/src/main/java/org/openmrs/util/DatabaseUpdater.java
api/src/test/resources/org/openmrs/util/testLiquibase.xml

see https://openmrs.atlassian.net/browse/TRUNK-6295

TRUNK-6295 - Ensure correct resource accessor is used by DatabaseUpdater

---

api/src/test/java/org/openmrs/test/jupiter/BaseContextSensitiveTest.java

see https://issues.openmrs.org/browse/TRUNK-6297

TRUNK-6297 - Ensure H2 database is not closed unexpectedly early

---

api/src/main/java/org/openmrs/liquibase/ChangeLogVersions.java
api/src/main/resources/liquibase-core-data.xml
api/src/main/resources/liquibase-schema-only.xml
api/src/main/resources/liquibase-update-to-latest-from-1.9.x.xml
api/src/main/resources/org/openmrs/liquibase/snapshots/core-data/liquibase-core-data-2.7.x.xml
api/src/main/resources/org/openmrs/liquibase/snapshots/schema-only/liquibase-schema-only-2.7.x.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-2.8.x.xml
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java

see https://openmrs.atlassian.net/browse/TRUNK-6310

TRUNK-6310: Create platform 2.7 liquibase snapshot files

---

.github/workflows/build.yaml
pom.xml

This adds a profile to fix same errors we faced with Java 17: https://github.com/openmrs/openmrs-core/blob/ac9f17fe4108c6b5b66a38ad229c0ac60b180f25/pom.xml#L1106-L1110.
see https://openmrs.atlassian.net/browse/TRUNK-6311

TRUNK-6311: Add support for Java 21

---

api/src/main/java/org/openmrs/BaseOpenmrsMetadata.java
api/src/main/java/org/openmrs/PatientIdentifierType.java

Define the column definition of description in patient_identifier_type as "text"
see https://openmrs.atlassian.net/browse/TRUNK-6313

TRUNK-6313: Fix patient_identifer_type audit table generation

---

web/src/main/java/org/openmrs/web/Listener.java

see https://openmrs.atlassian.net/browse/TRUNK-6309

TRUNK-6309: Fix logging issue at Listener.java

---

web/src/main/java/org/openmrs/web/Listener.java

Remove unused imports in Listener.java

---

web/src/main/java/org/openmrs/web/Listener.java

see https://issues.openmrs.org/browse/TRUNK-6309

TRUNK-6309: Fix logging issue at Listener.java 

---

README.md
api/pom.xml
api/src/main/java/org/openmrs/api/db/hibernate/search/SearchAnalysis.java
api/src/main/java/org/openmrs/api/db/hibernate/search/elasticsearch/ElasticsearchConfig.java
api/src/main/java/org/openmrs/api/db/hibernate/search/lucene/LuceneConfig.java
api/src/main/resources/hibernate.default.properties
api/src/main/resources/org/openmrs/api/db/hibernate/search/elasticsearch/es-index-settings.json
api/src/test/java/org/openmrs/util/databasechange/ValidateHibernateMappingsDatabaseIT.java
docker-compose.es.yml
pom.xml
startup-init.sh
web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java

see https://issues.openmrs.org/browse/TRUNK-6301
- [ x] My pull request is **based on the latest changes** of the master branch.
No? Unsure? -> execute command `git …

TRUNK-6301 Add ElasticSearch backend for full text search

---

README.md

Fixed a minor typographical error in README.md. No functional changes.
This is a trivial fix. No JIRA ticket created as per OpenMRS guidelines for minor changes.
- [] I have **added tests** to cover my changes. (If you refactored
(Not applicable — documentation fix only)
No? Unsure? -> …

fixing typo on readme

---

api/src/main/resources/applicationContext-service.xml
api/src/test/java/org/openmrs/test/jupiter/BaseContextSensitiveTest.java
web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
web/src/test/java/org/openmrs/web/filter/initialization/InitializationFilterTest.java

This pull request updates the InitializationFilter to support automated setup by loading initialization properties from multiple sources, prioritizing:
- System properties (-D JVM arguments)
- Environment variables (with selective normalization)
- Installation script file (OPENMRS_INSTALLATION_SCRIPT)
- Added resolveInitializationProperties() to merge properties respecting source priority.
- Environment variable normalization: underscores (_) replaced with dots (.) except for specific keys like install_method.
- Maintained full backward compatibility with existing installation script setups.
- Improved logging to show merged properties during initialization (at DEBUG level).
see https://issues.openmrs.org/browse/TRUNK-6334 …

TRUNK-6334: Define PropertySource so properties can be specified via property file or system property

---

api/src/main/java/org/openmrs/api/ConceptService.java
api/src/main/java/org/openmrs/validator/ObsValidator.java
api/src/test/java/org/openmrs/api/impl/ConceptServiceImplTest.java
api/src/test/java/org/openmrs/validator/ObsValidatorTest.java

This changes most of the ObsValidator machinery to take account of the reference ranges defined on the concept itself as well as those that match person-specific criteria. The concept-defined reference range is only used in cases where no reference range is defined for a concept or no defined reference range matches for a specific patient.
I've slightly adjusted things so that we only try to valid concept reference ranges for numeric concepts. While there's probably something to be said for being able to define rule-based restrictions on non-numeric obs, ReferenceRanges remain a numeric-only concept.
This is targeted at 2.7.x, but will be forward-ported to 2.8.x.
see https://issues.openmrs.org/browse/TRUNK-6356 …

TRUNK-6356: Concept reference ranges should be taken into account

---

web/src/main/java/org/openmrs/web/filter/update/UpdateFilter.java

Keeps the user authenticated throughout the entire database update process.
see https://issues.openmrs.org/browse/TRUNK-6329

TRUNK-6329: Persist authentication during maintenance mode database updates

---

api/src/main/java/org/openmrs/api/cache/CacheConfig.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateSessionFactoryBean.java
api/src/main/resources/infinispan-api.xml

To add cache.stack system property in order to load desired jgroups config.  Also i have changed the Transport for the infinispan api cache due to the conflict it had with the hibernate cache. For more information see [here](https://openmrs.atlassian.net/browse/TRUNK-6348?focusedCommentId=152602)  . Also the default jgroups configs have port range hard coded to 0 and do not take the values from system property, so i had to change the value for the infinispan api  cache programatically. The user can give a port value for api cache through -Dcache.api_bind_port. If the user does not provide any binding port value for api cache, it defaults to (hibernate-cache-bind-port)+1.
https://openmrs.atlassian.net/browse/TRUNK-6365
##Testing
I tested this with the help of docker.
No? Unsure? -> …

TRUNK-6365: Add cache.stack system property for api and hibernate

---

api/src/main/resources/applicationContext-service.xml
api/src/test/java/org/openmrs/api/cache/CacheConfigTest.java
api/src/test/java/org/openmrs/api/cache/NonServiceTestBean.java
api/src/test/java/org/openmrs/api/cache/NonServiceTestBeanImpl.java
api/src/test/java/org/openmrs/api/cache/ServiceTestBean.java
api/src/test/java/org/openmrs/api/cache/ServiceTestBeanImpl.java
api/src/test/java/org/openmrs/api/context/DaemonTest.java
api/src/test/resources/TestingApplicationContext.xml
api/src/test/resources/cache-api.yaml
startup.sh

Updating changes from Rafal.

---

api/src/main/java/org/openmrs/api/ProviderService.java
api/src/main/java/org/openmrs/api/db/ProviderDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateProviderDAO.java
api/src/main/java/org/openmrs/api/impl/ProviderServiceImpl.java
api/src/test/java/org/openmrs/api/ProviderServiceTest.java
api/src/test/java/org/openmrs/api/db/hibernate/ProviderDAOTest.java
api/src/test/resources/org/openmrs/api/include/ProviderServiceTest-initial.xml

Implemented the `getProviderRole` method in `ProviderService`.
see https://openmrs.atlassian.net/browse/TRUNK-6377

TRUNK-6377:Implement getProviderRole in the core

---

api/src/main/java/org/openmrs/api/ProviderService.java
api/src/main/java/org/openmrs/api/db/ProviderDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateProviderDAO.java
api/src/main/java/org/openmrs/api/impl/ProviderServiceImpl.java
api/src/test/java/org/openmrs/api/PatientServiceTest.java
api/src/test/java/org/openmrs/api/db/hibernate/ProviderDAOTest.java
api/src/test/resources/org/openmrs/api/include/ProviderServiceTest-initial.xml

see https://openmrs.atlassian.net/browse/TRUNK-6377

TRUNK-6377: Implement getProviderRoleByUuid

---

api/src/main/java/org/openmrs/api/context/Context.java
api/src/main/java/org/openmrs/api/context/ServiceContext.java
api/src/test/java/org/openmrs/api/OrderServiceTest.java
api/src/test/java/org/openmrs/test/BaseContextSensitiveTest.java
api/src/test/java/org/openmrs/test/jupiter/BaseContextSensitiveTest.java

see https://issues.openmrs.org/browse/TRUNK-6364

TRUNK-6364: Cleanup api cache after each test for Transactional tests

---

pom.xml

Reverts openmrs/openmrs-core#5150

Revert "TRUNK-6332: Set minimum required Java version to 21"

---

api/src/main/java/org/openmrs/liquibase/ChangeLogVersions.java
api/src/main/resources/liquibase-core-data.xml
api/src/main/resources/liquibase-schema-only.xml
api/src/main/resources/liquibase-update-to-latest-from-1.9.x.xml
api/src/main/resources/liquibase-update-to-latest.xml
api/src/main/resources/org/openmrs/liquibase/snapshots/core-data/liquibase-core-data-2.8.x.xml
api/src/main/resources/org/openmrs/liquibase/snapshots/schema-only/liquibase-schema-only-2.8.x.xml
api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-3.0.x.xml
api/src/test/java/org/openmrs/util/DatabaseUpdaterDatabaseIT.java

see https://openmrs.atlassian.net/browse/TRUNK-6394

TRUNK-6394: Create platform 2.8 liquibase snapshot files

---

Dockerfile
startup-init.sh
web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
web/src/main/java/org/openmrs/web/filter/initialization/InitializationWizardModel.java

This PR copies properties from the installation script to the runtime properties only if those properties are not used in the installation script.
Note that this PR cannot be backported to earlier versions due to changes to the installation script unrelated to these changes. [A separate PR](https://github.com/openmrs/openmrs-core/pull/5198) is provided for versions 2.7.x and below.
see https://issues.openmrs.org/browse/TRUNK-6395
added all formatting changes to my …

TRUNK-6395: Unused properties from the installation script should become runtime properties

---

api/src/main/resources/org/openmrs/hl7/db/hibernate/HL7Source.hbm.xml

see https://openmrs.atlassian.net/browse/TRUNK-6400

TRUNK-6400: Remove the discriminator from HL7Source Hibernate Mapping

---

web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java
web/src/test/java/org/openmrs/web/filter/initialization/InitializationFilterTest.java

This inlines the `resolveInitializationProperties()` so that we can ensure we are _only_ copying properties from the installation script to the runtime properties.
I've left things so that the installer will still process environment variables and system properties to override installation properties, although this still feels odd to me.
see https://issues.openmrs.org/browse/TRUNK-6395
No? -> …

TRUNK-6395: Only copy properties from the install script

---

api/src/main/resources/org/openmrs/hl7/db/hibernate/HL7InQueue.hbm.xml

see https://openmrs.atlassian.net/browse/TRUNK-6403

TRUNK-6403: Remove the discriminator from HL7InQueue  Hibernate Mapping

---

api/src/main/resources/org/openmrs/liquibase/updates/liquibase-update-to-latest-3.0.x.xml
api/src/test/java/org/openmrs/util/databasechange/ValidateHibernateMappingsDatabaseIT.java

Reverts openmrs/openmrs-core#5249

Revert "TRUNK-6406: Bypass Hibernate Validation Errors Caused by JPA Inheritance and Incomplete Schema"

---

web/src/main/java/org/openmrs/web/filter/initialization/InitializationWizardModel.java

see https://issues.openmrs.org/browse/TRUNK-6329

TRUNK-6329: Fix OPENMRS_VERSION showing as null in initialization wizard header

---

api/src/main/java/org/openmrs/api/ProviderService.java
api/src/main/java/org/openmrs/api/db/ProviderDAO.java
api/src/main/java/org/openmrs/api/db/hibernate/HibernateProviderDAO.java
api/src/main/java/org/openmrs/api/impl/ProviderServiceImpl.java
api/src/test/java/org/openmrs/api/ProviderServiceTest.java
api/src/test/resources/org/openmrs/api/include/ProviderServiceTest-initial.xml

see https://issues.openmrs.org/browse/TRUNK-6407

TRUNK-6407: Implement a method to get all provider roles

---

api/src/main/java/org/openmrs/api/ProviderService.java

see https://issues.openmrs.org/browse/TRUNK-6407

TRUNK-6407: correct @since tag from 3.0.0 to 2.8.1

---

startup-init.sh
web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java

It was pointed out to me that the SDK has been using a scheme of naming properties meant to be set as runtime properties by prefixing them with `property.`, so instead of only excluding the properties the InitializationFilter knows how to process, we simply prefix the properties to be added with the same `property.`. This also makes the logic in the InitializationFilter simpler.
Note that for the Docker container, if the runtime properties already exists, any extras are copied as-is. It's only in the installation script that we're modifying them to start with `property.`
see https://issues.openmrs.org/browse/TRUNK-6395
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit …

TRUNK-6395: Saner scheme for copying properties from the installation script

---

api/src/main/java/org/openmrs/Obs.java
api/src/test/java/org/openmrs/ObsTest.java

TRUNK-6414: Obs.setValueAsString() should allow "blank" strings

---

api/src/main/java/org/openmrs/Obs.java
api/src/test/java/org/openmrs/ObsTest.java

This reverts commit b1c64339c33866956d2b36744ff57fbb7eb10c15.

Revert "TRUNK-6414: Obs.setValueAsString() should allow "blank" strings"
